### ISSUE TITLE
Question: Specifying an Adapter Per Model

### ISSUE THREAD

**Issue by shicholas** [rails-api/active_model_serializers#1001]
I would like to use the ``json`` adapter for some models and the ``json_api`` adapter for other models. Our team is interested in the ``json_api`` spec, but are not ready for a complete overhaul of how we render json. I tried creating some base classes that override the ``config`` in ``ActiveModel::Serializer`` to no avail.

Sorry if this is a duplicate, how would I go about this?

**Comment by shicholas** [comment]
Just read https://github.com/rails-api/active_model_serializers/pull/1000#issuecomment-121135502 which answered my question, sorry for the spam.

**Comment by joaomdmoura** [comment]
Hey @shicholas! Great, I glad you read that, so yeah, you could do something like:

```ruby
render @post, adapter: json_api
```
