### ISSUE TITLE
How to serialize a hash member that has values which are objects with custom serializers under AMS 0.10.0?

### ISSUE THREAD

**Issue by stevemadere** [rails-api/active_model_serializers#1008]
Described in this stack-overflow question:

http://stackoverflow.com/questions/31432702/how-to-serialize-a-hash-member-with-object-values-with-custom-serializers-with-a

**Comment by joaomdmoura** [comment]
Hey @stevemadere, I'm glad that you posted it on stackoverflow and here :smile: 
Just to make sure that I got it, is this part of you serializer or an action from a controller?

```ruby
def picklists
    grouped_items = @object.active_picklist_items.group_by(&:picklist_type)
    serializers = grouped_items.map do |picklist_type,picklist_items|
                    [picklist_type, ActiveModel::ArraySerializer.new(picklist_items,each_serializer: PicklistItemSerializer)]
                  end
    Hash[serializers]
  end
```

Could you please explain a little bit more the structure that you have and what you are trying to accomplish?

**Comment by stevemadere** [comment]
The picklists method is from the serializer.

The model that I am serializing called Thing has_many active_picklist_items which are of type
PicklistItem.

i.e.
```ruby
class Thingy < ActiveRecord::Base
  ...
  has_many active_picklist_items, -> { where active: true}, class_name: 'PicklistItem'
end
```

In the custom serializer for the Thing model, I want to group the  PicklistItems by 
picklist_type and store them in a hash accessed as 'picklists' so that in JSON, an
instance of my Thingy class would look like this:

```JSON
{
  "id": 72,
   "picklists": {
      "colors": [
                    { "id": 300, "picklist_type": "colors", "name": "blue", ...},
                    { "id": 301, "picklist_type": "colors", "name": "red", ...},
                     ...
                 ],
       "shapes": [
                      { "id": 415, "picklist_type": "shapes", "name": "square", ...},
                      { "id": 416, "picklist_type": "shapes", "name": "circle", ...},
                       ...
                  ],
         ...
     },
}
```

Note, that the JSON for each PicklistItem needs to be generated by the serializer
that I defined:

```ruby
class PicklistItemSerializer << ActiveModel::Serializer
  attributes :id, :picklist_type, :name, :global, :mutable, :color, :priority
end
```

I do not want 'default serialization' that includes every attribute in the PicklistItem model because
there is some other junk in there that I do not want sent over the wire to my API consumers.

This does in fact work under AMS < 0.10 using the custom AMS attribute method that
you quoted above.  

It does not work with AMS 0.10.0 however.   With that version, the resulting JSON
for the picklist_items hash values are serialized ArraySerializer objects instead of
a serialized array of PicklistItem objects.

**Comment by joaomdmoura** [comment]
It's probably because the way that the new AMS version splits it's logic between `serializers` and `adapters`.

```ruby
serializer_class = ActiveModel::Serializer.serializer_for(obj)
serializer = serializer_class.new(obj)
adapter = ActiveModel::Serializer.adapter.new(serializer)
adapter.serializable_hash # The JSON response itself
```
You could try to refactor the `picklists` virtual attribute to use something like it.
Another option would be not have the `PicklistItemSerializer` and built the `Hash` you need inside the custom serializer for the `Thing` model.

**Comment by OneMain** [comment]
serializers = datas.map do |group_type,items|
      [group_type, ActiveModel::Serializer::ArraySerializer.new(items,serializer: YourModelSerializer)]
    end
   by this way ,can  make serializer for hash
v:  0.10.7

**Comment by bf4** [comment]
@onehouse please don't do that
