### ISSUE TITLE
jsonapi for POROs

### ISSUE THREAD

**Issue by jpaas** [rails-api/active_model_serializers#1009]
I've been unable to use the jsonapi adapter for any object that is not an ActiveRecord object and ActiveModel::SerializerSupport seems to have been removed. Is there any plan for 0.10.x to support POROs?

**Comment by joaomdmoura** [comment]
Hi @jpaas, indeed the actual AMS implementation is deeply tied to AR. By doing this we were able to made a lot of optimizations.

In our tests we have being using POROs but in order to make it work you will need to create some methods that AMS expects. I'd recommend you to check [our implementation](https://github.com/rails-api/active_model_serializers/blob/master/test/fixtures/poro.rb#L1)

I'm closing this one for now, but please, let us know in case you find any problems!

**Comment by joaomdmoura** [comment]
oh @jpaas I'm sorry to hear that, can you share it with us so we can give a try and find a better way to help you?

**Comment by jpaas** [comment]
Here's my model:
```ruby
module Poros
  class Settings
    # include ActiveModel::SerializerSupport
    attr_accessor :id, :membership, :organization, :user

    def initialize(attributes)
      @id = attributes[:id]
      @membership = attributes[:membership]
      @organization = attributes[:organization]
      @user = attributes[:user]
    end

    def self.model_name
      @_model_name ||= ActiveModel::Name.new(self)
    end

    def initialize(hash={})
      @attributes = hash
    end

    def cache_key
      "#{self.class.name.downcase}/#{self.id}-#{self.updated_at.strftime("%Y%m%d%H%M%S%9N")}"
    end

    def cache_key_with_digest
      "#{cache_key}/#{FILE_DIGEST}"
    end

    def updated_at
      @attributes[:updated_at] ||= DateTime.now.to_time
    end

    def read_attribute_for_serialization(name)
      if name == :id || name == 'id'
        id
      else
        @attributes[name]
      end
    end

    def id
      @attributes[:id] || @attributes['id'] || object_id
    end

    def method_missing(meth, *args)
      if meth.to_s =~ /^(.*)=$/
        @attributes[$1.to_sym] = args[0]
      elsif @attributes.key?(meth)
        @attributes[meth]
      else
        super
      end
    end
  end
end
```
Here's my serializer:
```ruby
class SettingsSerializer < ActiveModel::Serializer
  attributes :id
  has_one :membership, embed_in_root: true, serializer: MembershipSerializerWithOrganization
  has_one :organization, embed_in_root: true, serializer: OrganizationSerializer
  has_one :user
end
```

Here's a sample of the JSON I get as a response. You can see it doesn't look very JSONAPI-like. Additionally, the serializers for the related ActiveModel objects were not used. Those are simple `to_json` hashes.
```
{
    "attributes": {
        "id": "me",
        "membership": {
            "created_at": "2015-07-14T14:21:48.559Z",
            "id": "a86b662e-d484-4692-a68b-94a92b3a3968",
            "organization_id": "ca8cf9b0-47fc-4937-99e4-8a7eaa2a42f8",
            "role": "superadmin",
            "updated_at": "2015-07-14T14:21:48.559Z",
            "user_id": "f673f449-681a-4945-9545-9528c2840bab"
        },
        "organization": {
            "country_code": "CA",
            "created_at": "2015-07-14T14:21:48.390Z",
            "id": "ca8cf9b0-47fc-4937-99e4-8a7eaa2a42f8",
            "lft": 1,
            "municipality": "Toronto",
            "name": "Prestige Worldwide",
            "parent_id": null,
            "postal_code": "H0H0H0",
            "properties": null,
            "rgt": 6,
            "status": "active",
            "street_address_1": "80 North St",
            "street_address_2": null,
            "subdivision_code": "ON",
            "updated_at": "2015-07-14T20:12:01.057Z"
        },
        "user": {
            "created_at": "2015-07-14T14:21:48.534Z",
            "email": "superadmin@prestige.com",
            "id": "f673f449-681a-4945-9545-9528c2840bab",
            "status": "active",
            "updated_at": "2015-07-14T14:21:48.534Z"
        }
    }
}
```

**Comment by joaomdmoura** [comment]
@jpaas and can you share where you are calling the serializer/adapter itself?
Yeap, probably what you would need is to `include` the other resources, [check it here](https://github.com/rails-api/active_model_serializers#jsonapi), it would also imply into removing `embed_in_root`. This would give you something that probably follows json-api conventions

**Comment by jpaas** [comment]
I'm using grape and grape-active_model_serializers. My grape endpoint returns the PORO, and grape-active_model_serializers calls the serializer/adapter.

Ah, I didn't realize that the convention had changed from the include directive being in the serializer to being on the render. I'm not sure if grape-active_model_serializers will pass that include option along for me, but I can try and I'll get back to you.

**Comment by beauby** [comment]
Would it make sense to define an abstract class that serializable POROs would inherit from? And maybe a generator.

**Comment by feedthebayer** [comment]
@beauby yeah!

**Comment by joaomdmoura** [comment]
btw just to keep it on the record, some user have being reporting some problems involving `grape-active_model_serializers`. 
I'm :-1: for the generators @beauby  but we can make some abstract class that can be even used on our on tests.
Maybe another issue for that.
I'm closing this one for now, if @jpaas come back with news we can reopen it.

**Comment by jpaas** [comment]
Sorry for being so late following up, but yes once I put the include in the serializer options it worked. Thanks! Now I have to figure out why its not wrapping it using "data" and "includes"

**Comment by jpaas** [comment]
I'm inching closer. But now I can't get it to include my relationships...

My lame poro:
```
class Settings
  attr_accessor :id, :foo, :membership, :organization, :user

  def self.model_name
    @_model_name ||= ActiveModel::Name.new(self)
  end

  def initialize(hash={})
    @attributes = hash
  end

  def cache_key
    "#{self.class.name.downcase}/#{self.id}-#{self.updated_at.strftime("%Y%m%d%H%M%S%9N")}"
  end

  def cache_key_with_digest
    "#{cache_key}/#{FILE_DIGEST}"
  end

  def updated_at
    @attributes[:updated_at] ||= DateTime.now.to_time
  end

  def read_attribute_for_serialization(name)
    if name == :id || name == 'id'
      id
    else
      @attributes[name]
    end
  end

  def id
    @attributes[:id] || @attributes['id'] || object_id
  end

  def method_missing(meth, *args)
    if meth.to_s =~ /^(.*)=$/
      @attributes[$1.to_sym] = args[0]
    elsif @attributes.key?(meth)
      @attributes[meth]
    else
      super
    end
  end
end
```

My serializer:
```
class SettingsSerializer < ActiveModel::Serializer
  attributes :foo

  has_one :membership, serializer: MembershipSerializerWithOrganization
  has_one :organization, serializer: OrganizationSerializer
  has_one :user, serializer: UserSerializerWithMemberships

end
```

The result (note that the relationships are always null). Perhaps I no longer have an issue with poros anymore, but its this issue? #1180 
```
{
    "data": {
        "attributes": {
            "foo": null
        },
        "id": "me",
        "relationships": {
            "membership": {
                "data": null
            },
            "organization": {
                "data": null
            },
            "user": {
                "data": null
            }
        },
        "type": "settings"
    }
}
```

**Comment by jpaas** [comment]
I solved my problem using the information in #1241. This new way of adding serialization support to POROs helped.

**Comment by bf4** [comment]
great, I wast just writing that for you here.. but you found it before I pasted the link :) 

t and examples for how to make a compatible poro https://github.com/rails-api/active_model_serializers/pull/1241#discussion_r41398549

**Comment by bf4** [comment]
Can this be closed? Will you help us update the documentation with what you've learned?

**Comment by jpaas** [comment]
Yes this can be closed. I think the documentation created in #1241 is excellent and sufficient. I followed it exactly as shown and it worked. Thanks.
