### ISSUE TITLE
Running Serializers with Rails Nginx and Unicorn

### ISSUE THREAD

**Issue by sternhenri** [rails-api/active_model_serializers#1012]
Hey there,

This is a bit of a shot in the dark but I am having trouble running the gem on a server to customize our API's json returns. (**see below for where it is included in the app**).

To make a long story short, the gem works great on the server when I run rails s, but somehow, when I deploy to the webserver using nginx/unicorn, I run into errors in my Unicorn log and the client can't access the app.

This is the error I am getting: 

```
E, [2015-07-16T17:38:46.737769 #12405] ERROR -- : uninitialized constant ActiveModel::Serializer (NameError)
/home/.../releases/20150716172308/config/initializers/api_configs.rb:3:in `<top (required)>'
/home/.../shared/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
```

When I comment out that line from my initializer, I get an error with the serialization_scope setting in my application_controller.rb (Undefined Method: serialization_scope) and the code similarly doesn't run. I have also tried manually including in the application_controller.rb 
```
Include ActionController::Serialization
```
to no avail (I receive the error Uninitialized Constant ActionController::Serialization). This was recommended in other issues but, unfortunately, it did not solve my problem. 

I thought this meant the the gem wasn't getting pulled in properly on my server (perhaps given that it's pulled in directly from github), but that can't be it since **it works just fine with rails s**

Has anybody seen this behavior before or know what I am doing wrong?

Thanks so much!

Henri

**_________**

AMS inclusions in my code:

*Gemfile*
```
gem 'active_model_serializers', github: "rails-api/active_model_serializers"
```
*initializer file*
```
ActiveModel::Serializer.config.adapter = :json
```
*application_controller.rb*
```
  serialization_scope :view_context
```
*Model Files (example)*
```
def active_model_serializer
	UserSerializer
end
```
*Serializer Files (example)*
```
class LinkSerializer < PostSerializer
	attributes :url
end
```

**Comment by zreitano** [comment]
I have the same exact problem! Any help would be greatly appreciated.

**Comment by joaomdmoura** [comment]
Hi @sternhenri and @zreitano.
This quite strange. In order to help you on this I'll try to cover the basics first.

- Make sure the gem is in your gemfile
- Make sure you have ran `bundle install` both, in you local environment and product/whatever

I know it might seem pretty basic stuff but you might have installed the gem without ran `bundler`

**Comment by sternhenri** [comment]
Hey @joaomdmoura Thanks so much for the reply, the gem is installed just fine, it was actually a problem with the gemset being loaded by unicorn!

**Comment by joaomdmoura** [comment]
awesome :+1:
