### ISSUE TITLE
README does not explain how to work with non ActiveRecord models

### ISSUE THREAD

**Issue by sentience** [rails-api/active_model_serializers#1022]
The README on master (for 0.10.0) does not explain how to use AMS with non-ActiveRecord models. Everything that Google will return pertains only to previous releases (i.e. including `ActiveModel::SerializerSupport`, which is no longer available).

It appears that mixing `ActiveModel::Serialization` is the main thing that is required. E.g., for a Mongoid document:

```ruby
class SomeDocument
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  include ActiveModel::Serialization # required to use Active Model Serializers
```

Is there something more to the setup?

**Comment by sentience** [comment]
Actually, with further experimentation, it seems that nothing is required for Mongoid documents, not even `ActiveModel::Serialization`. It seems they support `read_attribute_for_serialization` out of the box?

**Comment by joaomdmoura** [comment]
@sentience indeed we haven't mentioned anything on README. Would be awesome  if you could make a PR to add some guide into our [new docs](https://github.com/rails-api/active_model_serializers/tree/master/docs) to 0.10.x if you end up making it :smile: 
Our tests suit uses PORO objects as well so the best suggestion I have would be to [check it out](https://github.com/rails-api/active_model_serializers/blob/master/test/fixtures/poro.rb), we basically had to implement some methods from `AR`
I'm not sure about `Mongoid` there isn't a lot of ppl using AMS with it nowadays, but would be awesome to have a guide on how to do it on our docs as well :grin: 
Let me know if it helps you or if you need something else.

**Comment by feedthebayer** [comment]
Anyone figured this out yet? I'm currently trying to get AMS to work without ActiveRecord (with Neo4j, so basically vanilla Ruby classes).

**Comment by joaomdmoura** [comment]
hey @feedthebayer you would recommend you to check [our tests](https://github.com/rails-api/active_model_serializers/blob/master/test/fixtures/poro.rb). We use PORO objects. 
The new interface to serialize object without passing through render id:
```ruby
ActiveModel::SerializableResource.serialize(resource, options)
```

**Comment by feedthebayer** [comment]
Thanks @joaomdmoura. But it looks like that interface isn't in a release yet, correct?

From your suggestion, I found out I could test the serializer using this:
```ruby
ActiveModel::Serializer::Adapter.create(OrgSerializer.new(Org.first)).as_json
``` 
Which actually worked fine for me out of the box after following the basic AMS install instructions (I'm also using rails-api). So the real issue for me turned out to be I needed to render Org.all.to_a instead of Org.all because of how neo4j implements that.

The functions needed by AMS are apparently included with this:  `include Neo4j::ActiveNode`

**Comment by joaomdmoura** [comment]
Yeap, the version rc2 does not have the `SerializableResource` but I would recommend you to give it a try to master version. btw we might release RC3 version soon.
But I'm glad it worked out for you! :smile:

**Comment by Mohakjuneja** [comment]
AMS won't work with my mongoid models. I'm using the version 0.9.3. Is there any configuration that I'm supposed to add in order to make it work?

**Comment by joaomdmoura** [comment]
Hey @Mohakjuneja, the older versions are not as much coupled to AR as the new ones, something the some ppl usually did when using the older versions like 0.9.3 to make it work was creating a new initializer with the following:

```ruby
Mongoid::Document.send(:include, ActiveModel::SerializerSupport)
Mongoid::Criteria.delegate(:active_model_serializer, to: :to_a)
```

I'm not sure if it woks, but you can open a new issue for that and let us know about you progress on this and how we can help you.

**Comment by beauby** [comment]
I believe this is fixed: [How To: serializing POROs](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/serialize_poro.md).
Closing the issue for now, feel free to reopen if needed.

**Comment by mehta** [comment]
@joaomdmoura - this will change with upcoming release(commit SHA - aa4d89ab4765aa7721aa053840a4bb57152ea7ba), I believe -

> Mongoid::Document.send(:include, ActiveModel::SerializerSupport)
> Mongoid::Criteria.delegate(:active_model_serializer, to: :to_a)

updated (with  - 
> Mongoid::Document.send(:include, ActiveModelSerializers)

and it will solve the use-case, right?

**Comment by bf4** [comment]
@mehta please open a new issue.
