### ISSUE TITLE
[ams 0.10.2] undefined method `new' for nil:NilClass with relations

### ISSUE THREAD

**Issue by randallb** [rails-api/active_model_serializers#1023]
So i have one serializer which does `has_many` to another relationship. 

The second model doesn't have a serializer currently, and I get this error:

`undefined method `new' for nil:NilClass with relations`

stack trace:

```/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer/array_serializer.rb:16:in `block in initialize'
activerecord (4.2.3) lib/active_record/relation/delegation.rb:46:in `map'
activerecord (4.2.3) lib/active_record/relation/delegation.rb:46:in `map'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer/array_serializer.rb:11:in `initialize'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer.rb:209:in `new'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer.rb:209:in `block in each_association'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer.rb:202:in `each'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer.rb:202:in `each_association'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer/adapter/json.rb:17:in `serializable_hash'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer/adapter/flatten_json.rb:6:in `serializable_hash'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/active_model/serializer/adapter.rb:24:in `as_json'
activesupport (4.2.3) lib/active_support/json/encoding.rb:35:in `encode'
activesupport (4.2.3) lib/active_support/json/encoding.rb:22:in `encode'
activesupport (4.2.3) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
actionpack (4.2.3) lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/active_model_serializers-a7c8c60929ec/lib/action_controller/serialization.rb:49:in `block (2 levels) in <module:Serialization>'
actionpack (4.2.3) lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/2.2.0/set.rb:283:in `each_key'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/2.2.0/set.rb:283:in `each'
actionpack (4.2.3) lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
actionpack (4.2.3) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.3) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (4.2.3) lib/rails/engine.rb:518:in `call'
railties (4.2.3) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/rb/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'```

I would look at this but I don't have time to fix this week. This is from the `0-10-stable` branch.

**Comment by joaomdmoura** [comment]
@randallb could you give it a try to `master` to check if it's fixed already?

**Comment by kimsuelim** [comment]
It works fine in ``master``

**Comment by joaomdmoura** [comment]
Awesome @kimsuelim tks, I'm closing this one then.
