### ISSUE TITLE
Objects with an attribute named 'type' don't have that attribute serialized properly

### ISSUE THREAD

**Issue by jfelchner** [rails-api/active_model_serializers#1024]
We're overriding the polymorphic inheritance column:

```ruby
class MyModel < ActiveRecord::Base
  self.inheritance_column = 'whatever'
end
```

And we have a field in our DB named `type`.  It seems that AMS [has it hard coded](https://github.com/rails-api/active_model_serializers/blob/90fb1cf809dfa606181a1e047f30a05efe71912a/lib/active_model/serializer/adapter/json_api.rb#L105) that `type` should be deleted from the attributes which I believe is not correct.

**Comment by joaomdmoura** [comment]
@jfelchner yes, right now `type` is a protected word for anyone that we use to follow `json-api` conventions, `id` as well.
We are actually discussing about changing to no impact users that are using other adapter.

**Comment by joaomdmoura** [comment]
@jfelchner I'm closing this one. It's already implemented on master :smile: btw `id` as well.

**Comment by jfelchner** [comment]
@joaomdmoura awesome! 😄
