### ISSUE TITLE
Serializing Relationship Without Include

### ISSUE THREAD

**Issue by jfelchner** [rails-api/active_model_serializers#1025]
I've been looking through the code and there doesn't appear to be a way to serialize a `relationship` without also serializing an `include`.  Let me explain:

We have two systems.  In one we have, let's say, a `Product` and in the other we have, for example, an `Alert`.  An `Alert` has a `product_id` on it.  For the purposes of our backend systems, the alert system could care less about the `Product`.  All it needs is the ID.

So when I serialize the `Alert`, I want it to be able to generate the `relationship` but ignore the part where it puts the `include` section in.  I also don't want it to care about the model having a _literal_ association on it.  The `Alert` doesn't `belong_to :product` from an `ActiveRecord` perspective, but when the `Alert` JSON gets down to the client, the client will know how to go and fetch the product if it doesn't already have it.

This is what I was hoping that I could do:

```ruby
class AlertSerializer < ActiveModel::Serializer
  belongs_to :product, include: false,
                       type:    'my_other_app_module_product'
end
```

Obviously, the default could be that if you say `belongs_to :product`, it would assume an attribute of `product_id` and a type of `product`, but overriding the `type` is important because sometimes (as in our case) it will not be able to be inferred from the association name.

Anyway, the above would generate something like:

```json
{
  "data" : {
    "type" : "my_app_module_alert",
    "id" : "my_alert_id",
    "attributes" : {
      /* Attributes */
    },
    "relationships" : {
      "product" : {
        "data" : { "id" : "my_product_id", "type" : "my_other_app_module_product" }
      }
    }
  }
}
```

**Comment by beauby** [comment]
So by default the JsonApi adapter *does not* put the related objects in the `include`, *and* it still serializes the defined *relationship objects*. However, it currently relies on the corresponding object to exist an be available as a method on the parent. You could probably get away with defining a method on your model that would behave as expected by AMS to solve your situation. I am also thinking/working on some way to use the `#{relationship}_id` method when available for to-one relationships.

**Comment by scttnlsn** [comment]
I'm having this issue with the `FlattenJson` adapter.  I'd like to be able to pass in `include: []` and have none of the relationships included in the serializable hash (currently relationships 1 level deep are included by default it seems?).  In other cases I'd like to explicitly include various nested relationships.  Is that possible somehow?

**Comment by NullVoxPopuli** [comment]
@scttnlsn that's a good idea. I'll check on that real quick, I'm not sure if that's currently possible.

**Comment by scttnlsn** [comment]
@NullVoxPopuli OK, I'm happy to put together a pull request if this is something you'd be interested in.

**Comment by beauby** [comment]
@scttnlsn This is currently possible. Passing `include: ''` or `include: []` will make the adapter include no relationship at all.

**Comment by NullVoxPopuli** [comment]
are you using master? FlattenJson actually isn't the name of the adapter anymore, and I just wrote a test for the json adapter to achieve your desired result, and it worked.

**Comment by scttnlsn** [comment]
I'm using `0.10.0.rc3` and it is not working.  I try `master`.

**Comment by NullVoxPopuli** [comment]
@scttnlsn https://github.com/rails-api/active_model_serializers/pull/1227

it's not using the attributes adapter, but both json and attributes adapters use almost all the same code.

**Comment by scttnlsn** [comment]
@NullVoxPopuli OK, awesome.  It's working great on `master`.  Thanks!  Will this be in a `0.10.0.rc4` release?

**Comment by NullVoxPopuli** [comment]
@scttnlsn I'm glad!
and yes, it'll be either rc4, or official 0.10.0. Not sure on official next release.
@joaomdmoura probably knows

**Comment by beauby** [comment]
@scttnlsn Yes, it will be part of the next release.

**Comment by jfelchner** [comment]
@beauby yeah I know we could probably hack something but I'd prefer if AMS would take care of this more transparently for us.

**Comment by beauby** [comment]
This feature would create undefined behavior in case of inclusion. As mentioned, a workaround is to define the corresponding method on the model, so that AMS believes it's just a regular association.
Closing this issue for now, but feel free to keep commenting/making a case for it.
