### ISSUE TITLE
Pagination Links on AMS

### ISSUE THREAD

**Issue by bacarini** [rails-api/active_model_serializers#1040]
Hey guys,

I am working on an API and I need to return pagination links on my responses. I am wordering the best way to to that. [JSON-API](http://jsonapi.org/format/#fetching-pagination) specification does not let it clear on how it should display the links top-level.

what is your thoughts about the following example?

```
{
    "data": [..],
    "links": {
        "pages": {
            "first": "?page=1&per_page=1",
            "prev": "?page=2&per_page=1",
            "next": "?page=4&per_page=1",
            "last": "?page=10&per_page=1"
        }
    }
}
```

Anyway, I've opened a [PR](https://github.com/rails-api/active_model_serializers/pull/1041) and I would like to discuss it with you all.

**Comment by bacarini** [comment]
@joaomdmoura, 

I think we can close this issue, since #1041 was merged, no?

**Comment by joaomdmoura** [comment]
Indeed, closed! :smile:
