### ISSUE TITLE
root option in render json is not working

### ISSUE THREAD

**Issue by PratheepV** [rails-api/active_model_serializers#1046]
Hi,

I am using the rails-api and ams. But root option in render json is not working. Its always returning the class name only.

```ruby
#gem
gem "active_model_serializers", "~> 0.10.0.rc2"

#config
ActiveModel::Serializer.config.adapter = :json

#controller render
render json: current_user, root: :session

```
At https://github.com/rails-api/active_model_serializers/blob/v0.10.0.rc2/lib/active_model/serializer/adapter/json.rb#L40, are forcing the root as serializer json_key. 

It should respect my root option while rendering the json right.

If I change the code like below its working fine.
```ruby
{ (options[:root] || root) => @result }
```

--Pratheepv

**Comment by joaomdmoura** [comment]
@PratheepV  Would you mind to test it against master? I think it was already fixed.
Thank You. :smile:

**Comment by PratheepV** [comment]
@joaomdmoura , root options is not working for array serializers. Meaning if we have the 

```ruby
render status: 200,
        json: items, root: :apples
```
Getting the response as 

```javscript
  {"": [ {id: 1 , color: 'red'}]}
```

I tried using json_key in serializer also. 

I am using 0.10.0.rc3
