### ISSUE TITLE
embedding ids in 0.10.x

### ISSUE THREAD

**Issue by dbwieland18** [rails-api/active_model_serializers#1053]
I've come across a few issues that have started the discussion about including support for side-loading associations in 0.10.x, but with that still somewhere down the pipeline, I'm wondering if anyone has gone through the process of re-implementing the 'old' (not json-api) formatting that previous versions of AMS allowed for through use of 
```
embed :ids, include: true
```
... need to stay on master for caching support, but I'm stuck on where to get started on re-implementing this feature.

**Comment by joaomdmoura** [comment]
@dbwieland18 I think you can use the `include` option that we have on 0.10.x.

```ruby
render @posts, include: ['authors', 'comments']
```

You can also use `.` in order to chain associations

```ruby
render @posts, include: ['author', 'author.bio', 'comments']
```

We still have `embed` but only when declaring a association on a serializer:

```ruby
has_many :comments, embed: :ids
```

I'm not sure if this solves your problem, just let me know :smile:

**Comment by xawiers** [comment]
Anyway this does not work.

**Comment by NullVoxPopuli** [comment]
what adapter are you using?

**Comment by xawiers** [comment]
Tried latest 0.10 version.
adapter Redis, ruby 2.2.4, OS windows 10 x64, rails 4.2.6
have articles and topics relation many to many
defined in articles serializer has_many :topics, embed: :ids, include: true
changed to version ~0.9.5 and worked fine, but not with 0.10

**Comment by remear** [comment]
Redis is not an AMS [adapter](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md). This issue has been closed for a long time. Please open a new issue and provide the information requested by the issue template.
