### ISSUE TITLE
Move to Rails Github Org

### ISSUE THREAD

**Issue by maclover7** [rails-api/active_model_serializers#1055]
A recently extracted gem, ActiveModel::Serializers::Xml, is now hosted in the Rails Github organization. For consistency, and since rails-api is now in Rails master, does it make sense to move active_model_serializers as well, and to deprecate the rails-api Github org?

**Comment by joaomdmoura** [comment]
@maclover7 this is already being taken care of, we are in touch with the Rails team and working on the details. @spastorino is probably the one with the most up to date info regarding this matter.

**Comment by spastorino** [comment]
@maclover7 that's the idea and what I'd like to do but I'm waiting for a reply from the rest of the Rails core team.

**Comment by maclover7** [comment]
:+1:
