### ISSUE TITLE
Serializer unable to open file paths with colon

### ISSUE THREAD

**Issue by qasic** [rails-api/active_model_serializers#1057]
This line in `serializer.rb` is not Windows friendly.

```ruby
      serializer_file = File.open(caller.first[/^[^:]+/])
```

On Windows, `caller.first` could return a file path that contains a colon: 

```
C:/EmberYVR/backend/app/serializers/meetup_serializer.rb:1:in `<top (required)>'
```

After it goes through the regular expression, I path gets translated to

```
C
```

which obviously fails to resolve.

**Comment by conf** [comment]
It seems this has been fixed in https://github.com/rails-api/active_model_serializers/commit/215fb85c7fc10d8fce504e5a7f6256d8a364e16c (on master branch).

**Comment by joaomdmoura** [comment]
Yup. it seems to be fixed, and now we officially have appveyor to guarantee our windows support :smile:
