### ISSUE TITLE
Only use AMS (0.9.3) for specified controller?

### ISSUE THREAD

**Issue by yijia-zhan** [rails-api/active_model_serializers#1059]
I have been playing with AMS(0.9.3) and it has been working out really nice. My plan is to gradually introduce it to the application and replace existing JSON rendering. 

The problem is that, once the gem is included, it immediately affects all existing `render json: @object`. This breaks all existing versions of APIs. Is there a way to turnoff or disable AMS globally and only use it in newly added controllers?

**Comment by joaomdmoura** [comment]
Hey @yijia-zhan, first of all thank you to give a try :smile: 
I would recommend the newest version we have being working on, the 0.10.x, you can use the rc2 or the master (we focus on always keep it working).

Yup, the default behavior of AMS is to use a serializer (if there is one) on every  `render` of that object.

There someways to work-around this, the easiest one that come to my mind right now is to namespace your serializers (so the lookup wont find them), and use it only on the request you want by verbally defining it with:

```ruby
 render json: @post, serializer: NewApi::PostSerializer
```

This might not be so practical, but will enable you to keep track of the endpoints that uses serializer, and once you decide to remove the support for the old flow you can just remote the `serializer` option, keep the usual render and remove the namespaces.

Let me know how you feel about it, and if this work out for you. :smile:

**Comment by yijia-zhan** [comment]
Thanks for the super fast reply @joaomdmoura. So if i'm understanding you correctly, what you are suggesting is to namespace serializers to fool the look up logic? For example: 

```ruby
class NewAPI::BlogSerializer < ActiveModel::Serializer
  # ...
end
```
And with this, the old API would fall back to existing serializing behavior because it couldn't find the serializer for `Blog`? 
```ruby
class OldApi::BlogController
  def show
    # this won't be using AMS because it couldn't find the serializer
    render json: @blog 
  end
end
```

---


I did try `0.10.rc2`. But I think it currently has problems serializing nested resources as described in  https://github.com/rails-api/active_model_serializers/issues/835? Say I have

```ruby
class BlogSerializer
  has_many :posts
end

class PostSerializer
  has_many :comments:
end

class CommentSerializer
  has_many :replies
end
```

In my testing `0.10.rc2` only serializes the immediate associations. Would `render json: @blog` be able to give me all the nested resources? Is there any workaround on this yet?

**Comment by joaomdmoura** [comment]
Yup, that's exactly what I meant.
We do not support more than 1 level deep association for now, so in the example above the `blog` rendering would return the `posts`, but not the `comments`, unless you use the `include` option as described on the thread you mentioned :grin:

**Comment by yijia-zhan** [comment]
Actually, I just gave it a try with namespacing the serializer, but I got:

```
Unable to autoload constant BlogSerializer, expected /app/serializers/blog_serializer.rb to define it
```

**Comment by joaomdmoura** [comment]
@yijia-zhan you have to use the namespace on the render:
```ruby
 render json: @post, serializer: NewApi::PostSerializer
```
and the serializer have to follow the namespace convention, so it need to be on `/app/serializers/new_api/blog_serializer.rb`

**Comment by yijia-zhan** [comment]
It's the existing controllers which I don't want to use AMS that's having the problem. For example, I don't want the controller below to use AMS:
```ruby
class OldApi::PostController
  def show
    render json: @post 
  end
end
```
And my hid my `PostSerializer` in `/app/serializers/new_api/blog_serializer.rb`:
```ruby
module NewApi
  class PostSerializer
    # ...
  end
end
```
With this setup, I got the error below when I try to call the `/posts/:id`
```
Unable to autoload constant PostSerializer, expected /app/serializers/post_serializer.rb to define it
```

**Comment by joaomdmoura** [comment]
This is strange, I'll check the code, but for now other work-around that I'm sure that works is pass an option `adapter` as `false` instead.
```ruby
render json: @post, adapter: false
```
