### ISSUE TITLE
Deserialize from json_api to ActiveRecord's format

### ISSUE THREAD

**Issue by GCorbel** [rails-api/active_model_serializers#1061]
I'm using the :json_api adapter in Ember and Rails. I works very well when I receive data from Rails to Ember. Ember understand the format very well. When I save a record on Ember, I receive this kind of format : 

    {"data"=>{"id"=>"2", "attributes"=>{"email"=>"test@test.com", "nickname"=>"Test", "password"=>"[FILTERED]", "password-confirmation"=>"[FILTERED]"}, "relationships"=>{"trails"=>{"data"=>[{"type"=>"trails", "id"=>"13"}, {"type"=>"trails", "id"=>nil}]}}, "type"=>"users"}, 

To use it with ActiveModel, I need the format : 

    { user: { id: 2, email: { "test@test.com" ..... } }

 The goal is to use it like that : 

      render json: User.create(user_params)

There is a converter to write. Is there a way to do what I want. If nothing exists, I'm ready to do a pull request.

What you think? Is it a good idea? What's the best practice?

**Comment by GCorbel** [comment]
I made the uggliest code ever but it works for basics : 

    class JsonApiDeserializer
      attr_accessor :original, :converted

      def initialize(original)
        @original = original
        @converted = {}
      end

      def call
        original[:data].kind_of?(Array) ? convert_array : convert_hash
        converted
      end

      private

      def convert_array
        array_converted = []
        original[:data].each do |data|
          array_converted << JsonApiDeserializer.new({ data: data }).call
        end
        array_converted.each do |hash|
          hash.each do |key, value|
            converted[key] = {id: []} if converted[key].nil?
            converted[key][:id] << value[:id]
          end
        end
      end

      def convert_hash
        type = original[:data].delete(:type)
        converted[type] = original[:data]
        extract_attributes(converted[type])
        extract_relationships(type)
      end

      def extract_attributes(hash)
        attributes = hash.delete(:attributes)
        hash.merge!(attributes) unless attributes.nil?
      end

      def extract_relationships(type)
        relationships = converted[type].delete(:relationships)
        unless relationships.nil?
          relationships.each do |key, value|
            converted[type][key] = JsonApiDeserializer.new(value).call[key.to_s]
          end
        end
      end
    end

I have those results : 

    json_api = { data: { type: "posts", id: "42" } }
    p JsonApiDeserializer.new(json_api).call
    # => {"posts"=>{:id=>"42"}}

    json_api = {:data=>[{:type=>"trails", :id=>"12"}, {:type=>"trails", :id=>"13"}]}
    p JsonApiDeserializer.new(json_api).call
    # => {"trails"=>{:id=>["12", "13"]}}

    json_api = {:data=>
                {:id=>"1",
                 :type=>"users",
                 :attributes=>{:nickname=>"GCorbel"},
                 :relationships=>{:trails=>{:data=>[{:type=>"trails", :id=>"12"}, {:type=>"trails", :id=>"13"}]}}}}
    p JsonApiDeserializer.new(json_api).call
    # => {"users"=>{:id=>"1", :nickname=>"GCorbel", :trails=>{:id=>["12", "13"]}}}

Obviously, I have to do tests and refactoring but it works. What you think?

**Comment by bradleypriest** [comment]
I think you're looking for https://github.com/rails-api/active_model_serializers/pull/950

**Comment by joaomdmoura** [comment]
Hey @GCorbel, indeed we are aiming to have deserialization, as @bradleypriest mentioned, I've being working on that, we are almost done, and you can even you the branch itself to help us test it :smile:

**Comment by jimbeaudoin** [comment]
You can use rails strong_parameters to "deserialize" your data:

```ruby
def user_params
  params.require(:data).require(:attributes).permit(:username, :email)
end
```

**Comment by joaomdmoura** [comment]
Yup, #950 does it behind of the scenes as well.

**Comment by GCorbel** [comment]
Excellent ! I will try it. I lost some times to write the code but it was
fun. Thanks.

2015-08-18 13:36 GMT-04:00 João Moura <notifications@github.com>:

**Comment by bf4** [comment]
@GCorbel can think be closed? can you show us what worked and what didn't?

**Comment by beauby** [comment]
Yeah, we should close this one in favor of #950, in order to keep the discussion in one place.
