### ISSUE TITLE
Serializing ActiveModel::Model doesn't work

### ISSUE THREAD

**Issue by sschepens** [rails-api/active_model_serializers#1064]
Having a class that only includes ActiveModel::Model but doesn't inherit from ActiveRecord::Base fails simple serialization.
Class:
```ruby
class Log
  include ActiveModel::Model
  attr_accessor :message, :timestamp
end
```
Serializer:
```ruby
class LogSerializer < ActiveModel::Serializer
  attributes :message, :timestamp
end
```

This simple example fails with:
```
NoMethodError (undefined method `read_attribute_for_serialization' for #<Log:0x00000007542750>)
```

Modifying the serializer to proxy methods to object does work:
```ruby
class LogSerializer < ActiveModel::Serializer
  attributes :message, :timestamp

  def message
    object.message
  end

  def tags
    object.tags
  end
end
```
I know that making the class `include ActiveModel::Serialization` works, but one would expect that serializing ActiveModels would work out of the box.

**Comment by bf4** [comment]
You're correct that about `include ActiveModel::Serialization`  (also see [lint.rb](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/lint.rb)).  

`ActiveModel::Model`  "[includes the required interface for an object to interact with ActionPack](http://api.rubyonrails.org/classes/ActiveModel/Model.html)", which I guess doesn't include the serializer.  Maybe make a PR to Rails adding ActiveModel::Serialization?

**Comment by joaomdmoura** [comment]
yup, @bf4 is right. 
Let us know if there is something else we can help you with @sschepens

**Comment by bf4** [comment]
@sschepens PR to improve the docs?

**Comment by joaomdmoura** [comment]
Closing this for now waiting for a feed back from @sschepens
