### ISSUE TITLE
Trigger AMS from views? (0.9.3)

### ISSUE THREAD

**Issue by yijia-zhan** [rails-api/active_model_serializers#1072]
`render json: @posts` is most of the time called in controllers. Is there a way to render json using AMS from views? I tried making the exact same call in views but the error below. It's because `render` in the view context is different from in the controller context:

```
You invoked render but did not give any of :partial, :template, :inline, :file or :text option.
```

I tried creating a simple template `new_api/posts/index.html.erb` and rendering with `render template: ...`, but it doesn't trigger AWS:

```
# template 
<%= @posts.to_json%>

# rendering
render template: "new_api/posts/index"
```

Besides calling `render` in controller actions, is there any other ways that AMS can be triggered?

**Comment by yijia-zhan** [comment]
I figured out a workaround for this, basically I needed to support json rendering outside of Rails controllers. Closing this issue now.

**Comment by joaomdmoura** [comment]
Hey @yijia-zhan I'm glad you figured it out by yourself, sorry for take so long to show up! Lets u know if we can help you with anything more
