### ISSUE TITLE
Updating Documentation for 0.10

### ISSUE THREAD

**Issue by CodedBeardedSignedTaylor** [rails-api/active_model_serializers#1074]
Seems like there are a few ideas floating around for updating the documentation for the *current* version of AMS. I think a lot of confusion comes from the people not knowing what's in the current version of the gem. 

So, maybe we should highlight what's changed from 0.8.x and 0.9.x versions? Almost like an upgrade or "What's New" guide for users who are migrating from previous versions. Hopefully, this would clear the air about what needs to be changed within upgrading apps.

First and foremost, I want to propose fulfilling the requests of the following documentation issues.

### Relevant to 0.10.x

* ~~#1036~~ (Fulfilled by #1155) 
* ~~#844~~ (Closed) 
* #863 (Still has pending pull request)
* ~~#633~~ (Closed)

### Relevant to 0.9.x

* #831 
* #783 (has pending pull request)

**Comment by josemarluedke** [comment]
:+1:

**Comment by joaomdmoura** [comment]
Hey @CodedBeardedSignedTaylor, awesome github handler btw.
As I said, this is something I've reenforced across issues and PR's, and something that I'm deeply interested about.
I'm not sure about the "What's New", but would great to have some articles on the new docs with specific "tutorials" on how to updated from x.x.x to x.x.x.
Let us know through this PR if there is something we can help you with at anytime.

**Comment by CodedBeardedSignedTaylor** [comment]
Thanks dude! 

I'm gunning to have a PR with content to fulfill #1036 within the near future.

**Comment by bf4** [comment]
@CodedBeardedSignedTaylor Thanks for this! The issues referenced here are now merged or otherwise resolved and there is a mandatory issue for update docs https://github.com/rails-api/active_model_serializers/issues/1237

**Comment by CodedBeardedSignedTaylor** [comment]
@bf4 No problem! Glad to hear it helped. I'll hopefully have time soon to jump back in and help a bit!

**Comment by bf4** [comment]
@CodedBeardedSignedTaylor :heart: :sparkles:
