### ISSUE TITLE
Canonical way to general URLs

### ISSUE THREAD

**Issue by loganb** [rails-api/active_model_serializers#1076]
Hello, 

I googled around but couldn't find anything. What's the canonical way to generate URLs inside AMS?

**Comment by joaomdmoura** [comment]
Hey @loganb, what exactly is your need? Can you share an example? it might be easier for us to help you out, I can think in a bunch of way to generate URLs depending on what you want :smile:

**Comment by beauby** [comment]
Closing this for now, as it has been awaiting submitter response for a month. Feel free to reopen if needed.
