### ISSUE TITLE
Nested Associations

### ISSUE THREAD

**Issue by mrsutter** [rails-api/active_model_serializers#1077]
Hi, I've tried to move my project from 0-9-3 to 0-10-0 and found that version 0.10 doesn't support nested associations.

    class AppSerializer < ActiveModel::Serializer
      has_one :user, serializer: UserSerializer
    end

    class UserSerializer < ActiveModel::Serializer
      has_one :address, serializer: AddressSerializer
      has_one :account, serializer: AccountSerializer
      has_many :devices
      attributes :id, :login
    end

In my controller i have 

    render json: @app

and the response is 

    { user: {id: 1, login: "smb@email.com} }

Cause json adapter, takes into consideration only attributes of association, but not nested associations of user.

            serializer.each_association do |name, association, opts|
              if association.respond_to?(:each)
                array_serializer = association
                @hash[name] = array_serializer.map do |item|
                  cache_check(item) do
                    item.attributes(opts)
                  end
                end
              else
                if association && association.object
                  @hash[name] = cache_check(association) do
                    association.attributes(options)
                  end
                elsif opts[:virtual_value]
                  @hash[name] = opts[:virtual_value]
                else
                  @hash[name] = nil
                end
              end
            end

**Comment by joaomdmoura** [comment]
Hey @mrsutter, indeed 0.10.x right now does not support nested association, but that is something we look forward to! It's mandatory to 0.10.x release and I mention it on the [Future of AMS article](https://medium.com/@joaomdmoura/the-future-of-ams-e5f9047ca7e9).
You can make nested association using json-api and `include`, but would be just a workaround that might not suit you if you don't want to follow json-api conventions.

**Comment by johnnagro** [comment]
+1 same experience in my testing of 0.10.rc2

**Comment by johnnagro** [comment]
@mrsutter interesting: https://github.com/rails-api/active_model_serializers/pull/1073 and: https://github.com/rails-api/active_model_serializers/issues/921

**Comment by mankind** [comment]
@joaomdmoura  you mentioned that we could make nested association using json-api and include. I am using 0.10.0.rc2 and tried making nested association with include but it is not working.

       class UserSerializer < ActiveModel::Serializer
            attributes :id, :email
            has_one :account
       end

       class AccountSerializer < ActiveModel::Serializer
            attributes :id, :name, :domain
            has_many :segments
       end

       class SegmentSerializer < ActiveModel::Serializer
            attributes :id, :name,  :active
            has_many :base_segments
            has_one :account
        end

        class  Api::UsersController < ApplicationController
            def index
                @users = User.all
                render json: @users, include:  ['account', 'account.segments'] 
            end
        end
     
I also tried **render json: @users, include:  ['account', 'segments']**
Is there I anything I am missing to get this working. Thanks for your guidance and for your work on this gem.

**Comment by joaomdmoura** [comment]
So just updating this thread it seems we are getting close to get it on #1114 cc @johnnagro @mrsutter

**Comment by NullVoxPopuli** [comment]
resolved by #1127

**Comment by malroc** [comment]
@joaomdmoura @NullVoxPopuli I'm not sure about this solution. Am I right that we have to specify `include: ...` every time we need to serialize a nested association?
Isn't it the syntax AMS is supposed to replace? Instead, in the current implementation it is just moved one level deeper.
There was a great convention implemented in 0.8.x branch: if we need to serialize an association, the serializer of the association is called recursively. That was a great, clean, and intuitive approach. I'm not sure why it can't be used in 0.10.x

**Comment by malroc** [comment]
Also, I can try to implement 0.8.x approach for 0.10.x and send a pull request with the solution, but not sure about the exact dates.

**Comment by beauby** [comment]
See #1157, #1190.

**Comment by beauby** [comment]
Nested associations are back, and you can control what exactly will be nested through the `include` adapter option (#1158, #1127), or simply trust your serializers to choose for you by supplying the `include: '**'` to the adapter (default is to include only the first level of relationships).

Closing this for now, feel free to reopen if needed.
