### ISSUE TITLE
Respect controller namespace when looking up serializers

### ISSUE THREAD

**Issue by chancancode** [rails-api/active_model_serializers#108]
I have name-spaced my API controllers like so:

``` ruby
module EngineName
  class Post < ActiveRecord::Base; end

  class API::V1::APIController < ActionController::API; end

  class API::V1::PostsController < API::V1::APIController
    def index
      @posts = Post.all
      render json: @posts
    end
  end
end
```

Since each API version might serialize the models differently, ideally the serializers should be namespaced accordingly like so:

``` ruby
module EngineName
  class Post < ActiveRecord::Base; end

  class API::V1::PostSerializer < ActiveModel::Serializer
    attributes :id, :title, :body
  end

  class API::V1::APIController < ActionController::API; end

  class API::V1::PostsController < API::V1::APIController
    def index
      @posts = Post.all
      render json: @posts, serializer: PostSerializer # resolves to ::EngineName::API::V1::PostSerializer
    end
  end
end
```

This gets quite repetitive when you have to do it for all your controllers. I am wondering if it is possible to take into account of the controller's scope when looking up a serializer. In the example above, `render json: @posts` should these in order (via `controller.class.const_get :PostSerializer`):

``` ruby
::EngineName::API::V1::PostsController::PostSerializer
::EngineName::API::V1::PostSerializer
::EngineName::API::PostSerializer
::EngineName::PostSerializer
::PostSerializer
```

(I also thought about overriding `default_serializer_options` in `APIController`, but that won't work as the options are [merged _after_ the serializer lookup](https://github.com/josevalim/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L57), so `def default_serializer_options; { serializer: SomeSerializer }; end` won't work.)

**Comment by mattvague** [comment]
Anyone coming across this issue in the brave new world of 2017 should look here: https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#namespace

**Comment by pjg** [comment]
Anyone coming across this issue in the brave new world of 2018 should look here:
* https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/rendering.md#namespace
