### ISSUE TITLE
Using Ember Data 2.0.0-beta1 with ActiveModel::Serializer::Adapter::JsonApi

### ISSUE THREAD

**Issue by mattboldt** [rails-api/active_model_serializers#1080]
Since the new ember no longer has `DS.ActiveModelSerializer` or `DS.ActiveModelAdapter`, I'm looking to switch to their new `DS.JSONAPISerializer`. This seems to be the best way to go, if the previous two won't be supported in the future.

Ember is expecting the data from the api to be something like 
```
store.push({
  data: {
    id: '1', 
    type: 'user', 
    attributes: { 
      name: 'Pangratz' 
    }
  }
});
```

But from my rails app, with the `:json_api` option set to true, my api is returning `user` as `users` plural.

```
  data: {
    id: '1', 
    type: 'users', 
    attributes: { 
      name: 'Pangratz' 
    }
  }
```

Ember expects a singular model name, and as such cannot push data.

**Comment by beauby** [comment]
Right, the JSONAPI spec does not take a stand on whether the `type` should be singular or plural. I think there should be a global config for `ActiveModel::Serializer` to pluralize or not the resources.

**Comment by beauby** [comment]
I'm working on a PR to add this. Should be ready in a few minutes. Could you test it when it's out?

**Comment by mattboldt** [comment]
Absolutely!

**Comment by beauby** [comment]
@mattboldt Here it is. Simply set `ActiveModel::Serializer.config[:jsonapi_resource_type] = :singular` and it should work.

**Comment by mattboldt** [comment]
Yes, this worked! Thanks so much.
