### ISSUE TITLE
Passing in parameters from controller (0.9.3)

### ISSUE THREAD

**Issue by yijia-zhan** [rails-api/active_model_serializers#1085]
I've looked at https://github.com/rails-api/active_model_serializers/issues/946, https://github.com/rails-api/active_model_serializers/issues/599 and [this stackoverflow question](http://stackoverflow.com/questions/23347587/how-to-pass-parameters-to-activemodel-serializer). However, the approach suggested to pass options from controller to serializers for (0.9.3) doesn't seem to work for me:

```ruby
# in controller
render json: @posts, param_a: "abc", param_b: "xyz"

# in PostSerializer
def some_attribute_method
  # "serialization_options" is an empty hash here
end
```

The only way I can sort of pass in stuff is by using `scope`, suggested by @joaomdmoura in https://github.com/rails-api/active_model_serializers/issues/946. However, this seems to affect how records are retrieved.

```ruby
# in controller
render json: @posts, scope: { param_a: "abc", param_b: "xyz" }

# PostSerializer
def some_attribute_method
  # "scope" is available here 
end
```

Is there any other way I can achieve this? Thanks!

**Comment by yijia-zhan** [comment]
Just figured out the `serialization_options` way of passing in arguments. Turned out it's a `to_json` bug from OJ, https://github.com/ohler55/oj/issues/244, https://github.com/ohler55/oj/pull/252. In the latest release(2.1.2) Oj now supports arguments in the `to_json` method. 

However, it seems that the parameters from controller only get passed to the top node serializable object. For example:

```ruby
# in controller
render json: @blogs, param_a: "abc", param_b: "xyz"

# in BlogSerializer
class BlogSerializer < ApplicationSerializer
  has_many :posts

  def some_blog_attribute_method
    # "param_a" and "param_b" are available in "serialization_options" here
  end
end

# in PostSerializer
class PostSerializer < ApplicationSerializer
  def some_post_attribute_method
    # "param_a" and "param_b" are NOT available;
    # "serialization_options" is empty hash here
  end
end
```

Is there any way to cascade down the serialization options?

**Comment by yijia-zhan** [comment]
Ahh looks like this patch https://github.com/rails-api/active_model_serializers/pull/748 for propagating `serialization_options` to associations has been merged to `0-9-stable` but not in `0.9.3`. Switching to the branch for now.

**Comment by joaomdmoura** [comment]
I'm glad you manage to find your way through this @yijia-zhan! Please let me know with the patch merged work, and would be nice to update the StackOverflow question base on your experience with this.

**Comment by beauby** [comment]
Closing this one for now as it seems to be solved. Feel free to reopen if needed.

**Comment by yijia-zhan** [comment]
I'm spiking to update to `0.10.0.rc3` from `0.9.3`. Looks like `serialization_options` has been removed in `0.10.x`, is there any alternative way to achieve this?

**Comment by sd** [comment]
in 0.10, it seems that the method you're looking for is "instance_options" 

# in controller
render json: @posts, param_a: "abc", param_b: "xyz"

# in PostSerializer
def some_attribute_method
  instance_options[:param_a] == "abc"
end

**Comment by yijia-zhan** [comment]
Thanks @sd, that's what I was looking for! It's in the current latest master but not `v0.10.0.rc3`. I'll switch to using master for now.

**Comment by alanwilhelm** [comment]
thx.. thats the 3rd iteration, from options to serialization_options to instance_options.. this one does make the most sense.

**Comment by kirley** [comment]
I'm using 
```
gem "active_model_serializers", "~> 0.10.0.rc3"
```
and the instance_options method doesn't exist.   
Here is the relevant code in my controller:

```
render json: resource, serializer: UserAuthSerializer, torii_provider: 'google', status: :created, adapter: :flatten_json and return
```
and in my serializer:

```
def provider
    instance_options[:torii_provider] || 'devise'
end
```
I couldn't find where this happens in the source, perhaps someone can help point me in the right direction?

**Comment by yijia-zhan** [comment]
@kirley, `instance_options` is not available in rc3. Switch to master for now.

**Comment by kirley** [comment]
@yijia-zhan - Thanks.

**Comment by beauby** [comment]
@kirley I believe `options` was renamed to `instance_options` in rc3, so there's a chance you could stick with rc3 and use `options` if using master is not possible in your case.

**Comment by CostaRico** [comment]
Hi, guys, I've tried rc1 and rc3, and both 'instance_options' and 'serialization_options'. No one works, anybody knows whats the right way in >10.0 versions? Thx a lot!

**Comment by yijia-zhan** [comment]
@CostaRico, just a couple comments up. `instance_options` are not in the current RC versions of `0.10.x`. For now you will need to use the `master` branch for it.

**Comment by CostaRico** [comment]
Thx! I missed it (end of the day)
gem 'active_model_serializers', :git => 'https://github.com/rails-api/active_model_serializers.git'
