### ISSUE TITLE
Add Code Climate Coverage and Quality Badges

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails-api/active_model_serializers#1086]
https://codeclimate.com/github/rails-api/active_model_serializers/code

Currently, they display as:

[![Code Climate](https://codeclimate.com/github/rails-api/active_model_serializers/badges/gpa.svg)](https://codeclimate.com/github/rails-api/active_model_serializers) [![Test Coverage](https://codeclimate.com/github/rails-api/active_model_serializers/badges/coverage.svg)](https://codeclimate.com/github/rails-api/active_model_serializers/coverage)

So, someone with proper permissions on the rails-api org will need to set up the coverage reporting.

**Comment by joaomdmoura** [comment]
Thanks @NullVoxPopuli we will do it for sure!

**Comment by bf4** [comment]
I can add the codeclimate simplecov formatter to https://github.com/rails-api/active_model_serializers/pull/1069 (the pr that introduces simplecov)

**Comment by bf4** [comment]
Done

**Comment by joaomdmoura** [comment]
Done.
