### ISSUE TITLE
Close all 0.8 & 0.9 issues

### ISSUE THREAD

**Issue by sandstrom** [rails-api/active_model_serializers#1087]
I'd suggest closing all 0.8 and 0.9 issues, with a friendly note asking people to reopen if it's still an issue under the 0.10 branch (or submit a PR with passing tests against the older branch).

A good deal of the issues are already labeled, so gardening should be fairly easy :tulip: :deciduous_tree:.

**Comment by ahmeij** [comment]
I'd suggest first making sure that 0.10 can actually replace 0.8 and 0.9. I think at least one of the sideloading pullrequests should be completed and merged before 0.8 and 0.9 can be phased out like this.

**Comment by joaomdmoura** [comment]
We have iced the 0.8.x and 0.9.x support for now, but we also know that upgrade from older version might be a little tricky, so we are aiming to have a section on our [new docs](https://github.com/rails-api/active_model_serializers/tree/master/docs) to help ppl into upgrading their apps.

Anyway, I also feels there is a lot of older issues that might not even suit the older version, I think after 0.10.x release we need some sorte of clean up as suggested here. But right now we would not be able to handle ppl reopening issues and asking about updates on older versions.

**Comment by sandstrom** [comment]
That's a valid point, I agree on having a path ready first.
