### ISSUE TITLE
Getting the serialized hash without render

### ISSUE THREAD

**Issue by PericlesTheo** [rails-api/active_model_serializers#1101]
Hey humans,

Let's say I have

```ruby
class MessageSerializer < ActiveModel::Serializer
  attributes :content

  belongs_to :user
end
```

When I use `render json: @message` in the controller I get `{:message=>{:content=>"some peoisadfnsaidfnple like wefaefsushi", :user=>{:email=>"hi@example.com"}}}` which is what I'd expect.

However, I'd like to be able to get the same serialization without using `render` in the controller.

I couldn't find anything in the docs and the only way around I found is 
```
ActiveModel::Serializer::Adapter::Json.new(MessageSerializer.new(Message.last)).serializable_hash
```

Is there an easier way of achieving the above?

Cheers!

**Comment by bf4** [comment]
What version of AMS are you on?  That's more or less right. Take a look at `SerializableResource` or some of its tests if you're on 0.10.x but not on master

ref (just to link relevant issues/prs here for us and the future):
- https://github.com/rails-api/active_model_serializers/issues/1011
- https://github.com/rails-api/active_model_serializers/pull/1099
- https://github.com/rails-api/active_model_serializers/issues/878#issuecomment-96073030
- https://github.com/rails-api/active_model_serializers/pull/967
- https://github.com/rails-api/active_model_serializers/issues/1036
- https://github.com/rails-api/active_model_serializers/issues/1074
- https://github.com/rails-api/active_model_serializers/issues/1083
- https://github.com/rails-api/active_model_serializers/issues/1064
- https://github.com/rails-api/active_model_serializers/issues/1002
- https://github.com/rails-api/active_model_serializers/pull/954
- https://github.com/rails-api/active_model_serializers/issues/947
- https://github.com/rails-api/active_model_serializers/pull/1092#discussion_r38205560
- https://github.com/rails-api/active_model_serializers/pull/1093
- https://github.com/rails-api/active_model_serializers/pull/1093

**Comment by PericlesTheo** [comment]
I'm following the master branch currently on `0.10.0.rc2`

I had a look before in the SerializableResource` but probably I missed something as one can use `ActiveModel::SerializableResource.new(Message.last).serializable_hash` instead.

Should a reference of the above be added to the documentation? It would have saved me quite some time :)

**Comment by bf4** [comment]
Yes please!

B mobile phone

**Comment by beauby** [comment]
Should we close this issue now that the question seems to have been answered?

**Comment by PericlesTheo** [comment]
Yeap, I will create a PR for hopefully today. Cheers

**Comment by joaomdmoura** [comment]
Nice, I glad that you find your way through it @PericlesTheo, Would be nice to have it on our [new docs](https://github.com/rails-api/active_model_serializers/tree/master/docs) as well.

**Comment by PericlesTheo** [comment]
I know I'm terrible :(

I should have done it last week.

I'll try tonight

**Comment by joaomdmoura** [comment]
haha np, tks! :smile:
