### ISSUE TITLE
Consider refactoring override implementation _render_with_renderer_json

### ISSUE THREAD

**Issue by ccleung** [rails-api/active_model_serializers#1115]
Currently active model serializer only supports serialization to json of it's serializable hash

It would be nice to support other formats, such as xml, and can be as simple as adding `_render_with_renderer_xml` to the list here:
https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L49

and implementing something similar, or exactly the same as `as_json` but for xml in the adapter:
https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter.rb#L33

Rather than changing the existing codebase to support multiple formats, would it be possible to move https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L49

into a helper method that I can use to define an override for other formats, such as `_render_with_renderer_xml` ?

**Comment by joaomdmoura** [comment]
Hey @ccleung, first of all thank you for contributing :smile: 
Actually the whole idea of the `Adapters` is to enable developer into doing exactly what you suggested.

> Adapters describe how attributes and relationships should be serialized.

So we incentivize developers to create their on adapters, and then use it and submit it as a PR to us, basically trying to isolate all logic inside an `xxx_adapter.rb` file as we have `flatten_json_adapter.rb`, `json_adapter.rb` and `json_api_adapter.rb`.

Of course we might need to do some small changes on `action_controller/serialization.rb` but the idea is to isolate logic to specific rendering inside adapters. :smile:

**Comment by ccleung** [comment]
Ah I see, is there an example of how to configure different adapters for different formats (e.g., xml, json, csv...)?

Or would I extend an adapter, e.g., `:json` adapter, and try to hook into the xml renderer...? I know that the base adapter has a `as_json` (https://github.com/rails-api/active_model_serializers/blob/v0.10.0.rc2/lib/active_model/serializer/adapter.rb#L23) method that hooks into the rails json renderer.

**Comment by beauby** [comment]
@ccleung You are right, the adapters do not actually build any json, but just hashes that represent the structure of the serialized data. Hence, your first hunch was right, you do need to add `_render_with_renderer_xml` to the list. You also need to add something like `as_json` to the [adapter](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter.rb#L33)
However, Rails seems not to handle xml exactly like json, as far as separating the concerns between `as_*` and `to_*`, so you actually need to override `to_xml` instead of `as_xml`, like the following:
```ruby
      def to_xml(options = nil)                                                                                                                                                                             
        hash = serializable_hash(options)                                                                                                                                                                   
        include_meta(hash)                                                                                                                                                                                  
        hash.to_xml                                                                                                                                                                                                
      end 
```
Just tested it, it works like a charm.

**Comment by beauby** [comment]
@ccleung See #1133

**Comment by ccleung** [comment]
@beauby great looks like what I need!

And if I have additional formats I would need to support, such as say csv, would I append to `RENDERER_METHODS ` ? and create an adapter method to handle returning the seriliazable hash, similar to the xml PR?

**Comment by bf4** [comment]
@ccleung I'm curious, are you trying to represent json as xml?

**Comment by beauby** [comment]
@ccleung Technically yes, but you would have to build the string yourself in `to_csv`. However, I am not too sure AMS would be the right tool for CSV as it is a linear format, and makes it a pain to serializer relationships.
@bf4 You are right, but you don't need anything special to render json either!

**Comment by ccleung** [comment]
@bf4 I'm trying to take the `serializable_hash` i.e., https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json.rb#L7,  that activemodelserializer's adapter providers, and convert that to xml (e.g., calling `to_xml` on the hash that `serializable_hash` returns)

**Comment by bf4** [comment]
> I'm trying to take the serializable_hash i.e., https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json.rb#L7, that activemodelserializer's json adapter forms, and convert that to xml (e.g., calling to_xml )

@ccleung but why? does the record not serialize the way you want on its own?  AMS has a goal of helping you compose JSON and a record. Its origins and development are tied to JSON API and Ember.  I'm not say it's can't be used for XML, but I think, from a maintainer point of view, I wouldn't want to expand the scope of the gem, though I'd be ok if people write their own adapters, and as an end user, it's probably more work to use than an existing solution... my thoughts are own... from my point of view... so, opinions may diff

**Comment by beauby** [comment]
@bf4 Adapters themselves don't have much to do with JSON, they're merely a way of aggregating and organizing model data for presentation. The actual format you use for presentation is not really a concern.

**Comment by bf4** [comment]
I'd rather write instructions in the README on how to use it for other media types and encourage people to share issues and pull requests they encounter.

I just don't think expanding the scope of AMS is good for the project, which is different from saying it can't do it.  Also, I think think the library has code rot that should be cleaned up first.

**Comment by ccleung** [comment]
@bf4 @beauby I'm using the active model serializer in my current API. the json adapter gives me a hash in exactly the format I want, and if a user requests the response to be in xml, Ideally I would want the has to be transformed into xml in the response.

I see that this method: https://github.com/rails-api/active_model_serializers/blob/v0.10.0.rc2/lib/action_controller/serialization.rb#L37 has been refactored to `get_serializer` in master:
https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L51

perhaps then I can either override `_render_with_renderer_xml ` myself or create a custom `ActionController::Renderers.add` to:

1.) `get_serializer.as_json` to get the hash that AMS creates nicely for me
2.) call `to_xml` to get the xml representation

That way we do not need to change AMS, the customization can happen in my application instead

**Comment by bf4** [comment]
@ccleung Exactly. So, https://github.com/rails/activemodel-serializers-xml aka https://github.com/rails/rails/blob/4-2-stable/activemodel/lib/active_model/serializers/xml.rb#L196-L235 doesn't do the job? nor things like builder or oat or...

**Comment by ccleung** [comment]
@bf4 I won't be able to get the hash that AMS gives me using the links you sent, since AMS only overrides and takes care of `_render_with_renderer_json`

Once master is released though, I can easily get the AMS serializer_hash, and will not need to modify AMS gem itself

**Comment by beauby** [comment]
Closing this one as there will probably not be any official XML support.
