### ISSUE TITLE
Ember 2.0

### ISSUE THREAD

**Issue by xn** [rails-api/active_model_serializers#1134]
I've been reading the issues all morning trying to puzzle out which version of AMS and which adapter I need to use to communicate with ember data 2.0 and what I would need on the ember side as well. I see the underscore fix in #974, btw. It seems the release candidate and the jsonapi adapter isn't there yet. 

Can anyone point me in the right direction?
thanks.

**Comment by bf4** [comment]
Ember does support multiple adapters, and last time I looked, it's support of JSON API 1.0 wasn't complete, either.  If you're proficient at JavaScript, using the AMS JsonApi adapter on the Ruby side and customize your adapters as needed on the Ember side, you should have no problems.  Ember has built in dasherize and camelize  support, so master (0.10.rcx)  should be ok.  Maybe see

- https://github.com/kurko/ember-json-api
- https://github.com/pixelhandler/ember-jsonapi-resources
- https://github.com/ember-data/active-model-adapter/tree/master/addon

There are also other Ruby libraries you can use mentioned on http://jsonapi.org/implementations/

**Comment by xn** [comment]
Thanks!

**Comment by joaomdmoura** [comment]
Nice @bf4, maybe you could write a docs article about the easy way to integrate it before we release it :grin:

**Comment by bf4** [comment]
:eyes:
