### ISSUE TITLE
Handling Reserved Words

### ISSUE THREAD

**Issue by t2** [rails-api/active_model_serializers#1135]
I have a column named `method` on my payment model. This is throwing AMS for a loop. Giving me an error `ArgumentError (wrong number of arguments (0 for 1))`. Any way to circumvent this without changing the column name? That would be a huge hassle.

**Comment by bf4** [comment]
If you could use a different name that would really be best.  Besides in this library, replacing `Object#method(name)` with `Foo#method` is going to cause lots of unexpected bugs.  it's best to avoid names like `method`, `end`, `class`, and other core methods make your app work.

However, good news, you don't need to change the column name.  In your Rails record you can `alias_attribute :method, :some_method` and in your serializer refer to `:some_method`.

**Comment by t2** [comment]
@bf4 Thanks for the quick response! I was afraid of that. I have aliased the `:method` attribute even though is pains me :). Btw, for anyone reading this, it is actually `alias_method :some_method, :method`.

**Comment by bf4** [comment]
Thanks @t2 I thought I might have it reversed. Did `alias_attribute` not work?  That's better for Rails.

There's just some words in any language you want to avoid.  Also, 'case', 'task', 'process', 'object'..

**Comment by t2** [comment]
@bf4 Worked like a charm. I was afraid of that when building the model but wanted to be concise with my column names. I try to keep away from the underscore as much as possible. I aliased `:payment_method` with `:method` and all works as it should. I'll just cringe a little while typing it :smile:.

**Comment by adaam2** [comment]
Just to reiterate for those who are running into a problem with defining keys that match method names already defined in the `ActiveModel::Serializer` class, you can use the below (I was trying to define a key in the serialized output named `attributes` which is one of methods used in AMS to define the payload keys):

```
    attribute(:attributes) { custom_attributes }

    def custom_attributes
      {

      }
    end
```

**Comment by bf4** [comment]
Yeah, @adaam2 that would be a problem.  Thanks for the workaround. You could also specify the 'key' option, I think
