### ISSUE TITLE
Serializer is generated incorrectly when using references

### ISSUE THREAD

**Issue by zach-taylor** [rails-api/active_model_serializers#1145]
Using Rails 5 (master) and Ruby 2.2.3 and a fresh Rails API application (`rails new --api`), the following scaffold generation command:

`bundle exec rails g scaffold user organization:references name:string ...`

Produces:

```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :id, :name
end
  attribute :organization
```

**Comment by beauby** [comment]
I just tried and it produces:
```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :id, :name
  has_one :organization
end
```

Which version of AMS are you using?

**Comment by zach-taylor** [comment]
Hey @beauby. I'm using version 0.10.0.rc2

**Comment by beauby** [comment]
Bug confirmed, and I can confirm the bug is fixed in master (which will become RC3 in a few hours).

**Comment by zach-taylor** [comment]
Thank you!
