### ISSUE TITLE
Missing custom root ability in 0.10.x

### ISSUE THREAD

**Issue by yoda** [rails-api/active_model_serializers#1151]
The ability to customise the root json key has gone missing in 0.10.x. I think there has been some sort of merge issue or divergence from master as this doesn't seem to occur on master.

Problem on 0-10-stable
https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/active_model/serializer.rb#L170-L172

Issue seemed to occur at:
https://github.com/rails-api/active_model_serializers/commit/329691276a1bb2827f20bceda5d15fd79a08d3dc

Then it seems it was recitifed in this saga:
https://github.com/rails-api/active_model_serializers/pull/1013

Currently on master:
https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L125-L127

**Comment by joaomdmoura** [comment]
Yup, It's  working on master, and will be back on RC3 that will be release in a few hours :smile:

**Comment by yoda** [comment]
hooray thanks again

**Comment by beauby** [comment]
Closing as the issue seems to be solved. Feel free to reopen if needed.
