### ISSUE TITLE
Problem with namespacing

### ISSUE THREAD

**Issue by ciaoben** [rails-api/active_model_serializers#1152]
in my controller I call:

    render json: @customers_filtered, serializer: User::CustomerSerializer

My serializer:
```
module User
    class CustomerSerializer < ActiveModel::Serializer
      attributes :id, :firstname
    end
end
```

But when I call the controller's action, it gives me:

```

undefined method `id' for #<User::Customer::ActiveRecord_Relation:0x007f3f431ab678> Did you mean? #ids
```
But my Customer has the id attribute.

What is this `ActiveRecord_Relation` in the message? Why it is not a model?

**Comment by NullVoxPopuli** [comment]
Can you post your relevant models?
and, do you have a User class?

**Comment by ciaoben** [comment]
```
class User::Customer < ActiveRecord::Base
end
```

located in `models/user/customer.rb`

in the DB it has id, firstname, lastname

**Comment by NullVoxPopuli** [comment]
what's the definition of `User` look like?

**Comment by ciaoben** [comment]
User is not a class, it is only a namespace!

**Comment by NullVoxPopuli** [comment]
that's what I was hoping for :-)

but anywho, we'll need to write a test to verify this.

have you tried using the master branch of AMS?

**Comment by ciaoben** [comment]
I am actually using RC2

**Comment by NullVoxPopuli** [comment]
could you see if the issue exists on master?

you can just use 

`gem 'active_model_serializers', github: 'rails-api/active_model_serializers'`

if the issue persists, we'll file this as a potential bug.

Also, once that is tested, if you could paste the stack trace, that would be awesome.

**Comment by ciaoben** [comment]
Using the master branch, the error is now:
```
undefined method `read_attribute_for_serialization' for #<User::Customer::ActiveRecord_Relation:0x007f98a82b8868>
```

**Comment by NullVoxPopuli** [comment]
@ciaoben do you have a stack trace for that? (just between your render call and that error would be more than enough)

**Comment by ciaoben** [comment]
The error page it gives me only this under fulltrace:

```
app/controllers/user/customers_controller.rb:46:in `index'
app/controllers/application_controller.rb:35:in `block in with_timezone'
app/controllers/application_controller.rb:35:in `with_timezone'
```

But I don't think can be usefull

**Comment by NullVoxPopuli** [comment]
what about in your server log in the terminal?

**Comment by ciaoben** [comment]
```
I, [2015-09-15T15:02:10.635321 #2822]  INFO -- : Started GET "/api/customers?page=1&per=25&query=" for 10.0.2.2 at 2015-09-15 15:02:10 +0000
I, [2015-09-15T15:02:10.636259 #2822]  INFO -- : Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
I, [2015-09-15T15:02:11.068266 #2822]  INFO -- : Processing by User::CustomersController#index as JSON
I, [2015-09-15T15:02:11.068661 #2822]  INFO -- :   Parameters: {"page"=>"1", "per"=>"25", "query"=>""}
D, [2015-09-15T15:02:11.072079 #2822] DEBUG -- :   User::AuthInfo Load (1.2ms)  SELECT  `auth_infos`.* FROM `auth_infos` WHERE `auth_infos`.`session_token` = 'blurred LIMIT 1
D, [2015-09-15T15:02:11.075873 #2822] DEBUG -- :   User::Customer Load (1.7ms)  SELECT  `customers`.* FROM `customers` WHERE `customers`.`id` = 1 LIMIT 1
D, [2015-09-15T15:02:11.081759 #2822] DEBUG -- :   User::AuthInfo Load (3.1ms)  SELECT  `auth_infos`.* FROM `auth_infos` WHERE `auth_infos`.`authenticable_id` = 1 AND `auth_infos`.`authenticable_type` = 'User::Customer' LIMIT 1
D, [2015-09-15T15:02:11.085180 #2822] DEBUG -- :    (1.5ms)  SELECT COUNT(*) FROM `customers` WHERE (firstname like '%%' or lastname like '%%' or email_address like '%%')
D, [2015-09-15T15:02:11.090149 #2822] DEBUG -- :   User::Customer Load (1.4ms)  SELECT  `customers`.* FROM `customers` WHERE (firstname like '%%' or lastname like '%%' or email_address like '%%') LIMIT 25 OFFSET 0
I, [2015-09-15T15:02:11.133579 #2822]  INFO -- : Completed 500 Internal Server Error in 64ms (ActiveRecord: 7.5ms)
F, [2015-09-15T15:02:11.139971 #2822] FATAL -- : 
NoMethodError (undefined method `read_attribute_for_serialization' for #<User::Customer::ActiveRecord_Relation:0x007f98951bd890>):
  app/controllers/user/customers_controller.rb:46:in `index'
  app/controllers/application_controller.rb:35:in `block in with_timezone'
  app/controllers/application_controller.rb:35:in `with_timezone'


I, [2015-09-15T15:02:11.399871 #2822]  INFO -- :   Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (11.3ms)
I, [2015-09-15T15:02:11.407504 #2822]  INFO -- :   Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.9ms)
I, [2015-09-15T15:02:11.414961 #2822]  INFO -- :   Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
I, [2015-09-15T15:02:11.415304 #2822]  INFO -- :   Rendered /usr/local/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (31.8ms)
```

**Comment by NullVoxPopuli** [comment]
well, silly rails, that's not very helpful. haha

I'll see if I can come up with a test for this later today.

**Comment by ciaoben** [comment]
Thanks, will be great

**Comment by ciaoben** [comment]
An idea, should be implement a method to personalize the model (resource) of the Serializer. Would make things simplier

**Comment by beauby** [comment]
@ciaoben Could you post:
+ your `CustomerSerializer`
+ your `User::CustomersController#index` method

**Comment by ciaoben** [comment]
@beauby 

The serializer is exactly the simple one from the first post.

The method:

````
@page = params[:page] || 1
    @per = params[:per] || 25
    @query = params[:query] || nil
    customers = User::Customer.where("firstname like '%#{@query}%' or lastname like '%#{@query}%' or email like '%#{@query}%'")
    @total = customers.count
    @customers_filtered = pagination_filter customers, @page, @per
    
    render json: @customers_filtered, serializer: User::CustomerSerializer
````

**Comment by beauby** [comment]
Does adding `:id` to the attributes list of your serializer solve the problem?

**Comment by ciaoben** [comment]
@beauby no, sorry, I didn't notice that in the original post wasn't there... the :id attributes is present in the serialize, now I am editing the first post

**Comment by beauby** [comment]
Could you provide your `pagination_filter` method as well. I suspect this is where stuff is going wrong, as it seems to return an association.

**Comment by ciaoben** [comment]
```
def pagination_filter list, page, per = 25 
    if (list.class == Hash || list.class == Array)
      Kaminari.paginate_array(list).page(page).per(per)
    else
      list.page(page).per(per)
    end
  end
```

**Comment by beauby** [comment]
Just realized, you're serializing a collection with a serializer that's not designed for that. Try `render json: @customers_filtered, each_serializer: User::CustomerSerializer` (notice the `each_serializer` instead of `serializer`).

**Comment by beauby** [comment]
Closing this for now as I believe it is solved by my last comment. Feel free to reopen if needed.

**Comment by ciaoben** [comment]
@beauby I am sorry for my late response, but I did not get notified of your last solution. I had removed the gem because did not work, now re-installed, tested your method, and it works! thanks

**Comment by beauby** [comment]
@ciaoben Glad it did!

**Comment by joaomdmoura** [comment]
> now re-installed, tested your method, and it works! thanks
Nice :kissing_heart:
