### ISSUE TITLE
JSON adapter with empty array does not maintain root key

### ISSUE THREAD

**Issue by meltingice** [rails-api/active_model_serializers#1153]
If you attempt to serialize an empty array with the JSON adapter and ArraySerializer, the root key becomes an empty string. This issue is present in 0.10.0.rc2 and the latest master branch commit at this time (`17c353826056bc3eac3e6d6a2fd081af175bb6ad`).

**Example Code**
``` ruby
class Api::V1::ArticlesController < Api::V1::BaseController
  def index
    @articles = []
    render json: @articles, each_serializer: Api::V1::ArticleSerializer
  end
end
```

**Expected**
``` json
{
  "articles": []
}
```

**Actual**
``` json
{
  "": []
}
```

**Comment by beauby** [comment]
Thing is, when you have an empty array, there is no real way for AMS to infer the type of resources you would have had in it (at least not based on the resources themselves since, well there aren't any). Two possible workarounds:
+ explicitly specify the `root` option
+ make a custom collection serializer that inherits from `ArraySerializer` that sets the `root` for you.

**Comment by NullVoxPopuli** [comment]
AMS could attempt to safe_constantize the model part of  `{model}Serializer` and derive the root key from that?

**Comment by meltingice** [comment]
From a design standpoint, is there ever really an instance where you wouldn't have an array of homogenous object types? At least, for the JSON adapter? I don't see why AMS couldn't deduce the root key based on the serializer. The workarounds are fine, but it was definitely a surprise to me how it reacted in this instance. Doesn't seem like a good expected result.
--
Ryan LeFevre (@meltingice)
HODINKEE, Inc.
Sr. Software Engineer

    _____________________________

**Comment by NullVoxPopuli** [comment]
@beauby @joaomdmoura how do you feel about inferring the root name in this scenario? Can you think of any down sides?

**Comment by beauby** [comment]
I think we should do it but only if it cannot be inferred from the resources themselves (mainly because there are none), otherwise it will bring pain when serializing with a custom serializer (like `PostPreviewSerializer`).

**Comment by NullVoxPopuli** [comment]
yeah, that's what I was thinking.

**Comment by NullVoxPopuli** [comment]
Imma get a PR for this

**Comment by NullVoxPopuli** [comment]
Addressed in #1156

**Comment by bf4** [comment]
@meltingice are we discussing `Array.new` or `Article.none`?  

If `Array.new`, AMS does nothing to resources that have no serializer, and there's no serializer for the Array primitive ([0.10.0 master](https://github.com/rails-api/active_model_serializers/blob/610775a95fb4a9348990ace19f621a7921ae20c3/lib/action_controller/serialization.rb#L37-L39), [0.10.0.rc2](https://github.com/rails-api/active_model_serializers/blob/v0.10.0.rc2/lib/action_controller/serialization.rb#L51), [0.9.3](https://github.com/rails-api/active_model_serializers/blob/v0.9.3/lib/action_controller/serialization.rb#L55), [0.8.3](https://github.com/rails-api/active_model_serializers/blob/v0.8.3/lib/action_controller/serialization.rb#L50).  

The option for manually specifying the serializer is [`serializer`](https://github.com/rails-api/active_model_serializers/blob/v0.10.0.rc2/lib/action_controller/serialization.rb#L22), not [`each_serializer`](https://github.com/rails-api/active_model_serializers/blob/610775a95fb4a9348990ace19f621a7921ae20c3/lib/active_model/serializable_resource.rb#L37-L40).  Naming :boom: As I commented there:

>     # Get serializer either explicitly :serializer or implicitly from resource
    # Remove :serializer key from serializer_opts
    # Replace :serializer key with :each_serializer if present

Without `serializer`, it couldn't know the name of the instance variable.  The best it could do would be given no serializer is found for the argument to `json` in the controller, 

```ruby
class ArticleController < ApplicationController
  def index
   @articles = []
    render json: @articles, adapter: :json #=> { articles: [] }, where the resource root comes from the current controller.
  end
end
```

If `Article.none` (an empty collection), then it could find the serializer implicitly.

**Comment by meltingice** [comment]
Sorry, thought I replied to this, but must have forgotten to send the email. In this case it actually is `Array.new` because I'm not serializing an `ActiveRecord::Relation`.

**Comment by aserafin** [comment]
I've noticed it also doesn't respect the `root: false` option when we return empty array

**Comment by NullVoxPopuli** [comment]
For root false, the attributes adapter would cover that

**Comment by bf4** [comment]
@meltingice As I wrote in https://github.com/rails-api/active_model_serializers/issues/1153#issuecomment-140624893 there's no serializer for an Array, so AMS won't do anything and you'll get `[].to_json`. ref: https://github.com/rails-api/active_model_serializers/blob/architecture/docs/ARCHITECTURE.md  in https://github.com/rails-api/active_model_serializers/pull/1253

@aserafin 

> I've noticed it also doesn't respect the root: false option when we return empty array

Is that related to this issue?

**Comment by bf4** [comment]
Closing as stale. Please re-open if I closed this in error.
