### ISSUE TITLE
problem with loading ActiveModel::Serializer::Associations

### ISSUE THREAD

**Issue by shicholas** [rails-api/active_model_serializers#1170]
here's my stacktrace:

```
/Users/nick/.gem/ruby/2.2.3/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializer.rb:15:in `<class:Serializer>': uninitialized constant ActiveModel::Serializer::Associations (NameError)
        from /Users/nick/.gem/ruby/2.2.3/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializer.rb:4:in `<module:ActiveModel>'
        from /Users/nick/.gem/ruby/2.2.3/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializer.rb:3:in `<top (required)>'
        from /Users/nick/.gem/ruby/2.2.3/gems/active_model_serializers-0.10.0.rc3/lib/active_model_serializers.rb:21:in `<top (required)>'
```

It seemed to work fine when I required the associations file before ``active_model_serializers.``

FWIW I'm developing using AMS in a rails engine. I don't think that should matter, but maybe it does.

**Comment by NullVoxPopuli** [comment]
is this just when booting your app?

**Comment by shicholas** [comment]
yes

**Comment by shicholas** [comment]
* booting the app with the engine where I'm using AMS .10.rc3 in.

**Comment by NullVoxPopuli** [comment]
is your engine open source, or is there a way you can make an example engine demonstrating the problem?

**Comment by shicholas** [comment]
It's not but I can try to reproduce w/ an open-source project.

**Comment by bf4** [comment]
Looks like it may be a race condition.  Which Ruby are you on?

https://github.com/rails-api/active_model_serializers/blob/3f0794bd390521616c1270d1350b95ad31e0731c/lib/active_model/serializer.rb#L7-L15

should probably

```diff
-  autoload :Configuration
-    autoload :Associations
+  require 'ams/configuration'
+  require 'ams/associations'
    include Configuration
    include Associations
```

you can `bundle open active_model_serializers` try that, if it works, `bundle gem pristine active_model_serializers` and submit it as a PR :)

**Comment by shicholas** [comment]
ruby 2.2.3. and submitted a PR. Adding a require with the include did the trick.

**Comment by bf4** [comment]
yay!

**Comment by NullVoxPopuli** [comment]
@shicholas is this resolved?

**Comment by shicholas** [comment]
Yup, ha

**Comment by shicholas** [comment]
*thanks
