### ISSUE TITLE
Extract Attributes Adapter methods to a module to share between Attributes and Json for overriding.

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails-api/active_model_serializers#1179]
This is dependent on #1127 getting merged in to master as it contains a lot of refactoring of the now attributes adapter. 

So, if all the hash building methods get moved to a module, it would be really easy to change how relationships, and even the core data is added.

I forsee this affecting the json api adapter as well, and cleaning that up.

for example using sideloading:

lets say when building a relationship, you'd normally add a child relationship to the parent, like so:
```ruby
parent[key] = association
```

but when sideloading what you want to do is:
```ruby
parent[key_ids] = association_ids
_sideloaded[key] = association
```
(or something similar)

this can be done easily, by changing `add_resource_relationships` to call a method that takes a block for how to build the connection to the association.

```ruby
#add_resource_relationships
if serializer.respond_to?(:each)
  add_to_parent(parent, key, options) do
    to_many_relationship_for(serializer, options)
  end
else
  add_to_parent(parent, key, options) do
    to_one_relationship_for(serializer, options)
  end
end
```

and then for the attributes adapter, `add_to_parent` would be as simple as:
```ruby
def add_to_parent(parent, key, options)
  parent[key] = yield
end
```

but for sideloading it would be something like this
```ruby
def add_to_parent(parent, key, options)
  if options[:sideload]
    _sideloaded ||= {}
    associated = yield
    _sideloaded[key] = associated
    ids_key = key.to_s.singularize.foreign_key.pluralize.to_sym
  
    # in an actual implementation, we'd want to add to what's already on the key's value,
    # rather than replace it.
    parent[ids_key] = associated.is_a?(Array) ? associated.map{ |a| a[:id] } : associated[:id]
  else
    parent[key] = yield
  end
end
```

and then for the json api adapter, it could do something similar, but with it's format. (I'm not familiar enough with json api to give an example)

* just ideas - this isn't the best use of yield there is, but... I think the core concept should be have the super basic functionality extract from all adapters, and pass blocks for the parts that are specific to each adapter.

**Comment by NullVoxPopuli** [comment]
Or, maybe a lot of the methods in attributes can get moved to adapter::base, since all the adpters are pretty much going to have the same association traversing logic.

**Comment by NullVoxPopuli** [comment]
here is a better example of the refactor: https://github.com/NullVoxPopuli/active_model_serializers/pull/1/files

I'd have to work pretty closely with whomever knows the most about the json api workings to get the pattern extracted to Adapter::Base or something.

**Comment by bf4** [comment]
I'd like to keep the Attribute adapter slim, and would prefer to avoid using inheritance through modules to avoid inheritance through classes

**Comment by NullVoxPopuli** [comment]
Yeah, after some more thought, I think this stuff would work better in `Adapter::Base`

**Comment by beauby** [comment]
I believe we did make a decision on this so I'm closing for now.

**Comment by NullVoxPopuli** [comment]
yup
