### ISSUE TITLE
Inheritance of serializer

### ISSUE THREAD

**Issue by givigier** [rails-api/active_model_serializers#1188]
```ruby
class ApplicationSerializer < ActiveModel::Serializer
  attributes :id
  def id
    "test"
  end
end
```
```ruby
class CustomerSerializer < ApplicationSerializer
end
```
I'm trying to use something like this on branch master AMS but it does not work. When I use CustomerSerializer, it does include the attribute :id. Is it possible to do this on AMS?

**Comment by bf4** [comment]
Try defining `read_attribute_for_serialization(attr)` on your model and handle id there

Otherwise, we'll need some more information of 
- what you're trying to serializer and 
- with what data
- what you expected
- what you saw
- what you tried
- ruby flavor and version, rails version

**Comment by bf4** [comment]
Also, if you could help improve https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md#how-can-i-help that would be great, too :)

(and https://github.com/rails-api/active_model_serializers#getting-help )

**Comment by givigier** [comment]
Thanks @bf4. I could ask this on Stackoverflow. Could you close this issue please?

**Comment by beauby** [comment]
@givigier Closing for now, please post the link of the StackOverflow question here if you do open one.

**Comment by bf4** [comment]
(And link from your question here, as well.)

**Comment by givigier** [comment]
http://stackoverflow.com/questions/32722921/inheritance-of-serializer

**Comment by givigier** [comment]
I guess that it's a bug. I'll try to explain exactly what I did.
I have two serializers, first is ApplicationSerializer and the second is CompanySerializer that inherits of ApplicationSerializer.
```ruby
class ApplicationSerializer < ActiveModel::Serializer
  def id
    object.slug
  end
end
```

```ruby
class V1::CompanySerializer < ApplicationSerializer
  attributes :id, :email
end
```
When I run  on ``branch: '0-10-stable'`` I got:

```json
{"id"=>"company-1", "email"=>"name3@email.com"}
```
"company-1" is the slug of company with email name3@email.com

When I run on ``branch: 'master'`` I got:

```json
{"id"=>"1", "email"=>"name3@email.com"}
```
In this case, slug is not setted as id. I also does not work when I try to use concerns like this:

```ruby
module SerializerSluggable
  extend ActiveSupport::Concern

  def id
    object.slug
  end
end
```
```ruby
require 'concerns/serializer_slugglable'
class V1::CompanySerializer <  ActiveModel::Serializer
  include SerializerSluggable

  attributes :id, :email
end
```
I got exactly the same result:

When I run  on ``branch: '0-10-stable'`` I got:

```json
{"id"=>"company-1", "email"=>"name3@email.com"}
```
"company-1" is the slug of company with email name3@email.com

When I run on ``branch: 'master'`` I got:

```json
{"id"=>"1", "email"=>"name3@email.com"}
```

My rails version is 4.2.2 and ruby version is 2.2.0.

**Comment by givigier** [comment]
@bf4 @beauby is there any info i could post here to explain better?

**Comment by NullVoxPopuli** [comment]
what happens if you do:

```ruby
resource = SerializableResource.new(@company, serializer: V1::CompanySerializer)
resource.serializer.id
```
?

**Comment by givigier** [comment]
```ruby
resource = ActiveModel::SerializableResource.new(@company, serializer: V1::CompanySerializer)
resource.serializer.id
```
return NoMethodError: undefined method `id' for V1::CompanySerializer:Class

**Comment by NullVoxPopuli** [comment]
well, that didn't do what I thought it would... 

anyway,
I'll see if I can re-create your scenario in a test and debug a bit

**Comment by bf4** [comment]
I'm guessing the bug is in Serializer._attribute(*args) that conditionally defines attribute methods on the serializer , and that sonething is wrong in one of them

What's

ApplicationSerializer.instance_method(:id).source_location
ApplicationSerializer.instance_method(:id).source

And

CompanySerializer.instance_method(:id).source_location
CompanySerializer.instance_method(:id).source

And for each serializer

Serializer._attributes
serializer.attributes

On a SerializableResource you can call .serializer


B mobile phone

**Comment by beauby** [comment]
As you can see [here](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json_api.rb#L81), if the method `id` is defined on the serializer, that is what will be used as `id`. In your case, it seems like the `id` method is not defined on the inherited serializer. Could you post the output of what @bf4 suggested? That would probably help solve the issue pretty quickly.

**Comment by givigier** [comment]
```ruby
class Company < ActiveRecord::Base
end
```
Company is an ActiveRecord model. It's not necessary to add read_attribute_for_serialization(attr) or am I wrong?

@beauby I added ``id`` on serializer too and it does not work :cry: 
```ruby
class ApplicationSerializer < ActiveModel::Serializer
  def id
    object.slug
  end
end
```

```ruby
class V1::CompanySerializer < ApplicationSerializer
  attributes :id, :email
end
```

It only work when I'm using ``branch: '0-10-stable'``, on master it's broken.

**Comment by beauby** [comment]
> Company is an ActiveRecord model. It's not necessary to add read_attribute_for_serialization(attr) or am I wrong?

You're right about this.

In order to help you, we still need the output of:
```ruby
ApplicationSerializer.instance_method(:id).source_location
ApplicationSerializer.instance_method(:id).source

CompanySerializer.instance_method(:id).source_location
CompanySerializer.instance_method(:id).source

ApplicationSerializer._attributes
ApplicationSerializer.attributes

CompanySerializer._attributes
CompanySerializer.attributes
```

**Comment by givigier** [comment]
```ruby
ApplicationSerializer.instance_method(:id).source_location
```
["/Users/givigier/Sites/agrid-api/app/serializers/application_serializer.rb", 4]

```ruby
ApplicationSerializer.instance_method(:id).source
```
"  def id\n    object.slug\n  end\n"

```ruby
V1::CompanySerializer.instance_method(:id).source_location
```
["/Users/givigier/Sites/agrid-api/app/serializers/v1/company_serializer.rb", 9]

```ruby
CompanySerializer.instance_method(:id).source
```
"  def id\n    object.slug\n  end\n"

```ruby
ApplicationSerializer._attributes
```
[:id]

```ruby
ApplicationSerializer.attributes
```
[]

```ruby
V1::CompanySerializer._attributes
```
[:id, :email]

```ruby
V1::CompanySerializer.attributes
```
[]

**Comment by beauby** [comment]
So what happens is that, in your parent serializer (`ApplicationSerializer`), you define the method `id`, which get inherited to `CompanySerializer`. However, when you latter call `attributes :id, :email` in `CompanySerializer`, this overrides the custom `id` method inherited from `ApplicationSerializer`, and replaces it with a stock `def id; object.id; end`. This problem arrises only with the `id` attribute, because we somehow have to disable the check whether an `id` method already exists on the serializer when adding a stock one due to an `attributes` call (https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L65). I'll investigate this more thoroughly, but in the meantime, you could use a concern that you would include *at the end* of your serializer definition.

**Comment by beauby** [comment]
@givigier Could you test #1195 and confirm it fixes your issue?

**Comment by givigier** [comment]
It fixes the issue, thanks. I was going to try contributing but you fix fastly :+1:

**Comment by givigier** [comment]
@beauby Can I close the issue?

**Comment by beauby** [comment]
Sure :+1:
