### ISSUE TITLE
Include does not work on nested associations

### ISSUE THREAD

**Issue by givigier** [rails-api/active_model_serializers#1194]
I'm trying to use the feature of nested associations. My structure of serializers is:
```ruby
class V1::QuotesController < ApplicationController
  def show
    render json: @quote, serializer: V1::QuoteSerializer, include: { company: [:addresses, :phones] }
  end
end
```

```ruby
class V1::QuoteSerializer < ActiveModel::Serializer
  attributes :id
  has_one :company, serializer: V1::CompanySerializer
end
```

```ruby
class V1::CompanySerializer < ActiveModel::Serializer
  attributes :id
  has_many :phones, serializer: V1::PhoneSerializer
  has_many :addresses, serializer: V1::AddressSerializer
end
```

```ruby
class V1::AddressSerializer < ActiveModel::Serializer
  attributes :city
end
```

```ruby
class V1::PhoneSerializer < ActiveModel::Serializer
  attributes :number
end
```

When I add 'include' of associations on controller(like on QuotesController) it works fine and return:
``
{"id"=>"1", "company"=>{"id"=>"1", "addresses"=>[], "phones"=>[]}}
``

Otherwise, when I add 'include' of associations on serializer it does not work and doesn't return addresses and phones.

```ruby
class V1::QuotesController < ApplicationController
  def show
    render json: @quote, serializer: V1::QuoteSerializer
  end
end
```

```ruby
class V1::QuoteSerializer < ActiveModel::Serializer
  has_one :company, serializer: V1::CompanySerializer, include: [:addresses, :phones]
end
```

``
{"id"=>"1", "company"=>{"id"=>"1"}}
``

I was reading the docs and apparently it should work on serializer too.

**Comment by NullVoxPopuli** [comment]
It no longer is implemented on serializer association definitions. This was
a design decision. But an argument could be made for bringing it back.
Like, if you always want a few nested associations on a particular object.

**Comment by beauby** [comment]
As @NullVoxPopuli said, this feature is currently not part of master (only the adapter option). Could you provide a link to the doc where it says otherwise so that we correct it?

**Comment by givigier** [comment]
I was reading on https://github.com/rails-api/active_model_serializers/pull/1127. It's not a doc, sorry.

I understand the point that you said but this logic on controller is not against DRY? I'll need to set include on every controller that I use the serializer. If this logic was on serializer I didn't repeat on every controller.

**Comment by beauby** [comment]
@givigier Currently, we're thinking about going down the way described in #1193. Basically, what it allows, in your case, is:

```ruby
class V1::QuoteSerializer < ActiveModel::Serializer
  attributes :id
  has_one :company do
    attributes :id
    has_many :phones do
      attributes :number
    end
    has_many :addresses do
      attributes :city
    end
  end
end
```
Combined with `render json: @quotes, include: '**'`, it will have the desired result. Feel free to comment/add suggestions to #1090 (which is where we discuss how nested serializers should be).

**Comment by beauby** [comment]
Thanks for pointing out the inconsistent PR description though, I'm fixing this right now.

**Comment by givigier** [comment]
Thanks! I guess we could close this issue.
