### ISSUE TITLE
Associations no longer show when upgrading from 0.8.X to 0.9.X

### ISSUE THREAD

**Issue by nadeemja** [rails-api/active_model_serializers#1199]
Hi,

All of my associations disappear from the JSON when upgrading from 0.8.X to 0.9.X.

I've read the docs and the changelog and commits. There doesn't seem to be any breaking changes. 

Please help.

**Comment by bf4** [comment]
0.9 is quite different from 0.8..  You should either stay on 0.8 or move to the 0.10 rc (and please report and/or document any issues you have in upgrading)

**Comment by nadeemja** [comment]
Thanks. I will try it asap.

**Comment by nadeemja** [comment]
0.10.0.rc3 works!
