### ISSUE TITLE
JSON API - Include documentation

### ISSUE THREAD

**Issue by hut8** [rails-api/active_model_serializers#1200]
Looking here:

https://github.com/rails-api/active_model_serializers#json-api

it neglects to mention the `*` and `**` options which I found in `include_tree.rb`. Are these intentionally undocumented? Because `**`, I think, is exactly what I want in order to include one layer of everything. It seems like `**` isn't mentioned anywhere in the JSON-API spec, so is this intentionally undocumented in case support is removed? Or was this an oversight?

**Comment by beauby** [comment]
It is not mentioned yet, but will be. You're probably looking for `*` or `*.*` which respectively mean "include all first level relationships" and "include all first and second level relationships". `**` means "include *all* levels of relationships".

**Comment by beauby** [comment]
If you have time to make a PR for documentation on this, it would be amazing.
