### ISSUE TITLE
Recurse associations by default

### ISSUE THREAD

**Issue by brauliobo** [rails-api/active_model_serializers#1205]
Given these two serializers
```ruby
class TeamsPlugin::ContextSerializer < ActiveModel::Serializer
  has_many :teams, serializer: TeamsPlugin::TeamSerializer
end
class TeamsPlugin::TeamSerializer < ActiveModel::Serializer
  has_many :members, serializer: TeamsPlugin::MemberSerializer
end
```
If I call
```ruby
ActiveModel::SerializableResource.new(@article, serializer: TeamsPlugin::ContextSerializer)
```
It will serialize `teams`, but not `members`. For `members` I would have to specify `include: {teams: :members}` option for it to work.

But this seems very strange to me. Intuitively, by default it should go recursively.

**Comment by beauby** [comment]
You are right that the current default behavior of AMS with the Json/Attributes adapters is to embed only the *first level* associations. I am personally in favor of making the default embedding policy `**`, i.e. embed all levels, although we would need to add a check for infinite recursion in case the data graph has cycles. Thoughts @bf4, @NullVoxPopuli, @joaomdmoura?
As a workaround, you can specify `include: '**'` when serializing.

**Comment by brauliobo** [comment]
@beauby this is workaround is quite handy :)

**Comment by bf4** [comment]
I'd rather make deep nesting an intentional oractice, rather than easy, and so therefore like that more than two levels requires explicitness

B mobile phone

**Comment by beauby** [comment]
@bf4 I don't feel strongly either way, but it should be made clear in the docs so that people don't get surprised by this behavior (intuitively, at least I, would expect all relationships to be serialized for the Json/Attributes adapters).

**Comment by brauliobo** [comment]
@bf4 @beauby to make sense that the top association (`teams`) is going to get serialized, an option `include: true` on `has_many :teams` is necessary. otherwise, this option could be true recursively, by default.

**Comment by NullVoxPopuli** [comment]
I'm against having ** by default, as it could lead to an infinite loop of including, and redundant data. :-\

**Comment by brauliobo** [comment]
@NullVoxPopuli so what do you think about associations explicity saying they need to be included?

**Comment by beauby** [comment]
@NullVoxPopuli I agree this would happen, although it would just be the consequence of bad design (Json adapter + cyclic data graph).

**Comment by NullVoxPopuli** [comment]
The trend right now is to only have the model you ask for, and the ids of the asnociations for that model. I know ember prefers things to be sideloaded, so, this would align with that.  And there is a push for async relationships as well. But depending on what other people want to do, and what their workflow is, maybe we need a configuration option?

I don't know what is 'best', but having an AMS option that makes you specify what associations you want every time could be pretty helpful. Of course, you can do it right now just by passing empty string to the include option. When serializing

**Comment by beauby** [comment]
@NullVoxPopuli If you start doing sideloading and async relationships, you might as well go with JSON API. The goal of the Json adapter should not be to define a poor man's version of JSON API.

**Comment by NullVoxPopuli** [comment]
Agreed

**Comment by NullVoxPopuli** [comment]
We should maybe say that in the docs though, so people don't try it

**Comment by passalini** [comment]
I think that specify what associations you want is pretty helpful too and when I looked to the code I saw that adding 3 lines we can do it!!!

If I'm right (please correct me if I'm wrong) changing `#relationship_value_for` from the adapter will solve the problem. In my tests I created a new adapter...

```ruby
module ActiveModel
  class Serializer
    module Adapter
      class CustomAttributes < Attributes
        def serializable_hash_for_collection(options)
          serializer.map { |s| CustomAttributes.new(s, instance_options).serializable_hash(options) }
        end

        def relationship_value_for(association, options)
          return association.options[:virtual_value] if association.options[:virtual_value]
          return unless association.serializer && association.serializer.object

          include_tree_hash        = @include_tree[association.key].instance_variable_get(:@hash)
          include_association_hash = IncludeTree.from_include_args(association.options[:include]).instance_variable_get(:@hash)
          include_tree = IncludeTree.from_include_args(include_association_hash.merge include_tree_hash)

          opts = instance_options.merge(include: include_tree)
          CustomAttributes.new(association.serializer, opts).serializable_hash(options)
        end
      end
    end
  end
end
```

... now I can use `include` at the association's call just like in `controllers` and `serializers`...

```ruby
class UserSerializer < ApplicationSerializer
  has_many :accounts, serializer: UserScope::AccountSerializer, include: :roles
end
```

ps: the `include` from the `controller` still works and if you want you can overwrite the `include` from the association with it :)

**Comment by sandstrom** [comment]
I think many client-side applications are architected in a way that make it fairly easy to retrieve additional resources as needed. In addition HTTP/2 will make this cheaper (at the network level).

Thus, I'd vote for having it non-recursive by default (i.e. first-level only). But definitely in favour of making deep/recursive inclusion customisable.

**Comment by NullVoxPopuli** [comment]
I feel like at this point, everyone wants the json adapter to fit their specific use case -- it's not really capable of doing that.

I think the json adapter should be an example for how to make a basic adapter that aids in rendering basic json documents, such that users can implement whatever they need as they please.

JSON API is the future.

**Comment by prusswan** [comment]
Recurse was the default behavior in `0-9-stable`. To avoid confusion, the docs for 0.10 should mention this

**Comment by beauby** [comment]
@prusswan You are right. Would you mind issuing a PR to update the docs? That would really help.

**Comment by prusswan** [comment]
There is some inconsistency when using `include '**'` with associated models without explicit serializers (which I believe should default to the attributes adapter aka default Rails behavior). The result is also affected by `config.eager_load = true|false`, which is probably a bug. 

So it seems that 0.9 will be the stable release for quite some time to come, I tried working with 0.10 but it is just not suitable at this point.

**Comment by lserman** [comment]
I think recursing by default is fine because that was the behavior in 0.9.x (and 0.8.x afaik). What I would like though is a way to easily override the default serializer for associations via the adapter. In our case, we want to load only the IDs of the associated record unless explicitly included using the "include" parameter. Defaulting to one-level deep does not make sense for us.

Unless I am missing something, this requires a lot of rewriting and hacks because the serializer is already determined when it reaches the adapter. I was hoping to be able to just check the include tree, override the `serializer:` key in an options hash to an `IdSerializer`, and be done with it. The current adapter has `options` and `instance_options`, neither of which handle the `serializer` key.

**Comment by beauby** [comment]
So, the initial issue here is whether the `Attributes`/`Json` adapters should serialize all associations recursively by default.

Pros:
+ It is intuitive.
+ It was the behavior of 0.8 and 0.9.

Cons:
+ It crashes in case of cycles in the data graph.

The current consensus is that the default behavior will remain including only one level of relationships, although this should be explicitly stated in the docs.

For other issues mentioned here, please open separate GH issues.

Closing this issue for now, but feel free to keep commenting/making a case for it here.
