### ISSUE TITLE
[RFC] Clean up/rethink test infrastructure

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1206]
Currently the tests use models and serializers defined in `test/fixtures/poro.rb` and `test/fixtures/active_record.rb` (as well as some dynamically defined/locally scoped serializers inside tests) in combination with actual fixtures defined in the `setup` method of many test classes, which leads to lots of code duplication.
I am opening this RFC to discuss alternatives to this, as I feel writing tests should be easier and cleaner.

**Comment by NullVoxPopuli** [comment]
I've always been a fan of having a support folder under my test directory, and then having files named after groups of what they represent. I guess in our case, it could be: models.rb, serializers.rb, model_support.rb (this one could be the model object itself) etc.

**Comment by bf4** [comment]
ref something I wrote in RSpec on 0.10.0.rc1, https://github.com/rails-api/active_model_serializers/issues/878#issuecomment-96073030 as I will (hopefully) get to in https://github.com/rails-api/active_model_serializers/pull/967
