### ISSUE TITLE
Custom type for json-api adapter

### ISSUE THREAD

**Issue by youroff** [rails-api/active_model_serializers#1209]
Wouldn't it make more sense to have type set after serializer name, not the model class?
https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json_api.rb#L73-L79
I think that's the point of having multiple serializers for different occasions. In my example I have `ProfileSerializer`, but main object there is obviously `User`, however I expect Ember (which I use on front end) to understand that it's profile model came.

**Comment by youroff** [comment]
Just created a pull-request implementing something like this. I made it really simple so that if user sets type in serializer it'll be used, but also we can do setting to choose whether serializer class_name or model class_name should be used, or custom field.

https://github.com/rails-api/active_model_serializers/pull/1213

**Comment by beauby** [comment]
Closing as #1213 was merged.
