### ISSUE TITLE
cache not working

### ISSUE THREAD

**Issue by passalini** [rails-api/active_model_serializers#1210]
I google and try a lot, but I just can't see/do the AMS's cache work.
Right now I'm in `development env` using `0.10.0.rc3`

ps: I can use `Rails.cache` normally

```ruby
# enviroments/development.rb
  config.action_controller.perform_caching = true
  config.cache_store = :dalli_store, 'localhost:11211'
```

```ruby
# lesson_serializer.rb
class LessonSerializer < ActiveModel::Serializer
  cache key: 'lesson-serialized'
  delegate :cache_key, to: :object
  
  attributes ....
end
```

Any help will be very welcome!!

**Comment by passalini** [comment]
Update
----

I can see the cache working on ubuntu 15.04 but not in my other machine, OS X Yosemite 10.10.5,
both using rbenv, ruby 2.1.5 and rails 4.2.1.

I will close the issue, but when I figure out why it does not work in osx, I will do an updade here! 
:)

**Comment by beauby** [comment]
@passalini Great, please keep us posted if you find the reason so that we can include it in an FAQ.

**Comment by passalini** [comment]
@beauby today the code just work, memory's garbage perhaps? I don't konw yet, but if I figure out I will come back.

**Comment by sevab** [comment]
I have a similar issue, I was on `0.10.0.rc3` (specifically https://github.com/rails-api/active_model_serializers/tree/efe5128a2e6b8578d81bc7a807ace427c0b4d847) and updated to today's `master` (specifically https://github.com/rails-api/active_model_serializers/tree/df594c630db5b11c1c0b7c9f053fa4275a2ee035) and suddenly caching via `cache key: some_key` inside the serializer just stopped working, or at least no cache reads/writes are logged to the console. Caching via `Rails.cache.fetch` in the controller still works though.

I tried to find the last commit where caching still worked and https://github.com/rails-api/active_model_serializers/commit/21fe3abdfca7d78ef51ceaef0b2d194af560c5df is the last one. Starting from https://github.com/rails-api/active_model_serializers/commit/170db3ba88d9be78b61b22be4ceb91cdf7d4018c the caching stopped working.

I'm using OS X El Capitan, `ruby '2.3.0'` and `rails 4.2.1`.

`config.action_controller.perform_caching = true` is enabled

**Comment by bf4** [comment]
@sevab There's an open issue for this at https://github.com/rails-api/active_model_serializers/issues/923#issuecomment-167067238 if you'd like to repost there.

Also, I'm having a heckavu time demonstrating caching as improving performance,  and when that went away.  See https://github.com/rails-api/active_model_serializers/pull/1393 and I think https://github.com/rails-api/active_model_serializers/issues/1352 might help.  So, I'd appreciate any code you could share demonstrating the change in behavior and performance.   Maybe join the slack? https://github.com/rails-api/active_model_serializers#getting-help
