### ISSUE TITLE
NoMethodError: undefined method `key?' for nil:NilClass when using key

### ISSUE THREAD

**Issue by hut8** [rails-api/active_model_serializers#1211]
I was actually just trying to update my other pull request and was figuring out exactly what the "include" parameter expects for including related entities with JSON-API. Then I think I found a bug.

**Exception**

```
Frame number: 33/115
Frame type: method

From: /home/liam/fund-map/app/controllers/api_controller.rb @ line 8 ApiController#render_api:

    6: def render_api model
    7:   model = model.page(params[:page]) if model.is_a? ActiveRecord::Relation
 => 8:   render json: model, include: params[:include]
    9: end

NoMethodError: undefined method `key?' for nil:NilClass
from /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:95:in `block (2 levels) in associations'
[1] pry(#<Api::V1::OrganizationsController>)> wtf
Exception: NoMethodError: undefined method `key?' for nil:NilClass
--
0: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:95:in `block (2 levels) in associations'
1: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:94:in `each'
2: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb:94:in `block in associations'
3: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/adapter/json_api.rb:156:in `each'
4: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/adapter/json_api.rb:156:in `each'
--

```

**Working Steps**

I have a model that has this:
```ruby
has_many :organization_mappings
```

When I hit a route that invokes this code, it works great:

```
@organizations = Organization.all
render json: @organizations, include: 'organization_mappings'
```

**Broken Steps**

I have another model that has a `[model_name]_mappings` relationship, so be less redundant, I changed the `has_many` line to have a key:

```
  has_many :organization_mappings, key: :mappings
```

I figured that I would probably want to do this:

```
@organizations = Organization.all
render json: @organizations, include: 'mappings'
```

but that includes nothing. So then I tried the original, `include: 'organization_mappings'`, and it gave me the exception from above.

**Comment by bf4** [comment]
@NullVoxPopuli @beauby worked on that.  They may have some insight

**Comment by hut8** [comment]
Cool. Here's some stuff that might be useful from pry:

```
Frame number: 0/115
Frame type: block

From: /home/liam/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer/associations.rb @ line 95 ActiveModel::Serializer::Associations#associations:

    90: def associations(include_tree = DEFAULT_INCLUDE_TREE)
    91:   return unless object
    92:
    93:   Enumerator.new do |y|
    94:     self.class._reflections.each do |reflection|
 => 95:       next unless include_tree.key?(reflection.name)
    96:       y.yield reflection.build_association(self, instance_options)
    97:     end
    98:   end
    99: end

[5] pry(#<OrganizationMappingSerializer>)> include_tree
nil
```

**Comment by NullVoxPopuli** [comment]
@hut8 thanks for reporting this!

I'm at work right now, and can't look too deeply in to this for the next few hours. But if you have the time right now, it would be suuuuuuuuuper beneficial if you could maybe come up with a failing test for this scenarios?

we love PRs that are failing tests. they are best PRs :-)

**Comment by hut8** [comment]
Will do.

**Comment by NullVoxPopuli** [comment]
thanks a ton!

**Comment by hut8** [comment]
@NullVoxPopuli Done.

**Comment by NullVoxPopuli** [comment]
woo!

**Comment by beauby** [comment]
Ok, got it.
So, the issue is that [here](https://github.com/NullVoxPopuli/active_model_serializers/blob/issue/1211-failing-test/lib/active_model/serializer/adapter/json_api.rb#L136) and [here](https://github.com/NullVoxPopuli/active_model_serializers/blob/issue/1211-failing-test/lib/active_model/serializer/adapter/json_api.rb#L157), we use `association.key` and in [here](https://github.com/hut8/active_model_serializers/blob/ff87ac8b6f38d8bf6762387e6c6dc96ef7fb6f6e/lib/active_model/serializer/associations.rb#L95), we use `reflection.name`, which should really be `reflection.key`, both so that it does it does not crash and so that it is consistent with what a client might send as an include chain.
