### ISSUE TITLE
Deeply nested HABTM doesn't show in 0.10.0.rc3

### ISSUE THREAD

**Issue by nadeemja** [rails-api/active_model_serializers#1215]
Hi,

I have the following associations between three models:

Event has_many Schedules.
Schedule has_and_belongs_to_many Rooms

In 0.8.3, I get what i want:

    -Event
    -- Schedules:
    ---- Rooms:

In 0.10.0.rc3, I only get:

    -Event
    -- Schedules

I've downgraded to 0.8.3 for now.
Let me know if you need more info.

**Comment by NullVoxPopuli** [comment]
Hi there!

can you show us your serializer? and controller action where you are rendering the data?

**Comment by beauby** [comment]
Hi @nadeemja, in 0.10, the default is currently to serialize only the first level of relatinoships (this is being discussed here #1205). You can override this behavior either at the controller level, by specifying the `include: '**'` option in your render call (like `render json: @posts, include: '**'`), as *soon to be* mentioned in the docs (there's a pending PR to add this to the docs), or globally by subclassing `ActiveModel::Serializer` and overriding `serializable_hash`.

**Comment by NullVoxPopuli** [comment]
I'd be careful with `'**'` though. If you know exactly what associations you want, I think it would be safer to specify those. 

@beauby also has a pending PR where you can specify nested relationships in the serializers. see #1193

**Comment by beauby** [comment]
Closing this for now. Feel free to reopen if needed.
