### ISSUE TITLE
Inheritance of serializer does not inherits the cache!

### ISSUE THREAD

**Issue by passalini** [rails-api/active_model_serializers#1219]
I'm on `0.10.0.rc3` and when I do a serializer inheritance the child does not inherits the parent's cache config.. Is this expected or an issue? 

Expected or not, I think that it needs some doc.

**Comment by bf4** [comment]
Right now it is expected since it's a class method, not a `class_attribute`.  We could try a pr that changes 

```ruby
class << self
  attr_accessor :_cache #and whatever other
end
```

to 

```ruby
class_attribute :_cache, instance_writer: false, instance_reader: false
```

pr?

**Comment by passalini** [comment]
:+1: It will be nice! 

I tried to put this code in Gem's `Serializer` but just it does not work or I put it in the wrong place.. Right now I'm a little busy with russian dolls to spend more time with it, but when I finish it I will try to do your ideia work.
