### ISSUE TITLE
Deserialization

### ISSUE THREAD

**Issue by joaomdmoura** [rails-api/active_model_serializers#1238]
### **tl;dr**
The initial proposal of Deserialization is to convert your json input into something the ActiveRecord understands.

Edit: #1248 has been merged.

---
related to issues:
#1098

related to PRs:
#950
#1248

**Comment by frank06** [comment]
What's the status of deserialization?  Should I migrate to `jsonapi-resources` or will 0.10.x be out soon?

**Comment by beauby** [comment]
@frank06 I'm currently working on deserialization. You can check #1248 – would love your feedback on it.

**Comment by remear** [comment]
Basic deserialization is provided by #1248
