### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by groe** [rails-api/active_model_serializers#1244]
Hi,

I am currently thinking about migrating an existing [jbuilder](https://github.com/rails/jbuilder)-based API to ActiveModel::Serializers. However, I am not sure which version to use right now.

Version 0.9.3 is the latest stable on rubygems, but according to [this discussion on stackoverflow](http://stackoverflow.com/questions/23347587/how-to-pass-parameters-to-activemodel-serializer) the AMS team recommends 0.8 because 0.9 turned out to be a dead-end (I couldn't find the source of this statement however). Or is 0.10.0.rc3 stable enough for production already?

What would you recommend for a new project right now?

**Comment by beauby** [comment]
Hi @groe,

As the version indicates, 0.10.0.rc3 is a release candidate, meaning it's very close to being ready for prod. We're currently polishing the edges, and mainly adding some missing JSON API functionalities (but those were not present in 0.8/0.9 either). So I'd suggest using 0.10.0.rc3, as 0.10 is close to release.

**Comment by groe** [comment]
@beauby Awesome, that's what I was hoping to hear! :grinning: 

Thank you very much!

**Comment by joaomdmoura** [comment]
btw if you don't want ot be on cutting-edge 0.10.c-rc2 is a good option as well, You might not have some new features, but it would be something you would not have on 0.9/0.8 as well.
