### ISSUE TITLE
 No serializer found for resource

### ISSUE THREAD

**Issue by marucjmar18** [rails-api/active_model_serializers#1250]
AMS version -> 0.10.0.rc3
![Image of Yaktocat](http://i.imgur.com/OqrzQe3.png)

AMS version -> 0.9.3  All ok

**Comment by NullVoxPopuli** [comment]
can you post the model and serializer you expect it to use, and the controller action which tries to render with the serializer? 
thanks!

**Comment by bf4** [comment]
also, the full backtrace, ruby version, rand rails version (this should really all be in CONTRIBUTING.md but appears to be missing)

**Comment by bf4** [comment]
This is an expected situation for primitive associations, so we'll need more info to see why you're getting it. (It's handled later)

**Comment by marucjmar18** [comment]
model
```ruby
class Picture < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5 , maximum: 100 }
	validates :url, presence: true
	validates :user_id, presence: true

	has_many :picture_comments
	belongs_to :user
end
```
Serializer
```ruby
class PicturesSerializer < ActiveModel::Serializer
   attributes :id, :title, :url, :user_id, :rating,  :created_at

   has_one :user, serializer: SimpleUserSerializer
end
```
SimpleUserSerializer
```ruby
class SimpleUserSerializer < ActiveModel::Serializer
   attributes  :id, :nick, :avatar

end
```
grape controller
```ruby
module API
  module V1
    class Pictures < Grape::API
      include API::V1::Defaults

      format :json
      formatter :json, Grape::Formatter::ActiveModelSerializers

      resource :pictures do
        desc "Return pictures paginate"
        paginate per_page: 10, max_per_page: 200
        params do
          optional :top, type: Boolean
          optional :from_date, type: Date
          optional :to_date, type: Date
        end
        get "", root: :pictures, each_serializer: PicturesSerializer do
           ...
            pictures =  Picture.all.order(created_at: :desc)
            paginate pictures 
          end
        end
...
```

**Comment by bf4** [comment]
still missing https://github.com/rails-api/active_model_serializers/issues/1250#issuecomment-146139515

> also, the full backtrace, ruby version, and rails version (this should really all be in CONTRIBUTING.md but appears to be missing)

the fact that you're using Grape and not Rails is incredibly important to share. The gem you're using is out of date https://github.com/jrhe/grape-active_model_serializers/blob/ca9c8faaa99727300ff21419aa20471ac27eed42/lib/grape-active_model_serializers/formatter.rb#L15-L25

**Comment by bf4** [comment]
I'm going to close this, since it's a grape gem issue. I'll help you with a PR there if you want, or even a monkey patch

**Comment by bf4** [comment]
@rails-api/ams I'd be up for adding a grape adapter to AMS. It would be easier for end-users to track changes, and shouldn't include much code or otherwise involve much

**Comment by strivemag** [comment]
is there any news? @marucjmar

**Comment by asampatoor** [comment]
I am getting the same issue. Can anyone help me with this?

**Comment by marucjmar** [comment]
@strivemag, @asampatoor  Too old topic, I do not remember

**Comment by LeonidFilbert** [comment]
@strivemag, @asampatoor  add this to your config.ru: require 'grape-active_model_serializers'

**Comment by asampatoor** [comment]
@LeonidFilbert Thank you for the response. But that didn't fix the issue.
