### ISSUE TITLE
I found that root: false option is not working.

### ISSUE THREAD

**Issue by LcpMarvel** [rails-api/active_model_serializers#1256]
I use `ActiveModel::Serializer.config.adapter = :json` as adapter, but the `root: false` option is not working.

```ruby
render json: alliances,
           each_serializer: AllianceSerializer::Common,
           root: false
```

it will generate json as follow.

```ruby
{ alliance:  { id: 123 } }
```

**Comment by beauby** [comment]
In master, the way to remove the root of the JSON document is by using the `Attributes` adapter. Just pass the `adapter: :attributes` to your render call.

**Comment by LcpMarvel** [comment]
ok, thx
