### ISSUE TITLE
Grape Support

### ISSUE THREAD

**Issue by bf4** [rails-api/active_model_serializers#1258]
https://github.com/jrhe/grape-active_model_serializers/blob/ca9c8faaa99727300ff21419aa20471ac27eed42/lib/grape-active_model_serializers/formatter.rb#L15-L25

```ruby
        def fetch_serializer(resource, env)
          endpoint = env['api.endpoint']
          options = build_options_from_endpoint(endpoint)

          serializer = options.fetch(:serializer, ActiveModel::Serializer.serializer_for(resource))
          return nil unless serializer

          options[:scope] = endpoint unless options.key?(:scope)
          # ensure we have an root to fallback on
          options[:resource_name] = default_root(endpoint) if resource.respond_to?(:to_ary)
          serializer.new(resource, options.merge(other_options(env)))
        end
```
which uses `serializer = ActiveModel::Serializer.serializer_for(resource)).new(resource, options)` which is (somewhat intentionally) not supported in 0.10.

I'd be in favor of adding a grape serializer something or other (grape users can help here).

In the meantime, this may work

```diff
Grape::Formatter::ActiveModelSerializers.module_eval do # might be instance_eval
      class << self
        def fetch_serializer(resource, env)
          endpoint = env['api.endpoint']
          options = build_options_from_endpoint(endpoint)

           serializer = options.fetch(:serializer, ActiveModel::Serializer.serializer_for(resource))
-          return nil unless serializer


          options[:scope] = endpoint unless options.key?(:scope)
          # ensure we have an root to fallback on
          options[:resource_name] = default_root(endpoint) if resource.respond_to?(:to_ary)
+        serialization_options = options.merge(adapter: :json, serializer: merge!(other_options(env))).serializer) 
+          ActiveModel::SerializableResource.new(resource, serialization_options) # assuming you want json, I don't know which adapter to use

-          serializer.new(resource, options.merge(other_options(env)))
        end
  end
end
```

Related issues
- https://github.com/rails-api/active_model_serializers/issues/1250#issuecomment-146221950
- https://github.com/rails-api/active_model_serializers/issues/705
- https://github.com/rails-api/active_model_serializers/issues/1038#issuecomment-146658345
- https://github.com/rails-api/active_model_serializers/issues/1038

**Comment by bf4** [comment]
@rails-api/ams

**Comment by bf4** [comment]
ref: https://github.com/rails-api/active_model_serializers/issues/1268

**Comment by joaomdmoura** [comment]
Should we put it somewhere else, like docs? @bf4

**Comment by hut8** [comment]
Hey @bf4 -- thanks for documenting this. I'm a bit lost on this line:

```ruby
serialization_options = options.merge(adapter: :json, serializer: merge!(other_options(env))).serializer) 
```

Looks like unbalanced parenthesis and `merge!` isn't defined on that context.... what should this be?

**Comment by bf4** [comment]
I just wrote it up, untested, so do what makes sense? There's also a grape pr

B mobile phone

**Comment by bf4** [comment]
Implementation PR is in https://github.com/rails-api/active_model_serializers/pull/1273

**Comment by bf4** [comment]
Updated, is https://github.com/rails-api/active_model_serializers/pull/1336

**Comment by bf4** [comment]
Closed by https://github.com/rails-api/active_model_serializers/issues/1336
