### ISSUE TITLE
a "test" attribute on model will cause an exception

### ISSUE THREAD

**Issue by ryedog** [rails-api/active_model_serializers#1261]
If you have an attribute called "test" on your model it will throw an exception 

There is a "test" method from the kernel on Serializer so when serializing in the attributes instance method of ActiveModel::Serializer you'll get

```
 ArgumentError:
       wrong number of arguments (0 for 2..3)
     # /home/vagrant/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer.rb:156:in `test'
     # /home/vagrant/.rvm/gems/ruby-2.1.1/bundler/gems/active_model_serializers-1f08865a10bb/lib/active_model/serializer.rb:156:in `block in attributes'
```

The source of the test method is

```
ruby-2.1.1-p76 (#<BaseSerializer:0x0000000afe8e40>):0 > show-source self.test

From: file.c (C Method):
Owner: Kernel
Visibility: private
Number of lines: 137

static VALUE
rb_f_test(int argc, VALUE *argv)
{
    int cmd;

    if (argc == 0) rb_check_arity(argc, 2, 3);
    cmd = NUM2CHR(argv[0]);
    if (cmd == 0) {
```

Digging into the implementation of ActiveModel Serializer it's apparent that any attribute with the same name as a method on the Serializer will have similar issues.

**Comment by bf4** [comment]
yup, sorry about that.  do you not have a `test` method on your resource? I've seen similar issues with `select` which is an IO mixin that's in Kernel for some reason, and even a BasicObject has it

**Comment by bf4** [comment]
would it be helpful if we just defined a `test` and `select` method on the Serializer base object that raises if you try to call it but haven't defined it?

**Comment by beauby** [comment]
That sounds like a terrible idea, as we would keep defining many such methods as more similar issues arise.

**Comment by beauby** [comment]
Plus, it does not fix the situation where you have a `select` attribute on your model, and declare it as `attribute :select` in your serializer (as the serializer will see that `#select` is already defined on the serializer, thus not defining it as `object.select`).

**Comment by bf4** [comment]
Dunno, OP hasn't responded.  As to Ruby stdlib gotchas, those are the only two I can think of.  Anyhow, I just meant AMS could be nice and somehow tell you that you've asked for the `select` attribute but it's hitting Kernel.  I agree that I'm not sure that would necessarily be the better solution.  Hence the question :)

**Comment by beauby** [comment]
@bf4 There's also `binding`, `open`, `system` among those most likely to cause trouble.

**Comment by beauby** [comment]
Closing, as a fix has been merged in master. Could you confirm @ryedog ?
