### ISSUE TITLE
Missing tests for fragment cache.

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1264]
There are tests missing for some parts of the caching mechanism. 
The line [`end unless method_defined?(key) || _fragmented.respond_to?(attr)`](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L72) in `serializer.rb` is not being tested, as replacing it with `end unless method_defined?(key)` does not make any test fail. 
Moreover, I suspect (but I do not know enough about caching in AMS yet to be sure) that this line should actually be `end unless method_defined?(key) || _fragmented.respond_to?(key)` if anything.

**Comment by beauby** [comment]
cc @joaomdmoura

**Comment by joaomdmoura** [comment]
@beauby Indeed, I'll check it, I think I'm the one with more context on this.
