### ISSUE TITLE
Loading serializers in a namespaced engine failing

### ISSUE THREAD

**Issue by neilgupta** [rails-api/active_model_serializers#1274]
I have 2 serializers with 2 different engines:

Located at `#{Rails.root}/components/engine_a/app/serializers/engine_a/account_serializer.rb`:

```ruby
module EngineA
  class AccountSerializer < ActiveModel::Serializer
    attributes :name
  end
end
```

Located at `#{Rails.root}/components/engine_b/app/serializers/engine_b/session_serializer.rb`:

```ruby
module EngineB
  class SessionSerializer < ActiveModel::Serializer
    has_one :account, serializer: EngineA::AccountSerializer
  end
end
```

`EngineB::SessionSerializer` loads just fine within EngineB's controller, but it throws the following error:

`Unable to autoload constant AccountSerializer, expected /Users/ngupta/Documents/poject_name/api/components/engine_a/app/serializers/account_serializer.rb to define it`

Specifically, the `engine_a` namespace folder with `serializers` isn't included in the search path. I don't know if this is an ActiveSupport bug or an AMS bug, but any ideas would be helpful.

Interestingly, it only throws that error the first time the EngineA::AccountSerializer constant is loaded. It works the second time.

**Comment by neilgupta** [comment]
Nevermind, it was a silly user error....

**Comment by bf4** [comment]
@neilgupta Would you mind elaborating in case anyone else has the same or similar issue? Thanks

**Comment by neilgupta** [comment]
Sure, I somehow missed that I had forgotten to place `AccountSerializer` in its namespaced folder. The error message was actually showing the correct path and was complaining because that path wasn't being auto-loaded. As soon as I created the `serializers/engine_a` directory and moved `account_serializer.rb`into it, everything started working perfectly. This is what I get for not taking a break for several hours ;)

**Comment by bf4** [comment]
Thanks so much!

B mobile phone
