### ISSUE TITLE
Make it clear in the doc how to serialize a collection with a custom serializer

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1277]
A few issue were opened where people had issue serializing a collection with a custom serializer because they used the `serializer` option instead of the `each_serializer` option.
Ref: #1152, #1275

**Comment by bf4** [comment]
Addressed in https://github.com/rails-api/active_model_serializers/pull/1253/files#diff-264f0dd1ee08f0efe10ba3bcc1b93eebR48
