### ISSUE TITLE
Is it possible to pass outside variables into the serializer?

### ISSUE THREAD

**Issue by dmastylo** [rails-api/active_model_serializers#1278]
I have a collection that, in order to save db trips, uses a second collection that has some data associated to the records in the first collection. In RABL I could simply reference the global variable ```@data``` inside the view template and be done. Is this doable with AMS?

**Comment by beauby** [comment]
Could you be more specific?

**Comment by dmastylo** [comment]
Controller
```ruby
def index
    @games = Game.games

    # returns a hash
    @temp_players = GameQueue.players(params[:input])

    render json: @games, include: [:perimeters, :start_zones]
  end
```

Serializer
```ruby
class GameSerializer < ActiveModel::Serializer
  attributes :id, :name, :max_players, :description, :level, :best_finish
    
  attribute :buy_in_price, key: :buy_in_price_dollars

  has_many :perimeters, serializer: PerimeterSerializer
  has_many :start_zones, serializer: StartZoneSerializer

  def best_finish
    if @mongo_players
      @mongo_players[object.id]
    end
  end
end
```

**Comment by bf4** [comment]
what's the variable you're trying to pass in?  Check out
https://github.com/rails-api/active_model_serializers/pull/1252

In the past, I've created an attr_accessor on my model and used that to
pass in info

**Comment by dmastylo** [comment]
@bf4 @beauby I want to pass in that `@players` variable from the controller.

**Comment by beauby** [comment]
@dmastylo You could add `attr_accessor :best_finish` to your `Game` model, then in the controller you could do `@games.each { |g| g.best_finish = @temp_players[g.id] }`.

**Comment by dmastylo** [comment]
Thanks that works! @beauby
