### ISSUE TITLE
Unable to set side loaded objects `type` for JSON API

### ISSUE THREAD

**Issue by constantm** [rails-api/active_model_serializers#1279]
I'm unable to set the `type` for `relationships` in the JSON payload. I have a User model, which is mapped to a `Candidate` model in Ember. The `Candidate` model has_many `UserQualifications`, which maps to the `Qualification` model in Ember. For it to work properly in Ember, I need to give provide custom types for the serialisers. Everything works perfectly fine, except for the sideloaded `UserQualification`, of which I can't override the `type`, which stays on `type:"users"`. 

I have the following two serialisers:

```ruby
# Uses User model
class CandidateSerializer < ActiveModel::Serializer
  attributes	:id, :email, :name

  type :candidate
  has_many :qualifications

  def image
  	object.profile_image.url(:medium)
  end
end
```

```ruby
# Uses UserQualification model
class UserQualificationSerializer < ActiveModel::Serializer
  attributes :name, :institution, :aggregate

  attribute :from_date, key: 'from-date'
  attribute :to_date, key: 'to-date'

  # I've tried overriding types here, but it doesn't work:
  belongs_to :user, key: :candidates, type: 'candidates'

  type :qualification

  def institution
  	object.institution.name
  end

  def name
  	object.qualification_display_name.name
  end
end
```

JSON rendering in my controller looks as follows:

```ruby
respond_to do |format|
  format.json { render json: @candidates, each_serializer: CandidateSerializer, include: ['qualifications' ] }
end
```

I have a JSON payload returning as follows:

```
{  
   data:[  
      {  
         id:"30",
         type:"candidate",
         attributes:{  
            email:'test@test.com',
            name:"Test Name",
         },
         relationships:{  
            qualifications:{  
               data:[  
                  {  
                     id:"10",
                     type:"qualification"
                  },
                  {  
                     id:"11",
                     type:"qualification"
                  }
               ]
            }
         }
      }
   ],
   included:[  
      {  
         id:"10",
         type:"qualification",
         attributes:{  
            name:"Bachelor of Test",
            institution:"University of Test",
         },
         relationships:{  
            candidates:{  
               data:{  
                  id:"30",
                  type:"users" <--- this should be candidates, not users.
               }
            }
         }
      }
   ]
}
```

How do I get `type:"users"` to be `type:"candidates"`? I'm using the master branch/0.10.0.rc3 of active_model_serializers.

**Comment by beauby** [comment]
You should set the type on the corresponding serializer (here, in your `UserSerializer`).

**Comment by constantm** [comment]
@beauby, the User serialiser gets used for something else and is completely unrelated. It needs to happen in the the two serialisers getting used here, ie. CandidateSerializer and UserQualificationSerializer. As said, I can override the type of everything except the sideloaded `type`.

**Comment by beauby** [comment]
By `UserSerializer` I meant `UserQualificationSerializer`.

**Comment by beauby** [comment]
Oops sorry, wait.

**Comment by beauby** [comment]
Just change this line:
`belongs_to :user, key: :candidates, type: 'candidates'`
to
`belongs_to :user, key: :candidates, serializer: CandidateSerializer`

**Comment by beauby** [comment]
I'm closing this as it is a usage issue. Feel free to keep commenting if you need further assistance.

**Comment by constantm** [comment]
Awesome thanks @beauby, that's exactly what I needed! 👯
