### ISSUE TITLE
ActiveModel::SerializableResource doesn't take into account ApplicationController's scope

### ISSUE THREAD

**Issue by dyatlov** [rails-api/active_model_serializers#1281]
Hope title makes sense..

**Comment by beauby** [comment]
Could you be more specific? Maybe write a snippet that describes the behavior you're talking about.

**Comment by dyatlov** [comment]
Sure..

ApplicationController:

```ruby
class ApplicationController < ActionController::Base
# ...
serialization_scope :current_business
# ...
end
```

my view:

```ruby
<%= react_component('CommunityRouter', posts: ActiveModel::SerializableResource.new(@posts).serializable_hash ) %>
```

and finally my serializer:

```ruby
class PostSerializer
  attribute has_voted

  def has_voted
      scope.voted_for? object
      # also tried current_business.voted_for?
      # scope is nil and current_business is not defined
  end
end
```

**Comment by dyatlov** [comment]
My current workaround is to pass `scope` to serializer options, like this:

```ruby
<%= react_component('CommunityRouter', posts: ActiveModel::SerializableResource.new(@posts, scope: current_business).serializable_hash ) %>
```

this works, but doesn't seem beauty and very scalable..

**Comment by beauby** [comment]
This is expected behavior. The `scope` is automatically set *only* upon `render` calls. The reason for that is that there is no restriction as to where you're instantiating `SerializableResource` from.
Your workaround is the way to go.
