### ISSUE TITLE
Document ActiveModelSerializers::Model

### ISSUE THREAD

**Issue by bf4** [rails-api/active_model_serializers#1283]
See https://github.com/rails-api/active_model_serializers/pull/1272#issuecomment-149645909
- [ ] https://github.com/rails-api/active_model_serializers/pull/1272#discussion_r42172925
- [ ] https://github.com/rails-api/active_model_serializers/pull/1272#discussion_r42111785
- [ ] https://github.com/rails-api/active_model_serializers/pull/1272#discussion_r42111871
- [ ] Add changelog

**Comment by charlie-wasp** [comment]
@bf4 Hello! Is this issue still relevant? I am looking for some issue for beginners, search for the label "Good for New Contributors" lead me here :)

**Comment by bf4** [comment]
@charlie-wasp I think you're correct, that this has been since closed :(
