### ISSUE TITLE
Specify which render options should go to adapter and which to serializer

### ISSUE THREAD

**Issue by vasilakisfil** [rails-api/active_model_serializers#1288]
Here:
https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L50-L51

we pass all options to both (adapter/serializer). We should only pass to each one the relevant options. We also explicitly separate the options, if the constructor is used, here: https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializable_resource.rb#L8-L12 so maybe just remove them from the serializer in default render? (JSONAPI pagination links fail though due to the fact that context is not passed down to the serializer).

**Comment by beauby** [comment]
I'm not sure I understand what you mean. Could you make a PR just to show your idea?

**Comment by vasilakisfil** [comment]
No need for a pull request. What I am saying is that here: https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L50-L51
default render passes all options to both the serializer and adapter (= to both SerializableResource constructor and serializable_hash method). Is that the desired behavior ?

**Comment by bf4** [comment]
@vasilakisfil what you describe is intentional.  All render options go to the serializer except those diverted to the adapter.

**Comment by bf4** [comment]
Closing for now, but please feel free to re-open

**Comment by vasilakisfil** [comment]
But if all options go to serializer by default why having options param for both ActiveModel::SerializableResource.new and serializable_hash ? To override them ?
