### ISSUE TITLE
AM::S trying to use non-ActiveModel::Serializer seriaizers

### ISSUE THREAD

**Issue by trek** [rails-api/active_model_serializers#1293]
I have a project is migrating to AMS over time. They have classes that AMS is finding but aren't AMS classes so don't adhere to the AMS interface. It'd be great if AMS skipped these or provided a interface for non-AMS classes to say "please don't use me" when `serializer_for` is called.

**Comment by trek** [comment]
Happy to a PR if someone chimes in with whether this should be a fix in `serializer_for` or an option passed to `render` like `render :json ... serializer: false`

**Comment by beauby** [comment]
As @bf4 stated somewhere, there is already an option to disable AMS on a render call, namely `render json: post, adapter: false`.
