### ISSUE TITLE
Add ruby 2.2.3 to the TravisCI build matrix

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1303]
Currently we only test ruby 1.9.3...2.2.0 and ruby-head. Rails5 requires ruby >=2.2.3.

**Comment by KaraAJC** [comment]
I'd like to solve this issue! This will be my first OSS contribution, so I'm using the steps in the contributors.md but any tips would be appreciated!

**Comment by beauby** [comment]
Great! If you're interested, have a look at #1302, which is a similar kind of issue.

**Comment by KaraAJC** [comment]
will do!

**Comment by bf4** [comment]
@beauby I noticed that tests are passing here on Rails 5 (master) on Ruby 2.2.2 and see the [gemspec in Rails is `>= 2.2.2`](https://github.com/rails/rails/blob/dbf867cfcb4dac32bdb0b9491229fa8198ed8033/rails.gemspec#L10).  I imagine there's another source out there that said 2.2.3, but I haven't found it. Could you help me?

**Comment by remear** [comment]
fwiw, I've only ever officially heard >= 2.2.2 for Rails 5, https://github.com/rails/rails/pull/19753. There has been talk of requiring 2.2.3 due to some Symbol GC bugs, but the decision seems to have been to leave the requirement at 2.2.2, https://github.com/rails/rails/pull/21620.

**Comment by bf4** [comment]
Closed by #1360
