### ISSUE TITLE
Performance optimization with fields option: AMS should compute only the requested fields

### ISSUE THREAD

**Issue by vasilakisfil** [rails-api/active_model_serializers#1307]
I am using JSON adapter but I am pretty sure it's the same on every adapter: When you request specific field from a serializer, it shouldn't compute everything in advance, only the fields you requested. For instance when you request only for :id: it should be much faster than computing all fields because some of them might be VERY expensive.

I found that the issue is here: https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L241-L251

Personally I solved that by monkey patching AMS: passing the fields in the serializer and checking the requested fields before computing them in that method.

**Comment by beauby** [comment]
You're very right. There is work being done in that direction, but let's use this issue as a tracker for what I refer to as "lazy computation of attributes and associations" (the attributes case is pretty straightforward, but for associations it requires a tad more work).

**Comment by beauby** [comment]
Fixed on master.
