### ISSUE TITLE
Delegate or only options for reflections

### ISSUE THREAD

**Issue by victor95pc** [rails-api/active_model_serializers#1308]
Guy I don't know if I using this awesome gem right, but I need to get just 3 fields from a has_one association, ex:

```ruby
Person(id: integer, name: string, created_at: datetime,
  updated_at: datetime, editing: boolean, sex: string, 
  photos: string, cre_id: integer, dead: boolean
)
```

I have a association between employed and person, so I build a serializer:

```ruby
class EmployedSerializer < ActiveModel::Serializer
  has_one :person
end
```

But there no options of what fields I want, it can be like this one:

```ruby
  has_one :person, fields: [:name, :sex, :dead]
```

My workaround was done that way, but is so fucking ugly :smile: :
```ruby
%i(name sex dead).each do |field|
	define_method(field) do
		object.person.public_send(field)
	end

	attributes field
end
```

Thx guys for your attention

**Comment by beauby** [comment]
You could simply define a serializer for your person model:
```ruby
class EmployedSerializer < ActiveModel::Serializer
  has_one :person
end

class PersonSerializer < ActiveModel::Serializer
  attributes :name, :sex, :dead
end
```

**Comment by victor95pc** [comment]
But I already have a serializer for Person and I need all that attributes on there, I just need :name, :sex, :dead when I get the json by EmployedSerializer

**Comment by victor95pc** [comment]
A good option maybe is creating a bunch of serializer for each use case like this, but I think there is a better way to do this, ex:

```ruby
class BasicPersonSerializer < ActiveModel::Serializer
  attributes :name, :sex, :dead
end
```
```ruby
class EmployedSerializer < ActiveModel::Serializer
  has_one :person, serializer: BasicPersonSerializer
end
```

**Comment by beauby** [comment]
In this case use a namespaced serializer:
```ruby
class EmployedSerializer < ActiveModel::Serializer
  has_one :person
  class PersonSerializer < ActiveModel::Serializer
    attributes :name, :sex, :dead
  end
end
```
Note that the `PersonSerializer` is defined inside the `EmployerSerializer` namespace, and AMS will give priority to such nested serializers.

**Comment by beauby** [comment]
More over you might be interested in the fact that to designate a person that is employed by a company, the English word is "employee" and not "employed".

**Comment by victor95pc** [comment]
Oh sorry, I wrote wrong in so many places(README) :smile:
Thx great solution.
