### ISSUE TITLE
Add examples for each adapter in docs.

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1314]
Add examples *of a sample JSON output* for each adapter in [adapters.md](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md).

**Comment by mooreniemi** [comment]
@beauby What kind of examples you looking for?

**Comment by beauby** [comment]
@mooreniemi Updated the description. I meant examples of a sample JSON output for each adapter. Thanks for noticing the ambiguity of the request!

**Comment by mooreniemi** [comment]
@beauby NP. I was wondering if this'd cover something I was looking for: examples of custom adapters. I'd like to write one for the [Mason](https://github.com/JornWildt/Mason) hypermedia type. Perhaps a separate issue?

**Comment by beauby** [comment]
@mooreniemi Yup, please open a separate issue. I'd be happy to help you, we can talk on [slack](https://amserializers.herokuapp.com/).

**Comment by robinboening** [comment]
@beauby your link is a 404. You probably mean this file: https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md

**Comment by beauby** [comment]
@robinboening Thanks, I just edited my post.

**Comment by robinboening** [comment]
We just picked this issue for the upcoming 9th edition of https://rubyissues.ongoodbits.com :)
