### ISSUE TITLE
Isolate namespace when used in an engine

### ISSUE THREAD

**Issue by garytaylor** [rails-api/active_model_serializers#1316]
I am currently using this gem with rails_api and my API is defined inside an engine.

So, if my model was called "FinanceManager::AccountTransaction" then the "type" property in the  serialized JSON API output is "finance_manager_account_transactions".  

Is this correct ?  When I was using the jsonapi_resources gem, it was just "account_transactions".

This does make the client side a little awkward as my gem will expect a resource named FinanceManagerAccountTransaction.  

Thanks

Gary

**Comment by beauby** [comment]
You can specify the type manually as follows:
```ruby
module FinanceManager
  class AccountTransactionSerializer < ActiveModel::Serializer
    type 'account_transactions'
    ...
  end
end
```

**Comment by garytaylor** [comment]
Thanks for that @beauby - never realised

Cheers

Gary

**Comment by lookitsatravis** [comment]
@beauby - I'm using 0.10.0.rc3 and I get the following error using the code you've provided:

```rb
undefined method `type' for MyEngine::UserSerializer:Class
```

My serializer looks like this:

```rb
module MyEngine
  class UserSerializer < ActiveModel::Serializer
    type 'users'

    attributes :id #etc
  end
end
```

I even went as far as created a brand new engine and only including AMS and a single model controller, and the result is the same. Am I missing something here?

**Comment by lookitsatravis** [comment]
Nevermind. I saw the 10.x tag and thought rc3 was included. But when I checked the 10-stable branch, the code for the 'type' method is not included.

**Comment by bf4** [comment]
Yeah, 10-stable should either be up-to-date or not exist until the actual release
