### ISSUE TITLE
ActiveSupport::Notifications Support

### ISSUE THREAD

**Issue by wagenet** [rails-api/active_model_serializers#1319]
Is there any objection to adding ActiveSupport::Notifications instrumentation? It looks like it existed briefly in 0.9 but is no longer in master. I'd be happy to help with this for use in [Skylight](http://www.skylight.io).

**Comment by beauby** [comment]
No objection. Possibly related to #1291.

**Comment by bf4** [comment]
Sure @wagenet you wanna make a PR?

**Comment by wagenet** [comment]
Looks like #1291 would actually address my use case. Missed it in earlier searching.
