### ISSUE TITLE
Conditional skip in each_serializer

### ISSUE THREAD

**Issue by eliduke** [rails-api/active_model_serializers#1326]
In an each serialization, is it possible to skip a record based on some conditions?

I have an Event Prize Entrant Serializer, which includes some basic information about an event attendee and the number of prizes that they have entered. I'm passing in a collection of users and then tallying their prize count. I don't need to return them if they haven't entered any prizes, so I'm imagining something like this:

```
module Adm
  class PrizeEntrantSerializer < ActiveModel::Serializer

    skip if entries == 0

    attributes :id, :first_name, :last_name, :title, :organization_name, :entries

    def entries
      prize_ids = @options[:event].event_prizes.map(&:id)
      object.event_prize_codes.where(event_prize_id: prize_ids).size
    end

  end
end
```

Does something like that exist?

**Comment by beauby** [comment]
This type of filtering should be done at the model level. Just define a method on your model that does the correct filtering, and expose that through your serializer.

**Comment by bf4** [comment]
Or even before it gets to ams...

**Comment by eliduke** [comment]
That's what I figured and that's what I did in the end, but it seemed somewhat simpler to do it in the serializer. Just wondered if that functionality existed. Thanks!
