### ISSUE TITLE
Using Parameters on Many Model Associations in Serializer

### ISSUE THREAD

**Issue by michaelstokes** [rails-api/active_model_serializers#1330]
Hello, 

I'm looking to use parameters to filter a query onto multiple model associations i.e. A Query to a Product table joining onto a category table where a category equals a param.

I'm not sure on the best approach, as the query can be constructed in an action call i.e. search 

```
  def search
    serialized_products =
      ActiveModel::ArraySerializer
               .new(Product.joins('LEFT JOIN product_categories ON product_categories.product_id = products.id')
               .joins('LEFT JOIN categories ON categories.id = product_categories.product_id
                LEFT JOIN subcategories ON subcategories.id = product_categories.subcategory_id')
               .where("products.name LIKE ? OR products.quantity = ? OR products.price = ? OR categories.name = ?", params[:name], params[:quantity], params[:price], params[:category]), each_serializer: ProductSerializer)

    render json: serialized_products
  end
```

but then in serialized_products

```
class ProductSerializer < ActiveModel::Serializer
  attributes :id, :name, :heading, :description, :quantity, :start_date, :end_date, :price, :condition_id, :user_id, :product_info
  has_many :product_categories, embed: :objects
  has_many :categories, through: :product_categories, embed: :objects
  has_many :subcategories, through: :product_categories, embed: :objects
```

Thanks

**Comment by michaelstokes** [comment]
Hi, Thank you! 

Yeah its mostly in terms of Querying based on Posted Parameters so in the case above with search being called and joining Product Categories, Left joining Categories and Subcategories and then rending the json and serializing but in this Serializer the querying will then happen again 
based on the has_many almost like the query could be done in the controller and then a serializer consisting of attributes for Product, Product Categories, Categories and Subcategories could be rendered rather. 

Thanks :)

**Comment by bf4** [comment]
It appears this issue is resolved.  Please comment and reopen if it is not.
