### ISSUE TITLE
Autoloading issue

### ISSUE THREAD

**Issue by Drabc** [rails-api/active_model_serializers#1331]
AMS: Master(0.10r3)
Rails: 4.2.3
Ruby: 2.2.2p95
I'll use the following structure as an example. I have:

-- comment_serializer
--posts
---- post_group
------- type1_post_serializer

    class CommentSerializer
        has_many :posts
    end

    module posts
        module postGroup
            class Type1PostSerializer
                attribute :id
            end
        end
    end

When I try to serialize a Comment, I'm having a LoadError being thrown. This line   

    chain.push("#{name}::#{serializer_class_name}") if self != ActiveModel::Serializer

in this method seems to cause the issue.

    def self.serializer_lookup_chain_for(klass)

The chain is pushing CommentSerializer::Type1PostSerializer, which for my understanding takes care of nested serializers. However, rails is trying to autoload CommentSerializer::Type1PostSerializer which throws the LoadError because it doesn't exists.

Am I doing something wrong here? Is there a workaround?

Thanks in advance!

**Comment by Drabc** [comment]
I can't post my actual structure, but I'll mimic it.

-- serializers
---- comment_serializer
----posts
------ post_group
--------- type1_post_serializer

model structure is the same as serializers

-- models
---- comment
----posts
------ post_group
--------- type1_post

the error is 

LoadError (Unable to autoload constant Type1PostSerializer, expected /home/dev/app/serializers/posts/post_group/type1_post_serializer.rb to define it):

I don't think it has to do with the file structure. I stepped the code and the error I'm getting is correct. CommentSerializer::Type1PostSerializer does not exists so it should throw an error.

**Comment by beauby** [comment]
Then please provide a minimal rails application exhibiting the issue as this is most probably a usage issue and experience shows that those can only be diagnosed with real code.

I see one possible issue: your module names (`post` and `postGroup`) have lowercase letters as first character, which is against rails conventions. But impossible to be sure, as this is not real code.

**Comment by Drabc** [comment]
Here is a minimal app that shows the issue. https://github.com/Drabc/AMS_test
To test do:
- Bundle install
- rake db:drop db:create db:migrate db:seed
- rails c
- Run ActiveModel::SerializableResource.new(Comment.first).serializable_hash

**Comment by Drabc** [comment]
I was able to Hack it by doing this. Hopefully, there is a better solutions

        def self.get_serializer_for(klass)
          serializers_cache.fetch_or_store(klass) do
            # NOTE(beauby): When we drop 1.9.3 support we can lazify the map for perfs.
            serializer_class = serializer_lookup_chain_for(klass).map { |x|
              begin
                constant = x.safe_constantize
                return constant if constant && constant < ActiveModel::Serializer
              rescue LoadError => e
              end
            }

            if serializer_class
              serializer_class
            elsif klass.superclass
              get_serializer_for(klass.superclass)
            end
          end
        end

**Comment by Drabc** [comment]
I was able to Hack it by changing this method. Hopefully, there is a better solutions

        def self.get_serializer_for(klass)
          serializers_cache.fetch_or_store(klass) do
            # NOTE(beauby): When we drop 1.9.3 support we can lazify the map for perfs.
            serializer_class = serializer_lookup_chain_for(klass).map { |x|
              begin
                x.safe_constantize
              rescue LoadError => e
              end
            }.find{|constant|
              constant && constant < ActiveModel::Serializer
            }

            if serializer_class
              serializer_class
            elsif klass.superclass
              get_serializer_for(klass.superclass)
            end
          end
        end

**Comment by beauby** [comment]
Looking into it

**Comment by beauby** [comment]
Indeed, there seems to be an autoloading issue here.
```
> "CommentSerializer::CustomPostSerializer".safe_constantize
LoadError: Unable to autoload constant CustomPostSerializer, expected /private/tmp/AMS_test/app/serializers/posts/group/custom_post_serializer.rb to define it
```

Will investigate more.

**Comment by Drabc** [comment]
Great. Thanks!

**Comment by beauby** [comment]
@Drabc Upon further investigation, it seems you'r manually adding `app/models` to the autoload paths. Is there a reason for that?

**Comment by beauby** [comment]
Ok, so the problem comes from the fact that you manually add `app/serializers` to your autoload path.

**Comment by Drabc** [comment]
We seem to have misunderstood some things around auto-loading. I removed the manual addition and everything is working as it should. Thanks for the help!
