### ISSUE TITLE
Dynamic attributes in associations. 

### ISSUE THREAD

**Issue by CostaRico** [rails-api/active_model_serializers#1334]
Hi. I user master branch.
```
gem 'active_model_serializers', :git => 'https://github.com/rails-api/active_model_serializers.git'
```
I'd like to control what attributes are needed in associations of a main model, how could I do it?
I have an Order
```ruby
class OrderSerializer < ActiveModel::Serializer
	has_one :client #here I'd like to pass special serialize set of attributes based on custom_options
       	#...
end
```
And Client:
```ruby
class Client < ActiveRecord::Base
	has_many :orders
        #...
end
```

And in controller:
```ruby
render json: @orders.order('id desc'), include: 'client', custom_options: custom_options
```

I can read custom_options with instance_options in serializer methods, but how can I pass serializer for Client in OrderSerializer?

Thx a lot!

**Comment by tylerwillingham** [comment]
> how can I pass serializer for Client in OrderSerializer?

I think this might be what you're looking for:

```ruby
class OrderSerializer < ActiveModel::Serializer
  has_one :client, serializer: YourCustomSerializer
end
```

**Comment by CostaRico** [comment]
@tylerwillingham thx a lot, but what if I need dynamic "YourCustomSerializer" based on query params?

**Comment by beauby** [comment]
@CostaRico Could you explain in what kind of situations this would be needed?

**Comment by CostaRico** [comment]
@beauby Hello, in one controller I need to show pretty big json (100 models with some associations) and I'd like to show only that fields that I will show in table on the frontend side, so this way I will make speed up. For now I see the only way to do that somehow like this 
```ruby 
custom_serializer = (Class.new(ActiveModel::Serializer) do
            attributes :id, :company_name, :site, :created_at, :updated_at, :broker_id, :next_communication_time, :next_communication_time_in, :status
            has_many :orders
#here some code
        end)
```

**Comment by beauby** [comment]
@CostaRico In case you are using the JsonApi adapter, you could make use of the `fields` option, which allows you to limit attributes for each type of resource you will be serializing.

**Comment by CostaRico** [comment]
@beauby it seems like exactly what I need. Thx u a lot!

**Comment by CostaRico** [comment]
If somebody needs the same, here the example:
```ruby
render json: @clients, include: ['orders'], meta: meta, fields: {orders: [:title], client: [:company_name]}
```
