### ISSUE TITLE
ams does not generate an initializer

### ISSUE THREAD

**Issue by JiHunJeon** [rails-api/active_model_serializers#1335]
i tried install version which 0.9.3 and 0.10.0.rc3

but didn't generate ac initailzer

my rails version is 4.2.4 
gem version is 2.4.5

**Comment by bf4** [comment]
It's not supposed to. Was anything not working? Did you run any commands?

**Comment by bf4** [comment]
see https://github.com/rails-api/active_model_serializers/pull/1374

**Comment by bf4** [comment]
Closing as OP has not responded. Please either comment on what you ended up doing or re-open if this is still a problem.  Ref: https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md#after
