### ISSUE TITLE
Resource level meta key

### ISSUE THREAD

**Issue by rafael** [rails-api/active_model_serializers#1339]
Does active model serializer supports jsonapi resource meta key at the resource object level? I would like to do something like this:

```
// ...
{
  "type": "articles",
  "id": "1",
  "meta": { "my_metadata": true" },
  "attributes": {
    "title": "Rails is Omakase"
  },
  "relationships": {
    "author": {
      "links": {
        "self": "/articles/1/relationships/author",
        "related": "/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    }
  }
}
// ...
```

I've been trying to see how to achieve this, but only been able to achieve it at the top level, not at the resource object level.

**Comment by tylerwillingham** [comment]
It looks like that doesn't conform to the jsonapi spec. The spec points to the meta key being specific to the document/response.

You can implement a custom key through a serializer to get the data that you want but if conforming to the spec is important to you I would choose a different name for your key.

**Comment by rafael** [comment]
@tylerwillingham are you sure that doesn't conform the spec? I was reading this part and thought it should be valid: 

```
Resource Objects
"Resource objects" appear in a JSON API document to represent resources.
A resource object MUST contain at least the following top-level members:
	•	id
	•	type
Exception: The id member is not required when the resource object originates at the client and represents a new resource to be created on the server.
In addition, a resource object MAY contain any of these top-level members:
	•	attributes: an attributes object representing some of the resource's data.
	•	relationships: a relationships object describing relationships between the resource and other JSON API resources.
	•	links: a links object containing links related to the resource.
	•	meta: a meta object containing non-standard meta-information about a resource that can not be represented as an attribute or relationship.
```

Is this not the right interpretation? Reading the docs looks to me that is allowed both at the `top level` and  the `resource object` level.

**Comment by beauby** [comment]
The spec, indeed allows it. It is not yet possible in AMS, but there's a PR in the making for this.

**Comment by rafael** [comment]
@beauby oh that's cool. Could add a reference to the PR?

**Comment by tylerwillingham** [comment]
My mistake. I should have provided a link to the section I was looking at it in the docs. It didn't give any mention of that :)

**Comment by beauby** [comment]
@rafael Just issued one. If you have time to write a few tests, it would certainly help getting it merged quickly. Otherwise I'll write some when I get a chance.

**Comment by rafael** [comment]
@beauby. Awesome. Will do, I can get some tests written by EOD tomorrow. Closing this ticket in favor of #1340.

**Comment by beauby** [comment]
@rafael Awesome
