### ISSUE TITLE
serialization of serialized columns

### ISSUE THREAD

**Issue by muichkine** [rails-api/active_model_serializers#1350]
I have such a model

    class WhiteScan < ActiveRecord::Base
      serialize :parsed_prices, Array
    end

the serializer looks like

    class WhiteScanSerializer < ActiveModel::Serializer
      attributes :parsed_prices
    end

which renders the `parsed_prices` attribute as a string/text. Shoudn't the attribute be rendered as a an array by default ?

**Comment by beauby** [comment]
Could you provide examples of expected/actual output?

**Comment by muichkine** [comment]
Sorry, my mistake. The behavior is in fact as expected. Problem was on my side.
