### ISSUE TITLE
Document usage in rails-api

### ISSUE THREAD

**Issue by vitorbaptista** [rails-api/active_model_serializers#1351]
Sorry if this is already documented somewhere, but I couldn't find and spent a few hours trying to understand what was going on.

When using `active_model_serializers` with Rails, there's no need to change the controllers. The same isn't true for when using `rails-api`. As far as I can see, you need to add `include ActionController::Serialization` to your `ApplicationController` (or each individual controller, if you don't want it to be the default).

Without it, the serializers aren't called.

**Comment by vitorbaptista** [comment]
As an example of another gem that has the same "issue" and how they solved it, https://github.com/CanCanCommunity/cancancan#getting-started

**Comment by bf4** [comment]
Hi @vitorbaptista Thanks for your issue.

I can't tell which AMS version you're on. Might you take a look at https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md and see what other information might help us?

Indeed, whatever controller you are using would need to have `ActionController::Serialization` included, but it should be included in the action controller base for both Rails and Rails-Api.  In my own usage of Rails-API I didn't have this issue, so my guess is you're using a different version of something.

If the solution for your version is to add `ActiveSupport.on_load(:action_controller) { include ActionController::Serialization }` to an initializer, that would make a nice PR

**Comment by bf4** [comment]
Closing as stale.  Please re-open and comment if this is still an issue.

**Comment by brownjohnf** [comment]
This just happened to me on 5.0.0.beta3. What I did:

* gem install rails -v "5.0.0.beta3"
* rails new blah --api
* cd blah && bundle
* bin/rails g scaffold foo
* (modify gemfile to include active_model_serializers)
* bundle
* bin/rails g serializer foo
* bin/rails s

And I wound up with no serialization. Adding `include ActionController::Serialization` to my ApplicationController solved the problem.

**Comment by bf4** [comment]
@brownjohnf which version of AMS are you on? Please open a new issue (or better, a PR!)

I've been wanting to have tests around this.

**Comment by brownjohnf** [comment]
`gem "active_model_serializers", '~> 0.10.0.rc1'` is what's currently in my Gemfile, but I think I manually bumped the version after having these issues. It might be that the only real issue is just a missing comment in the readme that if you're using the beta rails 5 w/api flag you should use the 0.10rc series for the serializer. I can make that change, if you like it.

Otherwise, I was presumably on the latest stable release.

**Comment by bf4** [comment]
Could everyone for whom this is an issue share

bundle show active_model_serializers

And their stacktrace if any?
