### ISSUE TITLE
Ignore serializer option in has_one in nested serializations

### ISSUE THREAD

**Issue by blanchma** [rails-api/active_model_serializers#1359]
I have the following:

class ParticipationSerializer < ActiveModel::Serializer
  attributes :id, :approved, :meeting_id, :created_at, :meeting, :user, :message

  has_one :meeting, serializer: MeetingBaseSerializer
  has_one :user, serializer: UserBaseSerializer
end

class MeetingSerializer < MeetingBaseSerializer
  has_one :user, serializer: UserBaseSerializer
end

class UserBaseSerializer < ActiveModel::Serializer
	attributes :id
end

When a participation is serialized, MeetingSerializer and UserBaseSerializer is used at this level. But inside MeetingSerializer, UserBaseSerializer is not used. It's just ignored and fetch the whole user from db.

**Comment by bf4** [comment]
Please see https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md

**Comment by beauby** [comment]
@blanchma `:user` and `:meeting` should not appear as attributes (and neither should `:meeting_id`, unless your API is designed that way for some legacy reasons).
Closing this as there has been no reply from op for almost 2 months. Feel free to reopen/keep commenting if you need further assistance.
