### ISSUE TITLE
Nested assocation

### ISSUE THREAD

**Issue by tak1n** [rails-api/active_model_serializers#1361]
I currently have following setup of serializers:

```ruby
# app/serializers/user_serializer.rb
class UserSerializer < ActiveModel::Serializer
  attributes :id, :created_at, :email, :active, :authentication_token, :sign_in_count, :last_sign_in_at, :trial_allowed, :plan_since

  has_one :profile
end

# app/serializers/profile_serializer.rb
class ProfileSerializer < ActiveModel::Serializer
  attributes :id, :firstname, :surname

  has_one :address
end
```

When I visit `/profiles/1.json` I get following json:

```
{  
   "id":1,
   "firstname":"Sesa",
   "surname":"Developer",
   "address":{  
      "id":1,
      "street":"Test",
      "number":"test",
      "postal_code":"test",
      "city":"test",
      "country":"Austria",
      "state":"test",
      "parent_id":1,
      "parent_type":"Profile",
      "created_at":"2015-12-02T16:10:19.726+01:00",
      "updated_at":"2015-12-02T16:10:19.726+01:00"
   }
}
```

Now when I visit the endpoint for giving me the user as json I get:

```
{  
   "id":1,
   "created_at":"2015-12-02T15:37:22.042+01:00",
   "email":"herbertm1970@gmail.com",
   "active":true,
   "authentication_token":"vxyz",
   "sign_in_count":1,
   "last_sign_in_at":"2015-12-02T15:39:48.211+01:00",
   "trial_allowed":true,
   "plan_since":null,
   "profile":{  
      "id":1,
      "firstname":"Sesa",
      "surname":"Developer"
   }
}
```

For displaying the profile address attributes in user json I would need to add `attributes :address` to my profile serializer:

```ruby
class ProfileSerializer < ActiveModel::Serializer
  attributes :id, :firstname, :surname, :address

  has_one :address
end
```

It feels somehow weird that for displaying it in a nested way you have to add the assocation as `attribute`. Is this a bug or did I just miss this somewhere in the doc and this is expected behaviour? 

P.S.: I'm using ams 0.10.0.rc3

**Comment by Drabc** [comment]
This version doesn't automatically include nested associations of a nested association. You have to specify what to include.

include: "profile.address" or include: "**" to specify you want all associations to be loaded
here is a link https://github.com/rails-api/active_model_serializers#json-api

**Comment by tak1n** [comment]
@Drabc  Thx for your comment, but note that I'm not using the json-api adapter.
I cannot switch to json-api because the project where I want to introduce AMS is not that tiny (currently json is done through rabl view) and therefore I have to be backwards compatible with the old json format.

Thats why I want to use AMS with its default adapter to reconstruct the old json format to switch stepwise to AMS.

Still even with the default adapter I have todo this `attributes :address` in addition to `has_one :address` to see the address in the profile json where the profile is nested for example in the user json.
The problem I have with it is this inconistent behaviour which surprised me, as for nested context I have to specify it again as attribute.

If I described my problem in a unclear way or I did not understand ur comment properly I'm sorry.
Again thx for your comment. :)

**Comment by Drabc** [comment]
@tak1n I believe you have to use include for any adapter. It has to do with the way AMS serializes associations. I use the attributes adapter and I still have to specify the include.
The reason why has_one :address is not working its because its not specify as part of the include chain, so AMS doesn't see it. The reason why attributes :address works its because AMS is calling profile.address. If you notice, it adds the active record model ignoring any serializer you have specified for address. Try calling the user serializer with an include as shown in the link I provided.

**Comment by tak1n** [comment]
Okay thx, will try it when I'm at home :)

**Comment by beauby** [comment]
Closing this as there has been no reply from op in more than a month. Feel free to reopen/keep commenting should you need further assistance.
