### ISSUE TITLE
Using multiple adapters for a single app

### ISSUE THREAD

**Issue by jordpo** [rails-api/active_model_serializers#1362]
We have a legacy code base that is using the default attributes adapter that we are building on for v2 and we want to use the JSON API adapter for v2 resources. Is there a way to specify an adapter in the Serializer class definition?

**Comment by bf4** [comment]
Please see https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md to help us with more information

In 0.10 the serializer and adapter interact through the controller (via serializable_resource).  They are intentionally separated.  You can always specify which serializer and adapter to use.

**Comment by jordpo** [comment]
Thanks. It's clear with the docs that you can specify an adapter in a initializer but what we are trying to do is specify an adapter in the serializer class, here:

```
class V2::JsonApiSerializer < ActiveModel::Serializer
  # specify the adapter here
end
```

The idea being that v1 resources will continue to use the attributes adapter while v2 resources can use the JSON API one. 

Sorry if this is still not clear or this is a rare situation that other developers wouldn't normally come across. I can close this issue if that is the case.

**Comment by beauby** [comment]
This is currently not possible, and will probably never be, as the direction we have taken is to make the serializers (almost) totally adapter-agnostic. A possible solution to your situation would be to add the `adapter: Whichever::Adapter::You::Want` to all your `V2` `render` calls. I realize this is not ideal, but it seems like the best solution right now (at least to me).

**Comment by jordpo** [comment]
Thanks for the info! Yeah maybe a custom render function scoped to the v2 application controller will let us get by. It makes sense that the serializers are adapter agnostic. Going to close this issuer. Thanks again.
