### ISSUE TITLE
version 0.10.0.rc3 returns ALL attributes, not just the ones specified in the serializer 

### ISSUE THREAD

**Issue by renaebair** [rails-api/active_model_serializers#1366]
In version 0.8.0 everything works as expected. If I have a model "ExampleThing" and generate a serializer "ExampleThingSerializer" and do something like: 

```
class ExampleThingSerializer < ActiveModel::Serializer
  attributes :title
end
```

```
module Api
  module V1
    class SomethingController < Api::BaseController
      def show
        @thing = ExampleThingSerializer.new(ExampleThing.last)
        render json: @thing
      end
    end
  end
end
```

The json output will be:
```
{"example_thing":{"title":"This is a title"}}
```
However, when I update to use Active Model Serializer 0.10.0.rc3 (and without making ANY other changes), the output will include not only the title, but every other attribute of the object:

```
{"object":{"id":1798,"slug":"this-is-a-title","display_date":"2015-11-12T19:25:00.000Z","title":"This is a title","body":"this is a body","emails":[],"comments_count":0,"state":"published","featured":false,"group_id":null},"options":{},"root":null,"meta":null,"meta_key":null,"scope":null}
```

I'm wondering if something changed in 0.10.0 that affects this and how I might circumvent this behavior? 

Or, maybe I missed something in the docs? I'd appreciate any help :)

**Comment by deepsystm** [comment]
same question!

**Comment by bf4** [comment]
Thanks for your question.  I'm going to need some more details in order to help you, ideally something reproducible.   I'm guessing your issue has to do with the adapter, but I can't say for sure.

Note:  I recommend running off of master.

**Comment by beauby** [comment]
Your issue lies in this line:
```ruby
        @thing = ExampleThingSerializer.new(ExampleThing.last)
```
Just replace it with 
```ruby
        @thing = ExampleThing.last
```

Or if you need to specify the serializer:
```ruby
        @thing = ExampleThing.last
        render json: @thing, serializer: ExampleThingSerializer
```

**Comment by deepsystm** [comment]
Thanks, i will try it now and provide feedback

**Comment by beauby** [comment]
Closing this, as it is a usage issue. Feel free to ask if you need further information.
