### ISSUE TITLE
Return non-wrapped json from specific serilaizer

### ISSUE THREAD

**Issue by pelted** [rails-api/active_model_serializers#1368]
I've been using rc3 with very good results on a rather large Rails based API project. I've run into an issue where I have a couple of routes where I need to return just the json array and not the fully wrapped response. 

```json
[
  {
    "id": "1",
    "name": "..."
  },
  {
    "id": "2",
    "name": "..."
  }
]
```

instead of

```json
{
  "data": [
    {
      "id": "1",
      "type": "...",
      "attributes": {
        "name": "..."
      }
    },
    {
      "id": "2",
      "type": "...",
      "attributes": {
        "name": "..."
      }
    }
  ]
}
```

Am I just not seeing a way of configuring this from the controller or serializer

**Comment by bf4** [comment]
Seems like you should just specify the adapter you want to use, or just serialize your record in the controller (`to_json`) and AMS won't change it

**Comment by beauby** [comment]
As @bf4 mentioned, you seem to be using the `JsonApi` adapter (from the second example), where you should be using the `Attributes` adapter in order to get the result in the format from the first example (`Attributes` is basically the same as the `Json` adapter, except the response document does not have a root).

**Comment by pelted** [comment]
@bf4 I'm just not sure how in the world I missed that the `adapter` option being available to pass to the renderer. I've got a couple of API projects and one is using the older .9 stable branch so maybe just got the docs confused.

**Comment by bf4** [comment]
@pelted Thanks.  If you'd like to help us with the upgrade docs, that'd be great! ref: https://github.com/rails-api/active_model_serializers/issues/1005
