### ISSUE TITLE
How to use AMS with the Sequel ORM ?

### ISSUE THREAD

**Issue by AlexCppns** [rails-api/active_model_serializers#1373]
I have been reading the docs and I was quite confused on the part about ORMs. Is there an example I can look at?

**Comment by bf4** [comment]
I'm not sure I understand your question, but I'll make some assumptions and throw a few ideas.

(Also, see https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md )

Assuming:

- You're on 0.10.0.rcx or master (I recommend master...)
- You're not sure how to use non-activerecord objects

Possible solutions if you're on 0.10.0 or master:

- Use ActiveModelSerializers::Model or use parts of it
  - https://github.com/rails-api/active_model_serializers/blob/master/docs/ARCHITECTURE.md#what-does-a-serializable-resource-look-like
  - https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/model.rb
- Maybe see some of the documentation I have in a PR https://github.com/rails-api/active_model_serializers/pull/1371

**Comment by bf4** [comment]
Closing, but please re-open and/or share your problem/solution :) https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md#after
