### ISSUE TITLE
How to include nested dynamic associations in object

### ISSUE THREAD

**Issue by casiodk** [rails-api/active_model_serializers#1379]
I have a search model, where i save the query params

depending on these search params i find a collection of Containers

If I want to render these containers as an association on the search model, and use the container serializer for that, how do i go about that?

ex    

    class API::V1::SearchesController < ApplicationController
      def show
        @search = Search.find_by_token!(params[:id])
        @containers = ContainerSearcher.new(search: @search, page: params[:page], per_page: params[:per_page])
        render json: @search # how to include containers here?
      end
    end

**Comment by bf4** [comment]
Please see https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md so we can help you

**Comment by beauby** [comment]
Closing this as there has been no reply from op for more than a month. Feel free to reopen/keep commenting should you need further assistance.
