### ISSUE TITLE
0.10.0.rc3 outside of rails?

### ISSUE THREAD

**Issue by svenfuchs** [rails-api/active_model_serializers#1389]
`active_model_serializers` unconditionally requires `action_controller/railtie` (https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers.rb#L4). This raises in an application that does have `railties` loaded:

```
[...]/activesupport-4.2.5/lib/active_support/i18n_railtie.rb:6:in `<module:I18n>': uninitialized constant I18n::Rails (NameError)
  from [...]/activesupport-4.2.5/lib/active_support/i18n_railtie.rb:5:in `<top (required)>'
  from [...]/activesupport-4.2.5/lib/active_support/railtie.rb:2:in `<top (required)>'
  from [...]/active_model_serializers-0.10.0.rc3/lib/active_model_serializers.rb:3:in `<top (required)>'
```

I've looked at including `active_model/serializer` directly, but that requires `ActiveModelSerializers` to be known.

It now also requires both `railties` and `actionpack` https://github.com/rails-api/active_model_serializers/blob/master/active_model_serializers.gemspec#L28-L33 as per gemspec.

Is ARM still supposed to be usable outside of rails, too?

**Comment by bf4** [comment]
@svenfuchs (nice to meet you)

Since AMS has always been coupled to Rails and used in Rails projects, it does assume most of the Rails stack, at this point. It walks kind of a funny line that way.

I believe when I added railties and actionpack to the gemspec it was because they were implicit dependencies.

But does it need to be so tightly coupled on load? No, I don't think so.

Besides making the railtie load only when Rails is loaded, what else might be helpful?  I'd support a PR or perhaps work on one.

**Comment by svenfuchs** [comment]
Hi @bf4, nice to meet you, too

I used to use ARM outside of Rails, simply by subclassing it and calling `as_json` on it. I seem to remember there are guides/tutorials out there for that. E.g. a Sinatra application that uses ActiveRecord and wants to serialize to json-api.

I feel requiring railties and actionpack in the gemspec might not actually be necesary if ARM only loaded it's own railtie if Rails is present (because it always already has railties and actionpack in this case)?

**Comment by bf4** [comment]
Yeah that's basically possible now except I guess we set the requirements too tightly.

If that's a PR you'd be interested in making, I'd love to help.  It would mostly be moving a few require statements around, and me finishing the PR to isolate the Rails app stuff in the Railties.

There's a docs page now that links to our slack, if you're interested.  Amserializers.herokuapp.com I believe

B mobile phone

**Comment by rikas** [comment]
I have the same problem. Also using AMS outside Rails (Sinatra API).

**Comment by bf4** [comment]
@rikas could you open a new issue? This is resolved in released code, I believe
