### ISSUE TITLE
[RFC] Option to decide whether a "link" should be a string or object

### ISSUE THREAD

**Issue by groyoh** [rails-api/active_model_serializers#1400]
JSONAPI spec speficy that a `link` can either a string or an object (http://jsonapi.org/format/#document-links). Currently when using `ActiveModel::Serializer::link` method, we cannot specify whether the link should be serialized as a string or an object.
If we don't use a block, then it is always serialized as a string:
```ruby
link :self, "//a-url" # => { :self => "//an-url" }
```
and if we use the block version, then it is always serialized as an object:
```ruby
link :self do
  href "//a-url"
end # => { :self => { :href => "//an-url" } }
```

I see some cases where we might want to use a block (to have a dynamic href) but still want it to be serialized as a string (since it is allowed by the spec) or not use a block and serialize it as an object.

I think an option parameter to the `Serializer::link` method could fix this e.g.
```ruby
link :self, "//an-url", as_string: false # => { :self => { :href => "//an-url" } }
link :self, as_string: true do
  href "//an-url"
end # => { :self => "//an-url" }
```

**Comment by beauby** [comment]
You make a valid point, although I'm not convinced by the `as_string` option. We could possibly add a `string` method to the `Link` class, which would force the value to be a string.

**Comment by bf4** [comment]
I think a config option would be sufficient.  The default would be: If a link has only one item in it, then the value is a string.  Else, it's an object. And configurable would be: Always use an object.  Also, passing in 'self: href' would always result in an object

**Comment by groyoh** [comment]
@beauby I thought about this too but then realized that it would prevent us from serializing as an object when not using a block e.g. `link :self, "//an-url" # => { :self => { :href => "//an-url" } }`. In my opinion, we should able to decide how to serialize it whether we use a block a not for consistency reason.

**Comment by beauby** [comment]
@groyoh Not really, as you could currently do `link :self, { href: '//an-url' }`.

**Comment by groyoh** [comment]
@beauby you're right. I forgot about this even though I'm not convinced it's the best idea to be able to pass in a hash directly. If I were to choose I'd rather only pass a string and then AMS would take care of serializing as string or a hash. I also find it less error prone (e.g. no chance of typo when writting `href`).

**Comment by beauby** [comment]
@groyoh That's why we introduced the DSL for link objects. I'd like to address as many use-cases as possible but at the same time I don't want to introduce too much complexity and confusion.

**Comment by groyoh** [comment]
@beauby alright, so in the end would it be like this:

```ruby
link :self, "//an-url", as_string: false # => { :self => "//an-url" }
link :self, { :href => "//an-url" }  # => { :self => { :href => "//an-url" } }
link :self { href "//an-url" }  # => { :self => { :href => "//an-url" } }
link :self do
  string
  href "//an-url"
end # => { :self => "//an-url" }
link :self do
  meta { :some_meta => true }
  href "//an-url"
end # => { :self => { :href => "//an-url", :meta => { :some_meta => true } } }
```
or did you expect a different usage of the `string` method?

**Comment by beauby** [comment]
I don't understand your first example. Your `link :self, "//an-url", as_string: false` outputs the exact same thing as `link :self, "//an-url"` currently does.

What I had in mind was:
```ruby
link :self, "//an-url" # => { self: "//an-url" }
link :self { string "//an-url" } # => { self: "//an-url" }
link :self { href "//an-url" } # => { self: { href: "//an-url" } }
```
So in the block, one could either specify a string (possibly using dymanic stuff), or call DSL methods to build an object (`href`, `meta`, etc.).

**Comment by beauby** [comment]
@groyoh Check out the PR I just issued (which does what I described above).

**Comment by groyoh** [comment]
@beauby there was a mistake in my answer which didn't make sense. I'll take a look at the PR ;)

**Comment by beauby** [comment]
@groyoh Should we close this now that #1406 has been merged?
