### ISSUE TITLE
undefined method `config' for ActiveModelSerializers:Module

### ISSUE THREAD

**Issue by stephanngamedev** [rails-api/active_model_serializers#1401]
I'm using Rails 5

My `.gemfile`
```
gem 'active_model_serializers', '~> 0.10.0.rc1'
```
My initializer (`config/initializers/active_model_serializers.rb`) based on guides (https://github.com/rails-api/active_model_serializers/blob/master/docs/general/configuration_options.md)
```
ActiveModelSerializers.config.adapter = :json_api
```
Error:
```
config/initializers/active_model_serializers.rb:3:in `<top (required)>': undefined method `config' for ActiveModelSerializers:Module (NoMethodError)
```

I solved with:
```
ActiveModel::Serializer.config.adapter = :json_api
```

**Comment by beauby** [comment]
You are right, the change from `ActiveModel::Serializer.config` to `ActiveModelSerializers.config` was made post-RC3. I'll close this issue for now, but it's good to have it pinned down for future reference.

**Comment by bf4** [comment]
Technically `AMS.config` just delegates to `AM::S.config`, for backwards compat. Maybe this could be a PR to the docs to emphasize they always apply to master?
