### ISSUE TITLE
Add JRuby-9000 to appveyor.yml

### ISSUE THREAD

**Issue by bf4** [rails-api/active_model_serializers#1408]
Per https://github.com/rails-api/active_model_serializers/pull/1405

Perhaps see https://github.com/shoes/shoes4/blob/master/appveyor.yml and https://github.com/rails-api/active_model_serializers/commit/8bddef6

Should just be

```yaml
 matrix:
    - ruby_version: "jruby-9.0.4.0"
```

**Comment by nadavshatz** [comment]
This can be closed btw :)
