### ISSUE TITLE
can't getting serialized associations of parent of object

### ISSUE THREAD

**Issue by mepatterson** [rails-api/active_model_serializers#1421]
I can't really get any use out of the `include` feature at all for the problem I'm trying to solve. I'm using the simple JSON adapter.

I have an OrganizationSerializer:
```ruby
class OrganizationSerializer < ActiveModel::Serializer
  attributes :id, :name, :created_at
  has_many :apps, class_name: 'Client::Application', serializer: ClientAppSerializer
  has_many :services
end
```
and a ClientAppSerializer:
```ruby
class ClientAppSerializer < ActiveModel::Serializer
  attributes :id, :name, :created_at
  belongs_to :organization
end
```
and a ServiceSerializer:
```ruby
class ServiceSerializer < ActiveModel::Serializer
  attributes :id, :name, :created_at, :updated_at
  belongs_to :organization
end
```
Pretty simple, right?

Let's say I want to serialize starting at the App level:
```ruby
render json: @app, serializer: ClientAppSerializer
```

I'll get the serialized data for the App, and the serialized data for the Organization, but the Organization won't have any Services array.

```ruby
{
                 "id" => 1,
               "name" => "Test App",
         "created_at" => "2016-01-09T18:52:50.666Z",
       "organization" => {
                "id" => 1,
              "name" => "Amazing Organization 1",
        "created_at" => "2016-01-09T18:52:50.634Z"
    }
}
```

So I try this...
```ruby
render json: @app, serializer: ClientAppSerializer, include: 'organization.services'
```
... but nothing changes in my serialized output. No services.

Am I missing something fundamental here?

**Comment by bf4** [comment]
Please see https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md and add the requested information to this issue.

**Comment by beauby** [comment]
Could you post the result of `@app.organization.services`?

**Comment by mepatterson** [comment]
```ruby
2.2.3 :001 > @app.organization.services
=> [#<Service:0x007f9360d085e0 id: 1, organization_id: 1, name: "test", secret: "notserialized", created_at: Tue, 12 Jan 2016 14:57:23 UTC +00:00, updated_at: Tue, 12 Jan 2016 14:57:23 UTC +00:00>]
```

**Comment by beauby** [comment]
Could you provide your AMS, Rails, and ruby versions, as well as your model definitions?

**Comment by mepatterson** [comment]
active_model_serializers (0.10.0.rc3)
rails (4.2.4)
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

```ruby
class Organization < ActiveRecord::Base
  has_many :registered_applications, class_name: 'Doorkeeper::Application', as: :owner, dependent: :destroy
  has_many :services
end

class Service < ActiveRecord::Base
  belongs_to :organization
end

# in this case, the 'Client::Application' is actually a Doorkeeper::Application, which has an `owner` that is the Organization. 
# I simplified the ClientAppSerializer example above for illustration purposes; in my code it's actually...

class ClientAppSerializer < ActiveModel::Serializer
  attributes :id, :name, :created_at
  belongs_to :owner, key: 'organization'
end

#...but I get same results with or without the key name change; that is, I get the 'organization' (aka owner) serialized, but it doesn't serialize any of its child associations.


```

**Comment by beauby** [comment]
Could you try with master instead of 0.10.0-rc3?

**Comment by pasku** [comment]
Any updated on this?

**Comment by beauby** [comment]
@pasku Awaiting submitter's response.

**Comment by mepatterson** [comment]
Hi, sorry… i haven’t had a chance to test yet. been pulled away on other things. will try to get to it soon.



On January 26, 2016 at 11:26:01 AM, Guillermo Pascual (notifications@github.com) wrote:

Any updated on this?

**Comment by alexperezpaya** [comment]
class ApplicationSerializer < ActiveModel::Serializer
  def self.has_one_included(*atts)
    atts.each do |att|
      attribute(att) do
        ActiveModel::SerializableResource.new(object.send(att))
      end
    end
  end
end

This is our current approach for solving this. cc// @pasku

**Comment by bf4** [comment]
Would you mind adding some more information per the CONTRIBUTING?  I'm not sure if this is a bug or feature request.

Thanks for writing!  

B mobile phone

**Comment by remear** [comment]
Closing due to lack of requested information. If this is still a problem, please open a new issue with as much information as possible.
