### ISSUE TITLE
Links object must be a member of Relationships object

### ISSUE THREAD

**Issue by d3crypt3d** [rails-api/active_model_serializers#1422]
I discovered that [links object](http://jsonapi.org/format/#document-links) currently is not a member of [relationships object](http://jsonapi.org/format/#document-resource-object-relationships). 
Here is an example of resource object that I got:
```javascript
{
  "data": [{
    "id":"980191848",
    "type":"projects",
    "attributes": {
      "name":"optio",
      "created_at":"2016-01-10T17:21:54.266Z",
      "updated_at":"2016-01-10T17:21:54.266Z"
      }, "relationships": {
           "tasks": { 
             "data": [{ 
               "id": "980191660", "type": "tasks"
             }]
         }
      }, "links": {
           "self":"//foo",
           "related":"//bar"
         }
      }
  ]}
}
```
In other words **link** object is a neighbour of the **relationships** one. However, according to JSON API specification, **relationships** should had included **links** inside the **tasks** container:
```javascript
  "relationships": {
     "tasks": {
       "links": {
         "self":"//foo",
         "related":"//bar"
       }, "data": [{ 
             "id": "980191660", "type": "tasks"
          }]
    }
  }
```
And it doesn't depend on how the links method is defined: 
```ruby
link :self, '//foo'
# or
def link
  api_path(object)
end
```
How does the link object could be placed in a proper container?

**Comment by beauby** [comment]
The JSON API spec defines various types of links. You are looking for relationship-level links, for which I'm working on a PR.

**Comment by jordonbiondo** [comment]
#1454
