### ISSUE TITLE
Serializing resource errors using json_api adapter

### ISSUE THREAD

**Issue by matixmatix** [rails-api/active_model_serializers#1428]
How to serialize model's errors in a way that conforms to [JSON API error response](http://jsonapi.org/examples/#error-objects-basics) spec when using json_api adapter? Is there a solution present for this or do I need to make my own custom errors serializer?

**Comment by bf4** [comment]
There is a branch that's being refined that does that  https://github.com/rails-api/active_model_serializers/pull/1004
