### ISSUE TITLE
Unable to use attributes adapter within controller

### ISSUE THREAD

**Issue by JahBrewski** [rails-api/active_model_serializers#1434]
I'm having trouble setting the attributes adapter for a particular controller.

For most of my controllers, I want to use the json adapter, so I have this line of code in my ams.rb initializer:
```ruby
ActiveModelSerializers.config.adapter = :json
```

However, I don't want the root element in several of my controllers, so I am trying to use the attributes adapter like so:

```ruby
def index
  respond_with ParkingLocation.all, adapter: :attributes
end
```
And now I'm getting this error:

```ruby
ActiveModel::Serializer::Adapter::UnknownAdapterError (NameError: uninitialized constant     ActiveModel::Serializer::Adapter::Attribute. Unknown adapter: :attributes. Valid adapters are: ["json"]):
  app/controllers/api/v1/parking_locations_controller.rb:25:in `index'
```

I am using:
```ruby
    gem 'active_model_serializers', '~> 0.10.0.rc3'
```

**Comment by bf4** [comment]
I haven't confirmed this is tests, but do you perhaps have any inflections configured

**Comment by JahBrewski** [comment]
That did it! Awesome.

**Comment by bf4** [comment]
@JahBrewski and thanks for coming back, commenting, and closing the issue!
