### ISSUE TITLE
Errors after rails s

### ISSUE THREAD

**Issue by Masquetina** [rails-api/active_model_serializers#1438]
Hi,

This is inside my config/json_api.rb:
ActiveModel::Serializer.config.adapter = ActiveModel::Serializer::Adapter::JsonApi

Problem is, when I run rails s, (after I installed active_model_serializer 0.10.0.rc3 of course), I get tons of errors, and can not get server to run. ... But sometimes, it just works... Most of the time it does not! Is there any rational explanation?
And important info is that I use Rails 5 API mode.

**Comment by natematykiewicz** [comment]
What are the errors?

**Comment by dkniffin** [comment]
I'm having a similar issue.

I tried adding this into `config/initializers/active_model_serializers.rb` (which is what the [the docs](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md) say to do):

````ruby
ActiveModelSerializers.config.adapter = :json_api
````

But now when I do `rails s`, I get:

````ruby
.../config/initializers/active_model_serializers.rb:1:in `<top (required)>': uninitialized constant ActiveModelSerializer (NameError)
````

**Comment by natematykiewicz** [comment]
@dkniffin, which version of active_model_serializers are you using? Is it 0.10.0.rc3 as well?

**Comment by dkniffin** [comment]
Nope, mine is the current release version: 0.9.3

**Comment by joaomdmoura** [comment]
@dkniffin the 0.9.3 does not support `json-api` only the 0.10 RCs support it.
@Masquetina could you paste the Rails logo here or in a gist so that we can check the errors?

**Comment by natematykiewicz** [comment]
Also, @dkniffin 0.8, 0.9 and 0.10 are all pretty different. You'll want to make sure you look at the docs for the version you're using.

https://github.com/rails-api/active_model_serializers/blob/v0.9.3/README.md

**Comment by dkniffin** [comment]
:+1: Switching to 0.10.0.rc3, and following the docs for it helped. I ended up needing `ActiveModel::Serializers.config.adapter = :json_api`

**Comment by Masquetina** [comment]
Exiting
/home/masquetina/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializer.rb:152:in `read': no implicit conversion of nil into String (TypeError)
	from /home/masquetina/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializer.rb:152:in `digest_caller_file'
	from /home/masquetina/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializer.rb:47:in `inherited'
	from /home/masquetina/Završni rad/II-TestApp/API/app/serializers/todo_serializer.rb:1:in `<top (required)>'

**Comment by beauby** [comment]
@Masquetina Could you try with master? I believe this is caused by your file's path having a space in it (`Završni rad/`), and was fixed post RC3.

**Comment by Masquetina** [comment]
@beauby Yes, that is it! Thank You!

**Comment by thomasbiddle** [comment]
@beauby I've run into this issue with 0.10.0.rc3 on Rails 4.2.5.1. I had to ensure my file path did not have a space - it is seem to be fixed.
