### ISSUE TITLE
Custom (default) CollectionSerializer

### ISSUE THREAD

**Issue by MarkMurphy** [rails-api/active_model_serializers#1440]
I'd like to configure a custom CollectionSerializer which would generate output similar to the following:

```json
{ 
  "object": "list",
  "url": "https://api.example.com/photos",
  "data": [
    {...}, 
    {...}
  ]
}
```
I know how to change the default collection serializer via the config settings in an initializer but I can't seem to get this output working. It continues to just output a basic array. I'm using [current master](https://github.com/rails-api/active_model_serializers/commit/f2d59b20caa52244f907aa607bf7d8827c46cb7f)

**Comment by natematykiewicz** [comment]
Which adapter are you using currently? For this kind of structure, you'll need to write your own custom adapter. Unfortunately there's currently no documentation on creating a custom adapter. See #1317 for some details, though.

I will say, this looks similar to http://jsonapi.org. JSON API is supported using the `:json_api` adapter.
