### ISSUE TITLE
Common functionality between Serializer and CollectionSerializer

### ISSUE THREAD

**Issue by MarkMurphy** [rails-api/active_model_serializers#1441]
It would be nice to have a shared api between `ActiveModel::Serializer` and `ActiveModel::Serializer::CollectionSerializer` (why not just `ActiveModel::CollectionSerializer`?) so that one could do something like this:

```ruby
# config/initializers/serializers.rb
ActiveModel::Serializer.config.collection_serializer = ListSerializer
```

```ruby
class ListSerializer < ActiveModel::CollectionSerializer
  attribute :object do
    "list"
  end

  attributes :url, :has_more

  def url
    # ... 
    # => "https://api.example.com/users"
  end

  def has_more
    # ...
    # => true
  end
end
```

```ruby
class UsersController
  def index
    # ...
    return render json: @users
    # => {
    #   "object": "list",
    #   "url": "https://api.example.com/users",
    #   "has_more": true,
    #   "data": [
    #     { ... } ,
    #     { ... } 
    #   ]
    # }
  end
end
```

**Comment by beauby** [comment]
Interesting idea. In the current philosophy of AMS, what you're doing in your `ListSerializer` is arguably the adapter's job. Note also that the format you are describing is really close to that of [JSON API](http://jsonapi.org), for which there is almost full support in AMS.

**Comment by MarkMurphy** [comment]
@beauby Yeah, not a fan of jsonapi.org's proposal for several reasons but I'll save that rant for another time. 

I think this idea would greatly simplify things for a lot of developers, although I admit I am lacking in depth experience/knowledge with AMS (mostly due to insufficient examples and documentation).

**Comment by bf4** [comment]
@markmurphy I'm going on vacation for a week and a half, and when I get back, I'd love to work with you on improving code and docs.  Have you read the Architecture doc or others?

**Comment by MarkMurphy** [comment]
@bf4 

> Have you read the Architecture doc or others?

Yes I have, I really didn't find them very helpful, my eyes sort of glazed over...

I've been looking through the repository's code over the last couple of days and I'm slowly beginning to wrap my head around how things are pieced together. However, the more I begin to understand the more  frustrated I become. It just shouldn't be this difficult for someone to customize a serializer any way they want (singular resource or collection). 

@bf4 If you're an API nerd, check this out while you're on vacation: http://amberonrails.com/move-fast-dont-break-your-api/

**Comment by bf4** [comment]
Yeah, codebase has cruft... I wrote the architecture docs orginally as a comment explaining how the main objects and what the do... I'd love your input on how to make it more helpful.  We're all in this together:) clarifying the public interfaces is one of my goals

B mobile phone
