### ISSUE TITLE
Move ActiveModel::Serializer::Adapter to ActiveModelSerializers::Adapter

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1446]

**Comment by beauby** [comment]
(cc @bf4, @joaomdmoura)

**Comment by bf4** [comment]
:)

B mobile phone

**Comment by domitian** [comment]
Hi,
Does this mean, there is discussion going on whether or not to change namespacing or can I start on moving the`ActiveModel::Serializer::Adapter` name to ` ActiveModelSerializers::Adapter`?

**Comment by bf4** [comment]
You can move it, and I'll help w any conplications and deprecations

B mobile phone

**Comment by domitian** [comment]
I Will try to have the PR by end of this week, thanks for help in advance.

**Comment by remear** [comment]
This looks resolved by #1535
