### ISSUE TITLE
Polymorphic association on JSON API

### ISSUE THREAD

**Issue by joaomdmoura** [rails-api/active_model_serializers#1448]
When using JSON-API with polymorphic associations there is a strange behavior, instead of using the name of the resource it chooses to use the name assigned to the polymorphic relation.

This is not `wrong` :copyright:, but if you think about the most of JS clients frameworks around, it makes more sense to use the resource's name.

Here is as example to illustrate:

*model/address.rb*
```ruby
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
end
```

*model/user.rb*
```ruby
class Address < ActiveRecord::Base
  has_one :home_address, as: :addressable, class_name: 'Address', dependent: :destroy
end
```

The serialized JSON output for address will be:
```ruby
'data': {
  'id': 1,
  'type': 'addresses',
  'attributes': {
    ...
  },
  'relationships':  {
    'addressable': {
      'data': {
        'id': 1,
        'type': 'users'
      }
    }
  }
}
```

My point is related to this part:
```ruby
  'relationships':  {
    'addressable': {
      'data': {
        'id': 1,
        'type': 'users'
      }
    }
  }
}
```

Despite of being a user the root name of this node is `addressable`, and IMO it should be `user`.

**Comment by beauby** [comment]
I agree. We might need a `polymorphic` relationship option as described in #1420.

**Comment by beauby** [comment]
cf #1453

**Comment by joaomdmoura** [comment]
Checked both! Nice!

**Comment by beauby** [comment]
What happens when the `addressable` association is `nil`? What name should we give it?
What happens with heterogeneous `has_many` polymorphic associations?

**Comment by cgmckeever** [comment]
Realize this is closed, but I am fighting a similar issue around the naming of polymorphic associations.  No offense @joaomdmoura, but I feel the way the json-api is set up is correct.  There may be multiple of those polymorphs, so nesting them under 'addressable' and then defining what type it is gives the flexibility needed.

It appears that this behavior stopped happening for the JSON adapter circa rc3 
https://github.com/rails-api/active_model_serializers/pull/1420#issuecomment-172623571

And, again, I feel this is limited ... I also have a issue open around this demonstrating more https://github.com/rails-api/active_model_serializers/issues/1717
