### ISSUE TITLE
How do I configure the adapter?

### ISSUE THREAD

**Issue by dkniffin** [rails-api/active_model_serializers#1451]
I tried adding this into `config/initializers/active_model_serializers.rb` (which is what the [the docs](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md) say to do):

````ruby
ActiveModelSerializers.config.adapter = :json_api
````

But now when I do `rails s`, I get:

````ruby
.../config/initializers/active_model_serializers.rb:1:in `<top (required)>': uninitialized constant ActiveModelSerializer (NameError)
````

Can someone please tell me how to configure AMS to use json_api?

**Comment by beauby** [comment]
`ActiveModelSerializer` should be `ActiveModelSerializers` (plural). Plus, this applies only if you're running master. Otherwise, you have to use `ActiveModel::Serializer.config`.
