### ISSUE TITLE
JsonApi pagination gives wrong links under specific circumstances.

### ISSUE THREAD

**Issue by dmons** [rails-api/active_model_serializers#1452]
It's very easy to bring down a per_page count for JsonApi adaptor.
Used:
* ams from github/master(7bc66c53342540a5a6e9506abdbc04db0c2c966d)
* rails 4.2
* kaminari
* ruby 2.1.1

Steps to reproduce:

1. Configure **:json_api** adapter and use it with any serializer for collection which have enough items for couple pages
E.g. We have ```{@items.count}.to eq 10```

2. Having `page[:size]=4` we are going to visit last page(`#3`) and will see 2 items as expected.

3. Visit generated link to previous page and you will see 2 items as well. But we still should have page[:size]=4 ! 

`page[:size]` param will become 2, because here https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json_api/pagination_links.rb#L17  will be captured value of 2 for last page.

**Comment by beauby** [comment]
This seems right indeed. Would you mind issuing a PR @dmons?

**Comment by remear** [comment]
https://github.com/rails-api/active_model_serializers/pull/1443#issuecomment-173623073
