### ISSUE TITLE
Options Variable is not defined

### ISSUE THREAD

**Issue by edwinlunando** [rails-api/active_model_serializers#1456]
I'm using the master branch of this Gem, but I cannot use the `options` on the serializer. This is the serializer. It says `undefined local variable or method 'options' for #<FormulaSimpleSerializer:0x007fbbce312bd0>`

```ruby
class FormulaSimpleSerializer < ActiveModel::Serializer

  attributes :favorited

  def favorited
    return nil if options[:user].blank?
    return true if options[:user].voted_for? object
    false
  end

end
```

This is the render code.

```ruby
render json: Formula.all, user: tokenized_user
```

When I'm using the `0.10` version, it works well.

**Comment by beauby** [comment]
`options` has been renamed `instance_options` post RC3.
