### ISSUE TITLE
Breaks Rails model generator

### ISSUE THREAD

**Issue by andrewhamon** [rails-api/active_model_serializers#1465]
Just by having `gem 'active_model_serializers', github: 'rails-api/active_model_serializers'` in my Gemfile, running `rails g model foobar` simply does nothing and returns immediately.

##### Version (from Gemfile.lock)

```
GIT
  remote: git://github.com/rails-api/active_model_serializers.git
  revision: 8981683b9fa8d0bcff0e76b3702d699689b787b4
  specs:
    active_model_serializers (0.10.0.rc3)
      actionpack (>= 4.0)
      activemodel (>= 4.0)
      railties (>= 4.0)
```

##### Operating system
OSX El Capitan

##### Ruby manager
chruby

##### Ruby version
`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`

##### Steps to reproduce

```
rails-api new test-app
cd test-app
echo "gem 'active_model_serializers', github: 'rails-api/active_model_serializers'" >> Gemfile
bundle
rails g model foobar
```

##### Expected outcome
A model and specs get generated

##### Actual outcome
```
ahamon in ~/code/test-app
> rails g model foobar
Running via Spring preloader in process 17464

ahamon in ~/code/test-app
> rails g model foobar
Running via Spring preloader in process 17466

ahamon in ~/code/test-app
> rails g model foobar
Running via Spring preloader in process 17469
```

It does nothing and returns immediately each time.

##### Things I've tried
- Turning off Spring

##### Test repo
https://github.com/andrewhamon/active_model_serializers_test_app

**Comment by anonova** [comment]
Did a bisect, and the offending commit is 8981683b9fa8d0bcff0e76b3702d699689b787b4. cc @dgynn @bf4

**Comment by beauby** [comment]
Thanks for the investigation guys! @bf4 won't be around until next week I believe. 
@dgynn: Would you mind investigating the cause?

**Comment by dgynn** [comment]
Yes. I've found the problem and I'm testing a fix now. Thanks for finding that @andrewhamon and @anonova.
