### ISSUE TITLE
Release 0.9.4

### ISSUE THREAD

**Issue by kurko** [rails-api/active_model_serializers#1468]
I talked to @bf4 about releasing 0.9.4.

@bf4 can you link here what issues are pending for a new release so we can track it in one place?

**Comment by beauby** [comment]
:+1:

**Comment by bf4** [comment]
Already released, https://rubygems.org/gems/active_model_serializers/versions/0.9.4 just didn't update the changelog on master yet

**Comment by bf4** [comment]
(It *is* updated on 0-9-stable https://github.com/rails-api/active_model_serializers/blob/0-9-stable/CHANGELOG.md )
