### ISSUE TITLE
Setting fields with a parameter using JSON API

### ISSUE THREAD

**Issue by DrSayre** [rails-api/active_model_serializers#1469]
I am trying to pass a fields parameter in my request.  It works fine if I do this:
```ruby
# app/controllers/authors_controller.rb
def index
    authors = Author.all
    render json: authors, include: params[:include], fields: {authors: [:id], posts: [:title]}
end
```
I get only the id on authors and title for posts, but if I have this:
```ruby
# app/controllers/authors_controller.rb
def index
    authors = Author.all
    render json: authors, include: params[:include], fields: params[:fields]
end
```
_http://localhost:3000/authors?include=posts&fields[authors]=id&fields[posts]=title_ will return all attributes on authors and posts.  I would expect I would get the same thing as I did in my first example.

Here is my models:
```ruby
# app/models/author.rb
class Author < ApplicationRecord
	has_many :posts
end
```
```ruby
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments
end
```
And here is my serializers:
```ruby
class AuthorSerializer < ActiveModel::Serializer
  attributes :id, :name
  has_many :posts
end
```
```ruby
# app/serializers/author_serializer.rb
class AuthorSerializer < ActiveModel::Serializer
  attributes :id, :name
  has_many :posts
end
```
```ruby
# app/serializers/post_serializer.rb
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :text
  belongs_to :author
  has_many :comments
end
```

**Comment by beauby** [comment]
Try `params[:fields] = params[:fields].map { |rel, fields| { rel => fields.split(',').map(&:to_sym) }.reduce({}, :merge)`.

**Comment by DrSayre** [comment]
@beauby did you forget a } in that? I put it at the end and got this error:
```
undefined method `map' for {"authors"=>"id", "posts"=>"title"}:ActionController::Parameters Did you mean? tap
```

**Comment by beauby** [comment]
Yeah I did. I just edited my answer.

**Comment by beauby** [comment]
You probably need to call `to_unsafe_hash` on `params[:fields]` though, as it does not inherit from Hash anymore.

**Comment by DrSayre** [comment]
Excellent, thanks @beauby!
