### ISSUE TITLE
Rspec tests & assert_response_schema

### ISSUE THREAD

**Issue by rubydev** [rails-api/active_model_serializers#1470]
Is possible use this method "assert_response_schema" for rspec? Or how can I test schema with rspec? Thanks for answer!

**Comment by bf4** [comment]
@rubydev I'm not sure where to implement that right now.  I'd be up for creating an rspec-active_model_serializers repo in the rails-api org.  I'd help write it, too.  Cc @rails-api/ams

**Comment by kurko** [comment]
IHMO, it'd not be rails-api's responsibility to maintain RSpec adapters (even though I use it). We should just expose a common interface and other libs could plug into it.

**Comment by rafaelgonzalez** [comment]
I would live to to see this :+1: 

Just started to use the gem and I would love to DRY up my specs using JSON schemas with the RSpec equivalent of `assert_response_schema `

**Comment by bf4** [comment]
@rafaelgonzalez I haven't tested this but you should be able to

```ruby
RSpec.describe SomeController, type: :controller do
  include ActiveModelSerializers::Test::Schema
  private def assert(expected, actual)
    expect(actual).to eq(expected)
  end

   it '#show' do
     get :show
     assert_response_schema
   end
end
```

When we wrote it we had this mind

**Comment by rafaelgonzalez** [comment]
Nice, it kinda works:

```ruby
require 'rails_helper'

RSpec.describe Api::V1::NeedsController, type: :controller do
  include ActiveModelSerializers::Test::Serializer
  private def assert(expected, actual)
    expect(actual).to eq(expected)
  end

  before do
    create_list(:need, 10)
  end

  describe '#show' do
    it '' do
      get :show, id: Need.first.id, format: :json
      assert_serializer "[Api::V1::NeedSerializer]"
    end
  end
end
```

```
$ rspec spec/controllers/api/v1/need_controller_spec.rb 
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 61288

Api::V1::NeedsController
  #show
    should eq false (FAILED - 1)

Failures:

  1) Api::V1::NeedsController#show should eq false
     Failure/Error: expect(actual).to eq(expected)
     
       expected: false
            got: "expecting <\"[Api::V1::NeedSerializer]\"> but rendering with <[\"Api::V1::NeedSerializer\"]>"
     
       (compared using ==)

Finished in 0.17125 seconds (files took 2.49 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/api/v1/need_controller_spec.rb:14 # Api::V1::NeedsController#show should eq false
```

I'm not sure what this means, I'll investigate on my end, thanks for your help!

**Comment by bf4** [comment]
If you can provide a more full example that I can run I might be able to help you debug that.  I might also write a custom rspec matcher.

**Comment by bf4** [comment]
@rafaelgonzalez (also, you changed to try the assert_serializer, which has a different requirement.. see https://github.com/rails-api/active_model_serializers/blob/f32c0d97d5a3a609979b57655e107f678470fdaa/lib/active_model_serializers/test/serializer.rb#L7-L9 though I admit that's a strange error message)

**Comment by bf4** [comment]
Oh, bug it my assert hack. should be

```ruby
private def assert(bool, failure_message)
  return if bool
  RSpec.configuration.reporter.message failure_message
  expect(bool).to eq(true)
end
```

I'm not sure how to get rspec to use that failure message without the reporter like that

**Comment by rafaelgonzalez** [comment]
Sweet, that works @bf4, thanks heaps :metal:

**Comment by bf4** [comment]
Wanna add a pr to the integrations docs? or maybe it should be under testing?  Or maybe testing should link to integrations?

**Comment by rafaelgonzalez** [comment]
No promises, but I'll try to make RSpec use that message in a better way, I have no idea how it works but I'll have look. :)

**Comment by rafaelgonzalez** [comment]
So, after looking at the [RSpec docs](http://www.relishapp.com/rspec/rspec-expectations/v/3-4/docs), I've worked out something a bit different:

```ruby
module ActiveModelSerializers
  module Test
    module Serializer
      extend ActiveSupport::Concern

      def serializer_matches?(expectation)
        @assert_serializer.expectation = expectation
        @assert_serializer.message = message
        @assert_serializer.response = response
        @assert_serializer.matches?
      end

      def message
        @assert_serializer.message
      end

      RSpec::Matchers.define :use_serializer do |expected|
        match do |actual|
          serializer_matches?(expected)
        end
        failure_message do |actual|
          message
        end
      end
```

Which allows you to do the following:

```ruby
  it { expect(controller).to use_serializer(Api::V1::NeedSerializer) }
  # or the following, since it does not matter what you pass to `expect()`, since we won't use `actual` anyway:
  it { is_expected.to use_serializer(Api::V1::NeedSerializer) }
```

And the errors are managed returned by RSpec!

I'm happy to submit this as a PR, I'm not sure you would want those in `ActiveModelSerializers::Test::Serializer` ?

**Comment by NullVoxPopuli** [comment]
I'd be very happy to see this as a PR. I'd review it right now :-)

**Comment by merqlove** [comment]
Hmm, it works for me after that, without `assert` hack:

```
# /spec/support/api.rb
RSpec.configure do |config|
  config.include ActiveModelSerializers::Test::Schema, file_path: /spec\/controllers\/api/
end
```

**Comment by bf4** [comment]
Well, there's no code yet, but started an rspec test helpers repo thinking any rspec integration should be tested rather than just documented, if anyone is interested in contributing some code or comments there https://github.com/bf4/active_model_serializers-rspec (should it be rspec-activemodelserializers? )

B mobile phone

**Comment by remear** [comment]
Should probably be `rspec-activemodelserializers`. I suggest continuing work on this over on that repo and eventually maybe move it under `rails-api`.

**Comment by dbwieland18** [comment]
I'm not able to ```include ActiveModelSerializers::Test::Schema```--did something change around that? Looking into it now...

**Comment by bf4** [comment]
@dbwieland18 could you update here with your resolution when you have it? (I'm guessing from our chat in the slack that is was Spring)

**Comment by leonelgalan** [comment]
@rafaelgonzalez, my dirty solution for the `ActiveModel::Serializer::CollectionSerializer` issue (rewrite `AssertSerializer`'s `subscribe` :

```ruby
class AssertSerializer
  def subscribe
     @_subscribers << ActiveSupport::Notifications.subscribe(event_name) do |_name, _start, _finish, _id, payload|
       serializer = payload[:serializer].name
       serializers << serializer
       return unless serializer == 'ActiveModel::Serializer::CollectionSerializer'
       serializers << payload[:adapter].serializer.send(:options)[:serializer].name
     end
   end
 end
```

I'm new to AMS 0.10.x, but other than going through the adapter's serializer private options, is there a cleaner way to get the serializer used inside `CollectionSerializer`

**Comment by leonelgalan** [comment]
About `assert_response_schema`, it worked for me with the following caveats: 

- I had to specify a `schema_path`. `schema_path_default` will return `"/.json"`. That's because `request.filtered_parameters[:controller]` was `nil`, instead `request.filtered_parameters['controller']` had the correct controller name and same for `request.filtered_parameters['action']`.
- I used the latest `assert` provided by @bf4.

The complete code can be found in this gist: https://gist.github.com/leonelgalan/752f79a2e630b7281b7d1fe60e99dfe9

I'm working on creating a matcher for `assert_response_schema`, but that might happen tomorrow after a night of sleep.

**Comment by bf4** [comment]
@leandrocp Would be great if you can share some of this work back as PRs!

**Comment by leonelgalan** [comment]
@bf4, wrong @-mention. I'm happy to submit something, but could we discuss a few things first:

- A better way to pull the serializer when `ActiveModel::Serializer::CollectionSerializer` is used, currently I'm doing `payload[:adapter].serializer.send(:options)[:serializer].name if payload[:serializer].name == 'ActiveModel::Serializer::CollectionSerializer'`
- What's the best way to include this functionality without monkey patching `ActiveModelSerializers::Test::Serializer`, `ActiveModelSerializers::Test::Serializer::AssertSerializer` and `ActiveModelSerializers::Test::Schema::AssertSchema`.

I'm currently trying to write `RSpec::ActiveModelSerializers::Matchers::Serializer` and `RSpec::ActiveModelSerializers::Matchers::Schema` after similar matchers find in other gems: _rspec-rails_, etc. I'll report back when I have something to show.
