### ISSUE TITLE
Overwriting root from within serializer - 0.9.3

### ISSUE THREAD

**Issue by eidge** [rails-api/active_model_serializers#1473]
I'm trying to set a root for a serializer, and even though I can set it per controller with:

```render json: MySerializer, root: 'fancy_serializer_name'```

And I can disable it per serializer with:

```ruby
class MySerializer < ActiveModel::Serializer
  self.root = false
end
```

I cannot overwrite per serializer, meaning I have to duplicate root naming per controller. What I would like to do is:

```ruby
class MySerializer < ActiveModel::Serializer
  self.root = "fancy_serializer_name" # gets automatically pluralized for ArraySerializer
end
```

Is there a way to do this?

**Comment by bf4** [comment]
This is for a single resource?  I recall dealing with that when I was on 0.9, that the root option wasn't actually being passed in.. did you look through old issues for anything related?

**Comment by eidge** [comment]
Couldn't find anything related to overwriting the default root.

Resource == Database table?

I do have that case as well, but in this case it's just serializing a PORO. I do have a case where I have a serializer for more than a single resource, and being able to overwrite the root is just as important.

**Comment by remear** [comment]
We're focusing on finishing 0.10. We'd welcome a PR for this if anyone is interested.
