### ISSUE TITLE
includes param ignored with JSON-API adapter

### ISSUE THREAD

**Issue by soberstadt** [rails-api/active_model_serializers#1474]
My test repo: https://github.com/soberstadt/ams-test

I am trying to use optional includes on a serializer, using the json_api adapter, but it's ignoring what I'm passing in and including everything. Here's what I mean:

``` ruby
class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class PostsController < ApplicationController
  def show
    render json: Post.find(params[:id]), include: params[:include]
  end
end
```

Regardless of what I pass into the include option, it always includes the comments. But it works with the json adapter. Here's my spec:
``` ruby
require 'rails_helper'

describe PostsController, type: :controller do
  describe 'show' do
    let!(:post) do
      p = Post.create(title: 'Test Post')
      Comment.create(body: 'this is a comment', post: p)
      p
    end

    it 'with json_api' do
      ActiveModelSerializers.config.adapter = :json_api
      get :show, id: post.id, format: :json, include: 'comments'
      json = JSON.parse(response.body)
      expect(json['data']['relationships']['comments']['data'].length).to be 1

      get :show, id: post.id, include: ''
      json = JSON.parse(response.body)
      relationships = json['data'].try(:[], 'relationships') || {}
      # this fails
      expect(relationships).to_not include 'comments'
    end

    it 'with json adapter' do
      ActiveModelSerializers.config.adapter = :json
      get :show, id: post.id, format: :json, include: 'comments'
      json = JSON.parse(response.body)
      expect(json['post']['comments'].length).to be 1

      get :show, id: post.id, include: ''
      json = JSON.parse(response.body)
      expect(json['post']).to_not include 'comments'
    end
  end
end
```

It the include param effects the json response when using the :json adapter, but not when I use :json_api.

I am using the latest master (58ff7535b7d619028d542f49831d43504b5d89be) with ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14] on rbenv, OSX 10.11.2.

**Comment by bf4** [comment]
@soberstadt awesome issue, thanks!

**Comment by bf4** [comment]
Uninformed lazy comment, maybe related to https://github.com/rails-api/active_model_serializers/issues/1469 cc @beauby

**Comment by soberstadt** [comment]
If I define the includes as empty in my controller, it still includes the related records.

More code tested:
``` ruby
class PostsController < ApplicationController
  def show
    render json: Post.find(params[:id]), include: '' # same thing if I put in []
  end
end

require 'rails_helper'

describe PostsController, type: :controller do
  describe 'show' do
    let!(:post) do
      p = Post.create(title: 'Test Post')
      Comment.create(body: 'this is a comment', post: p)
      p
    end

    it 'with json_api' do
      ActiveModelSerializers.config.adapter = :json_api
      get :show, id: post.id
      json = JSON.parse(response.body)
      p json # {"data"=>{"id"=>"1", "type"=>"posts", "attributes"=>{"title"=>"Test Post"}, "relationships"=>{"comments"=>{"data"=>[{"id"=>"1", "type"=>"comments"}]}}}}
      relationships = json['data'].try(:[], 'relationships') || {}
      # this fails
      expect(relationships).to_not include 'comments'
    end

    it 'with json adapter' do
      ActiveModelSerializers.config.adapter = :json
      get :show, id: post.id
      json = JSON.parse(response.body)
      p json # {"post"=>{"id"=>1, "title"=>"Test Post"}}
      expect(json['post']).to_not include 'comments'
    end
  end
end

**Comment by beauby** [comment]
This is expected behavior, c.f. JSON API spec. Those are Resource Identifiers, and not Resource Objects (they only contain linkage information, not the attributes/relationships).

**Comment by soberstadt** [comment]
Can you please give an example of how it is supposed to work? It doesn't make sense that the json_api adapter would behave differently from the json adapter.

**Comment by bf4** [comment]
> It doesn't make sense that the json_api adapter would behave differently from the json adapter.

Would it make sense if they behaved the same?

B mobile phone

**Comment by soberstadt** [comment]
My understanding was that the adapter controlled how the json was built, but that the logic for what was put into the json was the serializers job. Could someone show how that code is supposed to be to not include the related  objects?

**Comment by chrisrecalis** [comment]
Json API spec only says that the resource object may include relationships. Preferably I would want an option to exclude these unless otherwise specified in the include parameter (Maybe an option in the json api adapter?). This is because building the relationships object sometimes requires unnecessary (potentially costly) queries to build the object. Most of the time for my application relationships isn't needed unless the client wants the included relationships

**Comment by soberstadt** [comment]
Wow... so after reading this for the 10th time. I'm finally understanding @beauby's comment. My spec should be:
``` ruby
require 'rails_helper'

describe PostsController, type: :controller do
  describe 'show' do
    let!(:post) do
      p = Post.create(title: 'Test Post')
      Comment.create(body: 'this is a comment', post: p)
      p
    end
    before do
      ActiveModelSerializers.config.adapter = :json_api
    end

    it 'with json_api' do
      get :show, id: post.id, include: 'comments'
      json = JSON.parse(response.body)
      expect(json['included'].length).to be 1

      get :show, id: post.id, include: ''
      json = JSON.parse(response.body)
      relationships = json['included'] || []
      expect(relationships).to be_empty
    end
  end
end
``` 

I was confused about what I was looking for. The relationship definitions will always be served, but rendering the related objects are controlled by the include option.

Thanks for your patience!

**Comment by bf4** [comment]
@soberstadt the serializer describes the mappings for attributes and associations, but it is the adapter that chooses which to use and formats them (more or less).

**Comment by bf4** [comment]
@soberstadt I'm not just what that test is testing.. looks like whether or not AMS works?

Anyhow, I'd write those tests something like:

```diff
+ let(:post) { Post.new(id: '1234', title: 'Test Post') }
+ let(:comment) { Comment.new(id: '1337', body: 'this is a comment', post: post)
+ # Note: `p` is a dangerous name for a variable in Ruby since it's also a method on Kernel
-    let!(:post) do
-      p = Post.create(title: 'Test Post')
-      Comment.create(body: 'this is a comment', post: p)
-      p
-    end

+ # config/initializers/active_model_serializers.rb
+ ActiveModelSerializers.config.adapter = :json_api
-    before do
-      ActiveModelSerializers.config.adapter = :json_api
-    end

+    it 'with json_api', :aggregate do
-    it 'with json_api' do
+      allow(Post).to receive(:find).with(post.id).twice.and_return(post)
      get :show, id: post.id, include: 'comments'
-      json = JSON.parse(response.body)
-      expect(json['included'].length).to be 1
+      expect(json_response.keys).to match ['data', 'included']

      get :show, id: post.id, include: ''
-      json = JSON.parse(response.body)
-      relationships = json['included'] || []
-      expect(relationships).to be_empty
+      expect(json_response.keys).to match ['data']
    end
+ def json_response
+   JSON.parse(response.body)
+ end
```
