### ISSUE TITLE
Serializing draper decorators

### ISSUE THREAD

**Issue by mattiassvedhem** [rails-api/active_model_serializers#148]
When serializing a Draper Decorator:

```
class SomeDecorator < Draper::Base
  decorates :some

  def title
    # Something here
  end
end
```

```
some = SomeDecorator.find(params[:id])
render json: some, serializer: SomeSerializer
```

```
class SomeSerializer < ActiveModel::Serializer
  attributes :title
end
```

The serializer is calling the models underlying `title` method. However if I override `title` in the serializer, like this:

```
def title
  object.title
end
```

The serializer is calling the title method on the SomeDecorator object. 

I guess the attributes method is sending the method calls to the underlying `model_class` object . Is this correct? And if so shouldn't attributes also send the methods to the passed object instead of the "magically" resolved `model_class` object?

**Comment by patrickgordon** [comment]
I know this issue is almost 4 years old but... did you ever actually manage to do this?

**Comment by bf4** [comment]
@patrickgordon please open a new issue, reference this one, and describe your problems and include AMS version.  See https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md for help in what to provide.
