### ISSUE TITLE
Recommended way to override as_json / to_json for a class for a version of an API

### ISSUE THREAD

**Issue by tilo** [rails-api/active_model_serializers#1483]
What's an elegant way with Active Model Serializers to override as_json / to_json for a class?
(and for a given version of the API)

Using timestamps as an example. Let's say an API exposes created_at, updated_at, and you want to make sure in version 1 of the API all the timestamps are UNIX timestamps. 

I want to avoid having to define `created_at`, `updated_at` in each and every serializer by hand.

On approach seems to be to monkey patch:

      class ActiveSupport::TimeWithZone
        def as_json
          self.to_f
        end
      end

It's ugly, but it could work.

What if you want to change the timestamps in version 2 of the API to ISO8601 Zulu TZ format?
(and assuming you want to server both versions of the API)
Just monkey-patching TimeWithZone doesn't cut it.. so what's a better way to accomplish this? 

Is there an elegant way to specify that different versions of an API not only have different serializers, but also different as_json / to_json methods for given classes?

**Comment by bf4** [comment]
Intetesting question. The timestamp question is different, but maybe a superclass with a macro?
