### ISSUE TITLE
Deserialize collections

### ISSUE THREAD

**Issue by Andriykoo** [rails-api/active_model_serializers#1484]
Hello! I want to deserialize attached collection and I use ActiveModelSerializers::Deserialization.jsonapi_parse(*args) method for that. Problem is that after deserialization I receive empty hash like { }. Could you explain me how it should work or there is another possibility to solve this problem? Thanks! 
```
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    }
  }]
}
```

**Comment by bf4** [comment]
Current implementation is for single resource. Wanna help out?

**Comment by beauby** [comment]
Something along the line of
```ruby
params.map { |x| ActiveModelSerializers::Deserialization.jsonapi_parse(x) }
```

**Comment by mrryanjohnston** [comment]
@remear Just for clarification: Was this closed because this is a feature currently in development? If not, what is the best way to leave an issue open as a feature request?

**Comment by remear** [comment]
@mrryanjohnston The original question seemed answered. If you're looking for something more in the way of a feature, just open a new issue, give a detailed description and maybe an example of what you're looking for. You may also want to reference this issue if applicable.

**Comment by beauby** [comment]
As it popped up in another issue, I'll say it here as well. The snipped I posted above is not exact, you have to do:
```ruby
params[:data].map { |x| ActiveModelSerializers::Deserialization.jsonapi_parse(data: x) }
```
