### ISSUE TITLE
Override root when using JSON adapter is possible

### ISSUE THREAD

**Issue by AlexVPopov** [rails-api/active_model_serializers#1486]
The [documentation](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md#json) for the JSON adapter say:

> The root key can't be overridden, and will be derived from the resource being serialized.

However, within a controller, when I do
```ruby
render json: @my_resource_collection, root: 'foobar'
```

I am able to override the root to `foobar`. What is the documentation referring to?

**Comment by remear** [comment]
I believe this was intended for the JSON API adapter section.

https://github.com/rails-api/active_model_serializers/pull/1557/files
