### ISSUE TITLE
How to get to_json to behave without render?

### ISSUE THREAD

**Issue by dudo** [rails-api/active_model_serializers#1487]
In my controller, I can convince the app to use my serializers:
```
def show
  @user = User.find_by_id(params[:id])
  render json: @user
end
```
But for the life of me, I can't seem to figure out how to get the object to use the serializer on command. I've tried the following to no avail:
```
@user.to_json
@user.as_json
@user.serializable_hash

UserSerializer.new(@user)
UserSerializer.new(@user).attributes (this almost works, but I have a has_many that I can't get to show up)
```
What am I missing?? This is driving me nuts.

**Comment by domitian** [comment]
You can't, as it is mentioned in this document [https://github.com/domitian/active_model_serializers/blob/design-docs-from-textile-to-md/docs/DESIGN.md#the-most-basic-serializer](Basic Serializer) in design docs.

> Rails will transparently use your serializer when you use render :json in your controller.
So it won't use your serializers `as_json` and `serializable_hash` methods when you are calling from the console, it will by default use the active record methods.

**Comment by bf4** [comment]
@dudo What version of AMS are you on? https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md

The docs describe how to serialize outside a controller https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md

@domitian the file you linked is the original design doc from 2011

**Comment by dudo** [comment]
0.10.0.rc4

```
UserSerializer.new(User.first).as_json
  User Load (0.9ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> {"object"=>{"id"=>1, "name"=>"Brett Dudo", "plaid_public_token"=>nil, "created_at"=>Thu, 21 Jan 2016 05:28:45 UTC +00:00, "updated_at"=>Wed, 03 Feb 2016 05:27:23 UTC +00:00, "email"=>"brett@dudo.io", "public_token"=>"..."}, "instance_options"=>{}, "root"=>nil, "scope"=>nil}
```

```
class UserSerializer < ActiveModel::Serializer
  attributes :id, :name, :email, :monthly_income_amount, :monthly_available_balance

  has_many :current_transactions
end
```

Hopefully that describes the mismatch. I'm using Devise, not sure if that messes with serialization. Also, `plaid_public_token` is on there, which I'm not sure how... the column is actually just `public_token`.

**Comment by bf4** [comment]
Yeah, that's not the way to do it.  The json gem adds methods all ruby objects.  I am thinking of moving making the serializer behave like the attributes adapter when calling as_json on it.  In any case, see https://github.com/rails-api/active_model_serializers/issues/1487#issuecomment-178114848 where I ref'd what you need to do

**Comment by dudo** [comment]
To be clear, that's the instruction from /outside_controller_use.md, yes?

**Comment by bf4** [comment]
no prob. Glad it's figured out.
