### ISSUE TITLE
State of Nested Serializers

### ISSUE THREAD

**Issue by dsexton** [rails-api/active_model_serializers#1495]
I attempted to implement nested serializers as shown [here](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/getting_started.md#model-associations-and-nested-serializers) using namespaced models as also stated [here](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/getting_started.md#namespaced-models), however I am witnessing odd behavior. My implementation is pretty much a combination of these two ideas.

Using the example from the docs, if I load a collection of serialized posts everything is serialized fine, including its comment children. However, if I then immediately load a collection of serialized comments, then it is using the post's nested comment serializer. 

The same works in reverse, if I start by first loading a collection of serialized comments everything works fine, however when I got to immediately load a collection of serialized posts then the post serializer uses the global comment serializer and ignores the nested one.

So some general questions:
- What is the state of nested, or overridable `has_one|has_many|belongs_to` serializers?
- Do namespaces break the aforementioned serializes? 

Thanks!

**Comment by bf4** [comment]
Can you share which version of AMS you're on and some sample code? Thanks. See https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md#writing for some idea.

Also see https://github.com/rails-api/active_model_serializers/issues/1442

**Comment by SirUncleCid** [comment]
What I did was explicitly told the association which serializer to use:
```
class Api::V1::ProductSerializer < ActiveModel::Serializer
  attributes :id, :title, :price, :published

  class UserSerializer < ActiveModel::Serializer
    attributes :id, :email
  end

  # this line
  has_one :user, serializer: Api::V1::ProductSerializer::UserSerializer
end
```

You may also have to specify which serializer is to being used at the controller level.
`render json: products, each_serializer: Api::V1::ProductSerializer`

**Comment by bf4** [comment]
@SirUncleCid thanks for sharing your solution.  :+1: The intention of the codebase at this point is that you shouldn't have to do that, so I'd report that as a bug.  If you can write a failing test for it, I can help with making a PR (or help you with a PR).
