### ISSUE TITLE
:only and :except options return undefined method valid

### ISSUE THREAD

**Issue by hcarreras** [rails-api/active_model_serializers#1502]
When I add an except or only option to my serializer:

    cache key: 'order_item', expires_in: 3.hours, except: [:quantity]

I receive undefined method `valid' for #<OrderItem:0x007fe23da14ab0>

The two last error lines are:

    # /Users/haricarreras/.rvm/gems/ruby-2.2.3/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
    # /Users/haricarreras/.rvm/gems/ruby-2.2.3/bundler/gems/active_model_serializers-f5ec8ed9d462/lib/active_model/serializer.rb:127:in `read_attribute_for_serialization'

I'm using active_model_serializers (0.10.0.rc4).

I've tried to debug more, but I couldn't find the reason.
Any ideas or thoughts? 
Please, let me know if I can provide more info

**Comment by bf4** [comment]
Thanks @hcarreras would you mind sharing more of the serializer?  I'm wondering if you're declaring the cache key but not the attributes.
