### ISSUE TITLE
Document passing arbitrary options to serializer

### ISSUE THREAD

**Issue by bf4** [rails-api/active_model_serializers#1506]
See discussion in 

- https://github.com/rails-api/active_model_serializers/issues/599#issuecomment-144904554

But is basically the example by @jszwedko

PostController
```ruby
...
  def show 
    render json: @post, user_id: 1234
  end
...
```

PostSerializer
```ruby
...
  def my_comments
    Comments.where(user_id: instance_options[:user_id], post_id: object.id)
  end
...
```

**Comment by CodedBeardedSignedTaylor** [comment]
I'm down to look into this.

**Comment by CodedBeardedSignedTaylor** [comment]
Got a neat pull request out there.

**Comment by bf4** [comment]
related to https://github.com/rails-api/active_model_serializers/pull/1252

**Comment by groyoh** [comment]
Closed by #1545

**Comment by groyoh** [comment]
@bf4 changelog is missing though. How do you usually handle it in such case? New PR for changelog? Push a commit to master?

**Comment by bf4** [comment]
For maintainers just a push to master w[ci skip] if you're confident. Pr is
the defaulr
