### ISSUE TITLE
Serializer not loading on rails-api project

### ISSUE THREAD

**Issue by dsarhadian** [rails-api/active_model_serializers#1510]
Hi everyone,

I'm having some issues with AMS. I have a Rails 4.2.5 app created using the rails-api gem and the latest master commit of the AMS gem installed. 

I have setup a serializer for my Customer object but it's still returning attributes that I don't want it to return. 

My code is available here: [https://gist.github.com/dsarhadian/6612aa488c9c076c350e](https://gist.github.com/dsarhadian/6612aa488c9c076c350e)

I don't want it to return the created_at and updated_at attributes.

I have also added this line:
`include ActionController::Serialization` in my application_controller.rb file 

Any help is appreciated!

**Comment by bf4** [comment]
Thanks for your issue.

It looks to me like it's not using the CustomerSerializer in the controller. Have you tried passing it in explicitly `serializer: CustomerSerializer`?  Otherwise, if you could provide an example of the customer serialization it would be helpful.

Is your superclass `ActionController::API`?

**Comment by dsarhadian** [comment]
@bf4 When I try to pass it in I get this error: `uninitialized constant Api::V1::CustomersController::CustomerSerializer`

Yeah, my superclass is ActionAcontroller::API

**Comment by bf4** [comment]
@dsarhadian maybe join the amserializers.herokuapp.com slack if we keep going back and forth.

try `serializer: ::CustomerSerializer` to lookup the serializer in Ruby's global scope

**Comment by dsarhadian** [comment]
Doing that gives me this error: `uninitialized constant CustomerSerializer`. 

And okay, I'll join it right now.

**Comment by bf4** [comment]
(I asked about the superclass because I've been thinking we should test against it in AMS, but aren't now)

**Comment by dsarhadian** [comment]
It seemed to be an autoloading issue with my application.rb config file. Removing the config.autoload line in my application.rb seemed to fix the problem.
