### ISSUE TITLE
Some attributes are rendered as null?

### ISSUE THREAD

**Issue by AntonTrapp** [rails-api/active_model_serializers#1518]
obj with {title: 'Ing.', ...}

`ActiveModel::ArraySerializer.new(obj).to_json`

renders everything fine, but the title string is rendered as null, If I define the title and want to return a hardcoded string it is never called, in other custom attribute definitions the object.title has the correct value.

version is: active_model_serializers (0.9.3)

update: *LOL* - only happening in test environment :D

The object to serialize comes correct into the serializer, but not out of it:
```
        puts "?"*100+ContactPersonSerializer.new(@resource_class.all.first).inspect
        puts "!"*100+ContactPersonSerializer.new(@resource_class.all.first).to_json.inspect

```

development -> ? ... title: "Ing." ... and ! ... \"title\":\"Ing.\"
test -> ? ... title: "Ing." ... and ! ... \"title\":null

I really have no idea why the serializer works different depending on the environment and where to look for the problem... (as_json instead of to_json returns nil instead of null)

**Comment by bf4** [comment]
Thanks @AntonTrapp for the report.  Could you provide an example that I can run from start to finish?  There's some steps missing that make it hard for me to interpret the relationship between your model, serializer, any options, and resulting JSON

**Comment by AntonTrapp** [comment]
Thanks @bf4 - I tried to narrow it down. Rails.env is not responsible for this behavior. It seems like rspec, FactoryGirl, ... has an impact on the Serializer. Have removed the title attribute (as all others are working) for the test for the meantime and added this issue in my todo list, would close it for now as I am not sure which plugin is responsible for that. If I have more time and dig deeper into it and find the error inside the serializer, I will reopen it with detailed information, if that's OK for you.

**Comment by AntonTrapp** [comment]
So, debugged in that stuff...

```
[155, 164] in /Users/atrapp/.rvm/gems/ruby-2.2.1@aquadb2/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb
   158:     def attributes
   159:       filter(self.class._attributes.dup).each_with_object({}) do |name, hash|
=> 160:         hash[name] = send(name)
   161:       end
   162:     end

```

is working like it should for all attributes that are NOT named title:

```
[83, 92] in /Users/atrapp/.rvm/gems/ruby-2.2.1@aquadb2/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb
   87:           define_method striped_attr do
=> 88:             object.read_attribute_for_serialization attr
   89:           end unless method_defined?(attr)

```

If the attribute is called "title" I land here:

```
[3, 12] in /Users/atrapp/.rvm/gems/ruby-2.2.1@aquadb2/gems/capybara-angular-0.2.3/lib/capybara/angular/dsl.rb
    3:     module DSL
    4:       include Capybara::DSL
    6:       Capybara::Session::DSL_METHODS.each do |method|
    7:         define_method(method) do |*args, &block|
=>  8:           page.send(method, *args, &block)
    9:         end
   10:       end

```

"self" is always my ContactPersonSerializer, :title is just an :attribute as all others too. Really confused now... I have absolutely no idea why the serializer is calling Capybara methods here... will post this in capybara-angular too because I don't even have a clue what code is responsible for that.

Hope it helps.

**Comment by groyoh** [comment]
@AntonTrapp my best guess is that there is a:

```ruby
include Capybara::Angular::DSL
```

at the top-level namespace meaning that you include this module to the `Object` class and therefore define all the `DSL` methods for every class. This `DSL` module contain a `title` method and therefore the serializer assume that it already have a `title` method and does not override it. The serializer behaviour seems legit here. I'm not familiar with Capybara and can't tell if you're maybe misusing it.

Could tell me if my guess was correct?

**Comment by AntonTrapp** [comment]
*LOL* 100% correct and just a few moments before I stumbled about the DSL_METHODS in capybara's session.rb file which are used in the dsl.rb :D

TNX!

**Comment by groyoh** [comment]
Glad to help :wink:
