### ISSUE TITLE
jsonapi_parse! -- Should we raise when unpermitted parameters are given?

### ISSUE THREAD

**Issue by ianks** [rails-api/active_model_serializers#1519]
Imagine we have this payload:

```ruby
{ "data"=> { "attributes" => { "title" => "Changed it!" } } }
```

Currently, the result of `jsonapi_parse! params, only: [:foo]` ignores that unpermitted params were passed in by simply returning `{}`. As a user of the API, I would expect that it raises an error in this case. To me it seems like we are swallowing errors. 

Ping @bf4 for your thoughts on this. I'm not fully sold either way, and would like to hear your thoughts on this.

Cheers! :smile:

**Comment by bf4** [comment]
That payload is invalid json API

**Comment by ianks** [comment]
it is just the params object from rails

**Comment by bf4** [comment]
Sorry, but could you be more specific where the request is coming from?  The client is sending invalid data.  Try using the assert schema

B mobile phone

**Comment by ianks** [comment]
Here is my conundrum, certain params are OK for Admins but not OK for regulars Users. I want to conditionally parse certain params with `jsonapi_parse`. 

Warning, pseudo-code incoming:

```ruby
def update_params(resource)
  case resource
  when User then jsonapi_parse! params, only: [:status]
  when Admin then jsonapi_parse! params, except: [:status]
  else fail Error, "Unknown resource"
end
```

Now if an Admin passes in params like this:

```json
{ "data": { "attributes": { "status": "unread" } } }
```

No error is raised. My question is whether or not it would be wise to have `jsonapi_parse!` fail when a invalid params are passed.

Thus:

```ruby
jsonapi_parse! { "data"=> { "attributes" => { "status" => "unread" } } }, except: [:status]
```

Would raise an error.

**Comment by bf4** [comment]
Ok, but `{ "data": { "attributes": { "status": "unread" } } }` is invalid json api. So the json api deserializer won't work.  Could you paste your error message as well? I've included some guidelines on helpful info in the contributing doc https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md#writing (or help us simplify it https://github.com/rails-api/active_model_serializers/pull/1485 )  I'm excited to use the new templates https://github.com/blog/2111-issue-and-pull-request-templates !

**Comment by ianks** [comment]
Sorry, it was pseudo code. I think I am not communicating this well. I am not reporting a bug with error messages, I am wondering whether it would better for AMS to raise an error in this specific case:

```
2.2.3 (#<SmartTipsController:0x005631770b2e68>):0 > params
=> {"data"=>{"attributes"=>{"title"=>"Changed it!"}}, "controller"=>"smart_tips", "action"=>"update", "id"=>"b16227a0-f6d4-4f41-ad02-fd9c7cdaeb7e"}
2.2.3 (#<SmartTipsController:0x005631770b2e68>):0 > jsonapi_parse! params, except: [:title]
=> {}
```

**Comment by bf4** [comment]
Oh, I think it's me being slow or not detail oriented enough. https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json_api/deserialization.rb#L76-L80 should raise, but you say it doesn't? that's a bug

**Comment by ianks** [comment]
Ok, I looked through the code and noticed that there was no logic in `validate_payload` which validated attributes included in the `:only` or `:except` options, so I figured it was a design choice.

Just to be clear, should `jsonapi_parse!` validate that attributes included in the `except` field are not present in the params?

**Comment by beauby** [comment]
@ianks The way `jsonapi_parse!` was designed, it would simply take whatever was allowed/not forbidden, and ignore the rest. The idea was that this method is simply responsible for deserializing stuff, and failing if the necessary stuff wasn't present, but not to actually validate the payload (the name of `validate_payload` is misleading, I'll give you that).
