### ISSUE TITLE
Documentation for serializing PORO models.

### ISSUE THREAD

**Issue by hickscorp** [rails-api/active_model_serializers#1521]
Hi,

This is not really an issue, but more of a documentation help.

I've been trying to get ARS to serialize PORO models for a while, and I have the feeling that the documentation is somehow misleading.

For people willing to achieve the same thing as me, here is what I found out: The doc states that "Given a [serializable model](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/lint.rb)", you either have to descend from `ActiveRecord::Base` or from `ActiveModelSerializers::Model`.

To me, it seamt obvious that the 2nd option was the right one for me to use for addressing PORO. It however sounds absurd, as having an inheritance constraint on a model when programming in ruby threw me back in the 90's.

So I followed the docs advices, to discover that it simply wouldn't work (Had errors all over the place, one after another, not going to detail them here).

Hidden in the lint compliance interface, I found somewhere a sentence referring to the fact that including `ActiveModel::Serialization` would help. That's what I did, and now I got everything working really well, but it doesn't look like anything the doc prescribes:

A model:
```
class Foo
  include ActiveModel::Serialization

  ATTRIBUTES ||= %i(uuid bar).freeze
  attr_accessor *ATTRIBUTES

  def initialize(attrs)
    ATTRIBUTES.each { |col| send "#{col}=", attrs[col] }
  end
end
```

Important highlights differing from what I understood from the docs:
- I didn't have to inherit from anything I didn't *have to* (Important for decoupling ARS from third-party models, for example).
- Nor I had to implement `serializable_hash` /  `read_attribute_for_serialization`, as the awesome `ActiveModel::Serialization` did that for me.
- I didn't have to implement `serializer_class` on the class itself.

Its serializer:
```
class FooSerializer < ActiveModel::Serializer
  attributes :foo
end
```

I understand that the nature of the 10.0 tag makes it hard to document while final choices are not set in stone. But I think changing that documentation might be a good idea, at least for key-concepts, hopefully it will allow people to use ARS without too much of a headache.

I hope this will help!

**Comment by bf4** [comment]
Would you mind making a pr?

I had thought the docs were clear on the interface and that ams::model is a convenience.  And you say it doesn't work?  Please share details, including which ams version you're on and the backtrace.

**Comment by remear** [comment]
Closing due to lack of response from the submitter.
