### ISSUE TITLE
Serialization Options not set in nested resource

### ISSUE THREAD

**Issue by ablancag** [rails-api/active_model_serializers#1522]
Don't know if this might be an issue in master branch, but script could be easily modified to test for that. Currently found in the 0.9.x branch.

Originally reported @ https://github.com/rails/rails/issues/23741 because thought it was a framework issue. Was told to report it here first.

The issue is: a custom serialization, as exemplified by the attached script, generates incorrect output, because custom options are not being passed correctly to the nested, manual, serialization I'm doing (doing it through a "has_one" association solves the issue by the way). This is done using .new(object, options).

Looking at line 93 of lib/active_support/json/encoding.rb (Rail's Active Support FW), I see that the call to "as_json" is missing the options in the context. As a reference, the same call in method encode(value), of the same file, is done with the options. If this call was done with the options in context, the output of the custom serialization would be valid. Or so I think.

What do you think? 

Is the code I'm proposing incorrect? Is it something in the Active Model Serializers library or is it something in the ActiveSupport library? My analysis tells me it's in the latter, but I may be wrong since I'm not that familiar each package's specs. 

[action_controller_gem.rb.zip](https://github.com/rails-api/active_model_serializers/files/136624/action_controller_gem.rb.zip)

**Comment by bf4** [comment]
Pasting file contents here to save other from needing to download and unzip


```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'rails', '4.2.4'
  gem 'active_model_serializers', '0.9.4'
  gem 'activerecord', '4.2.4'
  gem 'sqlite3'
end

require 'active_record'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :entities, force: true do |t|
    t.string :some_field, null: false
  end

  create_table :child_entities, force: true do |t|
    t.string  :a_field,       null: false
    t.string  :another_field, null: false
    t.integer :entity_id,     null: false
  end
end

class Entity < ActiveRecord::Base
  has_one :child_entity
end

class ChildEntity < ActiveRecord::Base
  belongs_to :entity
end

class EntitySerializer < ActiveModel::Serializer
  attributes :id, :some_field, :childData

  def childData
    serialization_options[:root] = false
    # When calling like this, 
    # any options available here, won't be available to the child.
    # This is because of call in line 93 of 
    # lib/active_support/json/encoding.rb
    return ChildEntitySerializer.new(object.child_entity, serialization_options)
  end
end

class ChildEntitySerializer < ActiveModel::Serializer
  attributes :id, :a_field, :another_field

  def filter(keys)
    # This won't be available because of what I think is a bug.
    if (serialization_options[:customOption].nil? ||
        serialization_options[:customOption] != "BLABLA"
        )
      keys.delete(:another_field)
    end
    return keys
  end
end

require 'rack/test'
require 'action_controller/railtie'

class TestApp < Rails::Application
  config.root = File.dirname(__FILE__)
  config.session_store :cookie_store, key: 'cookie_store_key'
  secrets.secret_token    = 'secret_token'
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '/' => 'test#index'
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index

    # Toggle between the following to options to see the difference.

    # This renders ChildEntity incorrectly (missing field).
    render(json: Entity.all, status: :ok, customOption: "BLABLA") # 201
    # This renders ChildEntity correctly (with the appropriate fields)
    #render(json: ChildEntity.all, status: :ok, customOption: "BLABLA") # 201
  end
end

require 'minitest/autorun'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    e = Entity.new()
    e.some_field = "some_value"
    e.save!()

    cE = ChildEntity.new()
    cE.a_field = "a_value"
    cE.another_field = "another_value"
    cE.entity = e
    cE.save!()

    get '/'
    assert last_response.ok?
    # Printing result.
    puts(JSON.parse(last_response.body, symbolize_names: true))
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by groyoh** [comment]
@ablancag From what I found, you are indeed right saying that active_support does not forward the options (ref. https://github.com/rails/rails/blob/master/activesupport/lib/active_support/json/encoding.rb#L93). 

I have two solutions in your case:
* I would recommend you to use the following code as it does not require any fix or monkey patch:
```ruby
class EntitySerializer < ActiveModel::Serializer
  attributes :id, :some_field, :childData

  def childData
    return ChildEntitySerializer.new(object.child_entity).as_json(serialization_options)
  end
end
```

This is the safest solution to me.

Ref. https://gist.github.com/groyoh/2a510b2ba652bf885a6c.

* Fixing the issue within active_support. Unfortunately, fixing this does not "properly" fix you issue as forwarding the options might result in forwarding unwanted options. For example, if you use `render json: @entity, root: :entity`, the `root` option would also be forwarded to the `ChildEntity` and would cause improper results. I saw that in your example you used `serialization_options[:root] = false` but this might not be the best way to handle it as we only keep one reference of the options through the `as_json` serialization process. This might not cause you some trouble if you have other associations that uses the serialization_options. I created at gist with an active_support monkey patch that fix the issue if you want to use it as a ref in your rails issue

Ref. https://gist.github.com/groyoh/eb916988bfe27714b1e1.

**Comment by ablancag** [comment]
Sorry! Had a business trip and forgot about this until precisely today when I was tuning my code. 

Your solution worked: ChildEntitySerializer.new(object.child_entity).as_json(serialization_options)

I understand what you say about not suggesting a fix in active_support. I still feel that since you're in a sort of context, options should be available somehow. 

Thanks for your help. :)
