### ISSUE TITLE
Unable to render associations to string

### ISSUE THREAD

**Issue by fractaloop** [rails-api/active_model_serializers#1526]
I cannot figure out how to render my serializer to a string with associations. Any time I attempt to catch the values, it drops the associations.

If I `render json: @measurements` it will embed everything and look great.
> `{measurements: Array[2244], makes: Array[4], motors: Array[1], props: Array[11]}`

However, if attempt to get the string representation of the serializer by caching the value or using `render_to_string json: @measurements` it will fall back to the default ArraySerializer and fail to embed the associations.
> `[{measurement 1},{measurement 2},..]`

How do I get active_model_serializers to write a fully embedded object like `render json: @measurements`? I have included the working and failing code below.

```ruby
class MeasurementsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json do
        #render json: measurements_works
        render json: measurements_fails
      end
    end
  end

  protected

  def measurements_fails
    cache_key = "measurements/#{filtering_params.sort_by(&:to_a)}"
    Rails.cache.fetch(cache_key, expires_in: 20.seconds) do
      Measurement
        .includes(motor: [:make, :photos], prop: [:make, :photos])
        .references(motor: [:make, :photos], prop: [:make, :photos])
        .where(filtering_params)
    end
  end

  def measurements_works
    Measurement
      .includes(motor: [:make, :photos], prop: [:make, :photos])
      .references(motor: [:make, :photos], prop: [:make, :photos])
      .where(filtering_params)
  end

  # A list of the param names that can be used for filtering the Product list
  def filtering_params
    params.permit(:length, motor_id: [], prop_id: [])
  end
end
```

**Comment by fractaloop** [comment]
I can't determine why the behavior is different, but I did find a workaround:
> `ActiveModel::ArraySerializer.new(measurements, root: :measurements).to_json`

**Comment by bf4** [comment]
@fractaloop I'm guessing you're on 0.9? We can help more if you share a sample model and serializer so we can reproduce.

**Comment by remear** [comment]
Closing due to lack of response from the submitter. If this is still an issue, please add more information as requested and we'll re-open.
