### ISSUE TITLE
Overriding the association key when using include option with json adapter

### ISSUE THREAD

**Issue by AlexVPopov** [rails-api/active_model_serializers#1531]
If I have a serializer for model `A`, that `has_many :foos` and I define the association in it like this:

`has_many :foos, key: :bars`

then when this model is serialized the `foos` association is called `bars` as it should. However, assume model `B` has many `A`s and model `C` has one `B`. Now suppose, I need to serialize `C` and want to include its `B`, their `A`s and thier `foos/bars`. I can do:
```ruby
render json: @c, include: '**'
```
or
```ruby
render json: @c, include: 'b.**'
```
In both of these cases `A` will be rendered as having many `bars` because I have defined this in its serializer and here it is used explicitly. However, suppose I don't want to use the asterisk, but want to explicitly define which models exactly are rendered:
```ruby
render json: @c, include: 'b, b.as, b.as.foos'
```
Here, I am forced to use `foos` instead of `bars`, because otherwise I will get a `NoMethodError` for an instance of `A`. How can I override the key in the situation, where I include via strings?

**Comment by bf4** [comment]
I think that's a bug. can you share a backtrace so we can see where it's coming from?
