### ISSUE TITLE
Serialize nested elements on post and put request

### ISSUE THREAD

**Issue by sagits** [rails-api/active_model_serializers#1540]
Hi, how can i use nested objects instead of passing an id in a post/put request?

I would like to do something like this:

```
POST /products

{
"name": "Notebook Dell x500", 
"category" : {
                    "id": "10"
                    "name" : "Electronics"
                   }
}
```

Is this possible? Thanks in advance.

**Comment by bf4** [comment]
@sagits can you help us by answering some of the questions from https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md ?

I don't know which version of AMS you're targeting, which adapter your'e using, or what you want to happen with that post

**Comment by sagits** [comment]
Hi @bf4. I'm really new to rails, i just installed rails-api gem (using rails 2.1) and created a default project just for test purposes:

**Steps to reproduce**

rails-api products-app
rails g scaffold Category name: String name:boolean
rails g scaffold Product name:string category:reference
rake db:migrate
rails s

added this to applicationController aiming to take out model name from json root:

include ActionController::ParamsWrapper
 wrap_parameters format: [:json, :xml, :url_encoded_form, :multipart_form]


My problem is that i want to integrate an mobile app with this api. So, on my client code, my product model will be something like this (pseudocode):

```
class Product {
   String name;
   Category category;
}

```

So when i use a library to convert it to json, a new product, with a selected category will output this:

```
{
"name": "Notebook Dell x500", 
"category" : {
                    "id": "10"
                    "name" : "Electronics"
  }
}
```

I know this is a simple example and you can think "just create an category_id and pass the category id to the api!". But the REST goal is to make requests object based (eliminating boiler plate code like parsing an object to POST fields), image if i have 300 models that relate between themselves on my project, i would have to manually create multiples references ids every time i want to do a request?


I know that i can iterate over the json received on my controler POST and PUT and manually create an id for each subobject, but is there a way to do this automatically? Thank you in advance.

**Comment by bf4** [comment]
> using rails 2.1

I'm guessing you mean Ruby 2.1 and you're on the Rails 4 series (Rails 5 includes rails-api)

Which version of AMS are you using?  you can paste your `Gemfile.lock` here if that's easier

**Comment by bf4** [comment]
If you're on 0.10.0.rc4 sounds like you'd want to use the Attributes adapter and a Serializer something like

```ruby
class ProductSerializer < ActiveModel::Serializer
  attributes :name
  has_one :category
end
class CategorySerializer < ActiveModel::Serializer
  attributes :id, :name
end
```

and then in you're controller you'd `render json: product, adapter: :attributes` and you'd see it render the JSON document


```json
{
  "name": "Notebook Dell x500", 
  "category" : {
    "id": "10",
    "name": "Electronics"
  }
}
```

At this time, AMS does not include its own params parser, but the mapping your suggesting can be pretty easily handled:

```http
PATCH /products HTTP/1.1

{
  "products":  { "name": "Notebook Dell x500", "category": { "id": "10", "name": "Electronics"}}
}
```

**Comment by breim** [comment]
+1 at   active_model_serializers (0.10.0.rc4)

`class UniversitySerializer < ActiveModel::Serializer
  attributes :id, :name, :slug, :fiat
  has_many :course_graduations, class_name: 'CourseGraduation'
end`

`class CourseGraduationSerializer < ActiveModel::Serializer
	attributes :id

	has_one :course
	has_one :graduation
	has_one :university
end`

class Api::V1::UniversitiesController < ApplicationController
  def index
    @universities = University.all
    render json: @universities, adapter: :attributes
  end
end


GET http://localhost:3000/apv/v1/universities/

return 
`0{id: 1, name: "Universidade teste", slug: "universidade-teste", mais...}
id1
name"Universidade teste"
slug"universidade-teste"
fiat0
course_graduations[1]
0{id: 1}
id1`

dont load course, graduation or university attributes

**Comment by breim** [comment]
Solved passing include to controller
  
render json: @universities, include: '**'

**Comment by bf4** [comment]
@breim which adapter are you using?

**Comment by bf4** [comment]
@sagits can we close this? would you mind summarizing the resolutin?

**Comment by breim** [comment]
@bf4 Attributes - Default, i dont configure an adapter.

Changed my controller to  

     render json: @universities, include: {course_graduations: [:course, :graduation]} 
     
And work perfect.
I doing something wrong ? thx for your attention.

**Comment by sagits** [comment]
Hi @bf4, unfortunately i cant test it right now because im at work. But i believe your response.

I just want to understand one thing, this approach would work for post/put (add/edit) requests? I mean,  this would work:

````
POST /products HTTP/1.1

{
  { "name": "Notebook Dell x500", "category": { "id": "10", "name": "Electronics"}}
}

```


Another question is, if this works, is there anyway to automatically create a category on products/post when it has not an id, i mean, when i post this:

````
POST /products HTTP/1.1

{
 { "name": "Notebook Dell x500", "category": { "name": "Electronics"}}
}

```

My api would detect that the nested category has not an id, so it should create a category and them append the created category (with an id) to my product?


I know this seems strange, at first look, but my goal is to handle an array of subobjects, for example, i would have a customer with a list of phones, so my post would like like this: 

````
POST /customers HTTP/1.1

{
 { "name": "Jack Tyler", 
   "phones": [
     { "number": "30948319", "type":"work"},
     { "number": "30948319", "type":"mobile"},
     { "number": "30948319", "type":"home"}
    ]
}
```

In this scenario, can rails detect that phones must be created (as they do not have an id), or i would have to make this check manually? Thank you in advance.

**Comment by remear** [comment]
@sagits Your last question seems like it concerns Rails specifically and not AMS. If you haven't figured it out by now I'd suggest dropping by #rubyonrails on Freenode IRC.

**Comment by ricardobsilva** [comment]
NA PROXIM AVISEM QUE ESSA PORRA MUDOU, POR GENTI LESA
