### ISSUE TITLE
Version 0.10.0.rc4 not working on Rails 4.2.1

### ISSUE THREAD

**Issue by renatojf** [rails-api/active_model_serializers#1548]
My gem list returns this:
`Using active_model_serializers 0.10.0.rc4 from https://github.com/rails-api/active_model_serializers (at master)`

I have this serializer:

`class NegocioSerializer < ActiveModel::Serializer
  attributes :titulo, :descricao, :valor, :website
end`

When I go to the rails console and try to get the object serialized, it returns me the whole object with all attributes.

`NegocioSerializer.new(Negocio.first).as_json`
` {"object"=>{"id"=>1, "titulo"=>"Ponto", "descricao"=>"Essa é uma descrição de boa.", "valor"=>"300000.00", "faturamento_bruto_anual"=>nil, "lucro_liquido_anual"=>nil, "ano_fundacao"=>nil, "qtd_funcionarios"=>nil, "tipo_negocio_id"=>2, "user_id"=>2, "localizacao_id"=>2, "created_at"=>Tue, 01 Mar 2016 15:37:59 BRT -03:00, "updated_at"=>Tue, 01 Mar 2016 15:56:42 BRT -03:00, "website"=>"", "contato_nome"=>"", "contato_telefone"=>"", "contato_email"=>"", "avaliado_por_especialista"=>nil, "existem_corretores_apoiando"=>nil, "motivo_venda_id"=>2, "franquia"=>false, "plano_id"=>2, "completo"=>true, "aprovado"=>true, "qtd_emails_enviados"=>0, "ultimo_email_enviado"=>nil, "cancelado"=>false, "ultimo_email_estatistica_enviado"=>Wed, 16 Mar 2016 15:56:42 BRT -03:00, "cupom_nome"=>"", "informacoes_ponto_id"=>2, "informacoes_transferencia_id"=>2, "descricao_ativos"=>nil, "descricao_oportunidades"=>nil, "informacoes_participacao_investimento"=>nil, "percentual_participacao_societaria"=>nil, "video"=>nil}, "instance_options"=>{}, "root"=>nil, "scope"=>nil}`

**Comment by groyoh** [comment]
It is unfortunate but you cannot use directly `#as_json` on the serializer instance (at least not yet, see #1494). You can to use `ActiveModel::SerializableResource` as described at https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md.

In your case it would be:

```ruby
serializer = NegocioSerializer.new(Negocio.first)
ActiveModel::SerializableResource.new(serializer).as_json
```

**Comment by renatojf** [comment]
I understand. But still, it's not working. Here's the output:

`>> ActiveModel::SerializableResource.new(serializer).as_json
NoMethodError: undefined method `new' for nil:NilClass
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model/serializable_resource.rb:39:in `serializer_instance'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model/serializable_resource.rb:34:in `adapter'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model_serializers/logging.rb:84:in `notify_render_payload'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model_serializers/logging.rb:78:in `notify_render'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model_serializers/logging.rb:92:in `block in tag_logger'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model_serializers/logging.rb:92:in `tag_logger'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/bundler/gems/active_model_serializers-8a040052afc0/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `instance_exec'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `call'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:342:in `block in simple'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:497:in `call'
... 18 levels...
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /home/renatojf/.rvm/gems/ruby-2.2.2@bhiz/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/renatojf/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/renatojf/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'>>`

**Comment by groyoh** [comment]
My bad, there was an mistake in my snippet:

```ruby
ActiveModel::SerializableResource.new(Negocio.first).as_json
```

**Comment by bf4** [comment]
@renatojf we recently added an issue template to new issues.  Since this issue doesn't use it, I'm wondering if it's broken.  Did you see it show up when you created the issue?

@groyoh is right that you might have been less surprised if https://github.com/rails-api/active_model_serializers/pull/1494 were merged.  https://github.com/rails-api/active_model_serializers/issues/1548#issuecomment-190923976
