### ISSUE TITLE
Includes only works sometimes

### ISSUE THREAD

**Issue by Padchi** [rails-api/active_model_serializers#1582]
Restarting server, visiting /festival/1 everything is as it should be. Visiting /festival/1/bookings and my include `["artist.attachment"]` is ignored:
![skarmavbild 2016-03-12 kl 16 19 14](https://cloud.githubusercontent.com/assets/814347/13723739/3ac7cb3a-e86e-11e5-88ba-b7e2dac4a9c9.png)

Restarting server again and visits /festival/1/bookings, everything is now as i should be: 

![skarmavbild 2016-03-12 kl 16 25 59](https://cloud.githubusercontent.com/assets/814347/13723770/2f748ef2-e86f-11e5-8213-059c4d1d813b.png)

But when visiting /festival/1 now thats  `["attachment"]` is ignored!? Also attachment serialiser is ignored when the include doesn't work.

nothing fancy with my code:
```
#festival_controller.rb
def show
    render json: festivals, each_serializer: FestivalSerializer, include: ["attachment"]
end
```

```
#booking_controller.rb
def index
   render json: bookings, each_serializer: BookingSerializer, include: ["artist.attachment"]
end
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
master branch
Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
`ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]`
OS Type & Version: 
OS X El Captain, 10.11.3
Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails 4.2.4

**Comment by NullVoxPopuli** [comment]
can you post your serializers?

**Comment by Padchi** [comment]
It's nothing fancy just `has_one :attachment`

Skickat från min iPhone

**Comment by NullVoxPopuli** [comment]
what if your include value isn't an array? just `"artist.attachment"`?

**Comment by Padchi** [comment]
Samething @NullVoxPopuli

**Comment by bf4** [comment]
@Padchi Do you have any caching on?

**Comment by Padchi** [comment]
@bf4 no! Wierd after i restarted my computer it worked but now it's back again without a single change on the code..

**Comment by bf4** [comment]
@Padchi Hey, so, I'd really appreciate if you could put together a failing spec or some code I can run that demonstrates this.  It seems important, but I'm just one person.. :)

**Comment by Padchi** [comment]
Specify which serializer to use looks like a fix to this problem, `has_one :attachment, serializer: AttachmentSerializer`, but it shouldn't be necessary

**Comment by bf4** [comment]
Right. It should be able to look it up, unless you have some autoloading issue, perhaps

**Comment by Padchi** [comment]
The autoloading doesn't work for me so thats the problem i guess.

**Comment by bf4** [comment]
How have you confirmed that? Is this now resolved?

B mobile phone

**Comment by Padchi** [comment]
The problem is that the autoload doesn't work for me as it should so on first render it works and the attachment is loaded as it should. On the second request the autoload don't work for some reason so the attachment is generated without a serializer. 
Closing now cuz the problem is autoloading and have nothing to do with the include of a relationship.
