### ISSUE TITLE
Option for overriding format of type globally

### ISSUE THREAD

**Issue by chrisdpeters** [rails-api/active_model_serializers#1591]
#### Expected behavior vs actual behavior

Per [this comment](https://github.com/rails-api/active_model_serializers/issues/974#issuecomment-119959744), I am overriding much of what I need to in order to get JSON API-style output with dasherized keys.

Here is what I'm doing exactly with a `BaseSerializer` that other serializers extend:

```ruby
class BaseSerializer < ActiveModel::Serializer
  def attributes(*args)
    Hash[super.map do |key, value|
      [transform_key(key), value]
    end]
  end

  def each_association(&block)
    super do |key, association, opts|
      if block_given?
        block.call transform_key(key), association, opts
      end
    end
  end

private

  def transform_key(key)
    key.to_s.dasherize.to_sym
  end
end
```

The last element that I need to cover is the `type`, which I can't seem to find a hook to include in this base serializer. Is that possible, or can it be added so that I can use it in the base class?

For now, I need to manually call `type` in each multi-word serializer, which I find to be less than ideal when it was possible to override everything else in the base:

```ruby
class ContentTemplateSerializer < BaseSerializer
  type 'content-templates'
end
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 0.10.0.rc4

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

OS Type & Version: Ubuntu 14.04

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails

**Comment by NullVoxPopuli** [comment]
this looks like #1574 wiss solve this? @chrisdpeters if you look over that PR, does it look to solve your issue?

That PR just needs a little bit of documentation before it gets merged.
 /cc @remear

**Comment by chrisdpeters** [comment]
@NullVoxPopuli That looks like I could do a `key_transform` on each render, but is there a way to do it globally or for `type`? I'm getting a little lost in all of those comments.

/cc @remear

**Comment by NullVoxPopuli** [comment]
@remear it should be some kind of AMS.config option, yeah? I can't remember if you added that

**Comment by remear** [comment]
There isn't a global option for the key transform feature yet. I haven't been sure how much of a demand there would be for a global option. With most APIs I've worked on, a top request has been to set key casing based on the language of the consumer asking for it. For example, Ruby and Python want to consume snake_case keys. Java and JS want to consume camelCase keys. #1574 has been implemented to set the transform on a per-request basis by passing it as an option in the render, e.g., 

For example, if you wanted to change case based on a request header, you could (mainly for illustrative purposes) do the following in your `ApplicationController`:

```ruby
def render(opts={})
  if opts.is_a?(Hash) &&
    (opts.has_key?(:serializer) || opts.has_key?(:each_serializer))
    super(opts.merge!({ key_transform: response_key_case }))
  else
    super(opts)
end

def response_key_case
  case request.env['HTTP_X_API_DATA_CASE']
  when 'camel' then :camel
  when 'camel-lower' then :camel_lower
  else :unaltered
  end
end
```

If you wanted your API to respond in a single case, you could hard-code the transform and pass it as a render option, ```render json: posts, each_serializer: PostSerializer, key_transform: :camel_lower```. You could also modify the above example to always merge in the transform you want.

I'm open to discussing a global option if there's a definite need.

**Comment by chrisdpeters** [comment]
@remear I wrote a bunch of stuff in this comment but deleted it. I was waffling around with, "I would just like for my base class to be able to override `type` too," and, "Gee, a global option would be nice too."

I cannot think of a reason why I'd want a `type` key to be underscored, but then the relationship names be camelCased and then the attribute keys dasherized. It seems like if I decided one format, it would be for all. Your example nails it that perhaps it should be overridable at the request level for convenience, but it applies to _all_ keys. Then if someone is crazy and wants an inconsistent format, they can do an ugly hack like the one in my issue description.

For my particular case, I want an opinionated API that gives everyone the same thing: dasherized keys. It's what the Ember adapter seems to require without additional overrides, and the JSON API examples all use dasherized keys. So that's what my API will standardize on.

A config option for AMS would certainly be more comfortable than overriding the `render` method in the controller. I can't imagine it being intuitive for other developers to look in the controller for overrides to how AMS works. My gut and continual perusal of reading GitHub issues for this project tells me that many others would welcome this global setting.

**Comment by remear** [comment]
Keep in mind, in #1574 the default transform for the `JsonApi` adapter is `:dashed`.

**Comment by chrisdpeters** [comment]
@remear That's nice to know. I guess I can call myself lucky that the default will match what I want. :smile: :slot_machine:

**Comment by remear** [comment]
@chrisdpeters I've also added a config option to #1574.

**Comment by chrisdpeters** [comment]
@remear :+1: 

I think that option will be welcomed by quite a few. Thank you for taking the time to add it. I could imagine that I'd be frustrated if you told me that the default was snake_case or camelCase.

Can't wait until this is released so I can remove that `BaseSerializer` altogether!

**Comment by bf4** [comment]
@chrisdpeters re: `BaseSerializer`, there's actually some ancient secret code buried in the generator that checks if `ApplicationSerializer` is defined, and if so, generates the serializer inheriting from `ApplicationSerializer` instead of `ActiveModel::Serializer` :)

**Comment by chrisdpeters** [comment]
@bf4 Love it! I feel privileged to know about that little gem now and will promptly rename to `ApplicationSerializer`. :laughing:

**Comment by bf4** [comment]
@chrisdpeters Yeah, it's probably a good idea to have in any case.  Would love if you make a PR to document it :)
