### ISSUE TITLE
Document generator's auto-extending of `ApplicationSerializer` (if it exists)

### ISSUE THREAD

**Issue by chrisdpeters** [rails-api/active_model_serializers#1594]
As discussed at the end of #1591, I'd be willing to document this currently-hidden feature. It looks like the [Creating a Serializer](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/getting_started.md#creating-a-serializer) section of the Getting Started guide would be a good place to mention this. I'm open to ideas for other place(s) within the docs from those who are more in-the-know about the structure of the docs.

One thought before I continue. If this is considered a best practice, should the generator be changed to create a blank `ApplicationSerializer` for the other serializers to extend if it's not present? Perhaps if there aren't already some serializers in the `app/serializers` folder? (It would be confusing if some serializers extended the newly generated `ApplicationSerializer` while existing serializers didn't.) I don't think this would throw too many Rails developers off because it's basically how it works with `ApplicationController`.

**Comment by bf4** [comment]
> If this is considered a best practice, should the generator be changed to create a blank `ApplicationSerializer`

@chrisdpeters I think this would be a good idea. The generator would probably be something like `ams:install`, and could be done in a separate PR.

I think just adding docs there would be a great PR on its own.  There's already a test for its behavior :)

**Comment by bf4** [comment]
ref: https://github.com/rails-api/active_model_serializers/tree/a2d73faa63355e897873b4813b08d2db5f4a3617#applicationserializer-the-global-serializer and https://github.com/rails-api/active_model_serializers/pull/59#issuecomment-169490294 for some history :)

**Comment by chrisdpeters** [comment]
@bf4 Sure, I can do a PR for documenting how it works currently. Thanks for the pointer to the previously existing ones.

Perhaps I can dig into the generator in a bit to create the new `install` generator.

**Comment by bf4** [comment]
@chrisdpeters don't worry about the `install` generator for now.  Just the docs would be fine
