### ISSUE TITLE
Serializer files were broken by versioning

### ISSUE THREAD

**Issue by hightech** [rails-api/active_model_serializers#1597]
I added the api versioning feature in my project. My serializer files were broken by versioning. 

For example, when I didn't add those lines in `./app/serializers/api/v1/user_serializer.rb` file but I added in only controllers files.

```
module Api
  module V1
   .....
  end
end
```

It performed correct json file output the way I want it. But if I decided to add versioning in serializer files, the  json file output doesn't show the same results like the output (without versioning feature on serializer files). Any idea why it doesn't perform correct like "without version feature" in serializer files. Is this a bug or not? Any suggestion appreciated. Thanks.

Here is my snippet code:

**Serializers**

```
./app/serializers/api/v1/user_serializer.rb

module Api
   module V1
	class UserSerializer < ActiveModel::Serializer
 			attributes :id, :username
 			has_many :entries
	end
  end
end
```

```
./app/serializers/api/v1/entry_serializer.rb

module Api
   module V1
	class EntrySerializer < ActiveModel::Serializer
 			attributes :id, :description, :created_at, :updated_at

	 end
    end
end
```

**Routes**

```
./config/routes.rb

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :entries, except: [:new, :edit]
      resources :users, except: [:new, :edit]
    end
  end
end
```

**Controllers**

```
./app/controllers/api/v1/users_controller.rb

module Api
  module V1
    class EntriesController < ApplicationController
 
      before_action :set_entry, only: [:show, :update, :destroy]

      def index
        @entries = Entry.all
        render json: @entries
      end
	.
	.
	.
    end
  end
end
```

**Models**

```
./app/models/user.rb

class User < ActiveRecord::Base
	has_many :entries
end
```

```
./app/models/entry.rb

class Entry < ActiveRecord::Base
	belongs_to :user
end
```

**Comment by bf4** [comment]
@hightech Please add some more information as requested in the issue template so we can help you.  https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by hightech** [comment]
</br>
You can see that I had the old structure of my API project before I added version to serializer files:

```
app
|_controllers
    |_api
          |_v1
               |_entries_controller.rb
               |_users_controller.rb
    |_application_controller.rb

|_serializers
    |_entry_serializer.rb
    |_user_serializer.rb
```

I ran it with this `http://localhost:3000/api/v1/users` and got the correct output the way I want it. 

**The output:**
```
[{
     "id":3,
     "username":"myusername",
     "entries":[
              {
                  "id":4,
                  "description":"This is a decscription",
                  "created_at":"2016-03-16T14:40:52.614Z",
                  "updated_at":"2016-03-16T14:40:52.614Z"
              }
      ]
}]
```

------------------------------
</br>
So, let's say my goal to try to version my serializer files like this structure:

```
app
|_controllers
    |_api
          |_v1
               |_entries_controller.rb
               |_users_controller.rb
    |_application_controller.rb

|_serializers
  |_api
        |_v1
             |_entry_serializer.rb
             |_user_serializer.rb
```

I ran it with this `http://localhost:3000/api/v1/users` It gives me the wrong results not like the result above. You can see there is a missing "entries" part in this output.

**The output:**

```
[{ 
     "id":3,
     "username":"myusernmae"
}]
```
</br>
------------------------------

**Environment:** 
ActiveModelSerializers Version:  `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]`

(I tried to test each of these gems and received the same results like above. No luck.)
```
#gem 'active_model_serializers', '~> 0.8.3'
#gem "active_model_serializers", "~> 0.9.3"
#gem 'active_model_serializers'
gem "active_model_serializers", github: "rails-api/active_model_serializers"
```

This is what I have in my gem file:

```
gem 'rails', '4.2.3'
gem 'rails-api'
gem 'spring', :group => :development
gem "active_model_serializers", github: "rails-api/active_model_serializers"
gem 'pg'
```

Any suggestion appreciated. Thanks.

**Comment by NullVoxPopuli** [comment]
this looks like it relates to @beauby's PRs. #1436, #1265,

**Comment by remear** [comment]
Seems like this might also be related to the automatic serializer lookup issues. I have an application where I version my serializers as you've described in your second example and I have to do ```render json: companies, each_serializer: V1::CompanySerializer```. The last time I checked this was rc2 or rc3 though, so the behavior there might have changed.

**Comment by remear** [comment]
See #1338, #1442
