### ISSUE TITLE
Recursion/Nested Resources

### ISSUE THREAD

**Issue by louisscruz** [rails-api/active_model_serializers#1599]
How should I load nested comments? When getting my comments, I would like to get all comments on comments. I've tried many ways listed here in the issues, but no luck. My current setup includes one layer of comments, but not all. I've tried using `include: [:comments]`.

Comment.rb:

```
class Comment < ApplicationRecord
  include Votable

  after_create :update_comment_count
  after_destroy { update_comment_count(-1) }
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy

  private

  def update_comment_count(v=1)
    resource = self.commentable
    value = resource.comment_count
    resource.update_attribute :comment_count, value + v
  end
end

```

CommentSerializer:

```
class CommentSerializer < ActiveModel::Serializer
  attributes :id, :body, :commentable_type, :commentable_id, :user, :created_at
  has_many :comments
  def user
    { id: object.user.id, username: object.user.username }
  end
end
```

**Comment by NullVoxPopuli** [comment]
are you wanting infinite layers deep? or just a few?

the include string could be something like:

`'comments.comments'` 

or, since your comments only have one association, you could recursively include everything:

`'comments.*.*'`

**Comment by louisscruz** [comment]
Thanks for the help!

Now my controller has this:

`render json: @comments, include: ["comments.**"]`

Which is giving me infinite layers. Thanks!

**Comment by groyoh** [comment]
> are you wanting infinite layers deep? or just a few?
 
@louisscruz could you please answer this question. Also could you update your issue and follow the [issue templace](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md). Especially, could you provide an example of JSON response that you would expect and we you actually get right now?

**Comment by NullVoxPopuli** [comment]
it looks like, by the fact he chose to use `.**` as opposed to multiple `.*`, I'd say he wants infinite :-)

**Comment by groyoh** [comment]
Damn, the intent was definitely not clear then :grin:
