### ISSUE TITLE
Add node names for each element in a serialized collection.

### ISSUE THREAD

**Issue by sfkaos** [rails-api/active_model_serializers#1603]
I'm trying to add node names to each element within a serialized collection. I've tried using the #root method which only adds a root name to the parent collection, itself.

I've added 

ActiveModelSerializers.config.adapter = :json

to create this:

```
{
  "posts": [
   {
     "id": 1,
     "title": "Awesome Post Tile"
      "content": "Post content"
   },
   {
     "id": 2,
     "title": "Another Post Tile",
     "content": "Another post content"
   }
  ]
}
```

Is there someone way to add a node name to each element instead?

like this:

```
[
  {
    "post": {
       "id": 1,
       "title": "Awesome Post Tile",
       "content": "Post content"
     }
  },
  {   
    "post": {
       "id": 2,
       "title": "Another Post Tile",
       "content": "Another post content"
     }
   }
]
```

Thank you for your help.

**Comment by groyoh** [comment]
There something fishy about what you expect:

```json
{
  [
    post: {
      "id": 1,
      "title": "Awesome Post Tile",
      "content": "Post content"
    },
    post: {
      "id": 2,
      "title": "Another Post Tile",
      "content": "Another post content"
    }
  ]
}
```

There are many things wrong with your JSON response:
* You can't add keys to an array
* The `post` keys should be strings
* You can't add the same key  many times

Could you please fix your JSON response and clarify your expectation here?

**Comment by sfkaos** [comment]
@groyoh You are correct. Apologize for the confusion - incorrectly updated the copy-and-paste. I've updated the expectation above.

**Comment by groyoh** [comment]
Is there any particular reason why you want this behavior over this actual one?

**Comment by sfkaos** [comment]
@groyoh Its a legacy API that needs to be supported (currently implemented in JBuilder) but want to try and optimize for speed using AMS. After this I'd like to change it to a more standard structure.

**Comment by groyoh** [comment]
Could you tell me which version of AMS you're using?

**Comment by sfkaos** [comment]
active_model_serializers (0.10.0.rc4)

**Comment by groyoh** [comment]
The best way I can think of is to role out your own adapter:

```ruby
module ActiveModel
  class Serializer
    module Adapter
      class Custom < Base
        def serializable_hash(options = nil)
          options ||= {}
          serialized_resouce = Attributes.new(serializer, instance_options).serializable_hash(options)
          if serialized_resource.respond_to(:each)
            serialized_resouce.map! do |item|
              { root => item }
            end
          else
            { root => serialized_resource }
          end
        end
      end
    end
  end
end
``` 

and use it like this:

```ruby
render(json: post, adapter: :custom, root: :post)
```

You can checkout [this gist](https://gist.github.com/groyoh/b20bf94c700ea945a156) for the full example.

**Comment by sfkaos** [comment]
This is awesome! Thank you so much. I was thinking it had to be done on the adapter side. To include this adapter I'll have to fork the AMS project add it as an adapter correct? I can't just include this new class into my project.

**Comment by groyoh** [comment]
You can simply add it as part of your project. It can even just be:

```ruby
class CustomAdapter < ActiveModel::Serializer::Adapter::Base
  def serializable_hash(options = nil)
    options ||= {}
    serialized_resouce = Attributes.new(serializer, instance_options).serializable_hash(options)
    if serialized_resource.respond_to(:each)
      serialized_resouce.map! do |item|
       { root => item }
      end
    else
      { root => serialized_resource }
    end
  end
end
# The adapter can be specified by using the class name underscore'd:
# render json: post, adapter: :custom_adapter, root: :post
```



Just be careful though. `ActiveModel::Serializer::Adapter::Base` is deprecated on master and is meant to be replaced by `ActiveModelSerializers::Adapter::Base`. If you plan to use a later version than `0.10.0.rc4`, please have this in mind.

**Comment by sfkaos** [comment]
So I had to update your code above to subclass ActiveModelSerializers::Adapter::Base since I received the following warning: 
```
NOTE: ActiveModel::Serializer::Adapter::Base.inherited is deprecated; use ActiveModelSerializers::Adapter::Base. instead
ActiveModel::Serializer::Adapter::Base.inherited called from /Users/win/Development/Rails/rails-arttwo50-staging/lib/custom_adapter.rb:2.
```
So I added this file to my Rails project
```
class CustomAdapter < ActiveModelSerializers::Adapter::Base
  def serializable_hash(options = nil)
    options ||= {}
    serialized_resouce = Attributes.new(serializer, instance_options).serializable_hash(options)
    if serialized_resource.respond_to(:each)
      serialized_resouce.map! do |item|
       { root => item }
      end
    else
      { root => serialized_resource }
    end
  end
end
```
However, I'm getting the following error:
```
NameError: ActiveModelSerializers::Adapter::UnknownAdapterError. Unknown adapter: :custom_adapter. Valid adapters are: ["custom_adapter"]
```

Do I need to register my new adapter somehow?

**Comment by sfkaos** [comment]
Finally got it. I did indeed have to register the new adapter:

```
ActiveModelSerializers::Adapter.register(:custom_adapter, CustomAdapter)
```

Then I had to fix up the adapter a bit:
```
class CustomAdapter < ActiveModelSerializers::Adapter::Base
  def serializable_hash(options = nil)
    options ||= {}
    serialized_resource = ActiveModel::Serializer::Adapter::Attributes.new(serializer, instance_options).serializable_hash(options)
    if serialized_resource.respond_to?(:each)
      serialized_resource.map! do |item|
       { root => item }
      end
    else
      { root => serialized_resource }
    end
  end
end
```

Woot!
Thank you so much for your help. I'd be happy to do a quick doc to note down the steps for anyone else.

**Comment by remear** [comment]
@sfkaos That would be great. You could probably add it to adapters.md.
