### ISSUE TITLE
How to remove parameters from AMS 0.10.0.rc4 Deserialization?

### ISSUE THREAD

**Issue by Deovandski** [rails-api/active_model_serializers#1610]
#### Expected behavior vs actual behavior

As requested by BF4, I am copying over the [StackOverflow question](https://stackoverflow.com/questions/36121282/how-to-remove-parameters-from-ams-0-10-0-rc4-deserialization) of the same title.

Given the following user_params:

      def user_params
        ActiveModelSerializers::Deserialization.jsonapi_parse!(params.to_unsafe_h)
      end

I am unable to remove a parameter in order to do a specific operation that requires the `:current_password` not be within user_params. Previously the line below did the job:

    user_params.delete(:current_password) 

However, since implementing 0.10.0.rc4, the operation in question generates ActiveRecord::UnknownAttributeError (unknown attribute 'current_password' for User.)

    user.update_without_password(user_params) 

I could not find a way to remove the params, but using `.except(a)` does the trick in the Update method below:

      # Render the updated User using UserSerializer and the AMS Deserialization.
      def update
        # Check if password is blank, if so, clear :current_password
        # and update without password, else updates password.
        if user_params[:password].blank? || user_params[:current_password].blank?
          user.update_without_password(user_params.except(:current_password,:password))
          render json: user
        else
          if user.update_with_password(user_params)
            render json: user, status: :ok
          else
            render json: user.errors, status: :unprocessable_entity
          end
        end
      end

#### Steps to reproduce

Going from the output under **Backtrace**, Line 18 refers to `tempUser = User.new(user_params)` while line 17 refers to `user_params.delete(:current_password)` which seems to do nothing....

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: **AMS 0.10.0.rc4**

Output of `ruby -e "puts RUBY_DESCRIPTION"`: **ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]**

OS Type & Version: **Ubuntu 14.04**

Integrated application and version *(e.g., Rails, Grape, etc)*:  **Rails**

#### Backtrace
```
01:08:25 web.1  | Started POST "/api/v1/users" for 127.0.0.1 at 2016-03-21 01:08:25 -0500
01:08:25 web.1  | Processing by Api::V1::UsersController#create as JSON
01:08:25 web.1  |   Parameters: {"data"=>{"attributes"=>{"full_name"=>"gsffgfgds", "display_name"=>"gfdfgsfgsd", "password"=>"[FILTERED]", "current_password"=>"[FILTERED]", "email"=>"gdfssdgffgsd@dfsfsddfs.com", "date_of_birth"=>"2001-01-01T06:00:00.000Z", "gender"=>"male", "facebook_url"=>nil, "twitter_url"=>nil, "personal_message"=>nil, "webpage_url"=>nil, "is_banned"=>false, "is_banned_date"=>nil, "legal_terms_read"=>true, "privacy_terms_read"=>true, "is_admin"=>false, "sign_in_count"=>nil, "last_sign_in_at"=>nil, "updated_at"=>nil, "created_at"=>nil, "show_full_name"=>true, "admin_messages_count"=>nil, "posts_count"=>nil, "comments_count"=>nil, "times_banned"=>nil}, "type"=>"users"}, "user"=>{}}
01:08:25 web.1  | Completed 500 Internal Server Error in 59ms (ActiveRecord: 0.0ms)
01:08:25 web.1  | 
01:08:25 web.1  | ActiveRecord::UnknownAttributeError (unknown attribute 'current_password' for User.):
01:08:25 web.1  |   app/controllers/api/v1/users_controller.rb:18:in `create'
01:08:25 web.1  | 
01:08:25 web.1  | 
01:08:25 web.1  |   Rendered /home/deovandski/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.5ms)
01:08:25 web.1  |   Rendered /home/deovandski/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.3ms)
01:08:25 web.1  |   Rendered /home/deovandski/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.7ms)
01:08:25 web.1  |   Rendered /home/deovandski/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (9.0ms)


```

#### Additonal helpful information

You can quickly setup the project and test yourself: 
[Fakktion Github repo](https://github.com/Deovandski/Fakktion)

If you do, then change the user controller create method to the one below in order to trigger the issue:

```
  # Render the created User using UserSerializer and the AMS Deserialization.
  def create
    user_params.delete(:current_password)
    tempUser = User.new(user_params)
    tempUser.sign_in_count = 0
    tempUser.webpage_url = ""
    tempUser.is_banned = false
    tempUser.facebook_url = ""
    tempUser.twitter_url = ""
    tempUser.is_admin = false
    tempUser.personal_message = "This person did not write anything here yet..."
    tempUser.save
    render json: tempUser
  end
```

Thanks for AMS! :+1:

**Comment by beauby** [comment]
Note that `Hash#delete` returns the deleted value, not the resulting hash (which is modified in place).

**Comment by Deovandski** [comment]
So, if I understood you correctly, this following sequence of actions should have worked in the first place since I was not passing `Hash#delete` into `user.update()`, instead I was passing what was supposed to be the modified Hash which did not got modified, hence the `ActiveRecord::UnknownAttributeError` raised by the second line below due to the undeleted **current_password** param.

```
user_params.delete(:current_password) 
user.update_without_password(user_params) 
```

If that is not the case, then what is the proper way to delete a hash param?

**Comment by beauby** [comment]
Oh sorry, I overlooked. Your problem is that `user_params` is a method, so when you do `user_params.delete(:current_password)`, it computes the right hash, but any subsequent call to `user_params` will recompute the hash from scratch.

**Comment by Deovandski** [comment]
I understand it now. Thanks!
