### ISSUE TITLE
What is the correct way to pass arbitrary  options to a serializer?

### ISSUE THREAD

**Issue by KevinSjoberg** [rails-api/active_model_serializers#1611]
#### Expected behavior vs actual behavior

The API for passing arbitrary options to a serializer has changed over time. According to [the documentation]([The documentation](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/passing_arbitrary_options.md)), `instance_options` is the way to go. Obviously it's not since `instance_options` does not exist anymore.

I'm guessing the `meta` attribute can be used to pass data to the serializer and I'd be more than happy to update the documentation accordingly if someone just point me in the right direction.

**Comment by bf4** [comment]
@KevinSjoberg You left out some info from the issue template so I don't know what version of AMS you're on.  `instance_options` still exists in 0.10.x

**Comment by bf4** [comment]
I'm going to close this assuming you're not on 0.10.0.rc4 or above. Please reopen if you are.

Please also comment in your resolution. Thanks!

**Comment by KevinSjoberg** [comment]
I'm sorry for leaving out details about the setup. I'm currently using `0.9.4` of `active_model_serializers` with `rails` version `4.2.4`. I'm not seeing `instance_options` being available in `0.9.4` or `0.10.x` for that matter.

Currently, my solution is to utilise the `meta` tag to pass arbitrary information to the serializer.

**Comment by bf4** [comment]
Can you share any more info, such as requested in the issue template?

B mobile phone
