### ISSUE TITLE
enable key_transform option outside of controller

### ISSUE THREAD

**Issue by jachenry** [rails-api/active_model_serializers#1613]
ActiveModel::SerializableResource.new(resource).serializable_hash

#### Expected behavior vs actual behavior
Expected:  keys should be transformed using ActiveModelSerializers.config.key_transform
Actual: keys are not transformed

#### Steps to reproduce
1) add ActiveModelSerializers.config.key_transform = :camel_lower to initializer
2) open rails console
3) run `ActiveModel::SerializableResource.new(resource).serializable_hash`

#### Environment
ActiveModelSerializers Version: 61412d80cabc3900dfbd886bc3f25fb0e0d39433
Ruby version: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
OS Version: Mac OS X El Capitan (10.11.3)
Integrated application:  Rails

**Comment by groyoh** [comment]
#1572 should fix this. Could you try it out with this branch maybe and let us know if it works for you?

**Comment by jachenry** [comment]
@groyoh I'm seeing the same results with the PR branch. In my case I'm setting the `ActiveModelSerializers.config.key_transform` option to `:camel_lower` in the initializer. I would expect this configuration value to return keys with lower camel (created_at -> createdAt) even when running commands like `ActiveModel::SerializableResource.new(resource).serializable_hash`  outside the controller.

**Comment by groyoh** [comment]
My bad. It seems like the `transform_key_casing!` (https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/adapter/base.rb#L73) method expect the options to contain a serialization context to actually transform the keys. You are indeed right, this seems more like a bug. You should be able to transform the keys without passing the serialization_context.

@remear what was the idea behind putting the option into the `serialization_context`? For me, this belongs to the adapter options and not the `serialization_context` (ref. https://github.com/rails-api/active_model_serializers/pull/1574/files#diff-426cb6b4484fa95a18649ea3cc74474aR72).

**Comment by remear** [comment]
The goal was to allow specifying a key transform on a per-request basis. If an adapter option can achieve the same thing, then I have no specific objection to it. However, this is probably a better question for @bf4 as many older issues regarding key transformation mention that it should be implemented in the `serialization_context`.

**Comment by groyoh** [comment]
It would indeed achieve a per-request transformation. Actually, changing it to an adapter option wouldn't even change the interface when used within a controller e.g. `render json: resource, key_transform: :camel`. The main advantage would be to be able to use it without a `serialization_context` e.g. using it outside a controller.

**Comment by jachenry** [comment]
@groyoh would you still like me to issue a PR or are we changing to an adapter option?

**Comment by groyoh** [comment]
@jachenry If this is blocking you in any way, please provide a PR and I'll be happy to merge it :wink:

In the meantime, @bf4 could you give your point of view on the `:key_format` being an `serialization_context` option?

**Comment by bf4** [comment]
> The goal was to allow specifying a key transform on a per-request basis. If an adapter option can achieve the same thing, then I have no specific objection to it.

Sounds good

>  :key_format being an serialization_context option?

sure, let it go straight to the adapter

**Comment by jachenry** [comment]
@remear I believe your PR solved this issue so I am going to close. Please let me know if there is a reason to reopen.
