### ISSUE TITLE
When keys are transformed, the values of "type" attributes should be transformed in the same way

### ISSUE THREAD

**Issue by rthbound** [rails-api/active_model_serializers#1625]
#### Expected behavior vs actual behavior

When keys are transformed (e.g., json api spec defaults to dasherized keys), the values of `type` attributes should be transformed in the same way.

#### Steps to reproduce

See the modifications to tests made here: https://github.com/rails-api/active_model_serializers/compare/master...rthbound:bug-in-1574

I believe this was introduced in #1574.

**Comment by snwfog** [comment]
Looks like this is a dup from https://github.com/rails-api/active_model_serializers/issues/1612

**Comment by rthbound** [comment]
@snwfog I think you're right. Good eye. I'll close this one.
