### ISSUE TITLE
Should we have an ams.github.io page for our docs?

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails-api/active_model_serializers#1626]
That way our docs could still be versioned / tracked with git, and we'd be able to embed runnable examples via something like repl.it or something.

**Comment by bf4** [comment]
cc @remear 

My preference is that all docs should be able to be changed as part of a PR, so that they don't get out of sync.  This would be similar to the Rails Guides pattern, which builds them manually. 

We could write a webhook build the docs and push to a gh-pages branch when a PR is merged.

**Comment by NullVoxPopuli** [comment]
I like that idea. I'll see what options are available for doing that tomorrow morning. :-)

**Comment by NullVoxPopuli** [comment]
this could be a good tool: http://couscous.io/docs/

**Comment by remear** [comment]
The short answer here is, probably, in the sense that there's a high likelihood the generated documentation will be served by GitHub pages. I'm still working on a solution to the docs issue on a larger scale.
