### ISSUE TITLE
Deserialization gives an empty hash with JSON Api

### ISSUE THREAD

**Issue by GCorbel** [rails-api/active_model_serializers#1640]
#### Expected behavior vs actual behavior

With the current master branch, I tried to deserialize like [in the doc](https://github.com/rails-api/active_model_serializers/blob/88d4fe5b5e58db4c1fc1a60c4f032ab6a1bbbc76/docs/general/deserialization.md) with a simple copy/paste. Instead of 

```
ActiveModelSerializers::Deserialization.jsonapi_parse(document)
#=>
# {
#   title: 'Title 1',
#   date: '2015-12-20',
#   author_id: 2,
#   second_author_id: nil
#   comment_ids: [3, 4]
# }
```

I have this : 

```
ActiveModelSerializers::Deserialization.jsonapi_parse(document)
#=> { }
```

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

Copy and paste from the doc

#### Environment

Integrated application and version *(e.g., Rails, Grape, etc)*: 

Rails 5.0.0.beta2

**Comment by GCorbel** [comment]
The code stops at [this line](https://github.com/rails-api/active_model_serializers/blob/v0.10.0.rc4/lib/active_model/serializer/adapter/json_api/deserialization.rb#L117). `payload['data']` gives nil but `payload[:data]` works.

Calling `deep_stringify_keys` works. It sill don't work for parameters because I can't apply this function, it's done when the action is triggered.

**Comment by bf4** [comment]
I think this will be fixed by https://github.com/rails-api/active_model_serializers/pull/1645 cc @remear

**Comment by GCorbel** [comment]
I gave the current code of this PR and its not resolved yet.

**Comment by GCorbel** [comment]
I tried to do a fork and I added `document.deep_stringify_keys!` on the parse method. Now, I have `{:title=>"Title 1", :date=>"2015-12-20", :id=>1}`. 

I don't understand how parameters are parsed.
When I do a request with this data `{"data":{"attributes":{"allow_multiple_payment":false},"type":"settings"}}`, I have this kind of params `Parameters: {"fomat"=>:json, "setting"=>{}}`.

**Comment by bf4** [comment]
For what it's worth, we *have* labeled deserialization as experimental

**Comment by beauby** [comment]
The `jsonapi_parse` method is intended for deserializing JSON hashes, for which the keys will always be strings.

**Comment by beauby** [comment]
@GCorbel I just fixed the doc according to my previous comment. Closing this, thank you for spotting it!
