### ISSUE TITLE
Issue deprecation notice for key_transform default changes

### ISSUE THREAD

**Issue by ianks** [rails-api/active_model_serializers#1646]
Today I upgraded AMS and spent a chunk of time trying to understand why my keys were all incorrect. It turns out that all of the keys in the JSONAPI adapter are now, by default, using the `:dashed` option....

IMO, this a  breaking change, and unexpected. If we want to set some defaults that are different from the current behavior, I think a deprecation cycle is necessary. Also, we should keep the transformation as `:unaltered` until the deprecation cycle is over.

This change is going to cause some pain and breakage if we do not have some sort of warning about this behavior change.

**Comment by bf4** [comment]
@ianks Sorry about that.  I agree. It should have been in a `breaking changes` section at the very least.  cc @remear

**Comment by bf4** [comment]
the JSON API default is good, but we should deprecate till next release

**Comment by NullVoxPopuli** [comment]
@ianks were you at least able to configure your keys to be what you need?

**Comment by bf4** [comment]
Was this from https://github.com/rails-api/active_model_serializers/pull/1629 (gotta :runner: )

**Comment by NullVoxPopuli** [comment]
Yeah, it should stay the way it is, dasherized is what the spec says. But yeah, we should be sure to catch breaking changes in the changlog in the future.

**Comment by ianks** [comment]
The spec *recommends* dasherizing, it is not a must. Therefore I think it is reasonable to change the default _after_ a deprecation cycle, since we are still technically in line with the spec. Making dasher-izing the default will serve to _enhance_ the spec.

**Comment by NullVoxPopuli** [comment]
@ianks were you able to get ams working with your project via the key transform config option? (which will become transform, after @groyoh's next PR).

we are still in release candidate phases so nothing is totally set in stone yet. We strive to achieve reasonable defaults by the time we get to 0.1 (maybe 1.0) released.

**Comment by bf4** [comment]
@nullvoxpopuli I still favor communicating better.  We recommend people use master. Our rc isn't a real rc. We're in a weird state.

If we're closing this issue, I'd like to see some resolution or action item.

**Comment by bf4** [comment]
On a side note, @ianks you up for updating your benchmarking pr?  I'll help if you want.

**Comment by bf4** [comment]
@ianks I'm following you so we can DM? (or join the amserializers.herokuapp.com slack)

**Comment by bf4** [comment]
@ianks with https://github.com/rails-api/active_model_serializers/pull/1645 in flight, and you seem to be around, any thoughts about how we can improve master in the next 24 hours :)

**Comment by bf4** [comment]
I think the biggest issue right now is just that anything but `unaltered` is much slower

**Comment by ianks** [comment]
yeah, i noticed that. i almost think that key transformation should be a plugin of sorts, mostly decoupled from AMS. something a user can add to a pipeline if they want it. this also makes it easier to build an native extension which can do the key transformation at the tail end of the serialization (which would have huge perf benefits).

**Comment by bf4** [comment]
yeah... adding hook methods or middleware like stack would be awesome

**Comment by remear** [comment]
> which can do the key transformation at the tail end of the serialization

I'm curious to know what you mean here since https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/adapter/json_api.rb#L52 is about as tail-end as it gets, but does not cover all cases (#1645). If you need to transform keys, it's going to be slower than not transforming them. I'm not sure how moving it to a plugin would provide a performance gain vs just setting the default transform to `unaltered`.

The transforms might be improved by refactoring them to not require performing an `underscore` before transforming into the desired case.

**Comment by ianks** [comment]
i'm imagining some sort of pipeline archtecture here, and speaking in the abstract:

```ruby
ActiveModelSerializers.pipeline = [
  Adapters::JSONAPI,
  ActiveModelSerializers::KeyTransform(:dashed),
  OJ::JSONRenderer
]
```

Users could easily plug in their own methods to this pipeline
```

**Comment by bf4** [comment]
@ianks see https://github.com/sorentwo/knuckles :)
