### ISSUE TITLE
undefined local variable or method `cache_store' for ActionController::API:Class

### ISSUE THREAD

**Issue by GCorbel** [rails-api/active_model_serializers#1648]
In a Rails 5 app, on the master branch of AMS, when I go to any controller, I have : 

    undefined local variable or method `cache_store' for ActionController::API:Class

It stops at [this line](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/railtie.rb#L31). `cache_store` seems to not be available in Rails 5.

**Comment by bf4** [comment]
This is fixed on master
