### ISSUE TITLE
Inherited methods are nil

### ISSUE THREAD

**Issue by pareeohnos** [rails-api/active_model_serializers#1658]
#### Expected behavior vs actual behavior
I've created an `ApplicationSerializer` which I want to contain the property `success` which is in all child serializers. My understanding is that by declaring the attribute within the superclass, all child classes will inherit this. I am finding that this is partially true when the attribute declared is a method, rather than a property on the underlying resource.

When I render using an instance of the child serializer, the attribute key is present, however the value is always null. If I override the attribute method and simply call `super` within it, I get the value I expect, however this defeats the purpose of inheritance.

#### Steps to reproduce
I have the following structure

```ruby
class ApplicationSerializer < ActiveModel::Serializer
  attributes :status

  def status
    object.try(:errors).blank? && object.try(:error).blank?
  end

end
```

```ruby
class ErrorResponse < ActiveModelSerializers::Model
  attr_accessor :error
end
```

```ruby
class ErrorResponseSerializer < ApplicationSerializer
  attributes :error
end
```

In my controller, I am rendering the response using:

```ruby
render json: ErrorResponse.new('Error message here'), status: :unauthorized
```

I am expecting to get the JSON response of

```json
{
    "success": false,
    "error": "Error message here"
}
```

However, I instead get the response

```json
{
    "success": null,
    "error": "Error message here"
}
```

To remedy this, I can change the definition of the `ErrorResponseSerializer` class to the following:

```ruby
class ErrorResponseSerializer < ApplicationSerializer
  attributes :error

  def success
    super
  end
end
```

And this then works as expected.

#### Environment

ActiveModelSerializers Version: 0.10.0.rc4 d30aa4c 
Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin13.0]
OS Type & Version: Mac OS X 10.11.3
Integrated application and version: Rails 4.2.1

**Comment by NullVoxPopuli** [comment]
@pareeohnos hey, can you try this commit: 5be33afbfb77489db9bd8ea99b20d53b17d2ec9c

**Comment by pareeohnos** [comment]
hmm that's strange @NullVoxPopuli that's worked. Something after this commit must be breaking something though. I have just installed from master before trying this, and that commit appears to have been added to master 3 days ago?

**Comment by pareeohnos** [comment]
have just tested - your commit 5be33afbfb77489db9bd8ea99b20d53b17d2ec9c works, but the commit straight after dba85f2720a167aa3e37c0367cf7fc9861840126 causes it to break once again, even though the commit is 100% documentation. How is that possible!?

**Comment by NullVoxPopuli** [comment]
I have no idea, I'm confused about this, too.

**Comment by bf4** [comment]
Should be fixed by https://github.com/rails-api/active_model_serializers/pull/1661

**Comment by NullVoxPopuli** [comment]
Closing for now, please re-open if this issue still exists

**Comment by pareeohnos** [comment]
Seems to be working for me. Cheers guys :)
