### ISSUE TITLE
Undefined method '*' in specs (wildcard) with RSpec

### ISSUE THREAD

**Issue by kofronpi** [rails-api/active_model_serializers#1659]
#### Expected behavior vs actual behavior

When I run specs to test my controller, specs fails because '*' is not a method of the parent model class.

#### Steps to reproduce

1. Install rails 5.0.0beta3
2. Install active_model_serializers 0.10.0rc4
3. Install rspec 3.5.0beta3
4. Create a dummy `Company` class which `belongs_to` a `CompanyStructure` class
5. Configure AMS to use `:jsonapi`
6. Use this serializer:
```
class CompanySerializer < ActiveModel::Serializer
  attributes :id
  belongs_to :company_structure
end
```
7. Use this controller:
```
module Api
  module V1
    class CompaniesController < ApiController
      def index
        render json: Company.all, include: '*'
      end
    end
  end
end
```
8. Use this rails initializer:
`ActiveModelSerializers.config.adapter = :json_api`
9. Use these specs:
```
require 'rails_helper'
require "#{Rails.root}/app/controllers/api/v1/companies_controller.rb"
RSpec.describe Api::V1::CompaniesController, type: :controller do
  describe '#index' do
    it_behaves_like 'an index request'
  end
end
```
and

```
shared_examples_for 'a successful request' do
  it 'returns an OK (200) status code' do
    expect(response.status).to eq(200)
  end
end

shared_examples_for 'an index request' do
  before do
    FactoryGirl.create_list(described_class.controller_name.singularize.to_sym, 2)
    get 'index'
  end

  it_behaves_like 'a successful request'
end
```

Specs fail.

#### Environment

ActiveModelSerializers Version *0.10.0.rc4*

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`
 
OS Type & Version: Ubuntu 14.04

Integrated application and version *Rails 5.0.0beta3*: 

#### Backtrace
```
Failures:

  1) Api::V1::CompaniesController#index behaves like an index request behaves like a successful request returns an OK (200) status code
     Failure/Error: render json: Company.all, include: '*'
     
     NoMethodError:
       undefined method `*' for #<Company:0x00000007b68af8>
     Shared Example Group: "a successful request" called from ./spec/support/shared_api_examples.rb:13
     Shared Example Group: "an index request" called from ./spec/controllers/api/v1/companies_controller_spec.rb:5
     # ./app/controllers/api/v1/companies_controller.rb:5:in `index'
     # ./spec/support/shared_api_examples.rb:10:in `block (2 levels) in <top (required)>'
```

Thank you !

**Comment by bf4** [comment]
Can you paste your `Configure AMS to use :jsonapi` and which file it's in?

If you can help us debug the stack trace to see what's happening when it calls `'*'` on the `company` would be great.

**Comment by kofronpi** [comment]
I use this single statement in a rails initializer: `ActiveModelSerializers.config.adapter = :json_api`
I might have a look later on about a more accurate stack trace.
