### ISSUE TITLE
Methods defined in serializer are not used 

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails-api/active_model_serializers#1660]
#### Expected behavior vs actual behavior

Possibly related to #1658.

I expect the methods defined in the serializer to be used for the attributes.

What is happening is the attribute is invoked on the object, resulting in an error if the method does not exist.

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

- clone https://github.com/NullVoxPopuli/aeonvera
- clone https://github.com/NullVoxPopuli/aeonvera-ui
- add swing.vhost to your hosts file
- boot up both apps.
- visit swing.vhost:4200 (the ember-app)
- create an account
- open the network log
- login
- notice the call to current user fails, and gives this error message:
![image](https://cloud.githubusercontent.com/assets/199018/14248613/7eceffe2-fa43-11e5-8a64-27bf22c6be46.png)

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```
OS Type & Version: `Ubuntu 15.10 64bit`

Integrated application and version *(e.g., Rails, Grape, etc)*: 

rails: 4.2.6
AMS: RC4 works
AMS: master has this issue

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

![image](https://cloud.githubusercontent.com/assets/199018/14248685/e9815df8-fa43-11e5-9dab-c23e2726ff81.png)

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

https://github.com/NullVoxPopuli/aeonvera/blob/master/Gemfile.lock

I tried working on a failing test with the AMS code, but something funky is happening, I'll continue to investigate.

**Comment by NullVoxPopuli** [comment]
This commit works: https://github.com/rails-api/active_model_serializers/commit/5be33afbfb77489db9bd8ea99b20d53b17d2ec9c

**Comment by NullVoxPopuli** [comment]
which is weird, because no code changes have occurred after that commit -- just documentation changes.

**Comment by groyoh** [comment]
@NullVoxPopuli maybe related to #1650

**Comment by NullVoxPopuli** [comment]
@groyoh see these comments: https://github.com/rails-api/active_model_serializers/issues/1658#issuecomment-205295445

**Comment by bf4** [comment]
Related to https://github.com/rails-api/active_model_serializers/issues/1653 I believe I introduced this

**Comment by NullVoxPopuli** [comment]
Fixed by #1661
