### ISSUE TITLE
Error when trying to render a PORO that does not have a serializer

### ISSUE THREAD

**Issue by whatthewhat** [rails-api/active_model_serializers#1665]
#### Expected behavior vs actual behavior
When using `render json:` with a PORO that does not have a serializer and does not define `model_name` we get `NoMethodError: undefined method 'model_name' for Foo:Class`

#### Steps to reproduce

```ruby
class Foo
  def as_json(options)
    { foo: :bar }
  end
end

# in a controller action
render json: Foo.new
```

If we're using vanilla rails the response will be rendered as expected, but if we have AMS installed we get `NoMethodError: undefined method 'model_name' for Foo:Class`.

#### Environment

ActiveModelSerializers Version: `rc5`
Serializer: `json`
Rails: `4.2.5.1`

#### Backtrace

```
NoMethodError:
  undefined method `model_name' for Foo:Class
# /usr/local/bundle/gems/active_model_serializers-0.10.0.rc5/lib/active_model/serializer.rb:173:in `json_key'
# /usr/local/bundle/gems/active_model_serializers-0.10.0.rc5/lib/active_model_serializers/adapter/base.rb:53:in `root'
# /usr/local/bundle/gems/active_model_serializers-0.10.0.rc5/lib/active_model_serializers/adapter/json.rb:6:in `serializable_hash'
# /usr/local/bundle/gems/active_model_serializers-0.10.0.rc5/lib/active_model_serializers/adapter/base.rb:27:in `as_json'
# /usr/local/bundle/gems/activesupport-4.2.5.1/lib/active_support/json/encoding.rb:35:in `encode'
# /usr/local/bundle/gems/activesupport-4.2.5.1/lib/active_support/json/encoding.rb:22:in `encode'
# /usr/local/bundle/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
# /usr/local/bundle/gems/active_model_serializers-0.10.0.rc5/lib/active_model_serializers/serializable_resource.rb:8:in `to_json'
...
```

#### Additonal helpful information
This follows a discussion on slack with @NullVoxPopuli  and @bf4, I'll probably have some time to look into fixing it this week or on the weekend.

**Comment by bf4** [comment]
I just ran

```ruby
  class Foo
    def as_json(options)
      { foo: :bar }
    end
  end
  def test_render_without_serializer
    assert_equal({ foo: :bar }, ActiveModelSerializers::SerializableResource.new(Foo.new).as_json({}))
  end
```

And the test passed

**Comment by whatthewhat** [comment]
Interesting, maybe it only happens when using the ActionController extensions, I'll have some time tomorrow to look into it.

**Comment by whatthewhat** [comment]
After trying (and failing) to replicate this in the AMS test suite, I took another look at the app I was working on and it turned out there actually was a `FooSerializer` defined :facepalm:

Sorry for bugging you guys with this :)
