### ISSUE TITLE
Use with Action Cable?

### ISSUE THREAD

**Issue by gwincr11** [rails-api/active_model_serializers#1666]
Hello,

I would like to use ActiveModelSerializers with action cable. Does anyone know how I can serialize an instance directly?

Thanks,
Cory

**Comment by bf4** [comment]
@gwincr11 would you mind providing some more information?  Some of the requested info can be found in https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md

Please reopen when responding.
