### ISSUE TITLE
serializer option does not seem to be respected

### ISSUE THREAD

**Issue by sgringwe** [rails-api/active_model_serializers#1669]
#### Expected behavior vs actual behavior
I am passing the serializer option to a belongs_to on 0.10.rc5. I would expect it to use the serializer, but it doesn't.

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

Code like `belongs_to :job, serializer: ::Search::JobSerializer`

does not use that serializer, it uses `JobSerializer`

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`

OS Type & Version: 

Integrated application and version *(e.g., Rails, Grape, etc)*: 

Rails

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

N/A

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

I have overriden as_json method on 'Job' model, but my debugging doesn't seem to indicate it is called, anyways.

**Comment by bf4** [comment]
@sgringwe 

> Code like belongs_to :job, serializer: ::Search::JobSerializer

> does not use that serializer, it uses JobSerializer

Would you be able to provide some more details of your serializer, how you render, etc. so we can investigate?

**Comment by bf4** [comment]
Please reopen when adding more information

**Comment by sgringwe** [comment]
@bf4 I have two different types of serializers, the 'normal' one and ones for indexing data in ES. The ones indexing data in ES sometimes point to other serializers, such as the job serializer, of which i also want to use the ES indexing serializer rather than the normal one. Simple definition of a search serializer:

what i am hoping to do:
```
module Search
  class PostingSerializer < ActiveModel::Serializer
    # bunch of attributes
    belongs_to :job, serializer: ::Search::JobSerializer
  end
end
```

i ended up getting around it by doing
```
module Search
  class PostingSerializer < ActiveModel::Serializer
    # bunch of attributes
    attributes :job

    def job
      ::Search::JobSerializer.new(object.job)
    end
  end
end
```

it doesn't look like i can re-open

**Comment by bf4** [comment]
> it doesn't look like i can re-open

weird, sorry

**Comment by groyoh** [comment]
> The ones indexing data in ES sometimes point to other serializers

@sgringwe is it **sometimes** or **always**? Does your `Job` model have a `serializer_class` method?

Would it be possible for you to provide a gist or project that results in the described behavior?

**Comment by sgringwe** [comment]
@groyoh ah, it does. i've renamed that method and everything is working as expected now. thanks for the help.

**Comment by groyoh** [comment]
@sgringwe glab to help :+1:
