### ISSUE TITLE
Namespaced DSL for serializer

### ISSUE THREAD

**Issue by beauby** [rails-api/active_model_serializers#1680]
Quite a bit of confusion has emerged in the past from setting adapter-specific options inside serializers (example: `type`, `meta`). It is not clear which DSL method is relevant to each adapter, and the current implementation forces us to have a common interface for identically named options, although we might want to provide different behavior based on the adapter.
#### Expected behavior vs actual behavior

Current behavior:

``` ruby
class PostSerializer < ActiveModel::Serializer
  type 'posts'
  ...
end
```

Proposed behavior:

``` ruby
class PostSerializer < ActiveModel::Serializer
  JsonApi.type 'posts'
  ...
end
```

and/or

``` ruby
class PostSerializer < ActiveModel::Serializer
  extend JsonApi
  type 'posts'
  ...
end
```

Possibly, we could also define an `ActiveModel::JsonApiSerializer`, which would automatically extend the corresponding module.
I get this goes against the serializer being adapter-agnostic, but I think it is fair to say that approach has its limits, and explicitly tailoring an adapter to an adapter (possibly several) makes it easier to catch mistakes early on.

**Comment by NullVoxPopuli** [comment]
I like it makes things more explicit -- specifically the mention of JsonApi, but don't the other adapters have types as well? (just represented as the root key?)

what other JsonApi only settings would be available to the serializer? `links`, `meta`... others?

An argument against inheriting from `ActiveModel::JsonApiSerializer` could be that an API wants to respond to different format types, but wants to use the same serializers for all of those formats. (in which case, I guess just `extend` would cover all that)

**Comment by beauby** [comment]
`JsonApi` was used as an example here, but it is implied that there would be corresponding modules for other adapters (like `Json.root`/`Json.type` for instance).

Basically, all JSON API specific DSL methods would be scoped in the module (currently, it would mainly be `type`, `links`, `meta`).

As for your last concern, I definitely agree, although that suggestion was meant for "JSON API only" scenarios. The idea is that one would be able to provide `JsonApi`-specific as well as `Json`-specific options in the same serializer for multiple formats scenarios.

**Comment by NullVoxPopuli** [comment]
>  The idea is that one would be able to provide JsonApi-specific as well as Json-specific options in the same serializer for multiple formats scenarios.

I like that. :-)

Do you think there could be a way to have this sort of be an opt-in thing? so we don't break everyone's current serializer setup?  

I do like that this would make all the options very obvious as to what they are used for.

**Comment by beauby** [comment]
We could keep the current DSL with a deprecation warning.
