### ISSUE TITLE
Allow configuration of the default include tree

### ISSUE THREAD

**Issue by jtmarmon** [rails-api/active_model_serializers#1709]
Right now ams includes '*' [by default](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/adapter/attributes.rb#L6).

There's been discussion about making the default `**` (see: #1205), but the consensus was that it should stay the same and I agree. However, it's reasonable to want to configure this, and quite simple to implement (just change the hardcoded string to a variable from a global config).

I'll try to get a PR together sometime in the next c ouple days. Atm we just forked the repo and replaced `*` with `**`.

**Comment by bf4** [comment]
If you're interested in pick up where https://github.com/rails-api/active_model_serializers/pull/1426 left off that would be great!

**Comment by bf4** [comment]
The default for JSON API is always going to be no includes, per spec.  There are good reasons not to make `**` the default, but I agree it would be better to make that your choice.

**Comment by beauby** [comment]
I'm :+1: on making it a config.

**Comment by remear** [comment]
Resolved by #1426
