### ISSUE TITLE
json adapter doesn't seem to render includes

### ISSUE THREAD

**Issue by hbarrington** [rails-api/active_model_serializers#1713]
#### Expected behavior vs actual behavior

In my controller I do:

> tasks = policy_scope(Project).scheduled.includes(:scheduled_children).order(:name)
> render json: tasks, serializer: ActiveModel::Serializer::CollectionSerializer, include: ['scheduled_children'], each_serializer: Schedule::TaskSerializer, adapter: :json

We would like to use json as opposed to json-api, the format we use everywhere else in the app, for some client side performance considerations.

I would expect to get something like: 
![image](https://cloud.githubusercontent.com/assets/447636/14958808/71c25e02-105a-11e6-8a09-26faf3e6ca36.png)

Instead I get:
![screen shot 2016-05-02 at 11 39 08 am](https://cloud.githubusercontent.com/assets/447636/14958840/979a7da8-105a-11e6-8707-01fee8cb3440.png)

If it helps, serializer [edited] looks like:
```
 class Schedule::TaskSerializer < ActiveModel::Serializer
  attributes :id, :name, :percent_complete
  attribute :start
  attribute :end
  attribute :number_of_children
  has_many :scheduled_children, serializer: Schedule::TaskSerializer, key: :children

  def number_of_children
    object.children.size
  end

  def start
    if object.start_date_scheduled.nil?
      object.due_date_scheduled - 24.hours
    else
      object.start_date_scheduled
    end
  end

  def end
    if object.due_date_scheduled.nil?
      object.start_date_scheduled + 24.hours
    else
      object.due_date_scheduled
    end
  end


end
```

#### Steps to reproduce

Code is provided above. Happy to add more if desired.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

active_model_serializers-0.10.0.rc5

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

OS Type & Version: 

Mac OS X - 10.11.4 

Integrated application and version *(e.g., Rails, Grape, etc)*: 

rails-5.0.0.beta3

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by hbarrington** [comment]
I'll add that switching to `adapter: :json-api` renders and gives me the desired result.

**Comment by cgmckeever** [comment]
@hbarrington Im running into something similar.  Posted on the AMS slack as well over in StackOverflow

Mine has more to do with Polymorphs not appearing when I think they should
http://stackoverflow.com/questions/36974791/activemodelserializers-polymorphic-json

question for you with the json-api, it properly wraps everything ? (ie doesnt add a data key?) and also give you all attributes of the associated items?  If all that is true, why not use the json_api ?

**Comment by beauby** [comment]
Could you post the exact definitions of the `Schedule::TaskSerializer`? The fact that the `:jsonapi` serializer does render the relationships (note that it probably wouldn't render the children's attributes in the current situation) does not say anything.

**Comment by hbarrington** [comment]
@beauby I updated the original post with the full definition of Schedule::TaskSerializer.

You are correct, the :jsonapi serializer does not render the children's attributes. At one point I thought I had that working? I can follow up on that point in slack or research on my own later.

**Comment by groyoh** [comment]
@hbarrington please have a look at https://gist.github.com/groyoh/01b218e9e1f4a1af6fc7b700de17cd3e. It seems to work fine.

In your example, we can see `number_of_children: 0`, maybe that's the issue?

**Comment by hbarrington** [comment]
@groyoh thanks for the in depth example! You were right it worked correctly. 

I was including the relationship `scheduled_children` rather than the key name in the serializer `children` 

I assumed that in the render statement using include would need the name of the relationship. Is it a bug that using the json-api adapter gives the same result whether I do `include: ["scheduled_children"]` (the relationship name in the model) or `include: ["children"]` (the key in the serializer)? When I use `adapter: :json` only one works obviously.

This seems strange to me.

But it's working now. Thanks again 👍

**Comment by beauby** [comment]
Oh, I get it now, the problem came from the fact that you were aliasing the relationship (with the `key:` option), and the `include` logic checks for the keys, not the attribute name (which are the same when no `key:` option is provided). The reason behind that is that `include` which comes from the JSON API spec, can be a query parameter, hence it makes sense to `include` with the relationship names the API consumer face.
As for your question, no it is not a bug that the `JsonApi` adapter includes relationship _linkage_ even when the relationship is not included. For more information about how that works, have a look at http://jsonapi.org/format at the Compound Document section.

**Comment by hbarrington** [comment]
@beauby thanks for the help and the explanation to boot 👍
