### ISSUE TITLE
Dynamic serializer selection

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1719]
Currently the serializer param on `has_x` takes an object.

It would be cool if it could accept a method name as well.

Use case:

Dynamically setting the serializer for polymorphic relationships:

    has_one :user, polymorphic: true, serializer: :serializer_picker
 
    def serializer_picker
       if user.class == 'Admin'
         SparseAdminSerializer
       end
     end

**Comment by cgmckeever** [comment]
cant you just do this as an attribute then and make a method for said attribute?

```
class SomeSerializer < ApplicationSerializer
  attributes :id, :somefakerelationship

  def somefakerelationship
     ## do stuff
    ## profit?
  end

```

**Comment by KevinColemanInc** [comment]
@cgmckeever true, but I want to specify the serializer of the thing that spawned. For my particular use case, I am have a model called "Notifications"  It has a `source_obj` polymorphic relationship on it such that many different models can be a `source_obj`.

The default model's serializer is often too big for what I want.  So I want to the source_obj to have use special "sparse" serializers for each object. e.g. sparse_user_serializer, sparse_profile_serializer, etc. etc. instead of the default model serializer of user_serializer or profile_serializer.

does that make sense?

I think my hack to fix this will be to do:

    class SomeSerializer < ApplicationSerializer
      attributes :id, :source_obj

      def source_obj
        object.source_obj.to_json
      end
    end

so I am at least not accidently getting any N+1s

**Comment by groyoh** [comment]
@KevinColemanInc use this:

```ruby
class MySerializer < ActiveModel::Serializer
  def self.serializer_for(model, options)
    return SparseAdminSerializer if model.class == 'Admin'
    super
  end

  # the rest of the serializer
end
```

**Comment by cgmckeever** [comment]
@groyoh NICE!

**Comment by KevinColemanInc** [comment]
Cool! I will use that.  I was hoping to be able to something like this:

**Comment by beauby** [comment]
We should document this. PR anyone?
