### ISSUE TITLE
Question: the best way to serialize a model with 2 nested has_many (:through) associations with attributes of the associations. V: 0.10.x I: Question R: Not a bug

### ISSUE THREAD

**Issue by mitjok** [rails-api/active_model_serializers#1724]
**Question**: what is the best way to serialize a model with 2 nested has_many (:through) associations so that resulting :api_json included some of the attributes of the nested associations.

**Background**
```ruby
class Vendor < ApplicationRecord
  has_many :vendor_services
  has_many :services, through: :vendor_services
  has_many :items, through: :services
end

class Service < ApplicationRecord
  has_many :service_rules
  has_many :items, through: :service_rules
end

class Item < ApplicationRecord
  has_many :service_rules
  has_many :services, through: :service_rules
end
```

```ruby
class VendorSerializer < ActiveModel::Serializer
  attributes :id, :name, :lat, :lon, :address

  has_many :services, serializer: ServiceSerializer
end

class ServiceSerializer < ActiveModel::Serializer
  attributes :id, :name

  has_many :items
end

class ItemSerializer < ActiveModel::Serializer
  attributes :id, :name
end
```

**Question explanation**: I need resulting Vendor json to include Service#name and Vendor -> Service json to include Item#name. In another words I'd like to have Item#name properly nested in Service (with Service#name attribute) which in turn properly nested in Vendor (resulting) :api_json 

**P.S.** I ended up with 
```ruby
render json: vendor_search.result, include: { services: [:name,  items: [:name]] }
```
but not sure it's the best way possible.

**Comment by bf4** [comment]
@mitjok might you share why you closed it? If you have a resolution?

**Comment by maxKimoby** [comment]
@mitjok Yeah please explain the solution please.
