### ISSUE TITLE
Root no longer works?

### ISSUE THREAD

**Issue by icco** [rails-api/active_model_serializers#1735]
#### Expected behavior vs actual behavior

I have a very simple serializer:

```
class CacheSerializer < ActiveModel::Serializer
  attributes :url, :title, :size, :image, :modified
  root false
end
```

Which works great in 0.9, but in 0.10 fails with:

```
NoMethodError: undefined method `root' for CacheSerializer:Class
/Users/nat/Projects/inspiration/lib/cache_db.rb:332:in `<class:CacheSerializer>'
/Users/nat/Projects/inspiration/lib/cache_db.rb:330:in `<top (required)>'
/Users/nat/Projects/inspiration/site.rb:16:in `require'
/Users/nat/Projects/inspiration/site.rb:16:in `<top (required)>'
/Users/nat/Projects/inspiration/Rakefile:2:in `require'
/Users/nat/Projects/inspiration/Rakefile:2:in `<top (required)>'
/Users/nat/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/nat/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

#### Steps to reproduce

Above, but actual code is at https://github.com/icco/inspiration/blob/master/lib/cache_db.rb#L330

#### Environment

active_model_serializers (0.10.0)

```
  ruby:
    interpreter:  "ruby"
    version:      "2.3.0p0"
    date:         "2015-12-25"
    platform:     "x86_64-darwin14"
    patchlevel:   "2015-12-25 revision 53290"
    full_version: "ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]"
```

**Comment by remear** [comment]
As noted in https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md

> Attributes - Default
> It's the default adapter, it generates a json response without a root key

> JSON
> The response document always with a root key.
> The root key can't be overridden, and will be derived from the resource being serialized.

It sounds like you might want to use, or continue using, the `attributes` adapter and remove `root false` from your serializer.

**Comment by bf4** [comment]
I'm going to close this since the reason it doesn't work is because it's not a supported feature. However, if you'd like to make a PR adding a mixin that people upgrading from version 9 can use for easier upgrades, I would probably merge that!

**Comment by bf4** [comment]
(To clarify, what @remear wrote will help you with your issue https://github.com/rails-api/active_model_serializers/issues/1735#issuecomment-220039730 )

**Comment by dgdosen** [comment]
hmm - I'm still getting a root when I use the json adapter...  is this in the main branch yet?

**Comment by dgdosen** [comment]
In reading the documentation, I read there being two adapters (json and json_api).  I didn't realize there was a 3rd adapter (attributes).  I thought the use of attributes was describing how the json adapter worked... My mistake in reading that...

**Comment by chrishough** [comment]
@icco  how did you solve the root: false issue? I have the same requirement

**Comment by icco** [comment]
@chrishough I just ripped it out and wrote it myself. Got to remove a dependency and my implementation was only a few lines.
