### ISSUE TITLE
Getting PORO serialization to work with classes we don't have control over.

### ISSUE THREAD

**Issue by hickscorp** [rails-api/active_model_serializers#1737]
I'm trying to give another try at AMS. This issue might be a follow up on #1521. We're still usung `0.10rc3`.

We're hitting an API via an `ActiveResource` based gem we don't own. When we get results (Basically a collection of `ActiveResource::Base` derivates), we would like to be able to serialize them, so we could filter and remodel some fields.

For the sake of this explaination, let's say the object we want to serialize is an instance (Or a collection of instances) of `Foo`. We've created a serializer like so:

```
class FooSerializer < ApplicationSerializer
  attributes :id, :title, :image
end
```

This collection is contained in another PORO model of ours:

```
class FooPresenter
  include ActiveModel::Serialization

  ATTRIBUTES ||= %i(store page more_pages product_count products).freeze
  attr_reader *ATTRIBUTES

  def initialize(store, page)
    ...
  end

  def foos
    # Here, we return that collection of Foo instances.
  end
end
```

The serializer for that object of ours looks like so:

```
class FooPresenterSerializer < ApplicationSerializer
  attributes :page, :more_pages, :product_count
  has_many :foos, serializer: Foo
end
```

We render that base FooPresenter in a controller using:

```
render json: FooPresenter.new(@current_store, page)
       serializer: FooPresenterSerializer
```

We're getting the following error:

```
> private method `read_attribute_for_serialization' called for #<Foo:0x007fd371d66018>
Did you mean?  read_attribute_for_validation
```

How do you get AMS to work with classes you don't have control over (And collections of them)?
The example exposed here is our latest attempt at it, we tried numerous things, no cigar so far.

**Comment by remear** [comment]
Have you worked through https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#serializing-non-activerecord-objects?

**Comment by beauby** [comment]
You could either monkey-patch the foreign class in an initializer, adding the methods required by AMS, or you could use a decorator class.
