### ISSUE TITLE
How can I return relationships pagination in serializer?

### ISSUE THREAD

**Issue by EJIqpEP** [rails-api/active_model_serializers#1739]
Hello guys. I want to implement pagination in relationships but I didn't found any examples. Is it possible at all?
The url looks like this
/api/users/1/comments?page=1

The response is the single user with relationships
```
"data": {
  "id": 1,
  "type": "user"
},
"relationships": {
    "comments": {
        "meta": {
            "count": 21,
            "pagination": {
                "page": 1,
                "pages": 1,
                "count": 21
             }
        },
        "data": [
             {
                 "type": "comments",
                  "id": "874"
             },
             {
                  "type": "comments",
                   "id": "877"
              },
              {
                  "type": "comments",
                  "id": "2273"
              }
       ]
},
```

**Comment by beauby** [comment]
The way the spec. outlines [fetching relationships](http://jsonapi.org/format/#fetching-relationships), you would fetch `/api/users/1/relationships/comments`, which would not return the user, but only the comments as primary data. Pagination would be handled the same way as for any other collection.
