### ISSUE TITLE
Problem with serializing "included" array when the same model uses two different serializers

### ISSUE THREAD

**Issue by andrewhavens** [rails-api/active_model_serializers#1740]
#### Background

I have an application that uses the JSON API format with an endpoint that returns a polymorphic collection. Some of the records in the collection have relationships to the same records, but each use a different serializer in order to reduce the payload to the bare minimum that is needed.

#### Actual Behavior
When the serializer adds the record to the `included` array, it seems that it is only adds the first one it finds (or maybe it's the last, I'm not sure). So if the first record is a "preview", and the second should be a "full", it only serializes as a "preview". So if the collection is in a different order, the serialization may be different.

#### Expected Behavior
I would like the "full" serializer to be one that is serialized in the `included` array because it would be better to have more fields than less. However, I don't necessarily have a recommendation on how this should be specified. It seems like we would need a way of merging serialized records, or keeping track of the "level" of serialization (preview vs full).

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

Example Serializers:

```ruby
class MammalSerializer < ActiveModel::Serializer
  has_one :mammal_object # this is serialized with one of the below
  
  class DogSerializer
    belongs_to :owner, serializer: HumanPreviewSerializer
  end

  class CatSerializer
    belongs_to :owner, serializer: HumanPreviewSerializer
  end
  
  class HumanPreviewSerializer
    attributes :name
  end

  class HumanSerializer
    attributes :name, :email, :phone
    has_one :home_address
  end
end
```

Given an array of mammals:

- Dog
- Cat
- Human

The response will be something like:

```
{
  "data" => [
    {
      "id" => "1",
      "type" => "mammal",
      "relationships" => {
        "mammal_object" => {
          "data" => {
            "id" => "1",
            "type" => "dog"
          }
        }
      }
    },
    {
      "id" => "2",
      "type" => "mammal",
      "relationships" => {
        "mammal_object" => {
          "data" => {
            "id" => "1",
            "type" => "cat"
          }
        }
      }
    },
    {
      "id" => "3",
      "type" => "mammal",
      "relationships" => {
        "mammal_object" => {
          "data" => {
            "id" => "1",
            "type" => "human" // Should use the HumanSerializer
          }
        }
      }
    },
  ],
  "included" => [
    {
      "id" => "1",
      "type" => "dog",
      "relationships" => {
        "owner" => { // Uses the HumanPreviewSerializer
          "data" => {
            "id" => "1",
            "type" => "human"
          }
        }
      }
    },
    {
      "id" => "1",
      "type" => "cat",
      "relationships" => {
        "owner" => { // Uses the HumanPreviewSerializer
          "data" => {
            "id" => "2",
            "type" => "human"
          }
        }
      }
    },
    {  // Should have used the HumanSerializer, but did not
      "id" => "1",
      "type" => "human",
      "attributes" => {
        "name" => "My human name"
      }
    },
  ]
}
```    

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 0.10.0

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

OS Type & Version: Mac 10.11.4 (Mavericks) 

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 4.2

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

N/A

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

N/A

**Comment by cgmckeever** [comment]
@andrewhavens when you define the relationship in the serializer, make sure to add polymorphic: true (that will allow the nested relationships), and then if you want infinite traversal, include: '*.*'

Check out this test which seems to do (not as deep) what you are looking for?
https://github.com/rails-api/active_model_serializers/blob/660e982c7272e24cc7d11183b208dbda8bd9d91c/test/adapter/polymorphic_test.rb#L53

**Comment by cgmckeever** [comment]
or crap @andrewhavens I just realized you are using ``json_api`` which that example does not apply to.

**Comment by beauby** [comment]
The quick answer is: with the `JsonApi` adapter, you should only use one serializer per resource, and tailor it down with the `fields` adapter option and/or conditional attributes/relationships.
Due to the nature of JSON API serialization (flattening of the data graph, hence no duplicates), each resource can be serialized only once, even if it is referenced many times. Supporting your use-case would incur a performance decrease on serialization of densely linked data graphs.
Closing this, as the behavior won't change, but feel free to keep discussing it here.
