### ISSUE TITLE
feature: support for cancancan

### ISSUE THREAD

**Issue by u007** [rails-api/active_model_serializers#1742]
#### Expected behavior vs actual behavior

anyway to pass in current_user, or current_ability from cancancan gem to determine the serialisable attributes?

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

maybe:
options = {  ability: current_ability }
serialization = ActiveModelSerializers::SerializableResource.new(resource, options)

**Comment by cgmckeever** [comment]
@u007 this PR surprised me with the ability of getting the controller current_user
https://github.com/rails-api/active_model_serializers/pull/1734

Maybe it will lead you down the path you need?

**Comment by u007** [comment]
@cgmckeever nice :)
when will this be main stream?

**Comment by bf4** [comment]
this is already present https://github.com/rails-api/active_model_serializers/blob/db87f8d85e7a46ef195a555cb7e2509f1affc622/docs/general/serializers.md#scope as serialization scope, no?

**Comment by cgmckeever** [comment]
I think it is already in the 0.10 branch.  Which version are you using?

**Comment by bf4** [comment]
Or just https://github.com/rails-api/active_model_serializers/blob/db87f8d85e7a46ef195a555cb7e2509f1affc622/docs/howto/passing_arbitrary_options.md#passing-arbitrary-options-to-a-serializer

**Comment by u007** [comment]
nice, ive 0.10 :)
