### ISSUE TITLE
customize activemodel serializers error codes

### ISSUE THREAD

**Issue by mohsenjalalian** [rails-api/active_model_serializers#1744]
Hi . I use ActiveModelSerializers on Rails to response my clients in a restfull app . I use jsonapi.org standard in my response . I want to customize my error response like following :

"errors": [
{
  "code":   "123",
  "source": { "pointer": "/data/attributes/first-name" },
  "title":  "Value is too short",
  "detail": "First name must contain at least three characters."
}

I want to have error codes in my response like above example

**Comment by remear** [comment]
It's unclear to me if you're having an issue, encountering the inability to do something, or simply asking how to render error responses with custom status codes.

Please read through https://github.com/rails-api/active_model_serializers/blob/master/docs/jsonapi/errors.md

If after reading that document you're having specific issues, please clarify them in this issue so we can better assist you.

**Comment by Harry-YangHL** [comment]
@remear Are you covering problems?

I think @mohsenjalalian 's question is quite clear: How to add custom error code in the response just as JSON API specs. And I don't think the link you gave explains how to get this done.

**Comment by nallwhy** [comment]
@remear ErrorSerializer only serializes `errors.messages`. Is there any way to send other properties like `title` or `code` ?

**Comment by bf4** [comment]
@nadavshatz @Harry-YangHL @mohsenjalalian someone needs to write code to do that. PRs accepted :)

**Comment by nadavshatz** [comment]
@bf4 I think you confused me with @nallwhy :)
