### ISSUE TITLE
Concerns in Rails way

### ISSUE THREAD

**Issue by martinezcoder** [rails-api/active_model_serializers#1748]
#### Expected behavior vs actual behavior

This is about how to write class methods using ActiveSupport::Concern

https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/attributes.rb#L27

#### Steps to reproduce

Instead of

```ruby
module ClassMethods
   ...
end
```

ActiveSupport::Concern give us a cleaner way

```ruby
class_methods do
  ...
end
```

#### Additonal helpful information
http://api.rubyonrails.org/classes/ActiveSupport/Concern.html

**Comment by NullVoxPopuli** [comment]
this isn't compatible with rails 4.1
