### ISSUE TITLE
upgrade from rc2 changes the underscore ("_") to dash("-")

### ISSUE THREAD

**Issue by tokhi** [rails-api/active_model_serializers#1755]
After the upgrade all the attributes with `_` replaced to `-`
e.g; instead of `account_id` the response renders `account-id`

**Comment by janvarljen** [comment]
@tokhi yes it's the default key_transform now.

Check docs here:

https://github.com/rails-api/active_model_serializers/blob/master/docs/general/configuration_options.md#key_transform

**Comment by tokhi** [comment]
Thanks alot @janvarljen .
