### ISSUE TITLE
Exclude namespace in root key in 0.10?

### ISSUE THREAD

**Issue by ehannes** [rails-api/active_model_serializers#1756]
Using the `:json` adapter, is there some way to exclude the namespace part from the root key?

I used version 0.9 before and my JSON representation of a `User` at api/v1/users/1 was something like:

    { "user": { "id": 1, "first_name": "Foo", "last_name": "Bar" } }

I recently upgraded to version 0.10 and now I get the namespace included in the root key:

    { "api/v1/user": { "id": 1,"first_name": "Foo", "last_name": "Bar" } }

I want the root key to be like before, that is "user" instead of "api/v1/user".

**Comment by NullVoxPopuli** [comment]
According to https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md#json

The root key can't be overridden :-(

I think @beauby was doing some work on this.

**Comment by bf4** [comment]
You should be able to change it by controlling `Serializer#json_key`.  See `Adapter::Base#root`

```ruby
      def root
        serializer.json_key.to_sym if serializer.json_key
      end
````

**Comment by ehannes** [comment]
@NullVoxPopuli I read that, but I also read this at https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#overriding-the-root-key:

> Overriding the resource root only applies when using the JSON adapter.

Is that documentation obsolete?

**Comment by ehannes** [comment]
> So, looks like you can make a pr to update the docs :)

@bf4 What docs are you suggesting to be updated? The one that @NullVoxPopuli linked to?

**Comment by ehannes** [comment]
I have now two working solutions:

1. Set `type` in the serializer as @bf4 suggested.

2. Set the root key explicitly when rendering, something like:
`render json: @user, root: 'user'`

The second alternative is obviously only suitable when changing the root temporary.

I think I'll go the first alternative and programmatically determine the root key through a module or something. That has the advantage to work with the `:json_api` adapter as well.

**Comment by bf4** [comment]
Whatever would have helped you before you made the issue :) probably need to update those docs 

B mobile phone

**Comment by remear** [comment]
> The root key can't be overridden, and will be derived from the resource being serialized.

needs to be corrected in https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md#json. It should be updated to make known, in brief, it *is* possible to override the root key in the ways mentioned in this issue and link to the other guide sections:

- Passing `root` in `render` calls - Detailed in the [Rendering Guide](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#overriding-the-root-key)
- Setting `type` in the serializer - Detailed in the [Serializers Guide](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md#type)

ref: #1486

**Comment by ehannes** [comment]
Great work! Then I think we can consider this issue as resolved, right?

**Comment by groyoh** [comment]
@ehannes yeah, thanks for your input. 👍
