### ISSUE TITLE
ActiveModel::Serializer.setup(&config) not present in 0.10; causes failures in integrated gems

### ISSUE THREAD

**Issue by augustosamame** [rails-api/active_model_serializers#1770]
It seems this issue has been changing back and forth.

Previous versions of AMS can be configured with this block in the initializer:

ActiveModel::Serializer.setup do |config|
 config.adapter == :json_api
end

as opposed to the way indicate in the latest documentation:

ActiveModelSerializers.config.adapter = :json_api # Default: `:attributes`

current version (0.10.0) will fail when using the block with the following error:
undefined method `setup' for ActiveModel::Serializer:Class (NoMethodError)

The change is breaking integrations with other gems (like devise_token_auth see https://github.com/lynndylanhurley/devise_token_auth/issues/644)

Is there a definitive answer to the proper syntax?

**Comment by bf4** [comment]
well, the AMS version 0.8, 0.9, and 0.10 are all incompatible, so I'd argue it's the job of any gem supporting multiple versions to put any necessary conditionals in there.  

If you want the old syntax, you could

```ruby
ActiveModel::Serializer.instance_eval do
  def setup
    yield config
  end
end
```

but I wouldn't implement that since you can just

```ruby
ActiveModelSerializers.config.tap do |c|
  c....
end
```

since `config` is essentially a hash, you could also just `config.merge!`

**Comment by augustosamame** [comment]
Thanks. So in order to fix devise_token_auth I could just check if the ActiveModel::Serializer class responds to setup or config and configure accordingly?

**Comment by bf4** [comment]
@augustosamame are you asking as a maintainer of devise_token_auth or someone who wants to work around its current incompatibility with 0.10.0

**Comment by bf4** [comment]
@augustosamame why not let's discuss this in https://github.com/lynndylanhurley/devise_token_auth/issues/644#issuecomment-223419787 where you're proposing a fix?
