### ISSUE TITLE
Add link to how-to page in the Readme file

### ISSUE THREAD

**Issue by jgamedev** [rails-api/active_model_serializers#1771]
If it had a link to : 
https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/add_pagination_links.md#json-adapter

..in the readme, it would have saved me hours of needless search and banging my head against the wall.

**Comment by NullVoxPopuli** [comment]
The docs to do need to be re-organized a bit

**Comment by jgamedev** [comment]
I actually missed the guides link. Twice :-P

**Comment by remear** [comment]
This should be solved in other ways. This method isn't scalable. We have some documentation changes in the works. Stay tuned.
