### ISSUE TITLE
polymorphic associations don't always follow the same footprint

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1772]
#### Expected behavior vs actual behavior
    class FooSerializer < ActiveModel::Serializer
      attributes :id

      has_one :fizz, polymorphic: true
    end

 EXPECTED OUTPUT:

    {  
       "id":3,
       "fizz":{  
          "type":"buzz",
          "buzz":{  
             "id":3
          }
       }
    }

ACTUAL OUTPUT:

    {  
       "id":3,
       "fizz":{  
          "id":3
       }
    }

#### Steps to reproduce
if Buzz does not have a defined serializer, then it calls as_json and delivers an unexpected format in the polymorphic response.

I think if you say an association is polymorphic, it should always be polymorphic.

**Comment by KevinColemanInc** [comment]
another potential problem with this breaking the polymorphic pattern:

    class Buzz
    end

    class Foo
      has_one :fizz, polymorphic: true
    end

    class FooSerializer
      has_one :fizz, polymorphic: true
    end

ACTUAL OUTPUT:

    buzz = Buzz.create
    foo = Foo.create fizz: buzz

    # if Buzz has no serializer
    ActiveModelSerializers::SerializableResource.new(foo, options).to_json

    {  
       "id":3,
       "fizz":{
          "id": 3,
          "type": "buzz",
          "updated_at": ...
          "created_at": ...
       }
    }

    # if Buzz has a serializer
    class BuzzSerializer;end

    ActiveModelSerializers::SerializableResource.new(foo, options).to_json

    {  
       "id":3,
       "fizz":{
          "type": "buzz",
          "buzz": {
            "id":3
          }
       }
    }

EXPECTED OUTPUT

failed polymorphic serialization (meaning we used the default serializer / to_json) could be mistaken for a successful polymorphic association if the polymorphic object uses single table inheritance

**Comment by bf4** [comment]
I assume this is AMS 0.10.0 with the attributes adapter?

**Comment by cgmckeever** [comment]
@KevinColemanInc .. it appears that (as you said), if no serializer is defined, it bumps out and doesnt include the nesting

https://github.com/cgmckeever/active_model_serializers/blob/bbed12864d96952293f9157ee53f8978bffd8307/lib/active_model_serializers/adapter/attributes.rb#L50

I wonder how when there is no ``relationship_value`` how it derives the response for that relationship?

actually L45 might be the case you are identifying ?

**Comment by beauby** [comment]
This is actually true even for non-polymorphic associations. There was an issue describing this behavior. Long story short, we need to issue a big warning, if not fail, when a serializer cannot be found.

**Comment by KevinColemanInc** [comment]
@bf4 I am still in the process of upgrading to 0.10.0 from 0.9-stable, so maybe this is fixed, although @cgmckeever seems to think this is an issue in 0.10.0.

I lean toward failing or maybe being smarter about generating the type:

    @object.class.to_s.demodulize.underscore.to_sym

**Comment by bf4** [comment]
@KevinColemanInc Please be the hero of everyone else upgrading and turn your notes and lessons learned into a PR here :) :) :)

This definitely an area of AMS that can best be improved by real-world use-case such as yours. Right now I'm thinking the collection serializer should optionally yield control when no serializer is found, that it exits too early

**Comment by KevinColemanInc** [comment]
@bf4 can you give me some guidance on how to add the documentation?  Would this fall under "How to"?

**Comment by kris** [comment]
I believe I'm running into this issue, but it makes little sense, and here's why:

    class Article
        has_many :entities
    end

    class Entity
        belongs_to :entityable, polymorphic: true
    end

    class ArticleSerializer < ActiveModel::Serializer
        has_many :entities
    end

    class EntitySerializer < ActiveModel::Serializer
        has_one :entityable, polymorphic: true
    end

When I do `EntitySerializer.new(Entity.last)` it serializes the entity and association as it should. If I do `ArticleSerializer.new(Article.last)` it serializes, except the entities attribute is returned as `[{}, {}]`, basically, an array of empty hashes. So I'm not sure what the issue is. If I add attributes to the `EntitySerializer`, it will show the attributes, but it won't show the `entityable` association.

**Comment by bf4** [comment]
@KevinColemanInc Just open a PR and we'll guide you :)

**Comment by bf4** [comment]
@kris please open a new issue and provide the context, per the issue template, we need to help us help you
