### ISSUE TITLE
single table inheritance classes cant find serializer

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1773]
#### Expected behavior vs actual behavior

    class ReviewRequestSignupInviteSerializer < SignupInviteSerializer; end

    class ParentFoo;include ActiveModel::SerializerSupport; end
    class ParentFooSerializer; attributes :id; end

    class Foo < ParentFoo; end

Actual Behavior:

    ActiveModelSerializers::SerializableResource.new(ParentFoo.new).to_json # uses ParentFooSerializer
    ActiveModelSerializers::SerializableResource.new(Foo.new).to_json # uses DefaultSerializer / to_json

Expected Behavior:

    ActiveModelSerializers::SerializableResource.new(Foo.new).to_json # uses ParentFooSerializer

#### Additonal helpful information
This is annoying for a few reasons:

1. You have to create a serializer for each of the sub-classes.  Forget to make a serializer for the subclass, then you loose your serialization.
2. You can force the Serializer to be the parent on in the `render` method.  but if you are referencing the single table inheritance in a polymorphic relationship, you either have to override `serializer_for` or create a serializer for each sub-class.
3. This can compound [Issue #1772](https://github.com/rails-api/active_model_serializers/issues/1772).  Because:

    class Buzz
    end

    class Foo
      has_one :fizz, polymorphic: true
    end

    class FooSerializer
      has_one :fizz, polymorphic: true
    end

ACTUAL OUTPUT:

    buzz = Buzz.create
    foo = Foo.create fizz: buzz

    # if Buzz has no serializer
    ActiveModelSerializers::SerializableResource.new(foo, options).to_json

    {  
       "id":3,
       "fizz":{
          "id": 3,
          "type": "buzz",
          "updated_at": ...
          "created_at": ...
       }
    }

    # if Buzz has a serializer
    class BuzzSerializer;end

    ActiveModelSerializers::SerializableResource.new(foo, options).to_json

    {  
       "id":3,
       "fizz":{
          "type": "buzz",
          "buzz": {
            "id":3
          }
       }
    }

EXPECTED OUTPUT

failed polymorphic serialization (meaning we used the default serializer / to_json) could be mistaken for a successful polymorphic association if the polymorphic object uses single table inheritance

**Comment by groyoh** [comment]
@KevinColemanInc which version of AMS do you use? This serializer lookup should lookup parent serializer. Please have a look at https://gist.github.com/groyoh/34356f48dbbbb2a70e1f6a52e19e6351.

**Comment by KevinColemanInc** [comment]
@groyoh I am in the process of moving up to 0.10.0, since I noticed it was released recently.  Thanks for fixing that in the latest version :) 👍
