### ISSUE TITLE
Controllers acting like helpers?

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1775]
#### Expected behavior vs actual behavior
I am not a huge fan of the decision to have the controller code create the pagination information for a given array with the json adapter.

In 0.8.x and 0.9.x, I was able to create a `PaginationSerializer < ActiveModel::ArraySerializer` that would automatically add in the pagination information when used.  It seems that in 0.10.0, the controllers are responsible for creating part of the json rather than the serializers creating the views.

    class PaginationSerializer < ActiveModel::ArraySerializer
      def initialize(object, options = {})
        meta_key = options[:meta_key] || :meta
        options[meta_key] ||= {}
        options[meta_key][:pagination] = {
          current_page: object.current_page,
          next_page: object.next_page,
          prev_page: object.prev_page,
          total_pages: object.total_pages,
          total_count: object.total_count
        }
        super(object, options)
      end
    end

I see that the json_api adapter is smart enough to do automatic pagination, but I can't use that because it doesn't match the existing api design I created in 0.8.x.

Thoughts?

**Comment by groyoh** [comment]
I strongly believe that the pagination is definitely not a serializer concern but more an adapter concern. I can understand that this may confuse you though as there was no concept of adapter in 0.8.

What I would suggest in your case would be to build your own adapter that would mimic what you expect:

```ruby
class PaginatedJsonAdapter < ActiveModelSerializer::Adapter::Json
  def meta
    return unless serializer.respond_to?(:each)
    object = serializer.object
    {
      pagination: {
        current_page: object.current_page,
        next_page: object.next_page,
        prev_page: object.prev_page,
        total_pages: object.total_pages,
        total_count: object.total_count
      }
    }
  end
end
```

**Comment by KevinColemanInc** [comment]
@groyoh yeah I am looking at creating my own adapter, but its not really behaving the in a way that makes sense to me.

It is my understanding that serializers are meant to take in an object and to generate JSON for that object.  I liked there is a (class)[https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/adapter/json_api/pagination_links.rb] for creating the pagination for the `json_api` but I am a little confused why I can't use a serializer to create the pagination information.

I was thinking something like

    def pagination_attributes
      PaginationSerializer.new(serializer.object).as_json
    end

where the object would be a paginated collection.  The serializer would specify the `current_page`, `last_page`, etc. attributes and the adapter would take those results.

**Comment by KevinColemanInc** [comment]
@cgmckeever yeah, the slicing would be done by the Kaminari upstream.  but my goal is to go from a model that has methods like `current_page`, `next_page`, `prev_page`, etc. to json using a serializer.
