### ISSUE TITLE
module classes

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1780]
#### Expected behavior vs actual behavior
I have a class `Review::Current` and its serializer `CurrentSerializer`  if I do:
    
    render json: current, serializer: CurrentSerializer

    # out {"review/current":{"status":null}}

Is that root expected behavior? I would think the root would just be "current"

**Comment by NullVoxPopuli** [comment]
that happens, because `current.class.name.underscore == 'review/current'` 

namespaces are prepended with /'s

**Comment by KevinColemanInc** [comment]
@NullVoxPopuli I think I understand why. but maybe it should be `.class.name.demodulize.underscore`

**Comment by NullVoxPopuli** [comment]
the root is customizable per-serializer, so you could set that, if you wanted.

see
https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md#type
and

https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md#root

**Comment by KevinColemanInc** [comment]
@NullVoxPopuli I haven't tested this with the json_api adapter, but I think this would be affected by the issue,  but according to this documentation the "/" is not a valid character for a member name.

http://jsonapi.org/format/#document-member-names-reserved-characters

**Comment by NullVoxPopuli** [comment]
yeah. Ember doesn't even support namespaced models -- so most people flatten them out and have to specify the `type` for their serializers. (This is what I do on my project: https://github.com/NullVoxPopuli/aeonvera/)

**Comment by KevinColemanInc** [comment]
so why don't you at least demodulize the member name so you can at least sorta follow the format?

**Comment by NullVoxPopuli** [comment]
because some people may want the namespace information and handle it differently. 

A common way to handle namespaces is a double dash.

Then on their client, they can do whatever with them.

**Comment by KevinColemanInc** [comment]
so what you're saying is the current implementation does not follow either the advertised jsonapi.org format or the "common way" of double dash?

**Comment by NullVoxPopuli** [comment]
yeah, the reason is to let the users decide how they want to handle it.

**Comment by KevinColemanInc** [comment]
Since the `json_api` does not follow the jsonapi.org, do you think that comment should be amended in the documentation?

**Comment by NullVoxPopuli** [comment]
perhaps. Though, what it really should say is that its recommended to use the 'type' setting
