### ISSUE TITLE
Thank you!!!!!

### ISSUE THREAD

**Issue by randallb** [rails-api/active_model_serializers#1784]
#### Expected behavior vs actual behavior

I should have to do work. I don't have to do as much work.

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

Install gem
Rejoice.

#### Environment

Joy

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

Thank you so much for this project. Today I upgraded from the RC to the 0.10 version and most (all?) issues that bugged me are gone / my life is simpler.

Thank you for this project! I haven't contributed anything yet but I thought I could at least contribute a thanks. 😄 ❤️

**Comment by NullVoxPopuli** [comment]
lol. thanks for the issue. Made me smile :-)
