### ISSUE TITLE
Serializing non-AR classes

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1789]
With the change to go from a mixin to parent class, I am finding I need to do something like this for my non-AR classes, because my non-AR class uses the initializer method.

    class Person < ActiveModelSerializers::Model
      attr_accessor :full_name, :email, :user

      ATTRIBUTES = %i(full_name email user)

      def initialize(obj)
        case obj
        when User
          from_user(obj)
        when Admin
          from_admin(obj)
        end
        super(Hash[ATTRIBUTES.map { |a| [a, send(a)] }])
      end

      def from_user(user)
        @user = user
        @email = user.email
        @full_name = user.profile.full_name
      end

      def from_admin(admin)
        @full_name = admin.best_name
        @email = admin.email
        @user = admin.user
      end
    end

Does this look like something that should go in the guides? or have suggestions to make cleaner?

version 0.10.0

**Comment by bf4** [comment]
You're not required to use AMS::Model, it's just usable documentation of what's required for a PORO...

**Comment by bf4** [comment]
Please let me know if this resolves your issue. If you think the docs or code could be improved with what you've learned, a PR would be most welcome.

**Comment by KevinColemanInc** [comment]
@bf4 ok! cool.  I miss the flexibility the mixin provided over the i AMS::Model.  I will look at creating my own.

**Comment by bf4** [comment]
>  I miss the flexibility the mixin provided over the i AMS::Model.

Maybe you can make a PR to make it more clear that AMS::Model is a convenience, you can see it for the mixins it uses AND/OR look at the serializer lint for required methods
