### ISSUE TITLE
calculated fields on non-AR models

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1790]
##### Actual
    # Powers the deprecated bubble chart.
    # Will be deprecated later by SkillScores
    class ScoredUser < ActiveModelSerializers::Model
      def score
        User.count
      end
    end

    class ScoredUserSerializer < ActiveModel::Serializer  
      attributes :score
    end

    scored_user = ScoredUser.new

    ActiveModelSerializers::SerializableResource.new(scored_user).to_json
      Rendered ScoredSkilleSerializer with ActiveModelSerializers::Adapter::PaginatedJson (0.8ms)
      => "{\"scored_user\":{\"score\":null}}"

    scored_user.score
       (0.4ms)  SELECT COUNT(*) FROM `users`
        => 29

So it only seems to render values that are passed in via the initializer.  It doesn't run the method in the object.  But if you do this:

    class ScoredUserSerializer < ActiveModel::Serializer  
      attributes :score

      def score
        @object.score
      end
    end

    ActiveModelSerializers::SerializableResource.new(scored_user).to_json
      (0.4ms)  SELECT COUNT(*) FROM `users`
      Rendered ScoredUserSerializer with ActiveModelSerializers::Adapter::PaginatedJson (1.94ms)
      => "{\"scored_user\":{\"score\":29}}"

It renders the score properly.  This behavior is unexpected, because AR models behave differently when serializing non-attributes.

    class User < ActiveRecord::Base
      def score
        User.count
      end
    end

    class ScoredUserNoMethodSerializer < ActiveModel::Serializer  
      attributes :score
    end

    scored_user = User.new
    ActiveModelSerializers::SerializableResource.new(scored_user, serializer: ScoredUserNoMethodSerializer).to_json
         (0.3ms)  SELECT COUNT(*) FROM `users`
      Rendered ScoredUserNoMethodSerializer with ActiveModelSerializers::Adapter::PaginatedJson (4.66ms)
      => "{\"user\":{\"score\":29}}"

#### Environment
0.10.0

I think this is related to https://github.com/rails-api/active_model_serializers/issues/1789

**Comment by bf4** [comment]
See my answer in https://github.com/rails-api/active_model_serializers/issues/1789#issuecomment-224720151 This is effectively a duplicate. You'll need to look at the source of AMS::Model
