### ISSUE TITLE
reserved characters in `json_api` adapter

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1793]
#### Expected behavior vs actual behavior

version 0.8.x removed reserved characters, but 0.10.0 does not seem to follow the guidelines laid out by [jsonapi.org](http://jsonapi.org/format/#document-member-names).

I think the documentation should stop claiming to follow the jsonapi.org or prevent reserved characters from being rendered.

two examples I have found so far:
##### Question marks are against spec.

Actual
`attributes :is_a_admin?`
   `{ "is_a_admin?": true }`

Expected
version 0.8.x would drop the "?" from the name.
##### Slashes in member names

Actual
if the class is Review::Current, 0.10.0 will render the root key by default to 'review/current'.

Expected
@NullVoxPopuli suggested the correct way to handle modularized class names would be to say `review--current`

**Comment by bf4** [comment]
> if the class is Review::Current, 0.10.0 will render the root key by default to 'review/current'.

fwiw, EmberData's JSON API does this too. Been a bug I've been meaning to go and fix.

> I think the documentation should stop claiming to follow the jsonapi.org or prevent reserved characters from being rendered.

PR's welcome

**Comment by remear** [comment]
#1563 and #662 already touched on this and the options presented seemed to be acceptable to those participating. If you have any new insight to add to those conversations, I'm open to hearing it here.

**Comment by leoskyrocker** [comment]
I think those issues weren't related to conforming to JSON API tho, so this still seems to be a valid issue?

**Comment by KevinColemanInc** [comment]
@bf4 / @leoskyrocker 

I see there is some consensus about how to fix the "?", but I don't see a solution for polymorphic attribute names.

Is there a PR for resolving the "/" issue?
