### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by KevinColemanInc** [rails-api/active_model_serializers#1796]
#### Expected behavior vs actual behavior
`render json: [nil]` causes `undefined method 'each' for nil:NilClass` when this is called `Attributes.new(serializer, instance_options).serializable_hash(options)` in the adapter.

maybe it should just do `[]` or `[null]`?

version: 0.10.0

**Comment by bf4** [comment]
`[nil]` doesn't make any sense to me as a value you'd want to render

**Comment by bf4** [comment]
but just call `[nil].to_json` if that's really what you want
