### ISSUE TITLE
Not working with api version system 

### ISSUE THREAD

**Issue by aditya01933** [rails-api/active_model_serializers#1822]
I am not sure if it's an issue with gem or I am following wrong steps. 

According to doc of 0.10 :
When serializing a model inside a namespace, such as Api::V1::Post, ActiveModelSerializers will expect the corresponding serializer to be inside the same namespace (namely Api::V1::PostSerializer)

I followed the same step but it's not working. Please check if it's a bug. 
My active model serializer version is 0.10.0, ruby '2.3.0', 'rails', '4.2.6'. I am using rails_api gem.

I have api with version system. 

My controller

        module Api;module V1
        	class PlansController < ApplicationController        
        	  def show
        		@plan = Plan.find(params[:id])
        		render json: @plan
        	  end 
            end
        end;end
I have folder serializers/api/v1 where i have plan_serializer.rb

    module Api;module V1
    	class PlanSerializer < ActiveModel::Serializer
    	  attributes :name, :amount, :days
    	end
    end;end	
	
But its not serializing json response automatically. 
Please tell me what wrong am I doing ?

I also tried adding 

    class ApplicationController < ActionController::API
      include ActionController::Serialization

but still its not working. Its not generating any error but It's showing normal json response without serialization of data.

If I am doing 

    render json: @plan, serializer: V1::PlanSerializer 

then it is working but I want it to work without adding serializer in every render.

Please tell me solution.

http://stackoverflow.com/questions/38085189/active-model-serialization-not-working-with-api-versioning

**Comment by NullVoxPopuli** [comment]
do you have a repo set up? 
can you answer the questions in the New issue template? https://github.com/rails-api/active_model_serializers/issues/new

thanks!! :-)

**Comment by NullVoxPopuli** [comment]
can you add your (unexpected) output?

**Comment by aditya01933** [comment]
Its not generating any error. It's showing normal json response without serialization of data.

**Comment by bf4** [comment]
What's a normal JSON response?

Namespace lookup isn't perfect.  Nothing wrong with passing in the serializer to render.

**Comment by aditya01933** [comment]
I have changed it to class Api::V1::PlanSerializer < ActiveModel::Serializer and its working. :)
