### ISSUE TITLE
How do I change the default pagination params?

### ISSUE THREAD

**Issue by ekampp** [rails-api/active_model_serializers#1823]
#### Expected behavior vs actual behavior

[JSON API states](http://jsonapi.org/format/#fetching-pagination) that "[...]  For example, a page-based strategy might use query parameters such as page[number] and page[size] [...]"

So I would expect some way of configuring this. I cannot find that place. Am I missing something, or is this just not a config option? 

#### Steps to reproduce

N/A

#### Environment

AMS 0.10.1
Rails 5.1 (master branch)

#### Backtrace

N/A

#### Additonal helpful information

Nil

**Comment by bf4** [comment]
There's a couple of ways, but basically you probably want to look at https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/add_pagination_links.md#how-to-add-pagination-links and report back here if that resolves your question or any followup questions

**Comment by ekampp** [comment]
I have looked there. It doesn't supply any immediate option for changing the resulting JSON from `page[number]` to e.g. `page`, and `page[size]` to `per_page`. 

As quoted the JSON API standard doesn't have any preference. So I would like to move away from the `page` hash and into a more simple, flat pagination parameter structure in my project. I would have expected this to be both possible and simple. This doesn't seem to be the case.

**Comment by bf4** [comment]
Maybe take a look at https://github.com/rails-api/active_model_serializers/issues/1549#issuecomment-191568335 and https://github.com/rails-api/active_model_serializers/pull/1596#issuecomment-202103599 ?

**Comment by ekampp** [comment]
Both of those relates to disabling pagination. I'm not interested in that. I'm interested in hot to configuring the `page[number]` to just `page`, and the `page[size]` to `per_page`.

**Comment by bf4** [comment]
@ekampp yeah, you need to disable the convention and then write it yourself.  I'm not sure what you were expecting.

**Comment by bf4** [comment]
@ekampp If you want to modify the PaginationLinks builder in a PR so that it can be customized, you are welcome to, but we already let you build what you want.

**Comment by ekampp** [comment]
Since the standard specifically states it's agnostic I did expect a configurable option for the names. But I'll figure it some other way, then.

**Comment by ekampp** [comment]
@bf4 Thanks for your help. 👍

**Comment by bf4** [comment]
@ekampp Yeah, we generally implement the recommendations when possible, but not require them. In some cases, such as this, we weren't as careful in making it easy to opt out of the recommended pagination

**Comment by saneshark** [comment]
Just added this to my initializer and it seemed to solve the problem.

```ruby
# This is a monkey patch of the pagination links for JSON Api adapter of AMS
module CustomPaginationLinks
  def as_json
    per_page = collection.try(:per_page) || collection.try(:limit_value) || collection.size
    pages_from.each_with_object({}) do |(key, value), hash|
      params = query_parameters.merge(page: value, per_page: per_page).to_query

      hash[key] = "#{url(adapter_options)}?#{params}"
    end
  end
end

# Prepend the method, so that it overrides the default one.
ActiveModelSerializers::Adapter::JsonApi::PaginationLinks.prepend CustomPaginationLinks
ActiveModelSerializers.config.adapter = :json_api
```

**Comment by richmolj** [comment]
@ekampp @saneshark on master, you can now do:

```ruby
ActiveModelSerializers.config.jsonapi_pagination_links_enabled = false
```
