### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [rails-api/active_model_serializers#1831]
Do you follow Semantic Versioning http://semver.org? If yes, can this be mentioned in README? If not, can you consider it?

**Comment by bf4** [comment]
We do use semantic versioning. I'd welcome a PR to add it to the readme.

**Comment by pravi** [comment]
@bf4 are you planning for a 1.0 release soon?

**Comment by bf4** [comment]
When we have a 1.0 we'll release it.
