### ISSUE TITLE
Testing JSON API

### ISSUE THREAD

**Issue by bdmac** [rails-api/active_model_serializers#1842]
Warning: I believe this issue is only tangentially related to AMS but is related to JSON API testing in general.
#### Expected behavior vs actual behavior

I am trying to upgrade an app to Rails 5 / AMS 0.10.2 and I am using `register_jsonapi_renderer` to register the JSON API mime type and parser with Rails. This works great for inbound data but I'm seeing some annoying behavior in Rails' `ActionController::TestRequest`.

This class (defined in https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb) has a method called `assign_parameters` which attempts to mock what a real request would have looked like when given some params. It is eventually called by all of the various test helpers (e.g. `post :create, params: { json_api_params_here }`).

Cool, except it looks directly at the `content_mime_type` to determine what to do and does not know how to handle the :jsonapi mime type (which is registered after requiring `register_jsonapi_renderer`). Since there's no handler it winds up basically just calling `params.to_query` here: https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L109. This would be fine except if for whatever reason you are testing with an empty array as a value in a hash since `to_query` still nukes that (e.g. `{foo: []}.to_query => ""`).

I don't really see any supported way to add additional **encoding** support for jsonapi testing like we do for jsonapi **parsing**. If I modify that method to treat :jsonapi the same as :json (e.g. call `ActiveSupport::JSON.encode` on it) then my tests work again.

Does anyone know how to add an encoder for testing JSON API parameters and if so, should `register_jsonapi_renderer` also handle that?

**Comment by bf4** [comment]
@bdmac would you mind adding which AMS version you're on and what's in your initializer, or wherever you are configuring AMS?

**Comment by bdmac** [comment]
Sure, here's the initializer I wound up with: https://gist.github.com/bdmac/e75870b162e1b842af3de46bc2bbc1db
