### ISSUE TITLE
Serializing a Plain-Old Ruby Object (PORO) via Inherited ActiveModelSerializers::Model fails

### ISSUE THREAD

**Issue by browrp** [rails-api/active_model_serializers#1854]
### Expected
In Rails, when using a Plain Old Ruby Object (PORO) with Active Model Serializers and inheriting from the **_ActiveModelSerializers::Model_** class as defined in the guides on page https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/serialize_poro.md, I expected the PORO to serialize to JSON.  

```
class Project < ActiveModelSerializers::Model

    def initialize
       project_sponsors = Array.new
    end

  attr_accessor :uuid_key, :project_name
  attr_accessor :project_sponsors

end
```

```
class ProjectSponsor < ActiveModelSerializers::Model
  attr_accessor :uuid_key, :first_name, :last_name
end
```

```
    render :status => 200,
           :json => { :success => true,
                      :info => "Project Sponsor Overview",
                      :data => { :project_list => @x}}

```

I expect to see:

```
{
	"success": true,
	"info": "Project Sponsor Overview",
	"data": {
		"project_list": [
			{
				"uuid_key": "afde-90-zxy",
				"project_name": "The X Files",
				"project_sponsors": [
					{
						"uuid_key": "a1a-x24",
						"first_name": "Mary",
						"last_name": "Smith"
					},
					{
						"uuid_key": "b1b-z39",
						"first_name": "Tom",
						"last_name": "Jones"
					}
				]
			},
			{
				"uuid_key": "bkij-11-bb",
				"project_name": "Sleepy Hollow",
				"project_sponsors": [
					{
						"uuid_key": "hhi1-h23",
						"first_name": "Henry",
						"last_name": "McNeal"
					},
					{
						"uuid_key": "iixf-i09",
						"first_name": "Icabob",
						"last_name": "Crane"
					}
				]
			}
		]
	}
}

```

### Actual
What I get is the following error:
```
NoMethodError in ProjectOverviewController#index
undefined method `keys' for nil:NilClass

```
I found that the Project's class' initializer is causing this error.  When I remove it the error stops but the JSON is returned is empty; none of the attributes are serialized:

```
{
	"success": true,
	"info": "Project Sponsor Overview",
	"data": {
		"project_list": [
			{
			},
			{
			}
		]
	}
}
```

However, when I follow alternate approach as described in the guide...
```
# my_model.rb
class MyModel
  alias :read_attribute_for_serialization :send
  attr_accessor :id, :name, :level

  def initialize(attributes)
    @id = attributes[:id]
    @name = attributes[:name]
    @level = attributes[:level]
  end

  def self.model_name
    @_model_name ||= ActiveModel::Name.new(self)
  end
end
```

...the expected JSON is returned, however,  **_ActiveModelSerializers.config.key_transform = :camel_lower_** doesn't seem to be working...

### Steps to reproduce
Sample Rails application to reproduce this issue can be found at: https://github.com/browrp/ProjectTrack

### Environment
ActiveModelSerializers Version *0.10*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.2.3p102 (2015-05-15 revision 50493) [x86_64-darwin14]

OS Type & Version: 
OS X El Capitan 
Version 10.11.5
Rails 4.2.6

**Comment by bf4** [comment]
The problem is you're clobbering the initialize method with

```
    def initialize
       project_sponsors = Array.new
    end
```

**Comment by browrp** [comment]
@bf4 I get that, however, when the initializer is removed 

```
class Project < ActiveModelSerializers::Model

  attr_accessor :uuid_key, :project_name
  attr_accessor :project_sponsors

end
```

All the attributes that are serialized to JSON are empty with this result:

`{"success":true,"info":"Project Sponsor Overview","data":{"project_list":[{},{}]}}`

There are 2 items in the array that are being returned however everything is empty...  I've updated my repo with changes to replicate this...  Should I re-open this issue or am I missing something that will make this work?

**Comment by bf4** [comment]
Sure, re-open it. Can you include a short snippet initializing and rendering it?

e.g.


```ruby
class Project < ActiveModelSerializers::Model
  attr_accessor :uuid_key, :project_name, :project_sponsors
end
class ProjectSerializer < ApplicationSerializer
  attributes  :uuid_key, :project_name, :project_sponsors
end
project = Project.new(.....)
render json: project, ....
# => result 
```

**Comment by bf4** [comment]
@browrp  So, this is a side point, but is anyone working with you on this code? It has a lot of concerning features.

```diff
class Project < ActiveModelSerializers::Model
-  attr_accessor :uuid_key, :project_name
-  attr_accessor :project_sponsors
+  attr_accessor :uuid_key, :project_name, :project_sponsors
end
```

and really `s/uuid_key/uui`

and

```diff
class ProjectSerializer <  ActiveModel::Serializer
-  attributes :uuid_key, :project_name, :project_sponsors
+  attributes :uuid_key, :project_name
  has_many :project_sponsors
end
```

```diff
-  @x = Array.new
-
-  proj_a = Project.new
-  proj_a.uuid_key ="afde-90-zxy"
-  proj_a.project_name = "The X Files"
-  proj_a.project_sponsors = Array.new
-
-  b = ProjectSponsor.new
-  b.uuid_key = "a1a-x24"
-  b.first_name = "Mary"
-  b.last_name = "Smith"
-  proj_a.project_sponsors.push b
-
-  c = ProjectSponsor.new
-  c.uuid_key = 'b1b-z39'
-  c.first_name = "Tom"
-  c.last_name = "Jones"
-  proj_a.project_sponsors.push c
-
-  @x.push proj_a
-
-
-  proj_b = Project.new
-  proj_b.uuid_key ="bkij-11-bb"
-  proj_b.project_name = "Sleepy Hollow"
-  proj_b.project_sponsors = Array.new
-
-  h = ProjectSponsor.new
-  h.uuid_key = "hhi1-h23"
-  h.first_name = "Henry"
-  h.last_name = "McNeal"
-  proj_b.project_sponsors.push h
-
-
-  i = ProjectSponsor.new
-  i.uuid_key = "iixf-i09"
-  i.first_name = "Icabob"
-  i.last_name = "Crane"
-  proj_b.project_sponsors.push i
-
-  @x.push proj_b
+  sponsored_projects = [
+    Project.new(
+      uuid_key: "afde-90-zxy",
+      project_name: "The X Files",
+      project_sponsors: [
+        ProjectSponsor.new(
+          uuid_key: "a1a-x24",
+          first_name: "Mary",
+          last_name: "Smith"
+        ),
+        ProjectSponsor.new(
+          uuid_key: 'b1b-z39',
+          first_name: "Tom",
+          last_name: "Jones"
+        )
+      ]
+    ),
+    Project.new(
+      uuid_key: "bkij-11-bb",
+      project_name: "Sleepy Hollow",
+      project_sponsors: [
+        ProjectSponsor.new(
+          uuid_key: "hhi1-h23",
+          first_name: "Henry",
+          last_name: "McNeal"
+        ),
+        ProjectSponsor.new(
+          uuid_key: "iixf-i09",
+          first_name: "Icabob",
+          last_name: "Crane"
+        )
+      ]
+    )
+  ]
```

and you either need a custom adapter or do something like the below.  AMS doesn't inspect your json for something it knows how to serialize. Either it does, or it doesn't.

```diff
- render :status => 200,
           :json => { :success => true,
                      :info => "Project Sponsor Overview",
                      :data => { :project_list => @x}}
+ json = ActiveModelSerializers::SerializableResource.new(sponsored_projects).as_json
+ render_options[:status] = 200
+ render_options[:json] = { success: true, info: "Project Sponsor Overview", data: { project_list: json } }
+ render render_options
```

I took some amount of time to write this up. I hope it is helpful.

**Comment by browrp** [comment]
@bf4 The code up here was a test project I threw together in 15 minutes to illustrate the issue that I was having, that is why the code to build the object model looks the way it does. Was there something specific that was concerning to you?  

I'm new to using AMS (was using Jbuilder before) and I was following the documentation in respect to POROs https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/serialize_poro.md  The only mention of the Serializer in the docs is, "_The default serializer would be MyModelSerializer._"  It didn't mention creating a custom adapter or creating a new SerializableResource as you did above...

**Comment by bf4** [comment]
@browrp 

>The only mention of the Serializer in the docs is, "The default serializer would be MyModelSerializer." It didn't mention creating a custom adapter or creating a new SerializableResource as you did above...

I admit the docs could be better, and ask for your help in improving them :)

Both those concerns are very much addressed in the docs.

- https://github.com/rails-api/active_model_serializers/#high-level-behavior
- https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md
- https://github.com/rails-api/active_model_serializers/blob/master/docs/ARCHITECTURE.md

If you can find an example in the docs that suggests AMS crawls arbitrary JSON hashes (such as in the above example) looking for resources please let me know so we can remove it.

**Comment by browrp** [comment]
@bf4 Will do, although I'm still rather new to Rails so the best contribution I could do at this time is towards the documentation.  Thanks for your help with my issue and putting all the pieces such as the SerializableResource into context for me.

**Comment by bf4** [comment]
@browrp Sure.  I'm just guessing, but I think a doc PR that added some cross-references would be helpful to future readers :)
