### ISSUE TITLE
Cannot initialize an activemodel serializer with user options

### ISSUE THREAD

**Issue by sxjoel** [rails-api/active_model_serializers#1859]
#### Expected behavior vs actual behavior
I would like to run some calculation based on serializer options (passed from the controller), and have it available to all serializer methods as an instance variable . It made sense in my eyes to do this in the initializer:

```ruby
class Admin::UserStatsSerializer < ActiveModel::Serializer 
 attributes ... 
 def initialize(a, **options)
   @my_calculation = options[:serializable_options][:some_value]
 end
```

however the constructor has no access to `serializable_options` so this won't work.  The only way I could get something similar is by using the filter method , but it feels like that's the wrong place to do that. 

Am I simply doing it wrong ?

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*:  0.9.3

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

OS Type & Version: 

Integrated application and version *(e.g., Rails, Grape, etc)*: 

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by bf4** [comment]
Hi, thanks for this.  Perhaps serialization scope will meet your needs? Without myself going and reading the source code, I don't know.

**Comment by bf4** [comment]
Closing as stale
