### ISSUE TITLE
Related links being sent over http instead of https

### ISSUE THREAD

**Issue by djsegal** [rails-api/active_model_serializers#1862]
#### Expected behavior vs actual behavior

I have `force_ssl` on, so I want my related links to have `https://` instead of `http://`

#### Steps to reproduce

+ Start project with rails.
+ Add `config.force_ssl = true`
+ Create user resource with nested comments
+ Add user serializer with:

```
  has_many :comments do
    link :related do
      user_comments_url(user_id: object.id)
    end
    include_data false
  end
```

+ Related links will only have **`http`**

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: `v0.10.2`

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`

OS Type & Version: `OS X v10.11.5`

Integrated application and version *(e.g., Rails, Grape, etc)*: `Rails`

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

On Ember app, I get this javascript error:

`Mixed Content: The page at 'https://test.com/users/1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.test.com/users/1/comments'. This request has been blocked; the content must be served over HTTPS.`

**Comment by bf4** [comment]
@djsegal Good catch for the documentation. The links are generated by Rails url helpers, which are just [included](https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/active_model_serializers/serialization_context.rb#L5) in the [Link](https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/active_model_serializers/adapter/json_api/link.rb#L42)) object

This most likely is a missing Rails config, but just to make sure:

What's the value of `SerializationContext.url_helpers` and `SerializationContext.default_url_options`?

They should be the same as `Rails.application.routes.url_helpers` and `Rails.application.routes.default_url_options` unless the [Railtie](https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/active_model_serializers/railtie.rb#L18-L21) is broken somehow.

`Rails.application.routes.default_url_options[:protocol]` should be `https`. See https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/url_for.rb#L118

**Comment by djsegal** [comment]
Sorry I don't have SSL working locally, but after macgyvering an error response in production, I got the following results: 

| command        | result           | 
| ------------- |:-------------:| 
| ActiveModelSerializers::SerializationContext.default_url_options     | {:host=>"api.ahab.io"}       | 
| Rails.application.routes.default_url_options  | {:host=>"api.ahab.io"}       | 
| ActiveModelSerializers::SerializationContext.url_helpers.methods - Rails.application.routes.url_helpers.methods     | [] |
| Rails.application.routes.url_helpers.methods - ActiveModelSerializers::SerializationContext.url_helpers.methods | []     |  

*p.s. `___blank___.url_helpers` is a module so i just checked the difference between the two modules helper arrays:*

**Comment by bf4** [comment]
@djsegal I don't think `ActiveModelSerializers::SerializationContext.url_helpers.methods - Rails.application.routes.url_helpers.methods` is what you're looking for.  See the action dispatch link I pasted above. Most of these methods are dynamic, so, in terms of equality, checking `object_id` would be more appropriate, or checking for `url_for`, I guess.  (Maybe try `public_methods` instead of `methods`).

In any case, unless you can show they are different, i.e. the bug is in AMS setting them up, the bug is in your Rails routing config :)

**Comment by djsegal** [comment]
@bf4, you're correct. closing the issue.

-----------------

for future reference:

to solve the problem, I added the following `initializer`:

```
# ./config/initializers/force_ssl.rb
if Rails.application.config.force_ssl
  Rails.application.routes.default_url_options[:protocol] = 'https'
end
```

**Comment by bf4** [comment]
@djsegal so much ❤️ ✨ for coming back and sharing your resolution! Do you think we should add this to the documentation?
