### ISSUE TITLE
0.9.x meta_key has to be a symbol and will not work for a string

### ISSUE THREAD

**Issue by vinodlala** [rails-api/active_model_serializers#1868]
For `meta_key`, use a symbol instead of a string.

The docs on http://www.rubydoc.info/gems/active_model_serializers/0.9.5 has this:

```
render json: @posts, serializer: CustomArraySerializer, meta_object: {total: 10}, meta_key: 'meta_object'
```

But that doesn't work.

This will work:

```
render json: @posts, serializer: CustomArraySerializer, meta_object: {total: 10}, meta_key: :meta_object
```

In `lib/active_model/serializer.rb`, check out the `initialize` method:

```
      @meta_key      = options[:meta_key] || :meta
      @meta          = options[@meta_key]
```

If `options[:meta_key]` is `nil`, `@meta_key` is `:meta` (a symbol, not a string).

Using the example in the docs, if `options[:meta_key]` is a string like `'meta_object'`, `@meta_key` is `'meta_object'` (a string, not a symbol).  

However, `options['meta_object']` does not exist. Only `options[:meta_object]` exists.

If `options[:meta_key]` is a symbol like `:meta_object`, `@meta_key` is `:meta_object`, which works.

**Comment by bf4** [comment]
Thanks @vinodlala would you mind making a PR (against the 0-9-stable branch) to fix the docs? Would be much appreciated.

**Comment by vinodlala** [comment]
Done - https://github.com/rails-api/active_model_serializers/pull/1869
