### ISSUE TITLE
Bug when starting application with Pow

### ISSUE THREAD

**Issue by dsnipe** [rails-api/active_model_serializers#187]
I'm using Pow as my dev server.  
When I add active_model_serializers to my app, I'm get error _ArgumentError: invalid byte sequence in US-ASCII_ when Pow trying to start application.
Rails 3.2.11
Pow 0.4.0
active_model_serializers from github
![Screen Shot 2013-01-14 at 1 36 21 PM](https://f.cloud.github.com/assets/1488587/64547/6da6a10e-5e4f-11e2-9b37-aa6aa2e744c2.png)

**Comment by appstersjulia** [comment]
For anyone still struggling with this (and only experiencing it with Pow, not `rails s`):
Add the following to  `~/.powconfig`:
```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
Then
`touch ~/.pow/restart.txt`

**Comment by bf4** [comment]
@appstersjulia Unless you have a good reason to use Pow (sorry to everyone from 2013), [puma-dev](https://github.com/puma/puma-dev) is much better
