### ISSUE TITLE
wrong number of arguments "attributes"

### ISSUE THREAD

**Issue by ivanstojkovicapps** [rails-api/active_model_serializers#1870]
Hi,

i am using the latest version 0.10.2 and i am getting this stacktrace:

> 2016-08-03 17:59:51.488 [ivanat1][INFO] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (0.35ms)
> 2016-08-03 17:59:51.488 [ivanat1][INFO] Completed 500 Internal Server Error in 64ms (ActiveRecord: 7.3ms)
> 2016-08-03 17:59:51.492 [ivanat1][FATAL][middleware.rb:123] 
> ArgumentError - wrong number of arguments (given 2, expected 0):
>   activerecord (4.2.1) lib/active_record/attribute_methods.rb:283:in `attributes'
>    () Users/ivanstojkovic/iPhone/TimeTrack_Enterprise/TTSyncBackend/app/serializers/time_entry_serializer.rb:2:in `attributes'
>   active_model_serializers (0.10.2) lib/active_model/serializer/caching.rb:216:in `fetch_attributes'
>   active_model_serializers (0.10.2) lib/active_model/serializer.rb:169:in `serializable_hash'
>   active_model_serializers (0.10.2) lib/active_model/serializer/collection_serializer.rb:27:in `block in serializable_hash'
>   active_model_serializers (0.10.2) lib/active_model/serializer/collection_serializer.rb:26:in `map'
>   active_model_serializers (0.10.2) lib/active_model/serializer/collection_serializer.rb:26:in `serializable_hash'
>   active_model_serializers (0.10.2) lib/active_model_serializers/adapter/attributes.rb:7:in `serializable_hash'
>   active_model_serializers (0.10.2) lib/active_model_serializers/adapter/base.rb:59:in `as_json'
>   activesupport (4.2.1) lib/active_support/json/encoding.rb:34:in `encode'
>   activesupport (4.2.1) lib/active_support/json/encoding.rb:21:in `encode'
>   activesupport (4.2.1) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
>   active_model_serializers (0.10.2) lib/active_model_serializers/serializable_resource.rb:8:in `to_json'
>   active_model_serializers (0.10.2) lib/active_model_serializers/logging.rb:69:in `block (3 levels) in notify'
>   activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
>   activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
>   activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
>   activesupport (4.2.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
>   activesupport (4.2.1) lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'

if i switch to 0.9.5 it works great

Rails 4.2.1

> class MySerializer < ActiveModel::Serializer
>   delegate :attributes, to: :object
> end

My model.rb has 

> def attributes
>     super.merge('project' => self.project)
>     super.merge('photoID' => self.photoID)
>     super.merge('color' => self.color)
>   end

but anyway if i comment this out i get the same problem

best regards Ivan

**Comment by bf4** [comment]
Why would you delegate `attributes` to `object`?  That's one of the most important and fundamental methods in AMS.  If you're going to do that, though, you should follow the same method signature as in AMS.  That's up to you, in userland, to hack yourself when monkey patching fundamental parts of a gem.  I'm closing, though I welcome you to bring up your use-case if you think it would be useful for AMS to consider.
