### ISSUE TITLE
AMS transforming key names replacing '_' with '-'

### ISSUE THREAD

**Issue by betasve** [rails-api/active_model_serializers#1871]
#### Expected behavior vs actual behavior

I'm using 
```
ActiveModelSerializers::Adapter::JsonApi.new(
  DeskSerializer.new(valid_desk)
).as_json
```
to generate a request object that I'm using in my RSpec tests (avoiding to write down the entire structure by hand. 

#### Steps to reproduce

The Desk class has attributes like: 
```
id, language_code, created_at, updated_at
```

When using the above method `as_json` on the instantiated object it generates: 
```
{
  "data": {
    "id": "6",
    "type": "desks",
    "attributes": {
      "language-code": "DD",
      "created-at": "2016-08-03T16:54:14.748Z",
      "updated-at": "2016-08-03T16:54:14.748Z"
    }
  }
}
```
instead of: 
```
{
  "data": {
    "id": "6",
    "type": "desks",
    "attributes": {
      "language_code": "DD",
      "created_at": "2016-08-03T16:54:14.748Z",
      "updated_at": "2016-08-03T16:54:14.748Z"
    }
  }
}
```
but I need `language_code` instead of `language-code` to be able to pass as a request parameter in my test. 

I can't find an option in the documentation that stops such a "sanitization" of the attributes names. 
Could somebody please help with some information if that's currently possible and if so, what's the proper param in the constructor. 

Thanks in advance.

**Comment by NullVoxPopuli** [comment]
the docs you're looking for are here: https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#key_transform

**Comment by bf4** [comment]
Closing. Please confirm the config you want is

```ruby
ActiveModelSerializers.config.key_transform = :unaltered
```

**Comment by betasve** [comment]
@NullVoxPopuli @bf4 Thanks guys, this is perfect. I couldn't find it for some reason. Then I was looking at http://www.rubydoc.info/gems/active_model_serializers/0.9.1/ with no success either.
