### ISSUE TITLE
JSON API SerializableResource relationships with attributes

### ISSUE THREAD

**Issue by jmarceli** [rails-api/active_model_serializers#1875]
Hi,
I'm using:
```
# where `order` is an instance of Order class
json = ActiveModelSerializers::SerializableResource.new(order).as_json
```
to generate JSON data for JSON API request. The problem is that relationships are generated without `attributes`.

Desired output is:
```
{
    "data": {
        "type": "order",
        "attributes": {
            "title": "First order",
            "code": "123123123"
        },
        "relationships": {
            "items": {
                "data": [{
                    "id": "1",
                    "type": "item",
                    "attributes": {
                        "name": "T-shirt",
                        "price": "12.50"
                    }
                }, {
                    "id": "2",
                    "type": "item",
                    "attributes": {
                        "name": "Sunglasses",
                        "price": "50.00"
                    }
                }]
            }
        }
    }
}
```

Actual result is:
```
{
    "data": {
        "type": "order",
        "attributes": {
            "title": "First order",
            "code": "123123123"
        },
        "relationships": {
            "items": {
                "data": [{
                    "id": "1",
                    "type": "item"
                }, {
                    "id": "2",
                    "type": "item"
                }]
            }
        }
    }
}
```

My serializers looks like this:
```
  class OrderSerializer < ActiveModel::Serializer
    type :order
    attributes :id, :code
    has_one :status
    has_many :items
  end
```
```
  class ItemSerializer < ActiveModel::Serializer
    type :item
    attributes :id, :number, :length, :width
  end
```

Is it possible to generate what I want with `active_model_serializers` ?

**Comment by bf4** [comment]
per JSON API, what you need to do is `include: :items`.  That will result in another top-level attribute `included` that has the relationships with their attributes. The resource identifiers only ever have `id` and `type`.

**Comment by bf4** [comment]
Since the answer is just how JSON API works, I'm going to close this. But please report back if this resolves your issue and if not, more details on the errors.

**Comment by jmarceli** [comment]
Thanks for your response.
I'm using [active_model_serializers-jsonapi_embedded_records_deserializer](https://github.com/spieker/active_model_serializers-jsonapi_embedded_records_deserializer) for resource deserialization and nested resource creation. I know it's not yet an official JSON API [way](https://github.com/json-api/json-api/issues/795) but as far as I know there is no official format for nested resources creation. `include: ...` is a format for resource retrieving but not for creation (correct me if I'm wrong).
All in all it is not possible with current JSON API adapter to achieve what I want?

**Comment by bf4** [comment]
@jmarceli So, AMS has adapters for this purpose.

> it is not possible with current JSON API adapter to achieve what I want

Correct, but you can subclass it :)

That embedded thing comes up periodically. It seems to cause a lot of problems.

**Comment by NullVoxPopuli** [comment]
@jmarceli these are all the modifications I use. https://github.com/NullVoxPopuli/aeonvera/blob/master/config/initializers/active_model_serializers.rb

I found that gem you found to be insufficient.

**Comment by jmarceli** [comment]
@NullVoxPopuli what is the advantage of your solution over mentioned gem?
I'm asking because I don't see any problems with it (as for now).

Meanwhile I come up with my own solution:
**config/initializers/nested_jsonapi_serializer.rb**
```
# Adds { include_nested: true } option for every serialization method
# Example:
# ```
# ActiveModelSerializers::SerializableResource.new(object).as_json({ include_nested: true })
# ```
# will include related items attributes
ActiveModelSerializers::Adapter::JsonApi::ResourceIdentifier.class_eval do
  def initialize(serializer, options)
    @id   = id_for(serializer)
    @type = ActiveModelSerializers::Adapter::JsonApi.send(
      :transform_key_casing!, type_for(serializer), options
    )
    @options = options
    @attributes = attributes_for(serializer) if options[:include_nested]
  end

  def as_json
    json = { id: id, type: type }
    json[:attributes] = attributes if options[:include_nested]
    json
  end

  protected

  attr_reader :attributes, :options

  private

  def attributes_for(serializer, fields = nil)
    serializer.attributes(fields).except(:id)
  end
end
```

So in order to get what I was trying to generate it is enough to write:
```
json = ActiveModelSerializers::SerializableResource.new(order).as_json(include_nested: true)
```

**Comment by NullVoxPopuli** [comment]
I actually took most of the code from the gem. I have namespaced and
polymorphic models, and the gem broke with one of those.

**Comment by jmarceli** [comment]
OK. Thanks for the clarification. If you have some time maybe consider a PR with your improvements.

**Comment by TrevorHinesley** [comment]
I'm not sure why AMS can't support this... according to the Inclusion of Related Resources section, relationships can be fully returned (including attributes) without being in the `include` key. See http://jsonapi.org/format/#fetching-includes

**Comment by NullVoxPopuli** [comment]
because of the complications of nested payloads, I've actually decided to go back to the JSONAPI recommended single object POSTs.
