### ISSUE TITLE
Best way url_helpers to work in json adapter (not json_api)?

### ISSUE THREAD

**Issue by attenzione** [rails-api/active_model_serializers#1879]
Hi!
i'm not using json_api adapter, so link method is not working for me.
Can you please advise good way to resolve problem with undefined url or path?

```
class ResourceSerializer < ApplicationSerializer
  attribute :embed_code

  def embed_code
    "<iframe src=\"#{embed_resource_url(object)}\"></iframe>"
  end
end
```

**Comment by markiz** [comment]
Try `include Rails.application.routes.url_helpers`

**Comment by attenzione** [comment]
yeas, that fastest approach, but this requires to ```:host``` in ```default_url_options``` and I don't like it, because url helper method in view context returns correct url, based on request I think. I don't like this ideas for json_api also.
Another solution (which works without specifying host):

```
class ApplicationController < ActionController::Base
  serialization_scope :view_context
end

class ResourceSerializer < ApplicationSerializer
  attribute :embed_code

  def embed_code
    "<iframe src=\"#{view_context.embed_resource_url(object)}\"></iframe>"
  end
end
```

**Comment by bf4** [comment]
@attenzione you'll need to either write a custom adapter or one of the above options. I'm going to close this issue as resolved since it is squarely in userland, but please report back here what you end up doing for others who are interested.

**Comment by attenzione** [comment]
@bf4 currently i'm using solution, what I've provided before. This way I have access to all helpers without including them in each/some serializers, more flexible
