### ISSUE TITLE
How do I get the JSON representation programatically?

### ISSUE THREAD

**Issue by m-mujica** [rails-api/active_model_serializers#189]
Hi guys! I hope you're doing well. 

I don't know if this is a dumb question, but image that you want to preload data for your client-side models and you rely on the json generated by the awesome active_model_serializers. How do you get the json representation? 

If I try with:
Model.all.to_json ; I get the [old version](https://github.com/rails-api/active_model_serializers)

Am I missing something? 

Thanks in advance.

**Comment by chibicode** [comment]
You can try

```ruby
ActiveModel::ArraySerializer.new(array, each_serializer: SomeSerializer)
```
