### ISSUE TITLE
ApplicationSerializer not picked up by generator

### ISSUE THREAD

**Issue by ganlron** [rails-api/active_model_serializers#1890]
#### Expected behavior vs actual behaviour
I've created an ApplicationSerializer in app/serializers/application_serializer.rb and was expecting rails g serializer foo to inherit from this, but it still defaults to ActiveModel::Serializer.

I can get around this by passing ApplicationSerializer with --parent and it works, but wasn't expected behaviour

#### Environment

Rails 5.0.0.1
ruby 2.3.1p112

**Comment by bf4** [comment]
@ganlron which AMS version? I'm unfamiliar with `--parent`.  You ran `rails g serializer User --parent ApplicationSerializer`?

**Comment by bf4** [comment]
Oh, ha, it's our own option https://github.com/rails-api/active_model_serializers/blob/master/lib/generators/rails/serializer_generator.rb#L9

Looks like it's because the generator checks if the ApplicationSerializer is defined, and it may not have been loaded yet?  So, logic there could be better?

**Comment by ganlron** [comment]
LOL ya, was your option :)

**Comment by bf4** [comment]
I'm pretty sure you could fix this by changing the `defined?` check


```ruby

      def parent_class_name
        options[:parent] or  ::ApplicationSerializer.name
      rescue NameError
          'ActiveModel::Serializer'
      end
```
