### ISSUE TITLE
key_transform not transforming keys to camelCase

### ISSUE THREAD

**Issue by thejourneydude** [rails-api/active_model_serializers#1891]
#### Expected behavior vs actual behavior
I expect the Rails controller response JSON keys to be camelCased. However, they respond with snake_case.

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*
I have added into the controller:

      def index
          render status: :ok,
                 json: Comment.all,
                 each_serializer: CommentSerializer,
                 key_transform: :camel_lower
      end

The CommentSerializer is 
```
class CommentSerializer < ActiveModel::Serializer 
  has_many :children_comments

  def children_comments
    object.children_comments.map do |comment|
      CommentSerializer.new(comment).as_json
    end
  end
end
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

0.10.2

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

OS Type & Version: 

OS X El Capitan 10.11.6

Integrated application and version *(e.g., Rails, Grape, etc)*: 

Rails 4.2.6

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

None.

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

I have not added any configurations to the initializers folder.

**Comment by NullVoxPopuli** [comment]
what adapter are you using?

**Comment by thejourneydude** [comment]
None. I have not specified an adapter.

**Comment by NullVoxPopuli** [comment]
the default is the attributes adapter. which hadn't respected key transform until earlier today actually. 
if you point your gemfile at master, it should resolve the issue.

**Comment by thejourneydude** [comment]
That fixed it. Thanks!

**Comment by NullVoxPopuli** [comment]
woo!

**Comment by benlakey** [comment]
This wasn't called out in the docs (that the attributes adapter does not support it) which bit me today. It just silently failed to to camelCase and I had to search around and find this issue to understand why the documented key transform wasn't functioning.

**Comment by NullVoxPopuli** [comment]
Long term, we will have all adapters support all options.  There is a case transform gem that you can use in the meantime

**Comment by benlakey** [comment]
@NullVoxPopuli Understood, but I was referring less to needing a solution (I just pointed at master for the time being) and more suggesting that the documentation be kept in-sync with what is and isn't currently supported. Right now the docs don't call out that certain adapters don't support certain options.

**Comment by NullVoxPopuli** [comment]
that's true.
