### ISSUE TITLE
Include attributes from another Serializer

### ISSUE THREAD

**Issue by ivanstojkovicapps** [rails-api/active_model_serializers#1892]
I am trying to include attributes from another serializer, for example my first serializer:

```
class MyMinimalSerializer < ActiveModel::Serializer
  attributes :id, :field1, :field2
end
```

i need new serializer that includes all attributes from MyMinimalSerializer and has few more

```
class MyMediumSerializer < ActiveModel::Serializer
  # include Attributes from MyMinimalSerializer and add :field3, :field4
end
```

How to do that?

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.

**Comment by ivanstojkovicapps** [comment]
Hi, what is here insufficient?

I have a model serializer with some fields, in my example: id, field1, field2. This is my minimal serializer because i don't want to transfer all model fields, just those 3. 
Now i need one new serializer that will transfer those three fields and one or two more.
Of course i can just create the serializer like this:

```
class MyMediumSerializer < ActiveModel::Serializer
  attributes :id, :field1, :field2, :field3
end
```

but i don't want to write every attribute that i used in MyMinimalSerializer, just want to inherit them.

Is this possible?

**Comment by NullVoxPopuli** [comment]
have you seen https://github.com/rails-api/active_model_serializers/blob/master/docs/general/fields.md ?

**Comment by ivanstojkovicapps** [comment]
Hi,

yes of course but this doesn't help me. 
Is there something like this:

```
class MyMediumSerializer < ActiveModel::Serializer
  attributes MyMinimalSerializer.attributes, :field3
end
```

**Comment by NullVoxPopuli** [comment]
i'd recommend you abstract your attribute definitions to a mixin module.

**Comment by ivanstojkovicapps** [comment]
hi, i am not sure are am following you, can you post some basic example, like i started?

**Comment by NullVoxPopuli** [comment]
```ruby
module SomeMixin
  include ActiveSupport::Concern

  included do
      attributes :field1, field2

      def field1
        if object.is_a?(TypeFromSerializerB)
          object.field1
        else
          object.relationship.field1
        end
      end 
   end
```

AMS will not support  what your asking out of the box, but it's pretty easy to achieve on your own.

**Comment by ivanstojkovicapps** [comment]
Ok, thanks a lot!
