### ISSUE TITLE
Unable to render hash

### ISSUE THREAD

**Issue by dnlsandiego** [rails-api/active_model_serializers#1893]
I have a Rails 5 app in API mode using this gem and [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) for token based authentication. `devise_token_auth`'s controllers renders plain hashes as responses but neither of all the 3 adapters seem to be able to render the hashes to JSON.

#### Expected behavior vs actual behavior
`curl -i -X DELETE http://localhost:3000/v1/auth/sign_out`

Expected response:
`{  errors: ['User was not found or was not logged in.'] }`

Actual response (with the default adapter):
`{}`

With the `:json_api` adapter:
```NoMethodError (undefined method `read_attribute_for_serialization' for {:errors=>["User was not found or was not logged in."]}:Hash)```

With the `:json` adapter:
`NoMethodError (undefined method `model_name' for Hash:Class):` 

#### The`devise_token_auth` destroy method
```ruby
def render_destroy_error
  render json: {
    errors: [I18n.t("devise_token_auth.sessions.user_not_found")]
  }, status: 404
end
```

#### Steps to reproduce
A fresh Rails 5 app in API mode with `active_model_serializers` version `0.10.0` and `devise_token_auth` version `0.1.37` gems.
I can provide a repo to reproduce this issue if needed but I feel like there is something I'm missing in usage of this gem.

Is rendering plain hashes supported in this gem? I tried looking through the docs, issues, and SO for answers but found nothing.

Is there a way to set active_model_serializer to allow rendering of hashes directly?

**Comment by bf4** [comment]
> { errors: ['User was not found or was not logged in.'] }


I'm guessing this is related to eager calling of the serialization context `current_user` upon render.  Try in your controller setting `serialization_scope nil` if you don't use scopes, or `serialization_scope :view_context` if you do.  see https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md#scope

**Comment by dnlsandiego** [comment]
Thanks for the reply. I tried setting `serialization_scope nil` in a controller and it didn't work. I also tried setting it instead in the `ApplicationController` but still didn't work. Is there anything else I can try setting or configuring?

**Comment by dnlsandiego** [comment]
@bf4 Sorry to bug you but I've been on this issue for almost a week. Do you have any other ideas or possible aspects I can look into to fix this?

**Comment by bf4** [comment]
Do you have a backtrace?

Btw, that gem appears buggy.  Had issues a lot.

**Comment by bf4** [comment]
Are you passing a hash into a serializer by any chance?  (Help me help you)

**Comment by dnlsandiego** [comment]
Here's a backtrace on a request thats suppose to `401` and return `{ success: false, errors: ['...'] }`.

<details>
    <summary>Backtrace</summary>
```
Started GET "/v1/auth/validate_token" for ::1 at 2016-08-30 21:03:19 -0500
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by DeviseTokenAuth::TokenValidationsController#validate_token as HTML
[active_model_serializers] Rendered HashSerializer with ActiveModelSerializers::Adapter::Attributes (0.14ms)
Completed 401 Unauthorized in 14ms (Views: 5.0ms | ActiveRecord: 0.0ms)
```
</details>

I'm not passing a hash into a serializer. `devise_token_auth` just renders hashes as response. This is one of the methods they handles responses:

```ruby
def render_validate_token_error
      render json: {
        success: false,
        errors: [I18n.t("devise_token_auth.token_validations.invalid")]
      }, status: 401
    end
```

Yeah, I realized that AMS and DTA has a lot of issues together while trying to debug this. Thanks for replying and trying to help me with this. I really appreciate it.

**Comment by dnlsandiego** [comment]
@bf4 I tried removing all of my serializers and completely deleting the serializers directory under `app` and `devise_token_auth` is able to render its responses just fine.

**Comment by dnlsandiego** [comment]
Figured it out. It was a custom serializer I've made that was causing the issue. Deleting it fixed the issue. 

This is the serializer:

```ruby
class HashSerializer < ActiveModel::Serializer
  def self.dump(hash)
    hash.to_json
  end

  def self.load(str)
    HashWithIndifferentAccess.new(JSON.load(str))
  end
end
```

Created this for convenience. So I could access AR object hash keys as symbols instead of strings.

Apologies on this ultimately unnecessary issue.

**Comment by bf4** [comment]
@dnlsandiego I figured it was something like that, but I didn't have enough info to point it out to you.  BTW, your 'backtrace' formatting is neat, but not a backtrace, just logging. I thought there was an exception?  Or if not `puts caller` (with some sanitization) might have been helpful.

**Comment by bf4** [comment]
Glad it worked out!

If you have any more info to share that might help a future person, please do!

**Comment by dnlsandiego** [comment]
Oh yeah, the backtrace was supposed to include 2 logs of requests. One with the exception, guess it got cut off somewhere. 

I'll probably spend some time looking into both AMS and DTA this weekend and figure out why having a custom serializer breaks DTA. Could be useful for people who run into the same issue I did.

Thanks again for the help!

**Comment by bf4** [comment]
@dnlsandiego It not a custom serializer per-se, it's that a Hash is not the kind of object AMS is meant to take as input. It expects a model.  AMS can handle virtual and dynamic attributes, so that might be a better way to add your special logic.
