### ISSUE TITLE
Encoding of pagination links

### ISSUE THREAD

**Issue by netbe** [rails-api/active_model_serializers#1896]
#### Expected behavior vs actual behavior

I have kaminari setup with the json_api adapter and I am getting the following links:

```
http://example.com/articles?page%5Bnumber%5D=17\u0026page%5Bsize%5D=1
```

instead of
```
http://example.com/articles?page[number]=3&page[size]=1
```

Am I missing something or is the expected behavior?

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

Controller:

```
  def index
    params.permit(:page)
    page = params[:page].to_i
    @articles = Article.all.page(page).per(1)

    render json: @articles
  end
```

#### Environment

ActiveModelSerializers Version *0.10.2*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
OS Type & Version: 
 15.5.0 Darwin Kernel Version 15.5.0
Integrated application and version *(e.g., Rails, Grape, etc)*: 
rails 5.0.0

**Comment by NullVoxPopuli** [comment]
- How are you getting the link?
- What's the output of the render call?
- is your problem just that page[number] is 17 instead of 3?
- actual is uri-encoded, decoded, it's identical, sans the unicode character and the 17 and 3 :-\ so, I'm not sure exactly what is expected / what is happening. :-\

**Comment by bf4** [comment]
@netbe per uri spec although we write `page[number]=3&page[size]=1` it's actually going to be uri encoded as `page%5Bnumber%5D%3D3%26page%5Bsize%5D%3D1` You're getting page%5Bnumber%5D=17\u0026page%5Bsize%5D=1` which has some encoding differences that are strange

```diff
- page%5Bnumber%5D%3D3%26page%5Bsize%5D%3D1
+ page%5Bnumber%5D=17\u0026page%5Bsize%5D=1
```

It's hard to know why the `%3D3%` would become `=17\u002` and `%3D1` become `=1` without having a more intimate look your code.

**Comment by bf4** [comment]
@netbe I can say though that you're using strong params wrong.

```diff
- params.permit(:page)
- page = params[:page].to_i
+ pagination_params = params.permit(:page)
+ page = pagination_params[:page] || 0
```

**Comment by netbe** [comment]
@bf4 good to know that links are encoded

I have tried with to decode them and this works well even for the `&`:

```
require 'uri'
URI.decode(link)
```
And thks for pointing out the strong params issue

**Comment by kwent** [comment]
Seeing the same issue

```bash
curl --request GET \                                                                                                                          ruby-3.1.4
  --url "https://dummy.example.com/api/v1/resources?hello&world" \
  --header 'Accept: application/vnd.api+json' \
  --header 'Authorization: Bearer TOKEN' \
  --header 'Content-Type: application/vnd.api+json'
  ```
  
data returned is 

```json
{"data":[],"links":{"self":"https://dummy.example.com/api/v1/resources?hello=\u0026page%5Bnumber%5D=1\u0026page%5Bsize%5D=50\u0026world=","first":"https://dummy.example.com/api/v1/resources?hello=\u0026page%5Bnumber%5D=1\u0026page%5Bsize%5D=50\u0026world=","prev":null,"next":null,"last":"https://dummy.example.com/api/v1/resources?hello=\u0026page%5Bnumber%5D=1\u0026page%5Bsize%5D=50\u0026world="},"meta":{"total_count":8,"total_pages":1}}
```
