### ISSUE TITLE
Fragment caching not working when using the JSON API adapter

### ISSUE THREAD

**Issue by jamesbrooks** [rails-api/active_model_serializers#1905]
When using the JSON API adapter fragment caching does not function correctly; rather full non-fragment caching is used, even when `:only`/`:except` options are specified to #cache.

Fragment caching does however work correctly with the standard JSON adapter.

From my initial investigation this seems to be because [`ActiveModelSerializers::Adapter::JsonApi#resource_object_for`](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/adapter/json_api.rb#L297) only calls [`#fetch`](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/concerns/caching.rb#L220-L228), which from looking through the caching concern is only used for full resource caching as gleaned from reading [`#fetch_attributes`](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/concerns/caching.rb#L205-L218).

Possibly unrelated, but both the class and instance methods #fragment_cache on `ActiveModelSerializers::Adapter::JsonApi` never appear to be called.

As of current I haven't written any failing tests or made any head-way into finding a resolution to the issue. I'm trying to go back through the commit history and follow the development of fragment caching in the project (as well as looking at existing issues) before I can attempt to make an educated guess to how a fix should be applied.

It feels like `#resource_object_for` should check to see if the serializer has fragment caching enabled and then attempt to fetch cached attributes and merge with non-cached attributes, though the structure of the JSON adapter and the JSON API adapater vary greatly so it's difficult to know (for myself) at this time if that is the right path to take.

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.

**Comment by bf4** [comment]
@jamesbrooks That said, I'd love to work with you in helping debug any of this.  It looks like you got a good start.  I just don't have enough info for any specific feedback.

**Comment by csaurav** [comment]
Im also facing the similar issue with fragment caching and json_api adapter 

AMS version: active_model_serializers (0.10.5)

**Comment by TONYHOKAN** [comment]
@jamesbrooks i encountered  the same problem like you that using JSON API adapter. May i know do you solve the problem?

**Comment by jamesbrooks** [comment]
I did not ever solve that issue. I opted to not use the fragment caching because of that issue unfortunately.

**Comment by TONYHOKAN** [comment]
@jamesbrooks thanks for your reply. It seems that i can only disable fragment caching now and keep track of this problem.
