### ISSUE TITLE
undefined local variable or method `object'

### ISSUE THREAD

**Issue by JasonMannon** [rails-api/active_model_serializers#1918]
I'm trying to assign attributes to my serializer, and i'm getting a "undefined local variable or method `object'" error

This is what my serializer looks like:

```
    class ImageSerializer < ActiveModel::Serializer
      attributes :id, :image, :order, :url

      def url 
        object.image.url
      end
    end
```

Anyone know why i'm having this problem?  I'm following this serializer guide at this link: [https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md)

**Comment by NullVoxPopuli** [comment]
Closing due to insufficient information. 
Please follow the issue template, and I'll re-open :-)
