### ISSUE TITLE
Fields should be mapped to the object methods and not to the final serialized values

### ISSUE THREAD

**Issue by vasilakisfil** [rails-api/active_model_serializers#1920]
#### Expected behavior vs actual behavior
Suppose that we have:

```ruby
#taken from tests
class RelationshipAuthor < ::Model; end
class RelationshipAuthorSerializer < ActiveModel::Serializer
  type :author

  has_one :bio, key: :somebio do
    link :self, '//example.com/link_author/relationships/bio'
  end

  has_many :locations, key: :somelocations do
    link :related do
      ids = object.locations.map(&:id).join(',')
      href "//example.com/locations/#{ids}"
    end
  end
end
```

and I call:

```ruby
@bio = Bio.new(id: 1337)
@location = Location.new(id: 1337)
@author = RelationshipAuthor.new(
  id: 1337,
  bio: @bio,
  locations: [@location]
)
ActiveModelSerializers::SerializableResource.new(author, {
  adapter: :json_api, fields: {
    author: [:id, :bio, :locations]
  }
}).serializable_hash
```

Expected behaviour: It returns the resource along with relationships (`bio` and `locations`).

Actual behaviour: It returns just the resource without the relationships.

#### Environment

Latest master branch of AMS

#### Other Info
The fields there should filter the **methods** of the object and not the *final* JSON keys.

This is because supporting the final JSON keys give me nothing programmatically. Instead, using Ruby's reflection I can filter object's relationships/attributes programmatically. If fields are supposed to filter the final JSON keys, the only thing I can do is to hardcode them because the final JSON keys are defined from the serializer only and I don't have any information about that. Also, I feel that the final conversion of the method ==> to the actual key name is a serializer's responsibility and one level down from the controller thus I shouldn't actually even care/know what are the final key names.

Test to reproduce errors:
```ruby
require 'test_helper'

module ActiveModel
  class Serializer
    module Adapter
      class JsonApi
        class RelationshipTest < ActiveSupport::TestCase
          class RelationshipAuthor < ::Model; end

          class RelationshipAuthorSerializer < ActiveModel::Serializer
            type :author

            has_one :bio, key: :somebio do
              link :self, '//example.com/link_author/relationships/bio'
            end

            has_many :locations, key: :somelocations do
              link :related do
                ids = object.locations.map(&:id).join(',')
                href "//example.com/locations/#{ids}"
              end
            end
          end

          def setup
            @bio = Bio.new(id: 1337)
            @location = Location.new(id: 1337)
            @author = RelationshipAuthor.new(
              id: 1337,
              bio: @bio,
              locations: [@location]
            )
          end

          def test_relationship_simple_link
            expected = {
              data: {
                id: '1337',
                type: 'bios'
              },
              links: {
                self: '//example.com/link_author/relationships/bio'
              }
            }

            author = @author.dup
            assert_author_relationship_serialized(expected, author, :somebio)
          end

          def test_relationship_block_link_href
            expected = {
              data: [{ id: '1337', type: 'locations' }],
              links: {
                related: { href: '//example.com/locations/1337' }
              }
            }

            author = @author.dup
            assert_author_relationship_serialized(expected, author, :somelocations)
          end

          private

          def assert_author_relationship_serialized(expected, author, relationship_name)
            hash = serializable(author, adapter: :json_api, fields: {
              author: [:id, :bio, :locations]
            }).serializable_hash
            puts hash
            actual_relationship = hash[:data][:relationships][relationship_name]
            assert_equal(expected, actual_relationship)
          end
        end
      end
    end
  end
end
```

I haven't test this with other adapters.

**Comment by richmolj** [comment]
I actually just ran into this same issue myself, but I arrived at the opposite conclusion.

Given the API response where `relationships` has `somebio`: The consumer of this API has no knowledge of the word `bio`. They only have knowledge of `somebio`. So they would expect a URL with `fields` and `include` to accept `somebio` not `bio`.

This is [per the jsonapi spec](http://jsonapi.org/format/#fetching-includes) - the `include` should match the relationship name.

So, we would actually have to internally convert all these things to their alternative names in `render`, which I ultimately think is more confusing.

> This is because supporting the final JSON keys give me nothing programmatically. Instead, using Ruby's reflection I can filter object's relationships/attributes programmatically. 

You can get the alternate names like:

```ruby
serializer.class._reflections

# { 
#   somebio: >#<struct ActiveModel::Serializer::BelongsToReflection name=:bio, options={}, block=nil>
# }
```

Does this work for you?

**Comment by vasilakisfil** [comment]
hmm ok no big difference here. Either way is ok for me as long as we have a method that gets one or another set of keys. Because yes client does not know the internal name, but other classes shouldn't know the "external" (or "final") key name.

I will play with that and let you know. I will close this issue for now although I think AMS should provide the method I described. Feel free to re-open if you think it's still an issue.

**Comment by richmolj** [comment]
@NullVoxPopuli @bf4 the suggestion I have @vasilakisfil is private, thoughts on some sort of public API for this?

Personally, I am not a favor of `key` in general. I would rather:

```ruby
belongs_to :somebio

def somebio
  object.bio
end
```

**Comment by NullVoxPopuli** [comment]
I agree that this is a bug. I've ran in to it, and I actually have a PR out there that addresses this (at the dev/user level): https://github.com/rails-api/active_model_serializers/pull/1840

But I'd rather the problem actually be resolved.

I think a complication is that fields can be taken from parameters, which the JSON API consuming client would prefer to be in whatever casing it uses.

BUT! I think we should put our feet down, and make everything from the perspective of the serializers, and not try to accommodate every casing use case out there. 

includes already requires to match the serializer definition. So... we should do that for all serializer options.

**Comment by richmolj** [comment]
@NullVoxPopuli wouldn't this be a problem for any API, not just JSON API? That's the example but it someone had an API where `foo` was supposed to limit fieldsets we'd have the same problem.

**Comment by NullVoxPopuli** [comment]
I use JSON API as an example, because that's what I work with day-to-day. :-)

**Comment by richmolj** [comment]
Sorry I think I was unclear - just wanted to note this is not a JSON API-specific problem.

It really comes down to whether or not you want to optimize for `render` (to match the URL) or outside-of-controller usage (to match the internal serializer). I'd prefer the former as it's the more 'usual' use case.

Or go a step further and deprecate `key` altogether...I'm not totally sure what this buys the user opposed to my refactor above. Seems to add confusion for not much purpose, but maybe I just don't know the valid use cases...

**Comment by richmolj** [comment]
@NullVoxPopuli @bf4 this just came up in slack as well. How do you feel about deprecating `key` and avoiding the complexity?

**Comment by NullVoxPopuli** [comment]
I'm a fan. The simpler the better.

**Comment by bf4** [comment]
@richmolj `key` and its ilk have been around for a while.  However, I agree it can be a confusing api since it forces an attribute -> method mapping in the reverse order that it is declared in the DSL.  I think it would be easier to understand as something like `attribute :somebio, method: :bio`.

On the other hand, the way it's currently written means that you the insides know which attributes to use, and they just let's you customize the key to the fetched attribute.

i.e.

```ruby
attribute :bio, key: :somebio
#=> { somebio: read_attribute_for_seriaization(:bio) #=> object.read_attribute_for_serialization(:bio) }
```

vs.

```ruby
attribute :somebio, method: :bio
#=> { somebio: object.send(:bio) }  # though I guess this api would be ambiguous if it's an object method or serializer method to send
```

which is inferior to using read attribute for serialization

(and is the same as

```ruby
attribute :somebio do object.bio end #=> { some_bio: instance_eval(&some_bio_attribute_block) }
```

and

```ruby
attribute :somebio
def somebio; object.bio; end
#=> { somebio: read_attribute_for_serialization(:bio) }
```

**Comment by bf4** [comment]
(I implemented `read_attribute_for_serialization` on the serializer instance for a more consistent api, and it's pretty convenient to have)

**Comment by richmolj** [comment]
@bf4 I *think* we agree? I would say either your last comment snippet or overriding `read_attribute_for_serialization` are superior to `key`, which suggests it should be deprecated.
