### ISSUE TITLE
[Q|BUG] 3 level of Nested Serializers

### ISSUE THREAD

**Issue by Elvinra** [rails-api/active_model_serializers#1924]
class ASerializer < ActiveModel::Serializer

has_many :bs

class BSerializer < ActiveModel::Serializer

belongs_to :c

class CSerializer < ActiveModel::Serializer
end
end

The C class is not serializer bug or not ?
if a put "attributes :c" my model is serializer but not with my CSerializer

i need to define manually the serialize

def c
{...}
end

i'm working on the lastest version of rails 4 on Ruby 2.3.1p221

**Comment by NullVoxPopuli** [comment]
Closing due to insufficient information, please follow the issue template (and format your code :-) )
Will re-open when the issue template is followed: https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md
