### ISSUE TITLE
Integer attribute was converted to string

### ISSUE THREAD

**Issue by polarlights** [rails-api/active_model_serializers#1929]
#### Expected behavior vs actual behavior

I'm new to AMS. I created a table named 'tags'.  Here it is.
```ruby
create_table "tags", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
end
```

The data type of id is Integer. However the output is **String**.

##### Expected:

```json
"data": [
  {
    "id": 1,
    "type": "tags",
    "attributes": {
    "name": "autem"
     }
  }
]
```

##### Actual:

```json
"data": [
  {
    "id": "1",
    "type": "tags",
    "attributes": {
    "name": "autem"
    }
  }
]
```

#### Steps to reproduce

* Model

```ruby
class Tag < ApplicationRecord
end
```

* Controller
```ruby
module Api
  module V1
    class TagsController < ApplicationController
      def index
        @tags = Tag.all
        render json: @tags
      end
    end
  end
end
```

* Serializer
```ruby
class TagSerializer < ActiveModel::Serializer
  attributes :id, :name
end
```

#### Environment

ActiveModelSerializers Version *0.10.0*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`:  ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

OS Type & Version: EI Capitan 10.11.2

Integrated application and version *(e.g., Rails, Grape, etc)*: 

* Rails: 5.0.0.1

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

None.

Thank U in advance.

**Comment by richmolj** [comment]
Hi @polarlights - looks like you're outputting jsonapi. According to the jsonapi spec, id must be a string: http://jsonapi.org/format/#document-resource-objects

**Comment by polarlights** [comment]
Yep. My fault. Thank you very much! 👍
