### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by runephilosof** [rails-api/active_model_serializers#1941]
0.10 should be backwards compatible with 0.9, because it is a minor version upgrade and the README says that this project adheres to semantic versioning.

Please increment the major version.

**Comment by NullVoxPopuli** [comment]
According to: http://semver.org/

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

We're working hard to get to 1.0.0 as fast as possible, but we've been toying around with some architectural changes between 0.8, 0.9, and 0.10.

1.0 will be mostly the same API as 0.10 -- or at least will have a super easy way to incrementally upgrade.

**Comment by runephilosof** [comment]
Yeah, sorry. But I do recommend releasing as 1.0.0 anyway. Having it released as 1.x doesn't prevent you from doing these kinds of changes. It just means a major version increment.

http://semver.org/#how-do-i-know-when-to-release-100

> If your software is being used in production, it should probably already be 1.0.0.

I am guessing that you are using this in production (considering how long this gem has been in active development). I know that I am.
