### ISSUE TITLE
thought on mixing adapters types within a Rails app? 

### ISSUE THREAD

**Issue by drewnichols** [rails-api/active_model_serializers#1951]
We have an API with about 30 endpoints used by 3 different clients which all currently use Active Model Serializer 0.9.  We'd like to begin migrating to JSON API but want to do the migration endpoint by endpoint rather than all at once. In looking at the 0.10 documentation (and google) there doesn't seem be an out of by way to specify the adapter other than with a global setting.

Are we missing something? Is this something Active Model Serializers could support?

**Comment by beauby** [comment]
You can override the adapter on the `render` call (`render json: foo, adapter: :json_api`).

**Comment by bf4** [comment]
@drewnichols @beauby is correct. In addition, there are a number of migration needs for going from 0.9 to 0.10. Please see the docs in this repo.
