### ISSUE TITLE
Serialized attributes are outdated on non-AR objects

### ISSUE THREAD

**Issue by lcoq** [rails-api/active_model_serializers#1953]
#### Expected behavior vs actual behavior

Expected behavior : 

```
> session = Session.new(email: 'test@email.com')
> session.as_json
=> {:email=>"test@email.com"}
> session.email = 'other@email.com'
=> "other@email.com"
> session.as_json
=> {:email=>"other@email.com"}
```

Actual behavior : 

```
> session = Session.new(email: 'test@email.com')
> session.as_json
=> {:email=>"test@email.com"}
> session.email = 'other@email.com'
=> "other@email.com"
> session.as_json
=> {:email=>"test@email.com"}
```

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

```
class Session < ActiveModelSerializers::Model
  attr_accessor :email
end
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: `0.10.0`

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

OS Type & Version:  `Ubuntu 15.10`

Integrated application and version *(e.g., Rails, Grape, etc)*: `Rails 5.0.0.1 (api)`

#### Reason

The [model `@attributes`](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/model.rb#L12) are never updated.

**Comment by groyoh** [comment]
As far as I remember, `AMS::Model` was created more for convenience and to have a PORO which only has the necessary interface for serialization. So I'm not sure if it is recommended to use it. I may be wrong though. @bf4 I think you extracted this so I'd love to get your opinion before creating a PR for this?

Concerning the bug itself, I would see three quick solutions for you fix/patch to this:

* Defining your own writer:

```ruby
class Session < AMS::Model
  attr_reader :email

  def email=(email)
    attributes[:email]=email
  end
end
```

* Reusing [this code](https://github.com/rails-api/active_model_serializers/blob/v0.10.2/test/fixtures/poro.rb#L9).
* Defining a model DSL for the attribute e.g.:

```ruby
class Model < AMS::Model
  def self.model_attr(name)
    define_method(name) do
      @attributes[name.to_sym]
    end

    define_method("#{name}=") do |value|
     @attributes[name.to_sym] = value
    end
  end
end

class Session < Model
  model_attr :email
end
```

**Comment by lcoq** [comment]
@groyoh Thank you for your answer and your suggestions.

Also, I just found a documentation on [How to serialize a Plain-Old Ruby Object (PORO)](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/serialize_poro.md) which seems to tell your solution is the expected way.

Just my two cents, but I think POROs serialization should be available by including a `Module` instead of using class inheritance.

Thanks anyway!

**Comment by groyoh** [comment]
@lcoq Using a mixin might indeed be more flexible and ruby-ish. But as I previously said, I'm not really certain if it was orignally meant to be used outside of AMS or simply taken as an example.
