### ISSUE TITLE
has_one association not included in rendered json

### ISSUE THREAD

**Issue by prrrnd** [rails-api/active_model_serializers#1954]
#### Expected behavior vs actual behavior

Parking has_many :cars
Car has_one :driver

```ruby
class ParkingSerializer < ActiveModel::Serializer
  attributes :id, :location
  has_many :cars
end
```

```ruby
class CarSerializer < ActiveModel::Serializer
  attributes :id, :brand
  has_one :driver
end
```

```ruby
class DriverSerializer < ActiveModel::Serializer
  attributes :id, :name
end
```

**Expected** 
A `driver` nested under each `car` in the json when rendering a `parking`

**Result**
json with parking's attributes, cars, cars attributes except `driver`

#### Steps to reproduce

See serializers above

Controller:

```ruby
# ...
def show
  @parking = Parking.find(params[:id])
  render json: @parking
end
# ...
```

#### Environment

ActiveModelSerializers Version 0.10.2
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
macOS Sierra
Rails 4.2.7.1

**Comment by beauby** [comment]
`JsonApi` adapter?

**Comment by prrrnd** [comment]
@beauby I'm using the default one, `:attributes`

**Comment by groyoh** [comment]
@prrrnd try:

```ruby
render json: @parking, include: "*.*"
```

With 0.10, associations are included by default only for the first level. If you want to include deeper associations, you need to specify it with the `include` directive. In this case, `include: "*.*"` means include any association up to 2 levels. You may also use `include: **` to include every level (not recommended) or be more specific `include: "cars.driver"`.

**Comment by prrrnd** [comment]
@groyoh Thanks, I'll try that and report back.
Seems like your explanation could be part of the [documentation](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#include), it's waiting for a PR.

**Comment by groyoh** [comment]
@prrrnd yeah the documentation is definitely lacking some love. If this was helpful for you, maybe you would kind enough to help us out with the doc :smile:

**Comment by prrrnd** [comment]
@groyoh The `include` directive definitely helped. I'll try to update the documentation in a PR.
