### ISSUE TITLE
Could not find jsonapi-parser-0.1.1.beta2 in any of the sources

### ISSUE THREAD

**Issue by BrahimDahmani** [rails-api/active_model_serializers#1956]
#### Expected behavior vs actual behavior

Today i'm not able to build my docker container it says `Could not find jsonapi-parser-0.1.1.beta2 in any of the sources`, in my Gemfile.lock only active_model_serializers depends from jsonapi witch depend from jsonapi-parser

on [rubygems](https://rubygems.org/gems/jsonapi-parser/versions/0.1.1.beta2) i found this

> This version has been yanked, and it is not available for download directly or for other gems that may have depended on it.
#### Environment

ActiveModelSerializers Version _0.10.2_: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

 Built on a Dokcer container (FROM ruby:2.3.0 conatiner image)
 Rails 5 (api-only)

**Comment by NullVoxPopuli** [comment]
you'll need to do a `bundle update active_model_serializers`

That version was mistakenly yanked.

/cc @beauby

**Comment by NullVoxPopuli** [comment]
oh, I see you made a PR. nice

**Comment by NullVoxPopuli** [comment]
the yanked gem has been restored, so it might be a gem cache issue, @BrahimDahmani

**Comment by beauby** [comment]
@NullVoxPopuli The yanked gem has **not** been restored.

@BrahimDahmani `$ bundle update jsonapi` will solve your issue though.

**Comment by Zooip** [comment]
Impossible to use TravisCI with this gem because of this problem

**Comment by beauby** [comment]
@Zooip Update your bundle. C.f. comments above.

**Comment by vyrak** [comment]
Had the same thing happen to me (twice actually, first incident was with `jsonapi 0.1.1.beta4` getting yanked). Can we have `jsonapi` be an optional dependency instead of a runtime dependency? We don't use this gem to serialize models to json api in our project.

**Comment by NullVoxPopuli** [comment]
@vyrak it was a mistake to yank the jsonapi gem. But, like with rails, can you imagine if we made each subset of features optional? that would be somewhat of a pain to install -- while it is a bit of a pain to manage sub dependencies like this when mistakes happen, it's in the majority's best interest to not make subdeps optional.

As @beauby said, `bundle update jsonapi` should fix it.

**Comment by scifisamurai** [comment]
Same issue happened today & yes `bunlde update jsonapi` did fix it, however that seems to strange to need to do that given https://github.com/rails-api/active_model_serializers/commit/cb20b957edbd393c3d09e4bb7b4623ea522cf45b unless there are plans to restore this version soon. 

@beauby will the yanked gem be restored at some point in the future?

**Comment by beauby** [comment]
@scifisamurai The yanked gem is `jsonapi-parser`, which is a dependency of `jsonapi`, and not `jsonapi` itself (v0.1.1.beta2 of which is not yanked: https://rubygems.org/gems/jsonapi/versions/0.1.1.beta2).

**Comment by scifisamurai** [comment]
@beauby Ah gotcha. Sorry got `jsonapi` and `jsonapi-parser` mixed up. Thanks for the clarification.
