### ISSUE TITLE
Relationships with ActiveModelSerializers::Model

### ISSUE THREAD

**Issue by andrewferk** [rails-api/active_model_serializers#1961]
I'm using version 0.10.2 and attempting to create a relationship (`belongs_to`) with `ActiveModelSerializers::Model` (and not `ActiveRecord::Model`). The relationship output keeps returning null.

Thanks!
### Model

``` ruby
class User::Registration < ActiveModelSerializers::Model

  attr_reader :user
  attr_accessor :email

  def save
    register_user
  end

  def email=(value)
    # Follow Devise's configuration to check if email is case insensitive
    @email = Devise.case_insensitive_keys.include?(:email) ? value.try(:downcase) : value
  end

  def id
    email
  end

  private

  def register_user
    @user = User.new(email: email)
    @user.provider = 'email'

    @user.send_confirmation_instructions if @user.save
    @user.clean_up_passwords

    @user.persisted?
  end
end
```
### Resource

``` ruby
class User::RegistrationSerializer < ApplicationSerializer
  attributes :email
  belongs_to :user
end
```
### Controller

``` ruby
def create
  @registration = User::Registration.new(email: @request[:email])
  @registration.save
  render json: @registration, status: :created
end
```
### Ouptut

``` json
{"data": {"id":"a@b.co","type":"user-registrations","attributes":{"email":"a@b.co"},"relationships":{"user":{"data":null}}}}
```

I'd expect the relationships output to not be null.

**Comment by beauby** [comment]
What is the output of `@registration.user` before the save call?

**Comment by andrewferk** [comment]
> What is the output of @registration.user before the save call?

It is `nil`.

It looks like I'm having problems with `ActiveModelSerializers::Model` as it sets `@attributes` in the initializers and [uses it for serialization](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers/model.rb#L32-L38). That doesn't work for me because I'm setting the user using `@user`.

My model has been updated to the following:

```ruby
class User::Registration < ActiveModelSerializers::Model
  include ActiveModel::Model
  include ActiveModel::Serialization
end
```

`ActiveModel::Serialization` sets `alias :read_attribute_for_serialization :send`.

**Comment by beauby** [comment]
As far as I can tell, you're not setting the user, so I do not understand why it would be surprising that the `user` is `nil` in the serialized document?

**Comment by andrewferk** [comment]
It's set in the `User::Registration#register_user` method.

**Comment by beauby** [comment]
As far as I can tell it is never called though.

**Comment by beauby** [comment]
Oops – it is indeed called in the `save` method.

**Comment by beauby** [comment]
What is the value of `@registration.user` **after** the save call?

**Comment by andrewferk** [comment]
It's a `User`, and it did save successfully. I think the change I did will allow this to work, although I haven't gotten around to checking yet.

**Comment by groyoh** [comment]
I guess this is related to #1953. @andrewferk you are right in https://github.com/rails-api/active_model_serializers/issues/1961#issuecomment-256805883. When `@user = ...` is set,  the `@attributes` value is not actually changed and `@attributes`  is the value used for serializing the object ([ref](https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/active_model_serializers/model.rb#L32)). That's an issue with the `AMS::Model` class itself. As mentioned in #1953 I'm not entirely aware of the purpose of `AMS::Model` and if it's really meant to be used outside AMS. @beauby what's your thoughts about that?

**Comment by bf4** [comment]
@andrewferk This is a known bug in AMS::Model that no one has fixed yet. see https://github.com/rails-api/active_model_serializers/pull/1903  until it is fixed, you can either roll your own poro, using AMS::Model as a reference doc (which is part of its intention), or call `attributes[:user] = self.user = User.new(email: email)` instead of `self.user = User.new(email: email)` :(

**Comment by bf4** [comment]
Looks like I've implemented a good chunk of this in https://github.com/rails-api/active_model_serializers/pull/1984

**Comment by axsuul** [comment]
@bf4 Sorry, I did some digging but still not quite sure if this has been fixed or not by your pull request

**Comment by bf4** [comment]
Also see https://github.com/rails-api/active_model_serializers/blob/3c5e11bb0f8d09562af9ee87474922ca4d50ea05/test/fixtures/poro.rb#L6-L26
