### ISSUE TITLE
How to use serializer in another one

### ISSUE THREAD

**Issue by tuxtux59** [rails-api/active_model_serializers#1966]
I'm looking for a way to call another serializer inside one for attribute. Here is my serializer
`class ResidenceSerializer < ActiveModel::Serializer`
`     attributes [....], :items`

My problem is `Item` default serializer bring too much attributes and I need few that already exists in my `ItemLightSerializer`. Is there a way to call `:items each_serializer ItemLightSerializer` or using `has_many` ?

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
'~> 0.9.5'
Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
OS Type & Version: 
MacOS Sierra

Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails 4.2.6

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by richmolj** [comment]
@tuxtux59 I believe you are looking for something like

```ruby
class ResidenceSerializer < ActiveModel::Serializer
  class CustomItemSerializer < ItemLightSerializer
    # move shared code to a mixin or base class, customize here
  end

  has_many :items, serializer: CustomItemSerializer
end
```

Is this along the lines of what you are looking for?

**Comment by tuxtux59** [comment]
Need I absolutely to have `CustomItemSerializer`inside the current Serializer? Can I use `has_many :items, serializer: ItemLightSerializer`?

**Comment by richmolj** [comment]
Absolutely you can just re-use `ItemLightSerializer` if that fits your use case. My solution is more for when `items` customization is very specific to the `ResidenceSerializer` context.

**Comment by tuxtux59** [comment]
Thanks ;)
