### ISSUE TITLE
Values outside of the root.

### ISSUE THREAD

**Issue by Tonkpils** [rails-api/active_model_serializers#197]
So, I have an Account model with it's serializer that looks like this.

``` ruby
class AccountSerializer < ApplicationSerializer
  attributes :id, :name
end
```

This outputs the expected

``` json
{ 
  "account" : { 
    "id" : 90, 
    "name": "Some Account" 
  }
}
```

I'm required to have a status and message in all my responses and I can't seem to figure out a way to do this with AMS. The status and messages are just values given by the controller. 

The output I would like to achieve is something like this:

``` json
{ 
  "account" : { 
    "id" : 90, 
    "name": "Some Account" 
  }, 
  "status" : "success", 
  "message" : "Your account" 
}
```

In a way it'd be sort of like the application layout in views. The only way I was able to come close to this was using `meta` but that wraps the contents in a meta key and I just need the status and messages outside of the account.

**Comment by gabrieltong** [comment]
+1
