### ISSUE TITLE
Include doesn't work on nested associations in serializer

### ISSUE THREAD

**Issue by kaanoo2904** [rails-api/active_model_serializers#1972]
I've already posted this on [Stackoverflow ](http://stackoverflow.com/questions/40564556/serialize-nested-attributes-in-rails) for more help, but I also post it here.

------------

So I have models like this: 

 - `folder`, `up_file` has 1 `chat_room`
 - `chat_room` belongs to `crmable` with polymorphic: true (so 1 `chat_room` may belongs to ` folder` or 1 `up_file`)
 - `chat_room` has many `comments`
 - `comment` belongs to `chat_room` and `user` (who posted the comment)

I've defined all relationship like this:

    class Folder < ApplicationRecord
        has_one :chat_room, as: :crmable, dependent: :destroy
    end
    
    class UpFile < ApplicationRecord
        has_one :chat_room, as: :crmable, dependent: :destroy
    end

    class ChatRoom < ApplicationRecord
        belongs_to :crmable, polymorphic: true

        has_many :comments, dependent: :destroy
        has_many :users, through: :comments
    end

    class Comment < ApplicationRecord
        belongs_to :chat_room
        belongs_to :user
    end

I've follow their tutorial [here][1] but my associations not rendered.

    class FolderSerializer < ActiveModel::Serializer
        
        attributes :id, :name, :ancestry, :creator_name #... my other attributes
        
        has_one :chat_room, include: [ :id, comments: :user ]
        # ^ I tried to serialize folder's chat_room with all it comments, along with these comments' users.
    end

All I got is this - `chat_room` association not serialized?

[![enter image description here][2]][2]

  [1]: https://github.com/rails-api/active_model_serializers/pull/1127
  [2]: https://i.stack.imgur.com/pO5Cv.png

**Comment by beauby** [comment]
Could you point me to where it says in the docs that this is supported? (serializer-level include directives)

**Comment by NullVoxPopuli** [comment]
per that PR's description:

> Note: the serializer-level include option has been dropped for now (i.e. doing has_many :comments, include: 'author, posts' is still not possible).

**Comment by NullVoxPopuli** [comment]
it's highly recommended to use render option's `includes`.
```ruby
render json: @resource, include: 'author,posts'
```
