### ISSUE TITLE
CollectionSerializer defaults to attributes adapter

### ISSUE THREAD

**Issue by AlexVPopov** [rails-api/active_model_serializers#1975]
#### Expected behavior vs actual behavior

Given that @foos is an `ActiveRecord::Relation` of model `Foo` and given that I have set the `json` adapter as the default adapter in an initializer, I expect that

```ruby
ActiveModel::Serializer::CollectionSerializer.new(@foos).as_json
```

 will return this:

```json
{
  "foos": [
    // array of attributes objects for each instance of Foo
  ]
}
```

Intstead I get

```json
{
  [
     // array of attributes objects for each instance of Foo // array of attributes objects for each instance of Foo
  ]
}
```

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

* clone [this repo](https://github.com/AlexVPopov/collection_problem);
* `bundle install`, `rake db:migrate` (the usual setup stuff)
* in `FoosController#index` uncomment `binding.pry`, call `localhost:3000/foos`, switch to the console and execute the command in the next comment - the problem will occur.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: `0.10.2` 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`

OS Type & Version: `Linux Mint 18`

Integrated application and version *(e.g., Rails, Grape, etc)*: `Rails 4.2.7.1`

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

Repo, where the problem occurs: https://github.com/AlexVPopov/collection_problem

Also, I think #1821 describes a similar behavior.

**Comment by bf4** [comment]
@AlexVPopov 

> ActiveModel::Serializer::CollectionSerializer.new(@foos).as_json

Why are you doing that? If that is documented somewhere it should be removed. Can you help?

**Comment by AlexVPopov** [comment]
In [this SO answer](http://stackoverflow.com/a/17914893/1836143) is mentioned the use of `ActiveModel::ArraySerializer.new`. However, I noticed that it is now replaced with `ActiveModel::Serializer::CollectionSerializer` and that's why I tried using it. Otherwise the docs speak of the `CollectionSerializer` [here](https://github.com/rails-api/active_model_serializers/search?l=Markdown&q=CollectionSerializer&utf8=%E2%9C%93) (I guess not much helpful :smile:).

So let me ask you then - how do you serialize a collection (and not a single resource) outside of a render action and by passing the `view_context`?

**Comment by bf4** [comment]
@AlexVPopov yeah, as a general rule, prefer the gems' docs over a stackoverflow answer from three years ago :)

**Comment by bf4** [comment]
https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md  https://github.com/rails-api/active_model_serializers/blob/a032201a91cbca407211bca0392ba881eef1f7ba/docs/howto/passing_arbitrary_options.md#passing-arbitrary-options-to-a-serializer https://github.com/rails-api/active_model_serializers/blob/a032201a91cbca407211bca0392ba881eef1f7ba/docs/general/serializers.md#scope

**Comment by bf4** [comment]
@AlexVPopov any way that would have kept you in the docs before going google would be an appreciated pr

**Comment by AlexVPopov** [comment]
But I couldn't find in the docs how to serialize a collection. [This](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/outside_controller_use.md) only tells you how to serialize a singular resource. What's more, I need to be able to pass the view_context via scope/scope_name.

**Comment by AlexVPopov** [comment]
All the resources you mention are relevant, but I can't put the pieces together.

**Comment by bf4** [comment]
Ok, so the problem is in the docs that it makes it sound like you can only pass in a single resource.  Really, that's the api used in the controller, so whatever you're trying to serialize, is what you'd pass in.

**Comment by NullVoxPopuli** [comment]
SerializableResource works for collections :-)

**Comment by bf4** [comment]
https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/action_controller/serialization.rb#L33

```ruby
# resource = model or [model, model]
# options = whatever
serializable_resource = ActiveModelSerializers::SerializableResource.new(resource, options)
serializable_resource.serialization_scope = options.fetch(:scope) 
serializable_resource.serialization_scope_name = options.fetch(:scope_name) 
serializable_resource.to_json
```

**Comment by AlexVPopov** [comment]
Damn! Thanks guys. I spent sooo much time fighting with this. If only I had tried passing a collection... Thanks a log :heart:

**Comment by bf4** [comment]
@AlexVPopov If you could help update the docs, I'm sure many people would appreciate the PR! (Great way to give back 😉 )

**Comment by bf4** [comment]
( @AlexVPopov The funny thing, it was this sort of problem that got me involved in AMS, haven't a hard time serializing something outside of a controller, so I added a consistent API, SerializableResource)

**Comment by AlexVPopov** [comment]
By the way, just of the record, there is even a [StackOverflow answer](http://stackoverflow.com/a/39606516/1836143) to the same question, which also gives the correct solution.

**Comment by array42** [comment]
What about each_serializer? Some claim that is wrong.

**Comment by bf4** [comment]
@array42 dunno what they're talking about
