### ISSUE TITLE
Filtering associated records

### ISSUE THREAD

**Issue by ITPROz** [rails-api/active_model_serializers#1983]
Hi,

I am having difficultly filtering an associated resources.  I am using JSON API and AMS version 0.10.  As an example i have the following

Author
Has Many - Books

If an author has 2 books
Harry Potter 
Lord of the Rings

And in my show action i do:
author = author.joins(:books).where(books: {title: 'Lord of the Rings')

When i return the object it returns all the books and not the ones filtered.

Any ideas as to what i have done incorrectly?

Thank you
Rudy

**Comment by beauby** [comment]
@ITPROz I think that is an ActiveRecord question rather than an AMS one so I'm closing this issue, but feel free to keep discussing your issue in case someone has a solution.

**Comment by ITPROz** [comment]
Hi @beauby,

I think it is to do with the way AMS handles the relationships (i am prob way off the mark), as looking at the rails console shows that when the books for the author is being serialized it makes a query to the db like 'SELECT * FROM books where author_id = 1' omitting the 'rest' of the query.  

Help appreciated thus far

**Comment by beauby** [comment]
What happens when you issue the same query directly in the console?

**Comment by ITPROz** [comment]
Thanks for the reply.  I simplified the situation but will post the real world console logs:

SELECT `buildings`.* FROM `buildings` INNER JOIN `rooms` ON `rooms`.`building_id` = `buildings`.`id` INNER JOIN `room_availabilities` ON `room_availabilities`.`room_id` = `rooms`.`id` WHERE `buildings`.`id` = 15 AND **(`room_availabilities`.`status_at` BETWEEN '2016-11-08' AND '2016-11-11') AND `room_availabilities`.`booking_id` IS NULL**
[active_model_serializers]   Room Load (3.4ms)  SELECT `rooms`.* FROM `rooms` WHERE `rooms`.`building_id` = 15

Then i get a series of these queries

[active_model_serializers]   RoomAvailability Load (0.4ms)  SELECT `room_availabilities`.* FROM `room_availabilities` WHERE `room_availabilities`.`room_id` = 238
...
[active_model_serializers]   RoomAvailability Load (0.4ms)  SELECT `room_availabilities`.* FROM `room_availabilities` WHERE `room_availabilities`.`room_id` = 245

I have highlighted in the bold the bits in question.  I expected the conditions on the room_availabilties query to be 'used' in the serialization process.

Thank you

**Comment by richmolj** [comment]
@ITPROz believe this is still an ActiveRecord question. What I believe is happening:

```
author = author.joins(:books).where(books: {title: 'Lord of the Rings')
```

This will return `Author` records. Not it will **NOT** eager load books - it only joined on `books` to figure out what `Author` records are returned. So when you call (under the hood) `author.books`, it will return all books for that author.

I *think* you can fix this by:

```ruby
author = author.joins(:books).includes(:books).where(books: {title: 'Lord of the Rings')
```

Which I think is redundant and will be equivalent to

```ruby
author = author.includes(:books).where(books: {title: 'Lord of the Rings')
```

I'm confident this is the problem, but haven't tested the solution.

**Comment by ITPROz** [comment]
Thank you! thank you! you guys are awesome, silly oversight really.  It worked

Thank you very much :)
