### ISSUE TITLE
ActiveModel::Serializer::Fieldset should underscore fields

### ISSUE THREAD

**Issue by nurey** [rails-api/active_model_serializers#2003]
#### Expected behavior vs actual behavior

Given a FooSerializer class with `attribute :foo_name`,
Given `foo`, an instance of Foo model

The following should render a jsonapi document with an attribute of `foo-name`

`render jsonapi: foo, fields: { foos: [ 'foo-name' ] }` 

What actually happens is that `foo-name` is not rendered in the jsonapi document. 

To get `foo-name` to render, the workaround is to `underscore` the field name as follows:

`render jsonapi: foo, fields: { foos: [ 'foo_name' ] }` 

#### Environment

ActiveModelSerializers Version 58ebf96e03272474aa7198b38fbbb01816f2e3e4: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

OS Type & Version: macOS 10.12.2

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 4.2.7.1

**Comment by NullVoxPopuli** [comment]
what's your AMS config?

**Comment by nurey** [comment]
```
ActiveModelSerializers.config.adapter = :json_api

ActiveSupport.on_load(:action_controller) do
  require 'active_model_serializers/register_jsonapi_renderer'
end
```
