### ISSUE TITLE
Using json_api adapter, includes does not eager-load relationships

### ISSUE THREAD

**Issue by tgmerritt** [rails-api/active_model_serializers#2013]
#### Expected behavior vs actual behavior

job = Job.includes(:customer, :products, :payments).where(id: params[:id])

render json: job

Should avoid N+1 query 

OR

render json: job, include: [:customer, :products, :payments] 

Should avoid N+1 query

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

```
  def show
    job = Job.includes(:products, :payments, :customer, :jobtype, :jobpriority).where(id: params[:id]).first

    authorize job

    render json:    job,
           status:  200,
           include: [:customer, :jobtype, :jobpriority, :payments, :products, :equipment]
    
  end
```

```
class Api::V1::JobSerializer < ActiveModel::Serializer
  attributes *Job.column_names

  has_many :products
  has_many :payments
  # belongs_to :user
  belongs_to :customer
  belongs_to :equipment
  belongs_to :jobtype
  belongs_to :jobpriority
end
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

  active_model_serializers (~> 0.10.3)

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

OS Type & Version: 

Mac OS Sierra

Integrated application and version *(e.g., Rails, Grape, etc)*: 

Rails 4.2.7.1

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

```
Started GET "/api/v1/users/30/jobs/1144" for 127.0.0.1 at 2016-12-29 14:56:22 -0600
Processing by Api::V1::Users::JobsController#show as */*
  Parameters: {"user_id"=>"30", "id"=>"1144"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "timnye850@gmail.com"]]
  Job Load (0.3ms)  SELECT  "jobs".* FROM "jobs" WHERE "jobs"."id" = $1  ORDER BY "jobs"."id" ASC LIMIT 1  [["id", 1144]]
  Product Load (9.9ms)  SELECT "products".* FROM "products" WHERE "products"."job_id" IN (1144)
  Payment Load (5.4ms)  SELECT "payments".* FROM "payments" WHERE "payments"."job_id" IN (1144)
  Customer Load (0.4ms)  SELECT "customers".* FROM "customers" WHERE "customers"."id" IN (1028)
  Jobtype Load (0.5ms)  SELECT "jobtypes".* FROM "jobtypes" WHERE "jobtypes"."id" IN (69)
  Jobpriority Load (0.2ms)  SELECT "jobpriorities".* FROM "jobpriorities" WHERE "jobpriorities"."id" IN (60)
[active_model_serializers] Rendered Api::V1::JobSerializer with ActiveModelSerializers::Adapter::JsonApi (147.67ms)
Completed 200 OK in 428ms (Views: 154.5ms | ActiveRecord: 25.2ms)
```

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

I've tried permutations found here in the issues as well as on SO or other blogs on the web.

The consensus is that what I've written above is correct - I pass includes(:stuff) on the query and should avoid N+1 - but it doesn't.

If I try "jobs.to_json" or "jobs.as_json" or anything - it doesn't matter, we hit the DB one time for each include.

This behavior does not happen if I'm not using the AMS gem.  How can I avoid N+1 ?

**Comment by bf4** [comment]
Looks correct to me. One query per included resource.  What queries did you expect?  This doesn't appear to be related to AMS at all, closing.  Please help show where this is an AMS issue,given that AMS doesn't do any eager loading for you (Writing from a lounge chair in Grand Cayman)

**Comment by beauby** [comment]
I do not see any N+1 here either.
