### ISSUE TITLE
Setting `serializer` option to nil still using default serializer.

### ISSUE THREAD

**Issue by esbanarango** [rails-api/active_model_serializers#2014]
#### Expected behavior vs actual behavior
When trying to disable AMS for an specific action, I'm doing:
````ruby
render json: @my_obj, serializer: nil
````
but it keeps using **MyObjSerializer**.

#### Environment

ActiveModelSerializers Version *0.10.3*:

**Comment by bf4** [comment]
@esbanarango is there documentation for passing `serializer: nil`?  The easiest thing to do in this case is just `render json: @my_obj.to_json`. I believe you may also do something like `render json: @my_obj, serializer: :none`.  There are some related issue here I'll dig up

**Comment by matthewrudy** [comment]
I've got a related issue which seems to be:

``` ruby
render json: @my_obj
```

where there exists no `MyObjSerializer`

Consequently I get an empty response `{}`
instead of `@myobj.to_json`

Is that intended?

**Comment by groyoh** [comment]
@matthewrudy would you mind giving more information (the `MyObj` class for example) or opening a new issue please?

**Comment by groyoh** [comment]
So @esbanarango @bf4 i created a gist to test this behavior https://gist.github.com/groyoh/1eb32f55c61d6f90bf64fbda4195d843. Turns out that using `adapter: nil` works fine but the log actually show:

```
I, [2017-01-07T14:21:50.088679 #5791]  INFO -- : Rendered UserSerializer with User (0.12ms)
```

@esbanarango is your output actually correct or is it different than `@my_obj.to_json`?

**Comment by feliperaul** [comment]
Also having this on 0.10.6 and Rails 5.2

**Comment by bf4** [comment]
@feliperaul If you'd like to add this as a feature, PRs appreciated.  Otherwise, please see my comment https://github.com/rails-api/active_model_serializers/issues/2014#issuecomment-270822262 .

My take is that this issue should be closed as stale as OP never came back. However, it could be a feature if someone wants to do that.
