### ISSUE TITLE
BigDecimal is converted into a string

### ISSUE THREAD

**Issue by chrisnicola** [rails-api/active_model_serializers#202]
I'm not sure if this is intentional because of Javscripts lack of support for a decimal. I presume it is? I'm wondering if there is support for specifying how to convert in the serializer classes?

**Comment by afeld** [comment]
FYI, Rails now gives this warning:

> ...in `encode_big_decimal_as_string=': The JSON encoder in Rails 4.1 no longer supports encoding BigDecimals as JSON numbers. Instead, the new encoder will always encode them as strings.
>
> You are seeing this error because you have 'active_support.encode_big_decimal_as_string' in your configuration file. If you have been setting this to true, you can safely remove it from your configuration. Otherwise, you should add the 'activesupport-json_encoder' gem to your Gemfile in order to restore this functionality. (NotImplementedError)

https://github.com/rails/activesupport-json_encoder

**Comment by glovguy** [comment]
What is the proper way to change this setting in Rails 5 ? I've tried adding `ActiveSupport::JSON::Encoding.encode_big_decimal_as_string=false` into `application.rb`, but it throws `NoMethodError: undefined method `encode_big_decimal_as_string=' for ActiveSupport::JSON::Encoding:Module`.

I'm currently running Rails 5.0.0.1

What is the recommended way to change this setting?

**Comment by BigChief45** [comment]
@glovguy Did you find any answer for this?

**Comment by bf4** [comment]
@glovguy @bigchief45 Y'all are commenting on a four-year old issue. Rails has changed a bit since then.  Please open an issue in the Rails tracker, not here, or in Ruby if you think the issue is in stdlib.  Thanks!
