### ISSUE TITLE
Is there a upgrade guide from 0.9.x -> 0.10.x ??

### ISSUE THREAD

**Issue by kapso** [rails-api/active_model_serializers#2028]
Something like this?

https://github.com/rails-api/active_model_serializers/blob/6c6e45b23f464bd0bb92ae05a4284b72b017be21/docs/howto/upgrade_from_0_8_to_0_10.md

Running into lot of issues, so was wondering. For example I am getting `ERROR! NameError: uninitialized constant ActiveModel::ArraySerializer` and cant seem to find the fix.

**Comment by toobulkeh** [comment]
@kapso did you find one?

**Comment by toobulkeh** [comment]
I'll keep some notes for a guide here.

1. Change the adapter to `json`:
```ruby
# in config/initializers/active_model_serializer.rb
ActiveModelSerializers.config.adapter = :json
```

2. On all `respond_with` calls, add full depth includes
```ruby
# in app/controllers/api/*.rb
@collection = Collection.where ...
respond_with @collection, include: "**"
```

**Comment by bf4** [comment]
@toobulkeh Thanks for keeping your notes here. I thought I remembered someone writing up their 0.9 -> 0.10 changes, but didn't want to make a guide because thought they were too idiosyncratic... didn't find it with the upgrade label...

**Comment by bf4** [comment]
Found it https://github.com/rails-api/active_model_serializers/issues/1864#issuecomment-238826170
