### ISSUE TITLE
Add an option to remove log messages

### ISSUE THREAD

**Issue by MSathieu** [rails-api/active_model_serializers#2029]
I would like an option to turn this 
`[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::JsonApi (136.7ms)`
 log message of.

**Comment by bf4** [comment]
@MSathieu Of course, we should reference that in https://github.com/rails-api/active_model_serializers/blob/93ca27fe444c3a940890cb7a4dedbd8369f481f3/docs/general/logging.md along with the [log subscriber](http://api.rubyonrails.org/v4.2/classes/ActiveSupport/LogSubscriber.html) and [active support notifications api](http://api.rubyonrails.org/v4.2/classes/ActiveSupport/Notifications.html).

It's unclear to me if you want to set AMS logger to `Logger.new(IO::NUL)` or just unsubscribe `ActiveSupport::Notifications.unsubscribe(ActiveModelSerializers::Logging::RENDER_EVENT)`  and maybe `ActiveSupport::LogSubscriber.log_subscribers.delete_if {|subscriber| subscriber.instance_of?(ActiveModelSerializers::Logging::LogSubscriber) }` though I haven't tried these myself.

**Comment by MSathieu** [comment]
I want to set `ActiveModelSerializers.logger = Logger.new(nil)`

**Comment by bf4** [comment]
@MSathieu did that resolve your issue?

**Comment by MSathieu** [comment]
`ActiveModelSerializers.logger = Logger.new(nil)` doesnt works,
 `ActiveModelSerializers.logger = Logger.new(IO::NUL)` raises an error,
but `ActiveSupport::Notifications.unsubscribe(ActiveModelSerializers::Logging::RENDER_EVENT)` works perfectly

**Comment by bf4** [comment]
@MSathieu Would you like to make a PR to improve the docs, especially based on how you went about looking for the info?

**Comment by MSathieu** [comment]
I will do that.
