### ISSUE TITLE
Is there a way to set include: '**' globally for all AMS ?

### ISSUE THREAD

**Issue by kapso** [rails-api/active_model_serializers#2032]
I am trying to upgrade from `0.9.3` to `0.10.4` and we have a lot of code that is already doing `includes` and it almost seems like more work trying to duplicate this in AMS calls. 

Also what was the design decision behind delegating includes to AMS? I would like to think that query includes should be done outside AMS.

**Comment by bf4** [comment]
@kapso 

> Is there a way to set include: '**' globally for all AMS ?

yes. Are you having trouble finding it?

> Also what was the design decision behind delegating includes to AMS? 

I'm not sure what you mean.  AMS doesn't treat active record objects differently from other Ruby objects. If that was different in 0-9-stable then I was unaware of that.

**Comment by kapso** [comment]
@bf4 
- Yea I could not find it anywhere. In fact I discovered in issues section this new `include:` requirement for `10.10.4` 
- Yea `include:` was not required in `0.9.3`

**Comment by kapso** [comment]
Found it, phew!!

https://github.com/rails-api/active_model_serializers/issues/2011
