### ISSUE TITLE
human_attribute_name overriding

### ISSUE THREAD

**Issue by eugen0329** [rails-api/active_model_serializers#2049]
#### Expected behavior vs actual behavior
`#human_attribute_name` on class that inherited from ActiveModelSerializers::Model returns it's translation according to ActiveModel::Translation#human_attribute_name functionality.

#### Actual behaviour

`#human_attribute_name` on class that inherited from ActiveModelSerializers::Model returns an attribute passed to it without any translations.

#### Steps to reproduce

1. Create a poro and inherit it from ActiveModelSerializers::Model:

```ruby
class TestObject < ActiveModelSerializers::Model
  attr_accessor :test_attr
end
```
2. Translate attribute with #human_attribute_name:

```ruby
TestObject.human_attribute_name(:test_attr)
```

#### Environment

  active_model_serializers (~> 0.10.2)

#### Additonal helpful information

I found the [method implementation](https://github.com/rails-api/active_model_serializers/blob/58e3983e4c18baea937535038c1324017793f166/lib/active_model_serializers/model.rb#L131) in ActiveModelSerializers::Model, and I have a question. Why do we need this method defined within ActiveModelSerializers::Model when it's already supplied within ActiveModel?

**Comment by bf4** [comment]
@eugen0329 Sounds like you understand the problem well enough to issue a pull request.  Would you be interested in doing that?  I don't see it included in ActiveModel::Model... oh, n/m it has `extend ActiveModel::Translation`

Looks like you're right, based on the active model errors docs https://github.com/rails/rails/blob/4-2-stable/activemodel/lib/active_model/errors.rb

```
  #     # The following methods are needed to be minimally implemented
  #
  #     def read_attribute_for_validation(attr)
  #       send(attr)
  #     end
  #
  #     def self.human_attribute_name(attr, options = {})
  #       attr
  #     end
  #
  #     def self.lookup_ancestors
  #       [self]
  #     end
  #   end
  #
  # The last three methods are required in your object for +Errors+ to be
  # able to generate error messages correctly and also handle multiple
  # languages. Of course, if you extend your object with <tt>ActiveModel::Translation</tt>
  # you will not need to implement the last two. Likewise, using
  # <tt>ActiveModel::Validations</tt> will handle the validation related methods
  # for you.
```
