### ISSUE TITLE
Change default jsonapi_namespace_separator to --

### ISSUE THREAD

**Issue by westoque** [rails-api/active_model_serializers#2062]
Currently, the default has been to dasherize the namespaced model. For example `Admin::User` to `admin-user`. This is bad because the default and standard behavior for camel casing and dasherizing models was from a structure that looks like `MyCamelCase` to `my-camel-case`.

So if you read the namespaced model `admin-user`, from the looks of it, you are expecting `AdminUser` but in reality, is just a namespace. It would be better written `admin--user` by default.

**Comment by bf4** [comment]
@westoque yes, we actually recommend this in our docs https://github.com/rails-api/active_model_serializers/blob/v0.10.4/docs/general/configuration_options.md#jsonapi_namespace_separator

Changing it, however, is a breaking change, so will have to wait for a major version :(
