### ISSUE TITLE
blank include param doesn't override relationships in serializer

### ISSUE THREAD

**Issue by jaredgalanis** [rails-api/active_model_serializers#2063]
#### Expected behavior vs actual behavior
A blank controller include param doesn't seem to be overriding the relationships in my serializer. I thought that the controller include param would take precedence?

my controller:
```
      render json: Requisition.where(account_id: params[:account_id]), include: []
```

ActiveModelSerializers Version *(commit ref if not on tag)*: 
0.10.1

Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails 5.0.0beta4

**Comment by bf4** [comment]
What adapter are you using?

Also, what's preventing you from upgrading AMS and Rails?

**Comment by jaredgalanis** [comment]
@bf4 I am using the JSONAPI adapter. Nothing is preventing me from updating either AMS/Rails, had it on my list to do anyway. I'll try that this evening.

**Comment by jaredgalanis** [comment]
@bf4, I updated to Rails 5.0.2 and AMS 0.10.4 and relationships are still being loaded.

**Comment by jaredgalanis** [comment]
@bf4, I just realized that includes doe something different than I was expecting. Using includes to include additional related records in the response payload works fine for me. If I don't specify includes or my includes param is blank then no additional records are included. When I do include a related record in my includes param that record is included with the response payload as expected.

What I was trying to do, was to get AMS to stop serializing each related record's id in the database query. The reason I wanted to do this is that for a record that is at the top of my model tree, it can take a very long time to load that record and each of its related record's id's. The problem is, I don't always want to do this. Sometimes I need a record's related id's.

Are you aware of anyway to control whether this happens other than not including the relationships in the serializer (not an option for me because I sometime use the relationships)?

**Comment by jaredgalanis** [comment]
Found that I can use links instead of serializing the ids all the relationships of a model.
