### ISSUE TITLE
Do you still accepts PR for 0.9?

### ISSUE THREAD

**Issue by yosiat** [rails-api/active_model_serializers#2064]
Hi,

I have some ideas on how to improve performance, do you still accept a pull request for 0.9?

**Comment by bf4** [comment]
Sure! Do you have a benchmark?

**Comment by yosiat** [comment]
@bf4 I have many improvements to suggest, but before that I want to submit PR with only benchmark s, if that's ok

**Comment by bf4** [comment]
@yosiat Fantastic!

**Comment by yosiat** [comment]
@bf4 what do you think - can I re-use most of the benchmarks from the master branch or do I need to write new ones?

**Comment by bf4** [comment]
@yosiat you can certainly re-use what's on master.  Unfortunately, I think master needs better scenarios that really flesh out the performance differences.. and I haven't encountered a good real-world test case yet

**Comment by yosiat** [comment]
@bf4 closing this in favor of pull request :)

https://github.com/rails-api/active_model_serializers/pull/2066
