### ISSUE TITLE
[0.9] ActiveSupport payload is incorrect

### ISSUE THREAD

**Issue by yosiat** [rails-api/active_model_serializers#2067]
Hi,

By reading the code (and then verifying this), I think I found a bug.
When I am subscribing to the serialize event I only get "serializer" in the payload and not all other instrumentation keys (object, scope, root, meta_key).

### Bug description

By looking at the instrument code:
https://github.com/rails-api/active_model_serializers/blob/0-9-stable/lib/active_model/serializable.rb#L51
```
payload = instrumentation_keys.inject({ serializer: self.class.name }) do |payload, key|
  payload[:payload] = self.instance_variable_get(:"@#{key}")
  payload
end
```
It keeps overriding the payload object with the current instrumentation key's value.

### Perf Impact

I found this code by looking at the object's allocations and found this method as the source of 50% of the allocations.
By replacing the payload to only be `{serializer: self.class.name}` - we get drop off 50% allocations and more ip/s.

Before:
```
Array: DefaultSerializer 726.6811271730311 ip/s  2657 objects
Array: PostFlatSerializer 975.9174166658823 ip/s  2059 objects
```

After:
```
Array: DefaultSerializer 819.9266362390441 ip/s  1957 objects
Array: PostFlatSerializer 1,321.0953937395007 ip/s  1009 objects
```

### Proposal
I suggest to remove instrumentation keys support and sending only the serializer.
Why?

- It's not working today, so nobody relies on it
- In 0.10 we send only `serializer` and `adapter` (If I am not mistaken)

What do you think?

**Comment by yosiat** [comment]
I found a conversation about this in the original commit -  https://github.com/rails-api/active_model_serializers/commit/eaedcefa4e186f60907f50b0980d9cc07fb3a1d3#commitcomment-14831558

**Comment by bf4** [comment]
@yosiat even if it's wrong I think it would be a breaking change... need to take a look

**Comment by yosiat** [comment]
@bf4 how this is going to be a breaking change?
Currently, the payload is nil.
If you remove the payload you preserve your behavior.

**Comment by bf4** [comment]
@yosiat good point

**Comment by bf4** [comment]
strange that no one would have noticed. Been years, no?

**Comment by yosiat** [comment]
@bf4 it looks like that someone noticed it.
https://github.com/rails-api/active_model_serializers/commit/eaedcefa4e186f60907f50b0980d9cc07fb3a1d3#commitcomment-14831558

**Comment by bf4** [comment]
@yosiat well, I meant noticed it and it was a problem...

Anyhow, I'll support a PR to fix it. cc @wagenet

**Comment by yosiat** [comment]
@bf4 Great!
So I will do a pr to change the payload to be on serializer and remove all `instrumentation_keys` ?

**Comment by bf4** [comment]
Sure

**Comment by yosiat** [comment]
Closing since pr is submitted and merged.
