### ISSUE TITLE
Rendering other JSON objects?

### ISSUE THREAD

**Issue by gregblass** [rails-api/active_model_serializers#2078]
I've got a Rails app with an API, and also a web based admin section. For the API I want to use active model serializers, and the 'render json: @collection' syntax works great.

However, in the web/admin section, I'm using DataTable POROs which return JSON - so in those controllers, I want to do 'render json: DataTable.to_json. However, once I added the API to the app and AMS, this functionality breaks.

Is there a way to specify that in some cases, I want render json: to behave in the traditional way?

**Comment by bf4** [comment]
What did you end up doing?

**Comment by gregblass** [comment]
I ended up using jbuilder instead of active model serializers.
