### ISSUE TITLE
How to make model is not handled by active_model_serializer

### ISSUE THREAD

**Issue by ElvisYang** [rails-api/active_model_serializers#2084]
#### Expected behavior vs actual behavior

If I want some model does not use serializer to serialized, how to do that? or I only want some specified model to use serializer?

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

OS Type & Version: 

Integrated application and version *(e.g., Rails, Grape, etc)*: 

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by bf4** [comment]
Closing as it's hard to tell what you're doing and what you've tried.  Are you asking how to render an object without a serializer?
