### ISSUE TITLE
Multiple serialization issue

### ISSUE THREAD

**Issue by sofianegargouri** [rails-api/active_model_serializers#2088]
Hey guys !

I have a model StoryLike, which belongs_to a Story, which belongs to a user and a License. When I index my StoryLikes, with the following Serializer:

    class StoryLikeSerializer < ActiveModel::Serializer
      attributes :created_at
  
      belongs_to :user, serializer: UserPreviewSerializer
      belongs_to :story, serializer: StorySerializer
    end

It is supposed to serialize the story with the right serializer (StorySerializer) which is:

    class StorySerializer < ActiveModel::Serializer
      attributes :id, :title, :summary, :image_url, :published, :likes_count, :published_at
      attributes :category_id
  
      belongs_to :license, serializer: LicenseSerializer
      belongs_to :user, serializer: UserPreviewSerializer
    end

In my callback, in my story preview, I have no license, nor user. When I add them as attributes, they are not serialized. Does someone have a workaround ?

**Comment by charlie-wasp** [comment]
@sofianegargouri hello!

Can you please elaborate, what do you mean by `callback`? Code, where you're using your serializers, would be helpful too :)

**Comment by sofianegargouri** [comment]
Here is my controller, from which I'm trying to get my informations

    class Api::V1::StoryLikesController < Api::V1::ApplicationController
      after_action only: [:index] { set_pagination_headers(:story_likes) }
    
      def index
        @story_likes = StoryLike.all
        @story_likes = @story_likes.story(params[:story_id]) if params[:story_id].present?
        @story_likes = @story_likes.user(params[:user_id]) if params[:user_id].present?
        @story_likes = @story_likes.page(params[:page]).per(params[:per])
    
        render json: @story_likes, each_serializer: StoryLikeSerializer
      end
    end

What I mean by callback is the response I get when I'm running my request (`GET /story_likes`)

**Comment by bf4** [comment]
@sofianegargouri I can't tell what version you're on, what you're expecting, what's happening, or how you're rendering the serializer.

Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
