### ISSUE TITLE
Add support for multiple request meta fields

### ISSUE THREAD

**Issue by priegler** [rails-api/active_model_serializers#2102]
#### Expected behavior vs actual behavior

currently it is possible to specifiy only a **single** meta element:
```ruby
render status: :ok, json: messages, meta: meta, meta_key: "request_meta", each_serializer: MessageSerializer, adapter: :json
```

which results in:
```json    
{
  "messages": [
    {
      "id": "71d70e7b-d8e8-40dc-a511-1a1e82e019c1",
      "author_id": "89727b10-e581-436a-8b7e-7653ba0d3af1",
    }
  ],
  "request_meta": {
    "page_length": 20,
    "total_length": 27,
    ...
  }
}
```

What we would actually need in our case are two different meta attributes in our response like: 
```json    
{
  "messages": [
    {
      "id": "71d70e7b-d8e8-40dc-a511-1a1e82e019c1",
      "author_id": "89727b10-e581-436a-8b7e-7653ba0d3af1",
    }
  ],
  "permitted_actions": {
    ...
  },
  "request_meta": {
    "page_length": 20,
    "total_length": 27,
    ...
  }
}
```

#### Environment

ActiveModelSerializers Version 0.10.4: 
Ruby Version 2.3.1

**Comment by bf4** [comment]
If you want to add another key to the response, probably easiest thing to do is the render the ams serialization before calling render, then merge this other thing into it.
