### ISSUE TITLE
render json does not work

### ISSUE THREAD

**Issue by lal-s** [rails-api/active_model_serializers#2103]
#### Steps to reproduce

I have a gem which I am integration testing using a rails application.
The rails application lives in the spec directory of the  non rails gem. 
The structure is something like this repo I referred: 
[skinny controllers](https://github.com/NullVoxPopuli/skinny_controllers
) .

When I run rspec, from the root directory, my rails application runs as expected  but when it hits the render, the json is not serialized.

The serializers work fine if I run the tests from the rails app but not when I run it from the root gem. 

However, when I debug it does go into the serializer but I think the options={} are missing.

ActiveModelSerializers Version 0.10.5

OS Type & Version:  Mac

Integrated application and version *(e.g., Rails, Grape, etc)*:  Rails 5

no errors in output

**Comment by bf4** [comment]
I'm unable to help with some details on your call to render, your serializer, your argument to render.  Otherwise, I'm only guessing what's happening.

Try something like this:

1. I am calling `render json: thing` and getting ....
1. `thing` is ....
1. My thing has a thing serializer which looks like ...

**Comment by lal-s** [comment]
Sure. Sorry if the question was not clear.

I have an application: `my_app` and it resides within the spec directory of `my_gem` for integration testing.

Here is the directory structure:
`
my_gem
|
|-- spec
|        |---my_app
|                 |             
|                 |
|                 |--- spec
                           |---some tests
'

my_app controller:

`class MyController < ApplicationController

  def show
    @example = //Model which subclasses active record
    render json: @example
  end

end`

my_app Serializer:

`class ExampleSerializer < ActiveModel::Serializer
  attributes :id

end`


my_app behaves as desired if I run it separately and all the tests pass when I run rspec.

However,
I have this scenario where I need to run rspec from the root of `my_gem` to make all the tests in `my_app` run as well i.e I am trying to run `my_app` from `my_gem`. In that case, everything else in `my_app` runs fine except for the serializers. 
The `render json` does not serialize the json

My guess is the serializer do not get loaded when I run `my_app` from the outside  gem.

**Comment by bf4** [comment]
Yeah, this seems like more of a rails/ruby issue than AMS

**Comment by lal-s** [comment]
thank you for the reply. It might be a rails thing, I will look into it.
