### ISSUE TITLE
Tests Fail Due to Grape's Dependencey on Musterman

### ISSUE THREAD

**Issue by cassidycodes** [rails-api/active_model_serializers#2109]
#### Expected behavior vs actual behavior

i.e.: https://travis-ci.org/rails-api/active_model_serializers/jobs/222201929

Grape v0.19.2, released on April 12, started using `'mustermann-grape', '~> 0.4.0'` which in turn uses mustermann `1.0.0`. According to the output from the test suite `mustermann-1.0.0 requires ruby version >= 2.2.0` (although this information conflicts with the [musttermann docs](https://github.com/sinatra/mustermann/tree/v1.0.0#requirements))

#### Potential Solutions

One or more of the following will fix this issue.

- modify [gemspec](https://github.com/rails-api/active_model_serializers/blob/master/active_model_serializers.gemspec#L60) to use grape v0.19.1
- drop Ruby 2.1 as [support for this version has ended](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/)
- As per @bf4's suggestion in #2104, move `active_model_serializers-grape` to its own repo.

**Comment by cassidycodes** [comment]
Edited my comment above to clarify the Grape v0.19.2 release date.

**Comment by cassidycodes** [comment]
@bf4 I'm happy do do any of the above. The most obvious solution to me is to drop 2.1 support and perhaps move active_model_serializers-grape to its own repo just to clean things up.

**Comment by bf4** [comment]
For now let's just 

> modify gemspec to use grape v0.19.1

I don't have energy for the other work atm

**Comment by cassidycodes** [comment]
Thanks. Done! Don't mean to create any extra work with these issues. : ) Hoping to be able to relieve some work once I know the code base better.
