### ISSUE TITLE
Possible to group nested associations by parent relationship using include?

### ISSUE THREAD

**Issue by stevenpslade** [rails-api/active_model_serializers#2127]
I am using the JSON API adapter and outputting associated resources in the "included" member of my Rails API response.

It is working as expected, however, I am wondering if it is possible to group the included data by their parent relationship? So if I make a call to /authors and there are 2 authors with 1 book each the included member will look like this:

```
"included": [
    {
      "id": "1",
      "type": "books",
      "attributes": {
        "title": "My Book"
      },
      "relationships": {
        "author": {
          "data": {
            "id": "1",
            "type": "author"
          }
        }
      }
    },
{
      "id": "2",
      "type": "books",
      "attributes": {
        "title": "Another Book"
      },
      "relationships": {
        "author": {
          "data": {
            "id": "2",
            "type": "authors"
          }
        }
      }
    }
 ]
```

Is it possible to group the included member by the relationship id so it is easy parse out the books by each author?

**Comment by bf4** [comment]
That's really an issue to be addressed by JSON:API jsonapi.org/format/.  Otherwise, you'd have to write your own adapter.

**Comment by stevenpslade** [comment]
Thanks! I guess I was hoping for a way to format it within AMS. I know that with the :json adapater, the nested associations will be rendered among the other attributes, which would mean they are grouped nicely by default.

However, given that I am using this for an API, I guess I should stick with the :json_api included member formatting and then just do some extra parsing on the receiving end.

**Comment by bf4** [comment]
Ok, to close?
