### ISSUE TITLE
What's up with the README docs?

### ISSUE THREAD

**Issue by talsafran** [rails-api/active_model_serializers#2134]
#### Expected behavior vs actual behavior

The first few sections of the README seem to be empty.

![](https://dl.dropboxusercontent.com/spa/0n9xxbuk27dn14b/ldzof63m.png)

Couldn't find the commit that introduced this.

#### Steps to reproduce

RTFM :) https://github.com/rails-api/active_model_serializers/blob/master/README.md

**Comment by hakunin** [comment]
It got wiped out here: https://github.com/rails-api/active_model_serializers/commit/0ef6ac30fc7c6ed8613a880c61ffde6f40d41a83#diff-04c6e90faac2675aa89e2176d2eec7d8L29

**Comment by bf4** [comment]
@talsafran There were some words below the screenshot

![screen shot 2017-05-16 at 11 57 44 am](https://cloud.githubusercontent.com/assets/142914/26118229/b32b5cdc-3a2e-11e7-96a3-0d8ba29524c8.png)

**Comment by bf4** [comment]
@hakunin Thanks for helping out! :)

**Comment by bf4** [comment]
> Couldn't find the commit that introduced this.

I included it at the bottom of the description of what's going on, figuring anyone interested in the details would want the high-level first. I guess I was wrong :(

![screen shot 2017-05-16 at 11 59 57 am](https://cloud.githubusercontent.com/assets/142914/26118281/f33e2a5c-3a2e-11e7-8dc2-9118f600c564.png)
