### ISSUE TITLE
has_many doesn't call the given serializer

### ISSUE THREAD

**Issue by marcosanfilippo** [rails-api/active_model_serializers#2143]
#### Scenario

I'm working on photo collection with mongoDB, where an **album** `embeds_many` **photos** (as mongoDB documents). **Album** has a `title`, each **photo** has a `description`. I'm able to call the album serializer, like this (album contains correct data):

```
render json: album, 
             serializer: AlbumSerializer, 
             root: 'album_details'
```

But I can't get the `each_serializer` on each `photo`, and the relation in **Album** is:

```
has_many :photos,
             class_name: 'MediaType::Photo',
             each_serializer: PhotoSerializer,
             root: 'photo_list'

```

#### Expected behavior vs actual behavior

I wish to have only photo_description, while I get also other details: so, serializer is not called!

#### Backtrace EXAMPLE

What I get:
```
{"album_details"=>
  {
   "album_title"=>"Title",
   "photos"=>
    [{"_id"=>{"$oid"=>"59274532b1011c513e7c48f4"},
      "c_at"=>"2017-05-25T22:57:22.210+02:00",
      "photo_filename"=>"38f1d74d3762af881103c9438a76e5b7.png",
      "u_at"=>"2017-05-25T22:57:22.210+02:00"    }]
   }
}
```

What I want:

```
{"album_details"=>
  {
   "album_title"=>"Title",
   "photos"=>
    [{
      "photo_filename"=>"38f1d74d3762af881103c9438a76e5b7.png",
    }]
   }
}
```

#### Why the "deep" serializer is not called?

**Comment by ssinghi** [comment]
Have you tried using:
```
has_many :photos, class_name: 'MediaType::Photo', serializer: PhotoSerializer, root: 'photo_list'
```

**Comment by marcosanfilippo** [comment]
Do you mean to put all in the same line? 
Yes, nothing changes.

**Comment by marcosanfilippo** [comment]
I changed strategy, I can't find the issue solution.

**Comment by bf4** [comment]
This appears to be a deep nesting question
