### ISSUE TITLE
ActiveModel::Serializer::CollectionSerializer each_serializer

### ISSUE THREAD

**Issue by seb-sykio** [rails-api/active_model_serializers#2154]
#### Expected behavior vs actual behavior
expected :
ActiveModel::Serializer::CollectionSerializer.new(options, each_serializer: OptionSelectedSerializer)
should use OptionSelectedSerializer

actual : 
ActiveModel::Serializer::CollectionSerializer.new(options, each_serializer: OptionSelectedSerializer)
use OptionSerializer

adapter: :json

ruby 2.4.1
active_model_serializers 0.10.6

**Comment by bf4** [comment]
either don't do that or read the source code. That's not a recommended way to use the library.

**Comment by robbie-mcfarlane** [comment]
You should use 'serializer' instead of 'each_serializer' as you're already using the ActiveModel::Serializer::CollectionSerializer:

`ActiveModel::Serializer::CollectionSerializer.new(options, serializer: OptionSelectedSerializer)`

**Comment by array42** [comment]
Now it serializes the object, but does not insert the correct node name.
'''        <activeRecordRelations>
            <activeRecordRelation>
                <activeRecordRelation>'''

**Comment by bf4** [comment]
@array42 Please open a new issue and/or see my original comment
