### ISSUE TITLE
Support extending cache_store fetch

### ISSUE THREAD

**Issue by ledhed2222** [rails-api/active_model_serializers#2155]
#### Background
I'd like to record cache hit rates for a complex serialization. IE something like this:
```ruby
cache_hit = true
result = Rails.cache.fetch(key) do
  cache_hit = false
  get_obj
end
record_hit_metric(cache_hit ? 1 : 0)
result
```
Ideally, this would be possible by overriding some method from `Caching`. However, the actual calls to the cache in that module are disparate and hidden. To accomplish this it looks like I'll have to re-implement `fetch_attributes`, rather than overriding it.

#### Expected behavior
Instead, it would be cool if `Caching` has one unified method wrapping actual call to the underlying cache. This way users can override/extend at the lowest level.

#### Steps to reproduce
N/A

#### Environment

ActiveModelSerializers Version 10.2/10.6

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`

OS Type & Version: 
OS X 10.12

Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails 4

**Comment by ledhed2222** [comment]
FYI - if there isn't another way to do this and there's agreement on this I'm happy to make a PR. Seems easy to implement.

**Comment by bf4** [comment]
@ledhed2222 you probably just want to either subscribe to the cache events (using active support notifications) or add a special ActiveSupport::Cache.logger https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/cache.rb#L156 

In any case, I don't believe this is in scope for AMS. Thanks! Let me know how using the logger works.

**Comment by ledhed2222** [comment]
oh that's really cool @bf4 - I hadn't used notifications before. Looks like it will even pass the hit in the payload! Thanks. Closing this issue.
