### ISSUE TITLE
API for cache pre-fetching

### ISSUE THREAD

**Issue by ledhed2222** [rails-api/active_model_serializers#2157]
#### Expected behavior vs actual behavior
There may be another way to do this, so please bear with me.

I have a complex and high-traffic serialization that will benefit from caching. I want to proactively write the cache just after it is invalidated (only for the most common invalidations). I've implemented this just fine, but it took a bit of source diving and wasn't particularly obvious how to access an AMS cache key from outside the serializer. The most opaque piece was that AMS adds the serializer adapter's name to the end of the key. I've accomplished this by writing a serializer method:

```ruby
def public_object_cache_key
  "#{object_cache_key}/#{self.class.serialization_adapter_instance.cache_key}"
end
```

Then in the model itself writing to that cache key.

Is there a reason why this there's no easy way to get a cache key for a serializer?

**Comment by ledhed2222** [comment]
Again - happy to put together a PR if there's agreement :)

**Comment by bf4** [comment]
well `serialization_adapter_instance` won't always the be same. Isn't there just `cache_key` method on the serializer instance?

Ok, I asked, but then went and looked. and found https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/active_model/serializer/concerns/caching.rb#L267-L276 it's just `serializer.cache_key(adapter_instance)`   (yeah, it's dumb that the adapter_instance is there just so we can call `adapter_instance.cache_key`. I'd support a PR to clean that up)


```ruby
      def cache_key(adapter_instance)
        return @cache_key if defined?(@cache_key)

        parts = []
        parts << object_cache_key
        parts << adapter_instance.cache_key
        parts << serializer_class._cache_digest unless serializer_class._skip_digest?
        @cache_key = expand_cache_key(parts)
      end
```

In any event, what are you using the cache key for once you calculate it? It sounds like you're expiring it even when the serialization doesn't change?

**Comment by ledhed2222** [comment]
The use case here is for a serialization that is complex, hit frequently, and also frequently invalidated by user actions. It's also scoped to multiple users, so one resource will have several parallel serializations for each scope.

Since there are some obvious and frequent cases where a user will invalidate the cache, I'd like to not just invalidate the prior cache (which happens automatically due to key design), but also proactively write to the new cache so that we ensure a cache hit at the next request.

So I calculate the cache key and then manually call `Rails.cache.write` on it.

**Comment by ledhed2222** [comment]
K I'll put together a PR and we can pick up this discussion there :)

**Comment by ledhed2222** [comment]
Looks like I don't have permissions to push branches - but I have a simple PR for addressing this. Just adding a `cache_key` method to `ActiveModelSerialzers::SerializableResource` should do the trick:

```ruby
def cache_key
  serializer_instance.cache_key(adapter)
end
```

Then if you're outside of a controller and want to manually write to the cache you could do this:

```ruby
user = User.find(1)
serializable = ActiveModelSerializers::SerializableResource.new(user, for_self: true)
Rails.cache.write(serializable.cache_key, serializable.as_json)
```

What do you think? Will open the PR once I'm allowed to push branches :)

**Comment by bf4** [comment]
@ledhed2222 you can make a PR from a fork :)

**Comment by ledhed2222** [comment]
derp , thanks @bf4
