### ISSUE TITLE
Generator not found in master

### ISSUE THREAD

**Issue by vedant1811** [rails-api/active_model_serializers#2163]
I ran `rails g serializer Model` but I get a generator not found error while using master i.e. `gem 'active_model_serializers', github: 'rails-api/active_model_serializers'`

It works in the latest stable version i.e. `gem 'active_model_serializers'`

**Comment by remear** [comment]
As mentioned in the README:

> Master, for the moment, won't have any released version of AMS on it

Sounds like you want to alter that line in your Gemfile to specify the `0-10-stable` branch.

**Comment by vedant1811** [comment]
@remear, in the [0-10-stable README](https://github.com/rails-api/active_model_serializers/tree/0-10-stable#about) it is mentioned:

> It is generally safe and recommended to use the master branch.

That is why I chose to use `master`.

**Comment by remear** [comment]
@vedant1811 A very good point. Would you like to open a PR against 0-10-stable to correct that?

**Comment by bf4** [comment]
Lulz, oops on me 😊
