### ISSUE TITLE
Second Request gets NameError (uninitialized constant ActiveModelSerializers...)

### ISSUE THREAD

**Issue by LucasCioffi** [rails-api/active_model_serializers#2165]
#### Expected behavior vs actual behavior
Using Firefox, the first time I visit http://localhost:3000/chatrooms/0.json I get a successful JSON response.

Without changing anything, if I reload the page, I get this error: 
```
NameError in CommunitiesController#chatrooms
uninitialized constant ActiveModelSerializers::CommunitySerializer
```

Then if I go to that file using my text editor (Atom) and merely save any ruby file without making any changes and reload the page, there is no error. Strange!

I can reload the page and see the error 10 times, but the only way to not see the error is to save the file (even if no changes are made) and then to reload.

This seems quite unusual.  Any suggestions as to which direction should I investigate?

**Comment by beauby** [comment]
Looks like an autoloading issue. Also, why namespace your serializers under `ActiveModelSerializers`?

**Comment by LucasCioffi** [comment]
@beauby Nice!

Changing 
`serialization = ActiveModelSerializers::CommunitySerializer.new(community, options)` to 
`serialization = CommunitySerializer.new(community, options)` did the trick!

So thankful!
