### ISSUE TITLE
ArgumentError: wrong number of arguments (given 0, expected 1+)

### ISSUE THREAD

**Issue by r72cccp** [rails-api/active_model_serializers#2173]
#### Expected behavior vs actual behavior
in `lib/active_model/serializer.rb:340:in `initialize'`:
```ruby
return Enumerator.new unless object
```

throw error:
`ArgumentError: wrong number of arguments (given 0, expected 1+)`

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

when i read documentation for Enumerator, i'm find, that it's expect [minimum one argument](https://ruby-doc.org/core-2.2.0/Enumerator.html#method-c-new), but in line 340 no arguments passed.

#### Environment

ActiveModelSerializers Version 0.10.6: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]`

OS Type & Version: `Linux u116 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Integrated application and version *(e.g., Rails, Grape, etc)*: 
`rails-5.0.5`

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*
```
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:340:in `initialize'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:340:in `new'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:340:in `associations'",
../active_model_serializers-0.10.6/lib/active_model/serializer/concerns/caching.rb:195:in `block in object_cache_keys'",
../active_model_serializers-0.10.6/lib/active_model/serializer/collection_serializer.rb:5:in `each'",
../active_model_serializers-0.10.6/lib/active_model/serializer/collection_serializer.rb:5:in `each'",
../active_model_serializers-0.10.6/lib/active_model/serializer/concerns/caching.rb:192:in `object_cache_keys'",
../active_model_serializers-0.10.6/lib/active_model/serializer/concerns/caching.rb:177:in `cache_read_multi'",
../active_model_serializers-0.10.6/lib/active_model/serializer/collection_serializer.rb:23:in `serializable_hash'",
../active_model_serializers-0.10.6/lib/active_model/serializer/association.rb:56:in `serializable_hash'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:401:in `block in associations_hash'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:348:in `yield'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:348:in `block (2 levels) in associations'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:343:in `each'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:343:in `block in associations'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:399:in `each'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:399:in `each_with_object'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:399:in `associations_hash'",
../active_model_serializers-0.10.6/lib/active_model/serializer.rb:360:in `serializable_hash'",
```

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

AMS 0.10.6

**Comment by andrjuha01** [comment]
@r72cccp Sorry, I can be wrong right here, but in documentation you can really find another example of creating object.
```new(size = nil) { |yielder| ... }```.
In that way, the size would be nil, but it would yield a block given after it.
Like here:
```
fib = Enumerator.new do |y|
  a = b = 1
  loop do
    y << a
    a, b = b, a + b
  end
end
```

**Comment by drn** [comment]
I ran into this as well.

I didn't track down the reason why `object` did not exist, but this pull addresses the issue -
 https://github.com/rails-api/active_model_serializers/pull/2179

```
irb(main):001:0> Enumerator.new
ArgumentError: wrong number of arguments (given 0, expected 1+)
        from (irb):1:in `initialize'
        from (irb):1:in `new'
        from (irb):1
        from /Users/darrencheng/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
irb(main):002:0> Enumerator.new { }
=> #<Enumerator: #<Enumerator::Generator:0x007fdc64b55a20>:each>
```

**Comment by bf4** [comment]
Hmm, don't know how I missed that in implementation and test

**Comment by bf4** [comment]
Fixed by https://github.com/rails-api/active_model_serializers/pull/2179
