### ISSUE TITLE
Plans to generate API documentation

### ISSUE THREAD

**Issue by cesarjr** [rails-api/active_model_serializers#2174]
Hi!

Do you have any plan to generate API documentation using AMS? Fo example using Swagger.

Thanks.

**Comment by bf4** [comment]
@cesarjr Depending on what you mean, it already exists, or there aren't active plans.  It wouldn't be too hard. If by Swagger you imply JSON-SCHEMA, then that's probably a good idea, but not in the pipes.  Also, documentation for a schema/serialization structure is a bit different from API docs. API docs would include a /users endpoint.  AMS would just be like here's the different things you can do to serialize a user.
