### ISSUE TITLE
[Bug] ID of a relationship not reading the overridden ID attribute on the serializer of the relationship

### ISSUE THREAD

**Issue by dasnixon** [rails-api/active_model_serializers#2178]
Version: `0.10.6` - Expect the ID of the relationship to first be read from the serializer, then the object.

There is no issue on `0.10.4`

I can help whip up a PR soon, just don't have the time at this moment. Figured you could fix this pretty quick (if it's a bug).

```
module Api
  module V1
    class QuoteSerializer < ActiveModel::Serializer
      attributes :id, ...
      ...
      # uses friendly_id gem
      belongs_to :adventure,
        serializer: Api::V1::AdventureSerializer
      ...
    end
  end
end
```

```
module Api
  module V1
    class AdventureSerializer < ActiveModel::Serializer
      attributes :id, ...
      ...
      def id
        object.to_param
      end
      ...
    end
  end
end
```

From `0.10.4`
<img width="567" alt="0 10 4" src="https://user-images.githubusercontent.com/672057/29736786-7df41eac-89b9-11e7-9844-1071af104e4e.png">

From `0.10.6`
<img width="563" alt="0 10 6" src="https://user-images.githubusercontent.com/672057/29736829-d22f10ee-89b9-11e7-8d8d-6a6002f1f30b.png">

Thanks!

**Comment by onomated** [comment]
Also seeing in 0.10.5

**Comment by onomated** [comment]
@dasnixon Haven't tried this on 0.10.6, but found a bug in my serializer where I was specifying `id` as an attribute.  I removed the id attribute definition and only keep the id method and it works fine for me in 0.10.5

**Comment by dasnixon** [comment]
Oh interesting, I'll try that and get back to you @onomated. Thanks.

**Comment by bf4** [comment]
this is because belongs_to default changed to read the id on self, which means it's not instantiating the association and, with it, the association serializer....

related:
- https://github.com/rails-api/active_model_serializers/pull/2211
- https://github.com/rails-api/active_model_serializers/pull/2151
- https://github.com/rails-api/active_model_serializers/pull/2140
