### ISSUE TITLE
Does not allow serialization for purposes of Creating Resources

### ISSUE THREAD

**Issue by xn** [rails-api/active_model_serializers#2180]
#### Expected behavior vs actual behavior
I expect to be able to serialize an object without an id for the purpose creating a resource.
Current behavior returns: `{data: null}`

#### Steps to reproduce
```
let(:user_attributes) { FactoryGirl.build(:user) }
post "/v1/users", params: ActiveModelSerializers::Adapter::JsonApi.new(UserSerializer.new(user_attributes)).serializable_hash
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
Everything south of `73eae19b3d0b8a3c03fda566a208eeee6720beed`

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

From the spec:
[Creating Resources](http://jsonapi.org/format/#crud-creating)
```A resource can be created by sending a POST request to a URL that represents a collection of resources. The request MUST include a single resource object as primary data. The resource object MUST contain at least a type member.```
This is implying that the resource object MAY contain an id, not MUST.

Also here:
https://github.com/rails-api/active_model_serializers/issues/2132

**Comment by bf4** [comment]
Fixed by #2216
