### ISSUE TITLE
Custom relationship not serialized properly

### ISSUE THREAD

**Issue by devtoro** [rails-api/active_model_serializers#2182]
Hello all ! I have a rails 5 application and I am using active model serializers **v 0.10.6** and the oj gem. 

I have a custom relationship in one of my models:
`class Team < ApplicationRecord`

 `  # Associations`
 `  has_many :users`
 `   has_and_belongs_to_many :projects`
 `   belongs_to :team_leader, class_name: 'User'`
`end`

and here is my serializer:

`class TeamSerializer < ActiveModel::Serializer`
`  attributes :id, :name, :can_delete, :can_edit`

`  has_many :projects`
`  has_many :users`
`  belongs_to :team_leader`
`end`

When I serialize a team object or a collection of team objects, team leader is in the relationships, but it is of type '**team-leaders**' instead of '**users**'. Is there a way to manually fix this issue or any other possible solution ?

Thanks!

**Comment by remear** [comment]
Sounds like you might be looking for https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/serializers.md#type

**Comment by jstdoit** [comment]
I met the same problem, did you solve this problem? @devtoro

**Comment by bf4** [comment]
@jstdoit please create a new issue and follow the issue template. There's not enough info to help you.

This issue should have been closed as stale with no response from OP.
