### ISSUE TITLE
Deserialize JSONapi

### ISSUE THREAD

**Issue by imadmoussa1** [rails-api/active_model_serializers#2187]
Hello ,
I am working on a rails api , that make calls to other apis using JSON api .
Those api are dynamic , It is possible to deserialize there response using active model Deserializes, without creating new models in our project ?

Thank you .

**Comment by NullVoxPopuli** [comment]
There are a couple ways: 
https://github.com/NullVoxPopuli/rails-NPlusOneTests/blob/master/deserialization_benchmark.rb#L98-L109

:-)
