### ISSUE TITLE
ID attribute is always shown for JsonApi adapter

### ISSUE THREAD

**Issue by sintro** [rails-api/active_model_serializers#2202]
The problem is when you use  JsonApi adapter and do not want id attribute to be hidden in serialized json output, you just can not achieve this.
If you try to remove :id from attributes method, it is still appears in output. If you try to override id method to nil or empty string, all the object will be empty.

**Comment by beauby** [comment]
Per the [JSON:API spec](http://jsonapi.org/format/#document-resource-objects):
> A resource object MUST contain at least the following top-level members:
> * id
> * type
