### ISSUE TITLE
Two-level nested objects don't get serialized

### ISSUE THREAD

**Issue by dkniffin** [rails-api/active_model_serializers#2203]
#### Expected behavior vs actual behavior

I'd like to be able to nest objects as deep as I'd like using `has_many` or `belongs_to`, and have them all serialize correctly. Currently, it looks like it only serializes correctly for one level.

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

Here's the example code I've come up with, using POROs

```ruby
class Dog < ActiveModelSerializers::Model
  attributes :name, :id
end

class Owner < ActiveModelSerializers::Model
  attributes :dog, :name
end

class OwnerGroup < ActiveModelSerializers::Model
  attributes :owners
end


class DogSerializer < ActiveModel::Serializer
  attributes :name
end

class OwnerSerializer < ActiveModel::Serializer
  attributes :name
  has_one :dog
end

class OwnerGroupSerializer < ActiveModel::Serializer
  has_many :owners
end


spot = Dog.new(id: 1, name: 'Spot')
joe = Owner.new(name: 'Joe', dog: spot)
rintintin = Dog.new(id: 2, name: 'Rintintin')
jack = Owner.new(name: 'Jack', dog: rintintin)
group = OwnerGroup.new(owners: [joe, jack])

ActiveModelSerializers::SerializableResource.new(group).as_json
```

I would expect this to return 

```
{
  :owners=>[
    {
      :name=>"Joe",
      :dog=>{
        :name=>"Spot"
      }
    }, 
    {
      :name=>"Jack",
      :dog=>{
        :name=>"Rintintin"
      }
    }
  ]
}
```

but it actually returns:

```
{
  :owners=>[
    {:name=>"Joe"}, 
    {:name=>"Jack"}
  ]
}
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
`0.10.5`

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

OS Type & Version: 
`MacOS 10.12.3`

Integrated application and version *(e.g., Rails, Grape, etc)*: 
`Rails 5.1.3`

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

N/A

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

N/A

**Comment by bf4** [comment]
ref https://github.com/rails-api/active_model_serializers/pull/1958 should resolve your issue?

**Comment by dkniffin** [comment]
Yes, that would have helped :) Would you mind explaining why `**` isn't recommended?

**Comment by dkniffin** [comment]
I just left a comment that the PR you linked to might need to be closed. The documentation is already available, I just missed it.
