### ISSUE TITLE
dynamic root Key in ActiveModel Serializers

### ISSUE THREAD

**Issue by kingstonAccionsLabs** [rails-api/active_model_serializers#2208]
I am using `Rails 5` and `Acive Model Serializer (0.10.6)` in my project. I need below format of JSON 

    {
       "account_lists": {
        "0": {
                "id": 1,
                "description": "test tets test tets"
              },
         "1": {
                "id": 2,
                "description": "test tets test tets"
              }
          }
    }

`0`,`1` keys would be the index of the object.  

I tried with below code, But result is not coming

`account_serializer.rb`

    class AccountSerializer < ActiveModel::Serializer
      attributes :custom_method
 
      def custom_method
     	{ object.id => {id: object.id, description: object. description } }
      end
    end

`accounts_controller.rb`

    render json: @accounts, root: "account_lists", adapter: :json

Result is

    {
    "account_lists": [
        {
            "custom_method": {
                "46294": {
                    "id": 46294,
                    "description": "test tets test tets"
                }
            }
        },
        {
            "custom_method": {
                "46295": {
                    "id": 46295,
                    "description": "test tets test tets"
                }
            }
       ]
     }

Could you please help me to get the result.

[https://stackoverflow.com/questions/46890409/custom-key-in-activemodel-serializers](url)

**Comment by bf4** [comment]
How about:


```ruby
class AccountSerializer < ActiveModel::Serializer
  attributes :id, :description
end
```

Then you'll get

```json
{
   "account_lists": [
    {
            "id": 1,
            "description": "test tets test tets"
    },
     {
            "id": 2,
            "description": "test tets test tets"
    
      }
   ]
}
```

which you can iterate in javascript to get the format you want

**Comment by kingstonAccionsLabs** [comment]
@bf4 Thanks for you comment. I can do it, But I have a production runing application in that am following the same JSON structure, If I change the structure more changes will come in front end, So only I asked for this exact format.

Thanks.

**Comment by bf4** [comment]
You can do the same thing in Ruby.  Nothing's stopping you from :) `¯\_(ツ)_/¯`

**Comment by beauby** [comment]
@kingstonAccionsLabs You could do it in many ways (overriding the renderer, or writing your own adapter). Basically, what you want to do in every case is:
```ruby 
def post_process(hash)
  {
    hash.keys.first => Hash[hash.values.first.map { |x| [x.delete('id').to_s, x] }]
  }
end
```

Example input:
```json
{
   "account_lists": [
    {
            "id": 1,
            "description": "test tets test tets"
    },
     {
            "id": 2,
            "description": "test tets test tets"
    
      }
   ]
}
```

Example output:
```json
{
   "account_lists": {
    "1": {
      "description": "test tets test tets"
    },
    "2": {
      "description": "test tets test tets"
    }
  }
}
```
