### ISSUE TITLE
Association variables not changing

### ISSUE THREAD

**Issue by laclance** [rails-api/active_model_serializers#2209]
An Activity has one Term. A Term has many Translations. 
A Translation has one TranslationImage. 
A TranslationImage has one attachable, Image (which uses paperclip) 

Here are my serializers:

```
class ActivitySerializer < ActiveModel::Serializer
  attributes :id, :name, :term

  has_one :task
  has_one :term

end
```

```
class TermSerializer < ActiveModel::Serializer
  attributes :id, :display_name, :translations

  has_many :translations

end
```

```
class TranslationSerializer < ActiveModel::Serializer
  attributes :id, :title, :definition, :term_id, :image_name

  def image_name
    'HELLO'
    # object.translation_image.attachable.image_file_name
  end

end
```

Previously image_name was image_url, like so:

```
  def image_url
    s3_url + object.translation_image.attachable.image_file_name
  end
```

But when requesting an activity I still get image_url, example below:

> activities_controller#show

`render json: Activity.find_by_id(params[:id])`

> result

```
{
    "id": 3,
    "name": "F_F1_1",
    "term": {
        "id": 2,
        "display_name": "Function",
        "translations": [
            {
                "term_id": 2,
                "id": 5,
                "title": "Umsebenzi",
                "definition": "umsebenzi lunxibelelwano",
                "image_url": ""
            }
        ]
}
```

#### Environment

ActiveModelSerializers V 0.10.0

ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

Rails 4.20

MacOSX Sierra 10.12.6

**Comment by beauby** [comment]
This is a usage issue. Make sure you modified the right files and restart your server.

**Comment by laclance** [comment]
sorry so you saying everything looks right? i have restarted my server locally and on heroku, and checked the files many times, also can't find any trace of image_url.

**Comment by beauby** [comment]
I'm saying that if there's no trace of `image_url` in your code, but you see an `image_url` attribute in your server responses, then the code running on your server is not the code you audited.

**Comment by laclance** [comment]
No its not the server, i get the same issue locally.
