### ISSUE TITLE
serializer: nil doesn't exclude object from serializer

### ISSUE THREAD

**Issue by greggawatt** [rails-api/active_model_serializers#2221]
I expect the line
`render json: @breeds, serializer: nil`
to allow me to skip the active model serializer, but it doesn't

What is the proper syntax?

**Comment by greggawatt** [comment]
Nevermind found that
`adapter: nil` 
works

**Comment by brunoocasali** [comment]
Idk but at log:
```
I, [2018-08-21T03:57:21.486177 #7]  INFO -- : [123b6fc9-1197-4d1c-b653-075b728bafa1] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (32.68ms)
```
I still getting this...

**Comment by kofiasare** [comment]
adapter: nil works.
