### ISSUE TITLE
Failed to migrate from 0.8 to 0.10

### ISSUE THREAD

**Issue by rc-eddy** [rails-api/active_model_serializers#2225]
Hi,

I've tried to follow [this guide](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/howto/upgrade_from_0_8_to_0_10.md) to migrate from 0.8 to 0.10, but when I test my Rails 4 app I get `NameError: uninitialized constant ActiveModel::V08`.

Can you clarify the 
> Add this class to your app however you see fit.

part? I've tried adding the classes as separate files under `/lib` and `/app/serializers` but it didn't seem to work.

**Comment by bf4** [comment]
Hi @rc-eddy That's really a Rails question, if I understand you.  Rails adds `app/**/*` to the autoload path, which it relies on for automatic constant loading.  Rails would expect `ActiveModel::V08` to be in `app/serializer/active_model/v08`, or, if you add `lib` to your autoload paths, `lib/active_model/v08`.  For more details, see rails docs on constant lookup, and me know if this helps!  Good luck!.
