### ISSUE TITLE
Relationships of relationships are being included in payload

### ISSUE THREAD

**Issue by EduardoBautista** [rails-api/active_model_serializers#2228]
Version 0.10.7

Say you have:

```ruby
class BookSerializer
  has_many :chapters
end

class ChapterSerializer
  has_many :paragraphs
end

class ParagraphSerializer
end
```

If your controller is:

```ruby
module Api
  module V1
    class BooksController < ApiController
      def index
        books = Book.all
        render json: books, include: [:chapters]
      end
    end
  end
end
```

The request will also include all of the paragraphs.  For that behavior, shouldn't you need to do:

```render json: books, include: [chapters: :paragraphs]```

**Comment by bf4** [comment]
I assume you're using the JSON adapter? Have you see default_includes somewhere?

**Comment by EduardoBautista** [comment]
@bf4 I don't even know `default_includes` existed.  I haven't used it.

**Comment by bf4** [comment]
You're right that it shouldn't be including paragraphs. I was asking if you might have a config /initializer setting somewhere, but that's a default, so should still shouldn't see paragraphs when passing an option.  Could you help make a failing test?

does this do anything?
```

      fields: {books: [:id, :name], chapters: [:name]}, include: [:chapter]
```

**Comment by EduardoBautista** [comment]
Including the fields option resolves the issue!  Thanks for the help!

**Comment by bf4** [comment]
So, @EduardoBautista would you like to close this?

**Comment by EduardoBautista** [comment]
Will do.
