### ISSUE TITLE
Memory leak with complex JSON serialization

### ISSUE THREAD

**Issue by christopherdbull** [rails-api/active_model_serializers#224]
I'm getting some weird behaviour where memory isn't being freed and is being allocated in what seems like quite large amounts each request where serialization is performed.  The requests involve quite a bit of nested json relationships with the result being an array of up to 20 relatively complicated hashes.  I'm also not performing much eager loading at this point either, but I can't imagine why that would be causing such huge memory leaks (~40mb per request).

My serialization code:

Root serializer (popup):

``` ruby
class Api::V1::PopupSerializer < ActiveModel::Serializer
  attributes :id, :text, :comments_count, :time_string

  has_many :comments, :each_serializer => Api::V1::CommentSerializer
  has_one :owner, :serializer => Api::V1::UserSerializer 
  has_one :place, :serializer => Api::V1::PlaceSerializer

  def comments_count
    object.comments.count
  end

  def time_string
    object.time_since_now_in_words + " ago"
  end
end
```

User serializer:

``` ruby
class Api::V1::UserSerializer < ActiveModel::Serializer
  attributes :id, :full_name, :is_friend, :profile_image, :current_user_friendship, :friend_count, :location
  def current_user_friendship
    if options[:scope].present?
      if object.friends.include?(options[:scope])
        return object.friendships.where(:friend_id => options[:scope].id).select([:id, :user_id, :friend_id, :confirmed]).first
      else
        return object.inverse_friendships.where(:user_id => options[:scope].id).select([:id, :user_id, :friend_id, :confirmed]).first
      end
    end
  end

  def is_friend
    if scope.is_friend?(object)
      true
    else
      false
    end
  end

  def profile_image
    if object.profile_image?
      {
        :thumb70 => object.profile_image.url(:thumb70),
        :thumb104 => object.profile_image.url(:thumb104)
      }
    else
      nil
    end
  end

  def friend_count
    object.all_confirmed_friends.length
  end
end
```

Comment serializer:

``` ruby
class Api::V1::CommentSerializer < ActiveModel::Serializer
  attributes :id, :body, :popup_id, :popup_owner_id, :time_string

  has_one :user, :serializer => Api::V1::UserSerializer

  def popup_owner_id
    object.popup.owner_id
  end

  def time_string
    object.time_since_now_in_words + " ago"
  end
end
```

Place serializer:

``` ruby
class Api::V1::PlaceSerializer < ActiveModel::Serializer
  attributes :id, :title, :point, :distance_from_current_location, :address

  def point
    object.geographic_point_hash
  end

  def distance_from_current_location
    if scope.current_location_point
      object.distance_from_point_in_km(scope.current_location_point).to_s + " km away"
    end
  end
end
```

Thanks, can provide anything else that's needed as well

**Comment by danabr75** [comment]
Why is this issue closed? I don't see any resolution.

I'm having the same problem, same complex nested JSON relationships, same sized chunks of memory lost. I was able to determine that memory was only being lost on serializers with the complex relationships. Simple ones, just with attributes, worked just fine.

Started on v0.8.1, but updated to the latest (0.10.5, 0.10.4) and the problem persists.

Additional information:
rails: 4.1.16
ruby_version: 2.2.4, 2.3.1 (tried both)

**Comment by bf4** [comment]
@danabr75 Per my reading of the issue, it was closed in 2013 by OP with no resolution.  It seems we might benefit from having a new issue that describes your situation in detail.

**Comment by wmakley** [comment]
I'm experiencing what I believe to be memory leaks in the current version in Rails 5.2 development mode. (Production mode is fine.) It could totally be another part of Rails, but I'm having trouble isolating it, and it doesn't happen until I start trying to work on my SPA pages that use active_model_serializers heavily.

**Comment by bf4** [comment]
@wmakley Thanks for your help!
