### ISSUE TITLE
JSON not give correct format

### ISSUE THREAD

**Issue by Uysim** [rails-api/active_model_serializers#2241]
I can see that my json return like this 
{"data":[{"id":"5","type":"chat-messages","attributes":{"chat-type":"image","text":null,"sticker":null,"image":{"url":"http://192.168.1.97:3000/uploads/chat_message/image/5/abc.jpg"},"audio":{"url":null},"video":{"url":null},"contact":{},"location":{},"trans":{},"file-size":null,"duration":null,"image-width":828,"image-height":null,"sent-time":"2018-02-05T06:02:34.007Z","seen-ids":[],"read-time":null},"relationships":{"user":{"data":{"id":"433","type":"users"}}}},{"id":"2","type":"chat-messages","attributes":{"chat-type":"text","text":"asdfasdf","sticker":null,"image":{"url":null},"audio":{"url":null},"video":{"url":null},"contact":{},"location":{},"trans":{},"file-size":null,"duration":null,"image-width":null,"image-height":null,"sent-time":"2018-01-26T11:25:59.201Z","seen-ids":[],"read-time":null},"relationships":{"user":{"data":{"id":"433","type":"users"}}}},{"id":"3","type":"chat-messages","attributes":{"chat-type":"sticker","text":null,"sticker":"d2_1","image":{"url":null},"audio":{"url":null},"video":{"url":null},"contact":{},"location":{},"trans":{},"file-size":null,"duration":null,"image-width":null,"image-height":null,"sent-time":"2018-02-05T04:29:22.549Z","seen-ids":[],"read-time":null},"relationships":{"user":{"data":{"id":"433","type":"users"}}}},{"id":"6","type":"chat-messages","attributes":{"chat-type":"image","text":null,"sticker":null,"image":{"url":"http://192.168.1.97:3000/uploads/chat_message/image/6/abc.jpg"},"audio":{"url":null},"video":{"url":null},"contact":{},"location":{},"trans":{},"file-size":null,"duration":null,"image-width":1242,"image-height":824,"sent-time":"2018-02-05T06:17:14.546Z","seen-ids":[],"read-time":null},"relationships":{"user":{"data":{"id":"520","type":"users"}}}},{"id":"1","type":"chat-messages","attributes":{"chat-type":"text","text":"abcd","sticker":null,"image":{"url":null},"audio":{"url":null},"video":{"url":null},"contact":{},"location":{},"trans":{},"file-size":null,"duration":null,"image-width":null,"image-height":null,"sent-time":"2018-01-26T11:13:30.399Z","seen-ids":[],"read-time":null},"relationships":{"user":{"data":{"id":"520","type":"users"}}}},{"id":"4","type":"chat-messages","attributes":{"chat-type":"image","text":null,"sticker":null,"image":{"url":"http://192.168.1.97:3000/uploads/chat_message/image/4/Love_Imge_022.jpg"},"audio":{"url":null},"video":{"url":null},"contact":{},"location":{},"trans":{},"file-size":null,"duration":null,"image-width":null,"image-height":null,"sent-time":"2018-02-05T04:36:07.265Z","seen-ids":[],"read-time":null},"relationships":{"user":{"data":{"id":"520","type":"users"}}}}]}

why is result wrap under attributes and relationships keys?
why my key name image_height change to image-height?

**Comment by bf4** [comment]
Closing due to insufficient information to easily help.

Please review the requested information in our [issue template](https://github.com/rails-api/active_model_serializers/blob/master/.github/ISSUE_TEMPLATE.md) and reopen with the additional information, or any questions and comments you may have.

Thanks for your help, and thanks for making this issue.
