### ISSUE TITLE
Is it possible to have 2 different meta objects?

### ISSUE THREAD

**Issue by shhavel** [rails-api/active_model_serializers#2245]
Is it possible to have 2 different meta objects (in any version of the gem) to have JSON format like this? Thanks

```json
{ 
  "data": {
    "id": 1,
    "name": "User Name"
  },
  "meta1": {
    "key": "value"
  },
  "meta2": "test"
}
```

**Comment by bf4** [comment]
Not with the default adapter. You can always extend an existing one.

**Comment by shhavel** [comment]
@bf4 Great thanks.
