### ISSUE TITLE
Autoload race condition: uninitialized constant errors 

### ISSUE THREAD

**Issue by f-mer** [rails-api/active_model_serializers#2255]
This is more like a hypothesis than a straight bug report.

#### Expected behavior vs actual behavior
Using ActiveModelSerializers with a threaded web server (in my case puma) I get infrequent `uninitialized constant ` errors. I think it's caused by the use of `autoload`. I guess that ActiveSupports `autoload` is not threadsafe and on application boot not all modules / classes are necessarily implicitly loaded. 

#### Steps to reproduce
I'm not sure there is a way to reproduce. I think it's a race condition which only emerges under load.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: `0-10-stable` 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`

Rails Version: `5.1.4`

#### Errors
```
NameError: uninitialized constant ActiveModelSerializers::Adapter::JsonApi::ResourceIdentifier
```
```
NameError: uninitialized constant ActiveModelSerializers::Adapter::JsonApi::Relationship
```
```
NameError: uninitialized constant ActiveModelSerializers::Adapter::JsonApi::Deserialization
```

#### Additonal helpful information
I'm trying to solve the problem in this [fork](https://github.com/f-mer/active_model_serializers/commits/0-10-stable-eager_load). Adding `ActiveModelSerializers::Adapter::JsonApi` to `eager_load_namespaces` in `application.rb`.

```ruby
class Application < Rails::Application
  config.eager_load_namespaces << ActiveModelSerializers::Adapter::JsonApi
end
```

This problem might also be cause by the [deactivation of dependency loading](https://github.com/rails/rails/commit/a71350cae0082193ad8c66d65ab62e8bb0b7853b) in rails 5?

**Comment by bf4** [comment]
Interesting. I haven't run on Rails 5 yet.

In the past I have used an initializer with

```ruby
ActiveSupport.on_load(:action_controller) do
  require 'active_model_serializers/register_jsonapi_renderer'
  ActiveModelSerializers.eager_load! if Rails.env.production?
  ActiveModelSerializers::Adapter::JsonApi.eager_load! if Rails.env.production?
  require 'active_model/serializer/null'
  ActiveModel::Serializer::Null
end

**Comment by bf4** [comment]
How come you're not using a release?

**Comment by f-mer** [comment]
From the [ActiveSupport::Autoload](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/dependencies/autoload.rb) source  I draw the conclusion that calling `eager_load!` will have no effect without wrapping `autoload` calls inside `eager_autoload` blocks.

Went also with an initializer but loading the constants explicitly on boot:

```ruby
ActiveModelSerializers::Deserialization
ActiveModelSerializers::Adapter::JsonApi::Relationship
ActiveModelSerializers::Adapter::JsonApi::ResourceIdentifier
``` 

Haven't seen the errors again since deployed. 

Platformatec's blog post [Eager loading for greater good](http://blog.plataformatec.com.br/2012/08/eager-loading-for-greater-good/) is a good read on this topic.
But I'm not entirely sure what needs to go into `eager_autoload` blocks.

> How come you're not using a release?

Oh, we are using `0.10.7`. Got confused by the by the part in braces.

**Comment by bf4** [comment]
Looks like we can add this to the docs as an FAQ of some sort, if you'd like to make a PR

**Comment by GeminPatel** [comment]
facing a similar issue:

  uninitialized constant ActiveModelSerializers::Adapter::JsonApi::Meta
Did you mean?  ActiveModelSerializers::Adapter::JsonApi::Meta

**Comment by bf4** [comment]
@GeminPatel I'm not sure how Rails 5 would differ, but have you tried an initializer like what I described https://github.com/rails-api/active_model_serializers/issues/2255#issuecomment-391555431

**Comment by f-mer** [comment]
Rails 5 unhooks autoloading ([#a71350c](https://github.com/rails/rails/commit/a71350cae0082193ad8c66d65ab62e8bb0b7853b#diff-bf85cfa3d5f11bd1db1c97843818351b)) after the application has booted. I suspect the error originates from this gem not explicitly loading all deps during application boot. 

The initializer is a workaround which actually forces autoloading during application boot.

@bf4 [#3f65eba](https://github.com/f-mer/active_model_serializers/commit/3f65ebaa08877ee6dda814cc103ff997277b2834) fixes the issue. Would you be interesetd in a pull request?

**Comment by bf4** [comment]
Yup, also generally help not leaving ams completely abandoned  :)
