### ISSUE TITLE
How to insert the ID attribute inside "attributes" key when Adpter is JsonAPI?

### ISSUE THREAD

**Issue by betosalvador** [rails-api/active_model_serializers#2257]
Hello

I would like to get the ID of the record inside the **attributes** key when I'm using JsonAPI adapter.

My UserSerializer is:
```
class UserSerializer < ActiveModel::Serializer
  attributes :id, :name, :email
end
```

My current json is:

```
{
  "data": {
    "id": "1",
    "type": "users",
    "attributes": {
      "name": "João Lucas",
      "email": "jocaolucas@email.com"
    }
  }
}
```

But I want:
```
{
  "data": {
    "id": "1",
    "type": "users",
    "attributes": {
      "id": "1",
      "name": "João Lucas",
      "email": "jocaolucas@email.com"
    }
  }
}
```

Can anyone help me to understand what I'm missing?

Thanks in advance

**Comment by bf4** [comment]
I mean, if you're doing that you probably aren't really doing json-api or there's something wrong with your client that it can't read out the id where it's expected.  

But if you really want to do that, there's all sorts of ways.  What have you read? What have you tried?

**Comment by betosalvador** [comment]
Hello @bf4 
Thanks for response.

And, sorry for delay in my response.

Well, I think that I were doing this the wrong way.

I'm now just using the default data.

THank you very much
