### ISSUE TITLE
Why is serializer significantly faster in the second iteration?

### ISSUE THREAD

**Issue by DmitryKK** [rails-api/active_model_serializers#2261]
I was checking perfomance ASM with Benchmark. And I discovered interesting situation.

For first iteration:

```ruby
Benchmark.measure { MySerializer.new(record).to_json }
```

=>

```ruby
 #<Benchmark::Tms:0x0055c1bcf3d2b0 @label="", @real=0.02018763590604067, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.019999999999999574, @total=0.019999999999999574> 
```

But for second iteration:

```ruby
Benchmark.measure { MySerializer.new(record).to_json }
```

=>

```ruby
 #<Benchmark::Tms:0x0055c1bcf16570 @label="", @real=0.0009513059630990028, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.009999999999999787, @total=0.009999999999999787> 
```

**Faster 2X**

Third iteration

```ruby
Benchmark.measure { MySerializer.new(record).to_json }
```

=> 

```ruby
#<Benchmark::Tms:0x0055c1bcee3828 @label="", @real=0.0008343658410012722, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.0, @total=0.0>
```

**Faster 24X**

For another record:

```ruby
Benchmark.measure { MySerializer.new(another_record).to_json }
```

=>

```ruby
#<Benchmark::Tms:0x0055c1bce92900 @label="", @real=0.001171208918094635, @cstime=0.0, @cutime=0.0, @stime=0.0, @utime=0.009999999999999787, @total=0.009999999999999787>
```

It is still **faster** than the first iteration **2X**

Why is so happening?

ASM - 0.10.7

My serializer:

```ruby
class MySerializer < ActiveModel::Serializer
  attributes :title
end
```

**Comment by bf4** [comment]
@DmitryKK there's not enough info in your report to really tell.

There's a number of possible reasons.  For one thing, you're calling `to_json` which includes whatever your JSON gem is.  try benchmarking `record.as_json` vs `Serializer.new(record).as_json` (though note, it's unlikely you're calling Serializer.new(record).as_json in production)

**Comment by bf4** [comment]
Also, `measure` isn't so much a benchmark as a measurement. It's like running a race and saying that's  you're average time.

**Comment by DmitryKK** [comment]
@bf4 thanks for response. I tried `as_json` and got similar pattern. There is no difference. As for measurements, i checked it so many times and got similar figure

**Comment by bf4** [comment]
> i checked it so many times and got similar figure

That's not very descriptive of how you checked.

So far, I still don't know 
- the relationship between your test code and your production code (are they called the same, same db, etc)
- if you've observed any of this in production or if it's possibly an artifact of your benchmarking set up
- what is actually under benchmark. Without any code, for all I know you're benchmarking constant lookup the first time. (Or as appears, you're just eye-balling things)

**Comment by bf4** [comment]
Closing as likely an artifact of userland benchmark code

**Comment by bf4** [comment]
@DmitryKK based on what you've shared I think you're not using it correctly. Bear in mind you've only shared a fragment of what you're running
