### ISSUE TITLE
Serializer will suddenly pick the wrong child serializer in production 0.10.4

### ISSUE THREAD

**Issue by juancaldera** [rails-api/active_model_serializers#2262]
#### Expected behavior vs actual behavior
Given the serializer defintions below: 

We're having problems with AMS using the wrong serializer in production. Everything will work after server startup, but after a while, it will suddenly break, and start using the wrong child serializer. (non-namespaced version). 

I take it, this is not specifically AMS's problem, i'm not sure anyone can reproduce this, and I'm assuming something weird is going on during garbage collection). I even added references to the child serializers in a `before_action` callback to ensure it's loaded into memory, and the behavior still occurs.

I can't provide reproducible code sample per-se because as I said, this generally works. All our tests pass, and for a while after deploy, everything works. After a while, it will just break. (anywhere from hours, to days later). So I'm not sure how to reproduce it.

As a workaround, Is there a more explicit way to force AMS to use a specific serializer? It seems like it's serializer selection strategies trump even the "serializer" option?

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

```ruby
class ParentSerializer < ActiveModel::Serializer
  has_one :child
end

class ChildSerializer < ActiveModel::Serializer
end

class Admin::ParentSerializer < ActiveModel::Serializer
  has_one :child, serializer: ::Admin::ChildSerializer
end

class Admin::ChildSerializer < ActiveModel::Serializer
end
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
0.10.4

Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails 4.2.6
Ruby 2.3.7p456

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by juancaldera** [comment]
0.10.7? Nothing in particular. We tend to be more conservative with regards to gem updates, but i'm sure updating to .7 should be fine.

**Comment by bf4** [comment]
Resolved?

**Comment by juancaldera** [comment]
I upgraded to 0.10.7 but did not solve the problem. I did have userthe "serializer_for" workaround, and seems like it'll have a really predicable outcome, and so far, seems to be working. 

I have no way of creating a re-producible scenario of of the original problem for ya, so I thought I'd just close the ticket.

**Comment by wasabigeek** [comment]
Hi,

I've run into a similar issue when running rspec, where the chosen serializer doesn't seem to follow the namespace (or I've understood differently). This is the file structure:

**serializers/abc_serializer.rb**
```
class AbcSerializer < ActiveModel::Serializer
   ...
end
```
**serializers/api/v2/abc_serializer.rb**
```
class Api::V2::AbcSerializer < ActiveModel::Serializer
  ...
end
```

When I specifically run spec/controllers/api/v2/xyz_controller_spec.rb, the tests run fine and the correct Serializer (serializers/api/v2/abc_serializer.rb) is chosen, however when I run the full suite (or all the controller tests), it chooses the generic Serializer (serializers/abc_serializer.rb). 

Am I using the right namespacing?

**Env**
ruby 2.5.0p0
rails 5.1.5
active_model_serializers 0.10.7
rspec 3.7.0
