### ISSUE TITLE
Not rendering in-depth relationships

### ISSUE THREAD

**Issue by rafaelfragosom** [rails-api/active_model_serializers#2282]
#### Expected behavior vs actual behavior
I was expecting something like:

```json
	{
        "id": 6,
        "email": "test1@test.com",
        "profile": {
            "id": 5,
            "name": "Rafael",
			"addresses": [...]
        }
    }
```

But for some reason, the addresses are not being rendered inside the profile.

#### Steps to reproduce

Here are my serializers:

```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :id, :email, :created_at, :updated_at, :role
  has_one :profile
  has_one :last_location
end

class ProfileSerializer < ActiveModel::Serializer
  attributes :id, :name, :title, :image, :social_number, :tel, :cel
  belongs_to :user
  has_many :addresses
end

class AddressSerializer < ActiveModel::Serializer
  attributes :id, :address1, :address2, :city, :state, :country, :name
  belongs_to :profile
  has_one :coordinates
end
```

And the place in the controller where I list them:

```ruby
def index
  @account = authorize current_user.accounts
  json_response(@account)
end
```
Where `current_user.accounts` are the accounts related to that User, all referring to the `User` model.

#### Environment

ActiveModelSerializers Version *0.10.0*:

**Comment by usama520** [comment]
add ```ActiveModel::Serializer.config.default_includes = '**'``` in application.rb.

**Comment by rafaelfragosom** [comment]
@usama520 Thank you for this.

It says the three is too deep, but you showed me the right path.
