### ISSUE TITLE
A media type parameter (charset) is set for JSON API, againsst the standard

### ISSUE THREAD

**Issue by tkalliom** [rails-api/active_model_serializers#2285]
#### Expected behavior vs actual behavior

Expected the `jsonapi` media type responses to have the header `Content-Type: application/vnd.api+json` _without_ any media type parameters, as per the JSON:API specification. Instead, `; charset=utf-8` is present in the response `Content-Type`

#### Steps to reproduce
Load `active_model_serializers/register_jsonapi_renderer.rb` and make a response in the `jsonapi` format.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 0.10.7

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]`

OS Type & Version: GNU/Linux 4.17 (Debian Stretch)

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 5.2

**Comment by bf4** [comment]
I'm pretty sure this is fine, but thanks for the issue!
