### ISSUE TITLE
ActiveModel::ArraySerializer#serializable_array equivalent in ActiveModel::Serializer::CollectionSerializer 

### ISSUE THREAD

**Issue by MattSmithASU** [rails-api/active_model_serializers#2305]
#### Expected behavior vs actual behavior
I am upgrading from Rails 4.1 to 5.2. I have a custom ActiveModel::ArraySerializer which adds meta data to the collection response. For example `:type => 'collection'`. This is done by creating a new class that extends from ActiveModel::ArraySerializer and overrides the `serializable_array` method. This process was documented here in the README at one point (https://github.com/rails-api/active_model_serializers/blob/d72b66d4c5355b0ff0a75a04895fcc4ea5b0c65e/README.textile)

```
class CustomArraySerialzer < ActiveModel::ArraySerializer
def serializable_array
    array = super
    collection = {
      :type => :collection,
    }
    collection[:data] = array
    collection
  end
end
```
However, I cannot find this behavior in Rails 5 (was using active_model_serializer version 0.8.1, now I'm on 0.10.8.
This Issue:
https://github.com/rails-api/active_model_serializers/issues/1809
Recommends to use ActiveModel::Serializer::CollectionSerializer instead. However, I cannot find a way to override the actual collection serialization, and not just each resource inside the collection.

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.5.3p105 (2018-10-18 revision 65156)

**Comment by bf4** [comment]
So, there's  couple of things going on here. Basically, you've changed versions from the 0.8 series to the 0.10. The upgrade itself requires changes unrelated to your Rails version.

My guess is part of the issue is what adapter you're using.

You can indeed customize your collection serializer. Compare the JSON adapter to the Attributes adapter.

**Comment by MattSmithASU** [comment]
> The upgrade itself requires changes unrelated to your Rails version.
Are those changes documented?
