### ISSUE TITLE
has_many model, serializer: ModelSerializer not using the serializer

### ISSUE THREAD

**Issue by maxrosecollins** [rails-api/active_model_serializers#2308]
#### Expected behavior vs actual behavior
When I use 

```
has_many :posts, serializer: PostSerializer do
    time = Time.current.beginning_of_day
    object.posts.where(created_at: time)
end
```
I expect it to use my custom serializer `PostSerializer` but it doesn't use it and instead gives me the following

```
 "relationships": {
                "posts": {
                    "data": [
                        {
                            "id": "773",
                            "type": "posts"
                        }
```

My post serializer

```
module Api
  module V1
    class PostSerializer < ActiveModel::Serializer
      attributes :id, :url, :created_at, :test

      def test
        {}
      end
    end
  end
end
```

#### Environment

Output of `ruby -e "puts RUBY_DESCRIPTION"`:  ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

AMS: 0.10.7

**Comment by bf4** [comment]
@maxrosecollins that relationships object you posted makes me think you're using the JSON API adapter.  That object comes from the adapter (via the spec). The serializer would be used if you *included* the posts relationship and show up in the 'included' member. Please let me know if that helps.

**Comment by maxrosecollins** [comment]
So do you mean I should do this?

`render json: model, status: 200, each_serializer: ModelSerializer, include: ['posts']`

**Comment by maxrosecollins** [comment]
Hmmm I think I understand now.

So there is no way to get this data into the `relationships` `data` part?
```
"relationships": {
                "posts": {
                    "data": [
                        {
                            "id": "773",
                            "type": "posts"
                        }
```

**Comment by bf4** [comment]
@maxrosecollins you *could* do things like that, but then it most of your examples would break JSON:API clients.  Allow me to translate how I understand your issue:

1. You've chosen to use the JSON:API adapter
2. You want something different from what the adapter is designed to do

So, I see a couple of options:

If you really want your own custom format, make your own custom adapter

If someone really wants use use the JSON:API spec, then nobody wants the format you're expecting, so you should either look over the spec to better understand it, or ask the someone about it

Just in case it's not clear https://jsonapi.org/ is a spec. i.e. application/vendor.api+json is a media type for a particularly formatted 'JSON API'
