### ISSUE TITLE
can we add push method to serializer?

### ISSUE THREAD

**Issue by mistraminayasa** [rails-api/active_model_serializers#2312]
Below is the output serialization:
```
[
    {
        "price": 1950,
        "quantity": null,
        "name": "Aqua Mineral 330ml"
    },
    {
        "price": 1950,
        "quantity": null,
        "name": "Aqua Mineral 330ml"
    },
    {
        "price": 1950,
        "quantity": 2,
        "name": "Aqua Mineral 330ml"
    }
]
```
As I know, they are array. So, I want to push another data from different table using that format. I try use push method. But, I always get error undefined method push.

**Comment by bf4** [comment]
any reason you wouldn't just serialize your object to serializable_hash and then push to that?

It think combining two collection serializers would be too janky, depending on your AMS version (which you didn't share :(
