### ISSUE TITLE
Deprecation warning in Rails 6.0.0 beta

### ISSUE THREAD

**Issue by iggant** [rails-api/active_model_serializers#2316]
DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1. (called from namespace_for_serializer at /usr/local/bundle/gems/active_model_serializers-0.10.9/lib/action_controller/serialization.rb:26)

**Comment by xyingsoft** [comment]
I have deprecation warning after upgrading rails,
So I tried to use master branch, but its not working with rails 6 at all.

```

Failure/Error: require File.expand_path("../../config/environment", __FILE__)
FrozenError:
  can't modify frozen Array
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:5:in `<top (required)>'

```
When will be next version released for rails 6?

**Comment by iggant** [comment]
don't use master branch use 


`gem 'active_model_serializers', '~> 0.10.0', require: true, github: 'rails-api/active_model_serializers', branch: '0-10-stable'`

**Comment by xyingsoft** [comment]
Thanks @iggant, I will try now

**Comment by xyingsoft** [comment]
Awesome it works, thanks @iggant
