### ISSUE TITLE
Using AMS with rails 6

### ISSUE THREAD

**Issue by auscaster** [rails-api/active_model_serializers#2320]
Hey team, 

I see that AMS currently restricts Rails version to < 6. Its currently the only gem in my bundle preventing the upgrade. Is there any plans for support or a way to use this gem with Rails 6?

Thanks for your great work!

**Comment by wasifhossain** [comment]
Thanks @auscaster for bringing it up.

@bf4 I found the tests for `0-10-stable` pass on Rails `master`. can we push rails version to 6 at this point, or should we wait until its officially released.

Otherwise, can you suggest how can we use rails 6 beta (which is released) with the present settings? Thanks

**Comment by iggant** [comment]
@auscaster  with this restriction < 6 you still can install beta2 Rails, 
but before you can do this, you probable have to merge https://github.com/rails-api/active_model_serializers/pull/2319 otherwise log file will blow up with deprecation warning log entries

This PR is almost ready to merge.

**Comment by jarkko** [comment]
Rails is now at 6.0.0.rc1, so the `< 6` doesn't work anymore. Gonna fork and see how things work with it.

**Comment by wasifhossain** [comment]
will make the change to make it work with the latest Rails version soon.

**Comment by wasifhossain** [comment]
Travis is all good with Rails 6.0.0.rc1. Please have a look at the PR. I have also tested it in a project by trying to upgrade Rails from 5.2.3 to 6.0.0.rc1 and it ran successfully.

@auscaster @jarkko can you please check it out? thanks

**Comment by Kaakati** [comment]
Works fine with Rails 6.0.0, and not yet with 6.0.1

**Comment by wasifhossain** [comment]
hi @Kaakati can you please elaborate the case with 6.0.1

thanks

**Comment by Kaakati** [comment]
@wasifhossain It was giving a 500 Internal Server Error, wasn't able to investigate much, I had to downgrade back to 6.0.0

**Comment by wasifhossain** [comment]
I will close this issue now. If you have more details on the problems, please open a new issue with those details. thanks
