### ISSUE TITLE
How to serialize a PORO Model generated from other attributes without specifying in the instantiation

### ISSUE THREAD

**Issue by Subomi** [rails-api/active_model_serializers#2345]
#### Expected behavior vs actual behavior   
Actual Behavior:

     module Models   
       class AllCats < ActiveModelSerializers::Model 
       
         attributes :cats
         attributes :total

         def total
           cats.count
         end
       end
     end

Controller:
  `cats = Models::AllCats.new(total: true,cats: cats)`

JSON:
`{ total: '..', cats: [...] }`

Expected Behavior:

Controller:
  `cats = Models::AllCats.new(cats: cats)`

JSON:
`{ total: '..', cats: [...] }`

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
0.10.9

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

OS Type & Version: 

Integrated application and version *(e.g., Rails, Grape, etc)*:

**Comment by wasifhossain** [comment]
Basically the serialization works like when you don't have any serializer defined for the model, `ActiveModel::Serializer::Null` is used by default. That will include the attributes that are present.

To achieve the expected behavior, you need to define a serializer like:
```rb
class AllCatsSerializer < ActiveModel::Serializer
  attributes :cats, :total
end
```

**Comment by Subomi** [comment]
@wasifhossain I skipped adding the below: 

```
class AllCatsSerializer < ApplicationSerializer
  attributes :total
  
  has_many :cats, serializer: CatsSerializer
end
```

**Comment by wasifhossain** [comment]
i am sorry. but its hard to debug your case further with the info given above

**Comment by Subomi** [comment]
@wasifhossain Figured it out already. Thanks.

**Comment by wasifhossain** [comment]
you are welcome! @Subomi
