### ISSUE TITLE
Serialize a collection with different models in it

### ISSUE THREAD

**Issue by davideluque** [rails-api/active_model_serializers#2346]
Hello,

I have a search procedure that returns a collection of three models in random order; post, profile, and tag. 

Active Model Serializer can perfectly render the collection by using the default serializers I have created before:

```ruby
r = Searchkick.search params[:q], models: [Post, Profile, Tag]
render json: r
```
However, for this procedure, I need to use specific serializer for each Post, Profile, and Tag, different from the ones that I have set by default for these models. They are model objects in the r variable.

How can I achieve this task?

**Comment by wasifhossain** [comment]
Hi.

lets assume you can access the models inside `r` as:
```rb
posts = r.posts
profiles = r.profiles
tags = r.tags
```

then you can serialize them individually using custom serializers as:
```rb
# controller
private

def serialize(collection, serializer, adapter = :json)
  ActiveModelSerializers::SerializableResource.new(
    collection,
    each_serializer: serializer,
    adapter: adapter
  ).as_json
end
```
finally you can merge them in the `render` method as:
```rb
result = serialize(posts, custom_post_serializer).
  merge(serialize(profiles, custom_profile_serializer)).
  merge(serialize(tags, custom_tag_serializer))

render json: result
```

**Comment by davideluque** [comment]
> Hi.
> 
> lets assume you can access the models inside `r` as:
> 
> ```ruby
> posts = r.posts
> profiles = r.profiles
> tags = r.tags
> ```
> 
> then you can serialize them individually using custom serializers as:
> 
> ```ruby
> # controller
> private
> 
> def serialize(collection, serializer, adapter = :json)
>   ActiveModelSerializers::SerializableResource.new(
>     collection,
>     each_serializer: serializer,
>     adapter: adapter
>   ).as_json
> end
> ```
> 
> finally you can merge them in the `render` method as:
> 
> ```ruby
> result = serialize(posts, custom_post_serializer).
>   merge(serialize(profiles, custom_profile_serializer)).
>   merge(serialize(tags, custom_tag_serializer))
> 
> render json: result
> ```

Hello Wasif, thank you for your help!

I have no way to separate the classes by using r.posts, etc. 

Also, I did not want to try to separate the models and merge them afterward because the order in which they are in r is relevant. 

r behaves like an array but it is a different object (Searchkick::Results, if this can be helpful)

**Comment by wasifhossain** [comment]
would help if you could provide an example of how `r` would look like. is there any way to retrieve the fields from a model encapsulated in that object? i mean if it was possible to define a serializer, how does the serializer get serialized attribute values for each different type.

thanks

**Comment by wasifhossain** [comment]
@davideluque any updates plz?

**Comment by davideluque** [comment]
> would help if you could provide an example of how `r` would look like. is there any way to retrieve the fields from a model encapsulated in that object? i mean if it was possible to define a serializer, how does the serializer get serialized attribute values for each different type.
> 
> thanks

The object behaves like an array but it is defined by a search gem I am used called SearchKick. I can iterate over the results, print them, etc. Inside that object, there are mutiple Active Record Model objects, of different types and in a random order.

**Comment by davideluque** [comment]
@wasifhossain 

I actually did not define a serializer for that `r` object, when I do

`render json: r`

Since it is an array, active model serializer serializes each of them with the default serializers

Is there a way that I can define a serializer for this array and then for each specific object inside the array specify a serializer? Example

```ruby
class CollectionSerializer < ApplicationSerializer
  def init
  object.each do |obj|
    if obj.class == "Profile"
      obj.serialize_with(CustomProfileSerializer)
   else if obj.class == "Post"
      obj.serialize_with(CustomPostSerializer)
    end
  end
end
```

**Comment by wasifhossain** [comment]
@davideluque sorry to make delay. unfortunately I am still under loads of work before looking for the response for your case.

btw, have you already got the way how to do it. In that case, we are eager to know about it. Otherwise please allow me some more time to investigate the case. thanks

**Comment by elik-ru** [comment]
I know it's too late, but may be will help someone else.

You can pass `namespace` parameter to `ActiveModelSerializers::SerializableResource`,   for instance:

```
ActiveModelSerializers::SerializableResource.new(
    collection,
    namespace: "Api::V1"
  ).as_json
```

It will try to find namespaced serializer for each item in collection, based on its classname:

Post => Api::V1::PostSerializer
Comment => Api::V1::CommentSerializer
