### ISSUE TITLE
FIPS 140-2 compatibility

### ISSUE THREAD

**Issue by alexzherdev** [rails-api/active_model_serializers#2358]
#### Expected behavior vs actual behavior
We'd like AMS to be compatible with FIPS 140-2 mode. This is currently not working because of the use of MD5 [here](https://github.com/rails-api/active_model_serializers/blob/ab47e983f587e93ece7ab2552537d1475a5eb234/lib/active_model/serializer/concerns/caching.rb#L59).

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*
- install FIPS-compatible OpenSSL binary (this probably differs by OS)
- turn on FIPS mode for OpenSSL with `OpenSSL.fips_mode = true`
- try to invoke an AMS serializer

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 
0.10.0.rc3, 8981683b9fa8d0bcff0e76b3702d699689b787b4

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
```
ruby 2.5.6p201 (2019-08-28 revision 67796) [x86_64-linux]
```
OS Type & Version: 
Amazonlinux 2

Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails 5.2.3

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*
```
md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
```
(there is no ruby stack trace, but I verified that `caching.rb` is the culprit)

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

Just replacing MD5 with SHA1 in that file seems to work.
Also note that Rails added FIPS compatibility in 5.2: https://github.com/rails/rails/pull/31651

**Comment by bf4** [comment]
sounds reasonable. surprising that it matters given the code's purpose
