### ISSUE TITLE
Serializing non-ActiveRecord objects fails

### ISSUE THREAD

**Issue by belgoros** [rails-api/active_model_serializers#2364]
#### Expected behavior vs actual behavior

```json
{
	"data": {
		"attributes": {
			"username": "user-1",
			"firs_name": "FName-1",
			"last_name": "LName-1"
		},
		"id": "1",
		"type": "users"
	}
}
```

#### Steps to reproduce
Here is the [gist](https://gist.github.com/belgoros/127a7e45104c27791f90daef01fab6c8) providing the required code snippets.

#### Environment

- ruby '2.6.5'
- gem 'rails', '~> 5.2.3'
- gem 'active_model_serializers', '~> 0.10.6'

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

OS Type & Version: 

Integrated application and version *(e.g., Rails, Grape, etc)*:  `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]`

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

The actula response is:
```json
{
    "first_name": "FName-1",
    "id": 1,
    "last_name": "LName-1",
    "username": "user-1"
}
```
The log in the console:
```
Started GET "/users/1" for ::1 at 2019-11-19 17:46:47 +0100
Processing by UsersController#show as */*
  Parameters: {"id"=>"1"}
[active_model_serializers] Rendered ActiveModel::Serializer::Null with User (0.09ms)
Completed 200 OK in 4ms (Views: 2.4ms | ActiveRecord: 0.0ms)
```

**Comment by bf4** [comment]
for posterity

```ruby
# models/user.rb
class User
  include ActiveModel::Model

  attr_accessor :username, :first_name, :last_name, :id
end

#serializers/user_serializer.rb
class UserSerializer < ActiveModelSerializers::Model
  attributes :id, :first_name, :last_name, :username
end

# controllers/users_controller.rb

class UsersController < ApplicationController
  before_action :init_users
  def index
    render jsonapi: @users
  end

  def show
    @user =  @users.select {|u| u.id == params[:id].to_i}.first
    if @user
      render jsonapi: @user
    else
      render jsonapi: {message: "Wrong user ID"}, status: :not_found
    end
  end

  private

  def init_users
    @users ||= []
    if @users.empty?
      (1...10).to_a.each do |x|
        @users << User.new(
          id: x,
          username: "user-#{x}",
          first_name: "FName-#{x}",
          last_name: "LName-#{x}"
        )
      end
    end

    @users
  end
end

# initializers/ams.rb

# frozen_string_literal: true

# In order to properly handle JSON API responses, we need to register a JSON API renderer,
# like so:
ActiveSupport.on_load(:action_controller) do
  require 'active_model_serializers/register_jsonapi_renderer'
end

ActiveModelSerializers.config.adapter = :json_api
ActiveModelSerializers.config.key_transform = :unaltered
```

that's odd. it appears to be ignoring the jsonapi adapter.

have you tried being explicit with the serializer? 

also, you error response isn't actually valid jsonapi.

Please be aware, as written, you're asserting that it hasn't worked for anyone for years and the tests lie.  I wrote and used the PORO code with jsonapi, so it's something in your setup. I can't tell what you've tried.

**Comment by belgoros** [comment]
@bf4 Yes, I know about error response, - I put there just to get feedback in any way. The main purpose was to be able to get a JSO API response. Another example, using a classic `Shop` model wth its serializer works as needed:
```json
{
    "data": {
        "attributes": {
            "category": "category-1",
            "fax": "789-1-123",
            "leader": "leader-1",
            "name": "name-1",
            "phone": "123-1-123"
        },
        "id": "1",
        "type": "shops"
    }
}
```
I've also tried to pass the explicite serializer as follows:
```ruby
# users_controller#show

render jsonapi: @user, serializer: UserSerializer
```
but it fails with:
```
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)


  
ArgumentError (wrong number of arguments (given 2, expected 0..1)):
  
app/controllers/users_controller.rb:10:in `show'
```

**Comment by wasifhossain** [comment]
you probably need to pass the json_api adapter explicitly in this way
```rb
render json: @user, adapter: :json_api, serializer: UserSerializer
```

**Comment by bf4** [comment]
@wasifhossain I'm closing this.  OP can include the stacktrace for the lib with the error if OP wants help from the lib maintainers.  Right now we know two things: 1) it works in general 2) it doesn't work for OP, and we don't know what's special about OP example

**Comment by belgoros** [comment]
@bf4 What do mean under `OP`? (just to better understand your response)
