### ISSUE TITLE
Ability to specify `key_transform` as `render` option erroneously removed over 3 years ago

### ISSUE THREAD

**Issue by endash-gdm** [rails-api/active_model_serializers#2365]
#### Expected behavior vs actual behavior

As documented, you ought to be able to specify `key_transform` as an option when calling `render`. This doesn't actually work, because a bad merge 3.5 years ago deleted the requisite line from `SerializationContext`:

https://github.com/rails-api/active_model_serializers/commit/3498647d1a07b9e8a183702bef53cf1ce8a76370#diff-ea6de8747ad0fa42a5489132019568d8

#### Steps to reproduce

Try to call `render`, specifying a `key_transform`. It won't do anything.

**Comment by wasifhossain** [comment]
Hi. I think its working as documented here: [docs/general/key_transforms.md](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/key_transforms.md#key-transforms)

You may be interested to see it working fine in the test suite: https://github.com/rails-api/active_model_serializers/blob/873cf4add2bfa1ca1a96f63ed7d89912c4d253e4/test/action_controller/json_api/transform_test.rb#L62-L63

**Comment by endash-gdm** [comment]
Great. It doesn't actually work in practice. That wouldn't be the first time a test inadvertently passed without actually validating the system under test. But if you want to just summarily close tickets when people have actually put real work and time into researching and tracking down problems, go right ahead. Just one more reason to jettison this library.

**Comment by bf4** [comment]
@endash-gdm sounds like you may be able to write a failing test and propose a fix?

Thanks for your efforts.

For what it's worth, key_transform is a feature that has some performance issues and rough edges, and may be better handling in the client js library. I have in the past set the key_transform to unaltered for more predictable results.

**Comment by dimasusername** [comment]
This is still an issue, why is this closed?

**Comment by bf4** [comment]
@dimasusername PRs welcome :) per OP the feature was erroneously removed due in the referenced merge commit even though the test suite still passes.
