### ISSUE TITLE
Is there a way to render attributes and variables together in JSON?

### ISSUE THREAD

**Issue by Sakaki-Ya** [rails-api/active_model_serializers#2381]
#### Question
It may not be related to Active Model Serializer, but let me ask you a question.

For example, the following action...
```ruby
def sign_up
  @user = User.create(user_params)
  token = GenerateToken(@user)
  render json: @user,serializer: UserSerializer, root: "user", adapter: :json # I want to render token too.
end
```

I want to render the user information and token as shown in the JSON below.
```json
{
    "user": {
        "id": 1,
        "name": "foo",
        "email": "bar@bar.com"
    },
   "token": "baz"
}
```

The Serializer is as follows.
```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :id, :name, :email
end
```

Is there a way to generate this JSON?
I would appreciate it if you could tell me how to do it better.
Thank you.

#### Steps to reproduce

[Codeanywhere](https://codeanywhere.com/s/l/o0aISyjIGqFWbd2JxVWa2VYXedgnABgMnlDxJwp4bCu9sVNQ5znSljre7gz2EJdU)
Need Codeanywhere account.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*:
```gem 'active_model_serializers', '~> 0.10.10'```

Output of `ruby -e "puts RUBY_DESCRIPTION"`:
```ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]```

OS Type & Version:
```macOS Catalina 10.15.4```

Integrated application and version *(e.g., Rails, Grape, etc)*: 
```Rails 6 API mode```

**Comment by wasifhossain** [comment]
you can use [ActiveModelSerializers::SerializableResource](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/howto/outside_controller_use.md) anywhere the same way as you serialize a json using `render`

```rb
response = ActiveModelSerializers::SerializableResource.new(@user, serializer: UserSerializer, root: 'user', adapter: :json).as_json
response[:token] = 'baz'
render json: response
```

**Comment by Sakaki-Ya** [comment]
Sorry it took me so long to reply.
I was able to render the JSON as I wanted.
Thank you so much.
