### ISSUE TITLE
Adapter options ignored when serializing ruby primitives

### ISSUE THREAD

**Issue by nickstanish** [rails-api/active_model_serializers#2386]
#### Expected behavior vs actual behavior

Adapter options are ignored for plain objects and arrays

##### Example1: Simple Object

```ruby
  def index
    resource = { key: 'value' }
    render json: resource, root: 'data', adapter: :json
  end
```

*Expected Result:*

```json
{
  "data": {
    "key": "value"
  }
}
```

*Actual Result:*

```json
{
  "key": "value"
}
```

##### Example2: Simple Array

```ruby
  def index
    resource = ['1', '2', '3']
    render json: resource, root: 'data', adapter: :json
  end
```

*Expected Result:*

```json
{
  "data": ["1","2","3"]
}
```

*Actual Result:*

```json
["1","2","3"]
```

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

Create a rails controller with above examples

Or call manually:

```ruby
resource = ['1', '2', '3']
ActiveModelSerializers::SerializableResource.new(resource, adapter: :json, root: 'data').to_json
# [active_model_serializers] No serializer found for resource: "1"
# [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with Array (0.07ms)
# => "[\"1\",\"2\",\"3\"]"
```
#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: v0.10.10

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin19]

OS Type & Version: Mac OS 10.15.5 (19F101)

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails v5.2.2

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

N/A

#### Additional helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

Appears that the adapter is set to the resource instead of `ActiveModelSerializers::Adapters::Json` due to this throw:

https://github.com/rails-api/active_model_serializers/blob/a6120f16918bd6013b99b89b7b30b6d0e66bb052/lib/active_model/serializer/collection_serializer.rb#L83

https://github.com/rails-api/active_model_serializers/blob/a6120f16918bd6013b99b89b7b30b6d0e66bb052/lib/active_model_serializers/serializable_resource.rb#L43-L45

**Comment by bf4** [comment]
yup, this is how it works.

**Comment by nickstanish** [comment]
> There's no way for the gem to know your intentions when serializing an array or hash or string
> – @bf4 

It looks like [the docs](https://github.com/rails-api/active_model_serializers/blob/a6120f16918bd6013b99b89b7b30b6d0e66bb052/README.md#primitive-handling) don't go into the reasoning behind this. Is it due to AMS hooking into `render: json` and `to_json` so AMS tries not to interfere with other serialization methods?

Maybe it would be possible to expose an alternative API so that intentions are clearer?

**Comment by bf4** [comment]
This comes up periodically.  But AMS has a clear api for serializing
models.  People who want to treat a hash like an object usually make their
own serializer for it.

If you want to preprocess something and turn it into a string, AMS and
Rails will ignore it
