### ISSUE TITLE
Provide serialization_scope when response is rendered using 'respond_with'

### ISSUE THREAD

**Issue by devonparsons** [rails-api/active_model_serializers#2387]
#### Expected behavior vs actual behavior

Expected: My application can access `scope` during serialization when my action uses `respond_with @model` and has set `response.format` to `:json`

Actual: My application can only access `scope` during serialization if I specifically use `render json: @model` in my action

#### Steps to reproduce
```
  # api_controller
  serialization_scope :current_user
  respond_to :json

  # before_action
  request.format = :json
  self.formats = [:json]
  
  # action
  respond_with @model

  # serializer
  def some_relation_on_model
    puts scope.inspect # => nil
    if scope
      filter_relation_by_permission(relation, scope)
    else 
      relation
    end
  end
```

#### Environment

ActiveModelSerializers Version 

0.10.10

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]

OS Type & Version: 

CentOS 7

Integrated application and version *(e.g., Rails, Grape, etc)*:

Rails 6 

#### Additonal helpful information

From reading the docs it appears that AMS specifically overrides `render :json`, but it would be convenient for me if I could continue to use `respond_with` while `response.format` is set to `:json`

**Comment by wasifhossain** [comment]
could you please share more insights on `some_relation_on_model` method, like how it is used in the serializer. 

fyki, I have tried to reproduce the case by following the above code, but got the **expected** result

**Comment by devonparsons** [comment]
Sure! Thanks for the quick reply.

```
class ContractSerializer < ActiveModel::Serializer
  has_many :signatories

  def signatories
    a = Ability.new(scope) # CanCan permissions; current user must be permitted to read the signatory
    object.signatories.select { |s| scope ? a.can?(:read, s) : true }
  end
end
```

I've also noticed that we set `self.responder = Responders::ApiResponder` in the API Controller. That class is pretty minimal; here's the only stuff that might be relevant:

```
  class ApiResponder < ActionController::Responder
    def json
      ... # some domain logic
      options[:root] = resource.class.name.demodulize.underscore #=> 'contract'
      controller.render_to_string json: ActiveModelSerializers::SerializableResource.new(resource, options).as_json
    end

    def to_json
      render(json: json, status: status_code)
    end
end
```

I'm not sure if this influences the serialization process. I've just tested and confirmed again that I see the following behaviour:

When my action returns `respond_with @contract, include: 'signatories.decorators'`, `scope` is `nil` in `ContractSerializer#signatories`  
When my action returns `render json: @contract, include: 'signatories.decorators'`, `scope` is `current_user` in `ContractSerializer#signatories`

Thanks for the help!

**Comment by wasifhossain** [comment]
awesome! assuming that you are trying to get access to the `current_user` scope in the serializer, you could pass the `scope/scope_name` options in AMS::SR.new

```rb
class ApiResponder < ActionController::Responder
  def json
    ... # some domain logic
    options[:root] = resource.class.name.demodulize.underscore #=> 'contract'
    
    # use whatever method you would like to pass in these options
    options[:scope] = current_user
    options[:scope_name] = :current_user

    controller.render_to_string json: ActiveModelSerializers::SerializableResource.new(resource, options).as_json
  end
```

could you please share the findings with this change

**Comment by devonparsons** [comment]
That worked! I had to store `@controller` from `args.first` in the initializer so that I could refer to `@controller.current_user` later. Now 
scope is set in the serializer and I can even refer to it by `current_user`.
