### ISSUE TITLE
{"message":"[NoMethodError] undefined method `singularize' for :features:Symbol"}   -- If request in .geojson

### ISSUE THREAD

**Issue by YashowardhanTripathi** [rails-api/active_model_serializers#2393]
Your service is good and easy to use but i stuck with this please help me out from this:

**Enviroment**

- ActiveModelSerializers Version 0.10.10
- ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]

**Issue**

Request:-  http://10.10.21.160:3000/api/v1/feeds.geojson
Response:- {"message":"[NoMethodError] undefined method `singularize' for :features:Symbol"}

**Alternate Try**

http://10.10.21.160:3000/api/v1/feeds.json -- Working fine (200)
http://10.10.21.160:3000/api/v1/feeds.csv -- Working fine (200)

Thanks

**Comment by wasifhossain** [comment]
Hi.

afaik, AMS provides no support for geojson. did you check https://github.com/rgeo/rgeo-geojson by chance

**Comment by bf4** [comment]
@YashowardhanTripathi you're going to want to include a backtrace at a minimum.

Closing this as likely unrelated

**Comment by YashowardhanTripathi** [comment]
Thanks all for reply  @wasifhossain  I do try your suggestion hope will work.
