### ISSUE TITLE
Fix ruby warnings

### ISSUE THREAD

**Issue by omisei** [rails-api/active_model_serializers#2402]
#### Expected behavior vs actual behavior
/Users/deissim/.rvm/gems/ruby-2.7.1/gems/active_model_serializers-0.10.12/lib/active_model_serializers/serializable_resource.rb:50: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*
When I run rspec this warning is shown.

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]

OS Type & Version:
MacOS BigSur (11.0.1)

Integrated application and version *(e.g., Rails, Grape, etc)*: 
rails-6.0.3.4

**Comment by bf4** [comment]
Options
1. Submit a PR :)
2. Upgrade to Ruby 2.7.2 with disables most of these by default
3. use a gem line Warning to ignore warnings from gems 

:)
