### ISSUE TITLE
instance_options are protected

### ISSUE THREAD

**Issue by alecvn** [rails-api/active_model_serializers#2421]
Can't access `instance_options` as they are protected in version `0.10.12`.

**Comment by wasifhossain** [comment]
we are accessing it just fine. could you share more details. thanks

**Comment by alecvn** [comment]
As you can see from the image, on `0.10.12` the `instance_options` are protected and thus can't be accessed from within the serializer.

![activemodel_serializer](https://user-images.githubusercontent.com/7558545/122563652-bd775500-d044-11eb-95bb-f0e7a604af1a.png)

Am I missing something?

**Comment by alecvn** [comment]
Okay, I found what's going on.  I'm looking in a child serializer, one that is `included` in the parent.  I do have access to `instance_options` in the parent.

Is there a way to access `instance_options` in the child serializers?  Removing `protected` in the line shown allows it to work.

**Comment by alecvn** [comment]
That also wasn't it...  I was trying to access `instance_options` in a `has_many` block, which I assume isn't allowed, though removing `protected` at the line indicated does give me access to it there.

I'll use a virtual attribute instead.  Thanks.

**Comment by alecvn** [comment]
@wasifhossain is there a way to access the parameters passed through from the controller in the `has_many` block?
