### ISSUE TITLE
How to use 'only' option in v10.13?

### ISSUE THREAD

**Issue by michael-royski-checkr** [rails-api/active_model_serializers#2441]
#### Expected behavior vs actual behavior
I have a project using AMS 0.8.1 where the only option is passed to the serializer so we only select the needed attributes like so
`serializer.new(object, only: [:id, :name]).to_json`

However in a new project that has AMS 0.10.13 I am trying to do something similar but the options are not being picked up and I end up with all attributes. One thing I tried was passing `instance_options` to the attributes method but that isn't possible.

Is it possible to achieve the same result with options? The only method I found so far that works is by overriding the attributes method like so
`serializer.new(object).attributes([:id, :name]).to_json`

It feels more like a workaround that fits my current scenario but would like to know if there is a recommended way to go about doing something like this?

**Comment by wasifhossain** [comment]
in v0.10.x, are you looking for [`fields`](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/fields.md)?

**Comment by michael-royski-checkr** [comment]
Thanks @wasifhossain. Fields should be the functionality I am looking for however the example is a totally confusing to me, as I am not rendering json in that manner. Was looking for an easy way to pass an option like `serializer.new(object, fields: [:id])` but it looks like using attributes is the easiest so far. Not sure why this is such a difficult thing for me to implement.

**Comment by wasifhossain** [comment]
besides `render`, you can also pass `fields` in [AMS::SR](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/howto/outside_controller_use.md), like this:
 
```rb
ActiveModelSerializers::SerializableResource.new(object, fields: %i[id name], serializer: serializer).to_json
```

**Comment by michael-royski-checkr** [comment]
@wasifhossain appreciate it! I had to use AMS::SR like you suggested but also needed to pass in `adapter: :attributes`
The application I am working on sets `ActiveModelSerializers.config.adapter` to a custom adapter that was created to handle the update from 0.8 to 0.10. I thought this would not be an issue because of this statement in the documentation:

"IMPORTANT: Adapter configuration has no effect on a serializer instance being used directly. That is, UserSerializer.new(user).as_json will always behave as if the adapter were the 'Attributes' adapter. See [Outside Controller Usage](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/howto/outside_controller_use.md) for more details on recommended usage."

But when using the serializer like this, it was still using the adapter set in the config.

**Comment by bf4** [comment]
@michael-royski-checkr things work out ok?
