### ISSUE TITLE
Please update master branch and GitHub releases

### ISSUE THREAD

**Issue by joshgoebel** [rails-api/active_model_serializers#2445]
@bf4 Benjamin, are you the maintainer here?  I see you as the only one listed as publishing on RubyGems.

Two asks:

- Could GitHub releases be kept up-to-date?  Your latest release is listed as v0.10.0.rc1 from 2015.  If you aren't going to use the release feature you could turn it off so people are not confused about the latest release.

<img width="325" alt="Screen Shot 2023-04-20 at 4 07 15 PM" src="https://user-images.githubusercontent.com/6473/233476352-6c569d27-e156-4ab3-855c-eacce96fe0d4.png">

- Could your master (or main) branch please point to the latest release?  Right now your Github landing page (at first glance) makes it looks like the project is dead and unmaintained. (files not changed in 5-6 years, last release 2015).

<img width="147" alt="Screen Shot 2023-04-20 at 4 08 07 PM" src="https://user-images.githubusercontent.com/6473/233476554-648d1889-0815-4d14-8a14-9d1d6aa4e10c.png">

Thanks,
Josh

**Comment by bf4** [comment]
I've never used github releases. Is that a problem? And the main readme does mention the maintenance state,.no?

**Comment by joshgoebel** [comment]
> I've never used github releases. Is that a problem? 

If you leave the feature on, but don't maintain it then it's pretty _misleading_ IMHO.  Considering going into settings and turning it off if you don't plan to update it when you issue new releases.

>  And the main readme does mention the maintenance state,.no?

I wouldn't know... When I see all the files are 6-7 years old I'm probably not going to bother to read the README... (yes, I managed to miss the 3 year old readme, but that's not much better).  If you're still actively maintaining the project I dunno why you wouldn't want THAT branch to be the first thing people see when coming here.

Just some easy to fix advice... you're free to take it or leave it.

**Comment by bf4** [comment]
You should be nicer

**Comment by joshgoebel** [comment]
I pointed out two real issues that would be easy to fix; for no other reason than to help improve the project. 

You asked follow up questions and I answered clearly and expediently. 

That's about as nice as I can be. I'm sorry if such help isn't appreciated here. 😕
