### ISSUE TITLE
How do I render a node that is not associated to an attribute?

### ISSUE THREAD

**Issue by seanarnold** [rails-api/active_model_serializers#2470]
#### Expected behavior vs actual behavior

I just want to nest some attributes under another node.

i.e I want my end JSON to look like:
```json
{
  "name": "Test",
  "aws": {
    "account": {
      "accountID": "123456789012",
      "region": "us-east-1"  
    },
    "some_has_one_model": {
      "some_info_from_another_model": true
    }
  }
}
```

All the data except for `some_has_one_model` is on the root model, and it `has_one: some_has_one_model`.

But so far I can't seem to find a way to just render that `aws` node and nest stuff under it?

The options I'm aware of are:

**Use attribute and a hash**
  - Problem: That doesn't let me use `has_one`

```ruby
attribute(:aws) do 
  {
    account: {
      accountID: object.account_id,
      region: object.rehgion
    },
    has_one :some_has_one_model # <--- This obviously does not work
  }
end
```

**Use a seperate serializer**

```ruby
attribute(:aws) { AwsSerializer.new(object).as_json }
```
but that seems wrong and annoying tom need to create a new file.

I'm surprised there is no `node` DSL so I could just do something like:

```ruby
node :aws do 
  node :account do 
    attribute(:accountID)
    attribute(:region)
  end
  has_one :private_link
end
```

As it stands AMS is making some assumptions that our JSON format maps quite heavily to our DB structure

Am i missing something here? 

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: `v0.10.13`

**Comment by bf4** [comment]
re `attribute(:aws) { AwsSerializer.new(object).as_json }`

That seems like what you want. you can define that serializer within this one if that helps with code organization.

In general, if you're building an object for an attribute, using a serializer seems like a good approach
