### ISSUE TITLE
Correct way to unit test serializers

### ISSUE THREAD

**Issue by Elexy** [rails-api/active_model_serializers#274]
What is the correct way to unit test serializers and is there a point to it? Maybe testing the controller is a more sensible approach. I have a working setup but it seems like a lot of code each time

currently I have this in serializer:

```
class ElementSerializer < ActiveModel::Serializer
  attributes :id, :tag, :htmlId, :htmlClasses, :page_id, :parent_id

  def page_id
    object.page_id
  end

  def parent_id
    object.parent_id
  end

  has_many :children
end

```

and my test:
require 'spec_helper'

```
describe ElementSerializer do
  element1 = Element.create(tag: "div", htmlId: "1", htmlClasses: "class1 class2")

  it "deserializes the hash" do
    expect(JSON.parse(ElementSerializer.new(element1).to_json)["element"]["tag"]).to eq('div')
  end
end
```

**Comment by timscott** [comment]
I'm just thinking about this. I agree, we don't need to test ```#to_json```.  I noticed a method ```#serializable_hash``` which perhaps provides a convenient way to access to the values with all behavior applied and just the actual serialization.
