### ISSUE TITLE
Passing serializer options for associations

### ISSUE THREAD

**Issue by grk** [rails-api/active_model_serializers#331]
Is there any way to pass serializer options to associations? 

I looked at the code, and it looks like it was planned, but is not "connected" yet.

ActiveModel::Serializer::Association takes the third argument for serializer_options, but I don't see it used anywhere. Perhaps getting them from options[:serializer_options] would be a good idea?

Would you accept a pull request with that change?

**Comment by gnapse** [comment]
Hi, sorry to resurface this discussion, but I'm not sure if this feature was finally provided, and if so, how to use it. Or else any workarounds. Any updates on this?

**Comment by oliverjesse** [comment]
afaict everyone has stopped using ams and gone back to jbuilder :( too bad, i like the ams interface way better

--
Jesse Sanford

**Comment by voltechs** [comment]
Not sure what poll you're referring to. Can you cite your source @oliverjesse? We for one are still using AMS...

I'd also like the 411 on how to use this feature, if it exists.

**Comment by jameswilliamiii** [comment]
You can use the options to pass along the info to the association.  An example would be:

```ruby
class PlantSerializer < ActiveModel::Serializer
  has_one :plant_type

  def initialize(object, options={})
    super
    # This options[:parent] will get passed through to the plant_type
    options[:parent] = object.parent
  end

end

class PlantTypeSerializer < ActiveModel::Serializer

  def my_method
    # I am able to access the previously set data using @options
    if @options[:parent]
      # do something special based on @options[:parent]
    end
  end

end
```
There is probably an elegant solution, but this is how I am solving the problem for now.
