### ISSUE TITLE
Meta key not being picked up

### ISSUE THREAD

**Issue by lserman** [rails-api/active_model_serializers#332]
The meta key option is not showing in the JSON, I am using similar syntax to the readme:

`render json: users, meta: @settings, meta_key: 'settings'`

`@settings` is a normal Ruby hash. The users are being rendered as expected with the UserSerializer, except the "settings" key is not present.

**Comment by NeoElit** [comment]
Custom meta not showing up even with root on active_model_serializers (0.9.3).
```
render :json => @place, :serializer => PlaceSerializer, :meta => {:content => "10", :type => "success"}
```
is working fine and meta is retrieved, however with:
```
render :json => @place, :serializer => PlaceSerializer, :meta => {:content => "10", :type => "success"}, :meta_key => 'message'
```
it's not giving any meta or message.

**Comment by bf4** [comment]
@NeoElit please open a new issue, or search existing issues. I believe I solved this for my team and have a comment on it in one of them.  Please also take a look at https://github.com/rails-api/active_model_serializers/blob/master/CONTRIBUTING.md

This issue was closed in 2013.
