### ISSUE TITLE
Wrongly formated ids when using mongoid head

### ISSUE THREAD

**Issue by sphw** [rails-api/active_model_serializers#354]
I am upgrade my application to rails 4 and I have noticed that the id field is being formatted wrong. it is being formated like this 
  "_id": {
    "$oid": "51c7bd98e77989d1f1000002"
  }
I believe this stems from mongoid returning a json object now instead of simple a string .

**Comment by dangalg** [comment]
What if I want the exact opposite? 

from:
"_id": "51c7bd98e77989d1f1000002"

to:
"_id": {
"$oid": "51c7bd98e77989d1f1000002"
}

**Comment by dfabreguette-ap** [comment]
Just had an issue using elasticsearch mongoid gem (calling rake es:reindex). After Some Search I found this github issue solving my problem : https://github.com/nesquena/backburner/issues/80

**Comment by jagdeepsingh** [comment]
### Configuration

```ruby
# Gemfile
gem 'rails', '~> 5.2.0'
gem 'mongoid', '~> 7.0.1'
gem 'bson_ext', '~> 1.5.1'
gem 'active_model_serializers', '~> 0.10.7'
```

### mongoid document serialized using `ActiveModel::Serializer`

#### Default

Output

```ruby
{
    "id": {
        "$oid": "5b336e9d6120b24c62287e5b"
    },
    "token": "823725b2eeb8ced8bed3c58fe18479d1d07d616c072dc02a0e",
    "refresh_token": null,
    "expires_in": 900,
    "revoked_at": null,
    "resource_owner_id": {
        "$oid": "59c8a5bd6120000c4e000164"
    }
}
```

#### With initializer 

```ruby
# config/initializers/bson.rb
module BSON
  class ObjectId
    alias :as_json :to_s
  end
end
```

Output

```ruby
{
    "id": "5b336e9d6120b24c62287e5b",
    "token": "823725b2eeb8ced8bed3c58fe18479d1d07d616c072dc02a0e",
    "refresh_token": null,
    "expires_in": 900,
    "revoked_at": null,
    "resource_owner_id": "59c8a5bd6120000c4e000164"
}
```

**Comment by rrecio** [comment]
@jstejada version worked better for me:

```
module BSON
  class ObjectId

    def as_json(*args)
      to_s
    end

  end
end
```

The other solutions crashed of generated a strings containing special quote characters which led my REST client consumers to read ids as "\"123131b23b1b23b1b3\"" instead of "123131b23b1b23b1b3"
