### ISSUE TITLE
Avoiding multiple SQL queries when using ArraySerializer?

### ISSUE THREAD

**Issue by brandonparsons** [rails-api/active_model_serializers#363]
Good morning,

I find that when I use AMS to generate JSON for a set of models that include associations, it is resulting in a ton of SQL queries (one for each association).  How can I avoid this?

I've tried to do an `include` in the controller:

`render json: Project.includes(tasks: [:workers])`

But this does not seem to work.  Even if I pass the relation (with includes) directly to `ArraySerializer` it doesn't help.

Thanks!

**Comment by wallace** [comment]
For those who may stumble upon this issue via direct searching in AMS issues, you want [this stackoverflow answer](http://stackoverflow.com/a/23814855/91029).

**Comment by bf4** [comment]
@wallace Thanks for that!
