### ISSUE TITLE
Configurable serializers for "expand" and "fields" parameters as REST API conventions

### ISSUE THREAD

**Issue by mateusmaso** [rails-api/active_model_serializers#370]
There are many cases that defining more than one serializer for a specific model who does the same behavior but with less attributes and relationships do not seem to be flexible when dealing with public REST APIs.

What I'm wondering is something that I could declare all methods and attributes possible and set defaults inside a serializer. Then let the users configure what they want to receive. Here is an example of the UserSerializer.rb:

```ruby
class UserSerializer < ActiveModel::Serializer

  defaults :id, :name, :slug, :gender, :work
  
  attributes :id, :name, :slug, :gender, :first_name, :image

  has_one :work
  has_many :followings
  has_many :followers

end
```

When I fetch to get users information, the default behavior would be:
```GET users/1234``` 
```ruby
UserSerializer.new(user) 
# => {id: 1234, name: 'Foo', gender: 'm', work: {...}}
```

But, for some users that want nested properties with only one request they should be able to configure by sending extra fields like "expand" for relationships and "fields" for attributes:

``` GET users/1234?expand=followers&fields=id,slug```
```ruby
UserSerializer.new(user, :expand => params[:expand], :fields => params[:fields]) 
# => {id: 1234, slug: 'foo', followers: [...]}
```

So, is it active_model_serializer's job or should I extend to reach what I want?

**Comment by thomasdavis** [comment]
Great tips so far guys, hope someone can come up with a plug and play solution =D

**Comment by joaomdmoura** [comment]
@thomasdavis this is not exactly the same implementation but we might add something similar to 0.10.x

**Comment by SirRawlins** [comment]
Just stumbled across this thread but it took a bit more hunting around to understand the current state of affairs.

Seems that this (or at least something similar) is now supported when using the JsonApi adapter.

https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md#json-api
