### ISSUE TITLE
CamelCase JSON format

### ISSUE THREAD

**Issue by wojtha** [rails-api/active_model_serializers#398]
Is there a recommended way how to produce camelized keys by default during serialization by using AMS?

In small APIs one can just override the attributes hash, but is not a feasible way for bigger APIs.

I guess that probably the best way would be to fork AMS and camelize the keys somewhere in the overriden `serialize` method? Or do someone has better idea?

Btw some interesting links about snake_case vs. CamelCase in JSON:
- https://blog.apigee.com/detail/restful_api_design_what_about_attribute_names
- http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#snake-vs-camel

**Comment by ratbeard** [comment]
Has anyone written a camelcase adapter for 0.10?

**Comment by joaomdmoura** [comment]
@ratbeard no, we haven't build a specific CamelCase adapter yet.

**Comment by semikolon** [comment]
Some models have trailing questionmarks in method names like model.was_good? and I wanted it to translate to wasGood in JSON. Here's my solution. Some repetition for has_many/has_one/belongs_to  - how would you simplify it?

```
class ApplicationSerializer < ActiveModel::Serializer
  def attributes(options={})
    super(options).map { |k, v| [ k.to_s.camelize(:lower).chomp('?').to_sym, v ] }.to_h
  end

  def self.has_many(*args)
    options = args.extract_options!
    options.reverse_merge!({ key: args.first.to_s.camelize(:lower).to_sym })
    args << options
    super(*args)
  end
  def self.has_one(*args)
    options = args.extract_options!
    options.reverse_merge!({ key: args.first.to_s.camelize(:lower).to_sym })
    args << options
    super(*args)
  end
  def self.belongs_to(*args)
    options = args.extract_options!
    options.reverse_merge!({ key: args.first.to_s.camelize(:lower).to_sym })
    args << options
    super(*args)
  end
end

```

Here's the current code for associations in AMS: https://github.com/rails-api/active_model_serializers/blob/aaa60bfdc131cbd96b322037f56bce99a9f36de5/lib/active_model/serializer/associations.rb

**Comment by sebbean** [comment]
hey ya'll

Just wanted to point out: https://github.com/domchristie/humps as a nice way to not have to change the API format (I'm partial to snake_case for API data) to fit the front end library (React in my case).

**Comment by dkniffin** [comment]
It looks like using a [key_transform](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/key_transforms.md) might be a good solution for this

**Comment by NullVoxPopuli** [comment]
there is now also https://github.com/NullVoxPopuli/case_transform
which will eventually be pulled in to AMS when I get it having native extensions

**Comment by thePooh** [comment]
@NullVoxPopuli, looking forward for it.

**Comment by NullVoxPopuli** [comment]
@thePooh case_transform is in AMS now, so you can optionally use the native extensions variant

**Comment by william-mendes** [comment]
Other option is add:
`ActiveModel::Serializer.config.key_transform = :camel_lower
ActiveModel::Serializer.config.default_includes = "**"`
To the: active_model_serializers.rb

Everything that goes through the serializer will be camelCase

**Comment by lapenz** [comment]
> Other option is to add:
> `ActiveModel::Serializer.config.key_transform = :camel_lower ActiveModel::Serializer.config.default_includes = "**"`
> 
> To the: active_model_serializers.rb
> 
> Everything that goes through the serializer will be camelCase

This works fine for me. I could use it for different scopes in my app:

class BaseSerializer < ActiveModel::Serializer
    ActiveModel::Serializer.config.key_transform = :underscore

  end
