### ISSUE TITLE
Should enforce snake_case attributes by default

### ISSUE THREAD

**Issue by eccegordo** [rails-api/active_model_serializers#507]
When I run the following generator:

```
rails g serializer student firstName
```

results in the following output in `app/serializers/student_serializer.rb`

```
class StudentSerializer < ActiveModel::Serializer
  attributes :id, :firstName
end
```

If feasible, this should probably enforce the snake_case convention. 

```
class StudentSerializer < ActiveModel::Serializer
  attributes :id, :first_name
end
```

The camelCased attribute presents subtle issues for users of Ember Data who are expecting snake_cased attributes in the JSON output.

Some related discussion here https://github.com/dockyard/ember-appkit-rails/issues/183

I recognize that there may be larger more subtle issues involved with enforcing the specific snake_case behavior. But if a user types in a camelCased attribute in their generator command they may introduce subtle issues that are not completely obvious.

Wondering if perhaps one solution is to keep the explicitly camelCased attribute (respect user intention in the generator) but inject a transformation of the attribute for the user.

```
class StudentSerializer < ActiveModel::Serializer
  attributes :id, :firstName, :first_name

  def first_name
    object.firstName
  end
end
``` 

This behavior perhaps could be hidden behind a special flag `--mixedcase`

**Comment by joaomdmoura** [comment]
I'm closing this one, mostly because it's out of date and we are already handling it on other PR's a discussions.
