### ISSUE TITLE
scope not passed to ArraySerializer

### ISSUE THREAD

**Issue by sebastianzillessen** [rails-api/active_model_serializers#510]
I have a code fragment where I decide to use a `Serializer` based on some ruby code, and then I want to serialize a collection with this Serializer.

```
     ser = if (week)
              PlayerHighscoreWeekSerializer
            else
              PlayerHighscoreSerializer
            end

      p [:serializer, ser]
      p [:current_player, :beforeArray, current_player]
      data = ActiveModel::ArraySerializer.new(pagination, each_serializer: ser, scope: current_player).as_json
```

My serializer looks like this

```
class PlayerOpponentSerializer < ActiveModel::Serializer
  cached
  attributes :id, :name, :is_friend

  def is_friend
    p 'is_friend?'
    p [:scope, scope]
    false
  end
end
```

The method `current_player` is defined in the context of the controller and returns a player.
But the `scope` in my `PlayerOpponentSerializer` is always `nil`!

What am I doing wrong?

Thanks

**Comment by petermumford** [comment]
For me I passed the **view_context** to the array serializer:

`ActiveModel::ArraySerializer.new(your_array, each_serializer: YourSerializer, scope: self.view_context)`

And make sure you include `serialization_scope :view_context` to you application_controller.rb and then `delegate :current_user, to: :scope` in your **serializer.rb**

With the above done you can simple call **current_user** as you'd normal do

using version: **0.8.3**
