### ISSUE TITLE
Cannot filter fields when the field in used as the embed key.

### ISSUE THREAD

**Issue by zhaohanweng** [rails-api/active_model_serializers#513]
I have a case that a message has a parent message, and would like to overwrite parent_id to something else, so the front end will not see the actual parent_id. I tried the following to sideload the parent message, but the message_id is always showing.

`has_one :parent, embed: :id, key: :message_id, include: true, root: :parent_messages`

```
def message_id
  object.parent_id
end
```

in this case I want to filter the message_id, so it would not show up in the json. 
I tried
`def include_message_id?; false end`
and
```
def filter(key)
  key - [:message_id]
end
```
The final json still contains the message_id.

It seems the filtered key is overriden by the association

Or is there any proper way to overwrite the parent_id to display something else, and still able to sideload the parent message?

**Comment by NullVoxPopuli** [comment]
If this is still an issue, please feel free to re-open. Just closing for cleanup of issues.
