### ISSUE TITLE
filter method not triggered

### ISSUE THREAD

**Issue by michaelirey** [rails-api/active_model_serializers#516]
In my serializer

```
class ProductSerializer < ActiveModel::Serializer
  attributes :id, :name, :description
  def filter(keys)
    keys - [:name]
  end
end
```

However, name attribute stays in.

I have tried this:

```
class ProductSerializer < ActiveModel::Serializer
  attributes :id, :name, :description
  def filter(keys)
    binding.pry
  end
end
```

The pry is not invoked.

**Comment by linesarefuzzy** [comment]
Why is the filter feature not in the master Readme? It is described in branch `0-9-stable`, but it works in my project, which has simply `gem 'active_model_serializers'` in the Gemfile (and `0.9.3` listed in Gemfile.lock).

**Comment by marknadig** [comment]
As one how is/was searching... surprised not in README... guess the 10.x overshadowed it.

**Comment by joaomdmoura** [comment]
Hi @linesarefuzzy and @marknadig, indeed our efforts are deeply focused on 0.10.x, but we still want to help ppl who use older versions!

First of all, we strongly recommend you to check 0.10.x version and give it a try, we already have a RC2 and you can also point it to master if you like to live on the cutting-edge.

I've just checked the 0.9-stable branch and it seems the `filter` features *is* mentioned there:

> Also, as with attributes, serializers will execute a filter method to determine which associations should be included in the output. For example:

```ruby
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body
  has_many :comments

  def filter(keys)
    keys.delete :comments if object.comments_disabled?
    keys
  end
end
```

> Or ...

```ruby
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body
  has_one :author
  has_many :comments

  def filter(keys)
    keys.delete :author unless scope.admin?
    keys.delete :comments if object.comments_disabled?
    keys
  end
end
```

**Comment by linesarefuzzy** [comment]
@joaomdmoura Yes, it's described in 0.9-stable but not in master. However, it works in whatever version is used when the Gemfile says `gem 'active_model_serializers'`, which I assume is master or previous to master. Shouldn't it then also be in the master readme?
