### ISSUE TITLE
Nested self-referential associations result in duplicate keys

### ISSUE THREAD

**Issue by dmarkow** [rails-api/active_model_serializers#521]
I have an `Address` class which `has_many :addresses`.

Using:
```
class AddressSerializer < ActiveModel::Serializer
  embed :ids, include: true
  attributes :id, :location
  has_many :addresses
end
```

And this in my controller:

```
@addresses = Address.where(address_id: nil)
render json: @addresses
```

I get this output. Note the duplicate "addresses" key. Because of this unexpected output, my client is only picking up one of the sets of "addresses" and ignoring the assocations.
```
{
  "addresses":
    [
      {"id":1,"location":"123 Main","address_ids":[2]}
    ],
  "addresses":
    [
      {"id":2,"location":"Unit 1","address_ids":[]}
    ]
}
```

If I rename the association on my model to `has_many :sub_addresses, class_name: "Address"` and use `has_many :sub_addresses` in my serializer instead, it works fine, even doing multiple levels deep, except that now my client needs to know to look in `sub_addresses` instead of `addresses`. Will I just have to use this different "sub" key instead, or is this a bug?

**Comment by NullVoxPopuli** [comment]
Ember hardcore recommends json-api for solving relationship issues. Closing in favor of 0.10. (and this is very old)
