### ISSUE TITLE
Pagination in serializers

### ISSUE THREAD

**Issue by brucexlin** [rails-api/active_model_serializers#543]
If I have an object that contain a list of associations (for example, album with photos) and I want to return the album with paginated photos. Shall I do this in album_serializer?  If so how should I pass the page_number and items_per_page since they don't belong to the album object?

**Comment by equivalent** [comment]
exampel of Kaminari gem pagination implementatin hcould be find here http://stackoverflow.com/questions/22947721/rails-active-model-serializer-with-pagination

**Comment by aivils** [comment]
Even this goes out of AMS's scope AMS already have built-in solution. You can
use any custom method as serialization_scope

```ruby
# controller sample
class MessageThreadsController < ApplicationController
  serialization_scope :serializer_scope

  private

  # write all your pagination, sorting needs in this method
  def serializer_scope
    {
      messages: {
        page: params[:messages_page]
      }
    }
  end
end

# serializer sample
class MessageThreadSerializer < ActiveModel::Serializer
  has_many :messages

  def messages
    object.messages.latest.page(scope[:messages][:page])
  end
end
```
Not very sane because you dont need 2nd page of messages of every message thead. Rather
you need limited count of messages per thread.
