### ISSUE TITLE
Undefined method `perform_caching` for nil:NilClass

### ISSUE THREAD

**Issue by ericpeters0n** [rails-api/active_model_serializers#544]
Seeing this error in my app on heroku --although it runs fine locally.

Offending calls is:
````
render json: { :events => event_pool }, serializer: ActivitySerializer
````
where ActivitySerializer is
```
class ActivitySerializer < ActiveModel::Serializer
	attributes :events, :timestamp

	def events
		object[:events].map { |event| EventSerializer.new(event) }
	end
	def timestamp
		Time.now.utc
	end
end
```
Note: No caching is enabled, nor is a cache_key defined

I can't follow the discourse in https://github.com/rails-api/active_model_serializers/issues/241. Any hints as to what I might be looking at?

**Comment by NullVoxPopuli** [comment]
This is an old issue. It might be resolved in 0.10, and I encourage you all to check out that version.
