### ISSUE TITLE
embed :ids, include: true causes many queries

### ISSUE THREAD

**Issue by daveroberts** [rails-api/active_model_serializers#558]
Imagine I have a data model:

```
class Teacher < ActiveRecord::Base
  has_many :students
end
class Student < ActiveRecord::Base
  belongs_to :teacher
end
class TeacherSerializer < ActiveModel::Serializer
  embed :ids, include: true
  attributes :id, :name
  has_many :students
end
```

If I call /teachers.json I get the expected output:

```
{"students": [{"id":1,"name":"Johnny"},{"id":2,"name":"Alice"}], "teachers": [{"id":1,"name":"Ruth","student_ids":[1]},{"id":2,"name":"Walter","student_ids":[2]}]}
```

However, when viewing the SQL logs, generating this output takes many more queries than necessary.  For example:

```
SELECT "students".* FROM "students" WHERE "students"."teacher_id" = ?  [["teacher_id", 1]]
SELECT "students".* FROM "students" WHERE "students"."teacher_id" = ?  [["teacher_id", 2]]
SELECT "students".* FROM "students" WHERE "students"."teacher_id" = ?  [["teacher_id", 3]]
(Repeat for each teacher)
```

If there are 1000 teachers in my database, there will be 1000 queries to get this data.

Fortunately, it looks like ActiveRecord has a solution:  Teacher.includes(:students).all

Is there any way Active Model Serializers can utilize this to cut down on the number of DB queries?

**Comment by chrise86** [comment]
What if you want to limit the number of associated records returned?

In the serializer you could do something like:

    has_many :students

    def students
      object.students.limit(5)
    end

But `Teacher.includes(:students)` is going to ignore that and eager load all (potentially thousands) of students. How would you handle this situation?

**Comment by JulianLeviston** [comment]
@chrise86 No, that'll limit it just fine.

**Comment by chrise86** [comment]
@JulianLeviston hm I had that exact issue recently, 0-8-stable branch. I had a user model that had over 20K+ followers, and it was eager loading every single one :-/ as soon as I took out the `includes(:followers)` it stopped...

**Comment by JulianLeviston** [comment]
If you limit it in the model, and use one of the model's associations, it should work just fine. Otherwise, file a bug with a failing test.
