### ISSUE TITLE
There needs to be a way to create versioned serializers.

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails-api/active_model_serializers#562]
I used to use the presenter pattern, which I've found to be very very helpful. But this serializer gem seemed to have all of the functionality I had implemented with presenters, and then additionally relationships.  The reason I was using presenters is because of how we versioned the API. Over time, we've changed the names of attributes and models. 

The presenter file layout was this:

```
app/presenters/api
/v1
  document_presenter.rb
/v2
  document_presenter.rb
```

and in those would be selected based on the the controller route (I know people like to use http headers for api versions, but that's not that hard to do, and this was easier at the time).

The big difference between the api versions is how json collections were rendered.

There are two common formats:

format 1:

```
{
    "resource" : [
          { attributes for this resource }, { attributes for this resource }
     ]
}
```

and 

format 2:

```
[
    "resource": { attributes for this resource },
    "resource": {attributes for this resource }
]
```

format 1 is the more prefered way now a days, which makes sense - it's cleaner, less verbose, and Ember.js uses it.  So that's what we are trying to migrate towards. The ActiveModel Serializers make format 1 really easy.  However, since Serializers don't support API versioning, we are kind of stuck between a rock and a hard place with our older clients' integrations. 

I've been trying to massage the Active Model Serializers for some time now, and came to realize that that I can't override (or don't know how to) the methods that I need to override -- due to the fact that ActiveModel Serializers are all singleton classes. The custom serializers are instances of subclasses of those singletons - which seems reeaaaly weird to me. 

Anywho, this is where I am with trying to extend ActiveModel Serializers to allow different kinds of collection / array json formats.

```
class ActiveModel::Serializer
  class << self

    # Used internally to create a new serializer object based on controller
    # settings and options for a given resource. These settings are typically
    # set during the request lifecycle or by the controller class, and should
    # not be manually defined for this method.
    def build_json(controller, resource, options)
      default_options = controller.send(:default_serializer_options) || {}
      options = default_options.merge(options || {})

      serializer = serializer_for(path: options[:prefixes].first, resource: resource)

      serializer = options.delete(:serializer) || serializer ||
        (resource.respond_to?(:active_model_serializer) &&
         resource.active_model_serializer)

        return serializer unless serializer

      if resource.respond_to?(:to_ary)
        unless serializer <= ActiveModel::ArraySerializer
          raise ArgumentError.new("#{serializer.name} is not an ArraySerializer. " +
                                  "You may want to use the :each_serializer option instead.")
        end

        if options[:root] != false && serializer.root != false
          # the serializer for an Array is ActiveModel::ArraySerializer
          options[:root] ||= serializer.root || controller.controller_name
        end
      end

      options[:scope] = controller.serialization_scope unless options.has_key?(:scope)
      options[:scope_name] = controller._serialization_scope
      options[:url_options] = controller.url_options

      serializer.new(resource, options)
    end

    def serializer_for(path: "", resource: "")
        ActiveModel::Serializer.serializer_for(path: path, resource: resource)
    end
  end

    # Finds the Serializer for a given path and / or resource
    # 
    # @param [String] path the app controller path. This is used to determine
    #  which API version we are requesting
    # @param [Object] resource the object to be serialized
    # @return [Class] the corresponding serializer or nil
    def self.serializer_for(path: "", resource: "")
      serializer = (
        default_serializer = "#{resource.class.name}Serializer"
        if path.present?
          api_version = path.scan( /api\/v(\d)\// ).flatten.first
          serializer_prefix = api_version.present? ? "V#{api_version}::" : ""
          if resource.respond_to?(:to_ary)
            default_serializer = "ArraySerializer"
          end
          "#{serializer_prefix}#{default_serializer}"
        elsif resource.present?
          default_serializer
        end
      )

      begin
        serializer.constantize
      rescue NameError
        nil
      end
    end
end
```

I was unsuccessful in creating `V1::ArraySerializer` and `V2::ArraySerializer` -  I couldn't seem to find any instance methods to override that would allow for changing the way the json structure is formatted. 

If you are curious about where I was with presenters, I put a good amount of the code in this gist: https://gist.github.com/NullVoxPopuli/32941b91c90f1226e828

**Comment by brancusi** [comment]
+1

**Comment by miguelpeniche** [comment]
+1
