### ISSUE TITLE
URL helpers don't work for embedded objects

### ISSUE THREAD

**Issue by estill01** [rails-api/active_model_serializers#563]
Given the following example embedded object relationship:

```
class Car < ActiveModel::Serializer
  attributes :id, :make, :model, :url
  has_many :passengers

  def url
    car_url(object)
  end
end

class Passenger < ActiveModel::Serializer
  attributes :id, :name, :url

  def url
    passenger_url(object)
  end
end
```

Visiting something like http://api.approot.com/car/3.json should return something like:

```
{        
  - car: {
      id: 3,
      make: 'Ford',
      model: 'F150',
      url: 'http://api.approot.com/car/3.json',
    - passengers: [
        - {
             id: 7,
             name: 'Bill',
             url: 'http://api.approot.com/passengers/7'
           },
        - {
             id: 13,
             name: 'Will',
             url: 'http://api.approot.com/passengers/13'
          }
      ]
    }
}
```

In practice however, the :url attribute for Passenger does not get rendered.

**Comment by Bernard4132** [comment]
This is a DIY way to solve this problem. Create a field on the model to store the url. then after the object has been saved, you update it with a manually generated url like this.
here is how i solved it.

if @questionsolution.save
generatedurl = 'http://localhost:3000/questionsolutions/' + @questionsolution.id.to_s
        @questionsolution.update(solutionurl: generatedurl)
end
 then you can get the url from the resource direclty without depending on active model serializers to do it for you.
