### ISSUE TITLE
ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

### ISSUE THREAD

**Issue by moger777** [rails-api/active_model_serializers#573]
Getting this error even when I set:

ActiveModel::Serializer.default_host_options[:host] = '127.0.0.1:3000'

while running tests

**Comment by dzoltok** [comment]
Issue still seems to be occurring on Rails 4.2.0, AMS 0.9.3, but for me it's occurring in a regular controller. Using the workaround above results in an error "undefined method `build_json' for SomeSerializer:class"

**Comment by gwagener** [comment]
I think upgrading to 0.8.3 fixed this for us with Rails 4.2, but code has changed so I can't check anymore. Can someone verify?

**Comment by typeoneerror** [comment]
Still exists in 0.9.x branch. Looks like if I have a database field that ends with `_url` it's trying to look up a route url in the app's namespace. Removing "terms_url" and "privacy_url" from my serializer fixes the bug.

**Comment by bf4** [comment]
@typeoneerror so, you're good? perhaps set a key for the `_url` attributes?

**Comment by typeoneerror** [comment]
@bf4 I'm good. What do you mean by "set a key for the _url attributes?"

**Comment by chrise86** [comment]
This also seems to be an issue on 0.10.0.rc3

**Comment by remear** [comment]
Rails url_helpers were added to 0.10 by #1550.
