### ISSUE TITLE
FYI url helpers 

### ISSUE THREAD

**Issue by andreasklinger** [rails-api/active_model_serializers#578]
Feel free to close this issue asap. It's meant as documentation for people who try to include urlhelpers into active_model_serializer. There are several complex pull_requests for this so i guess this is an active issue.

An easy way to include url helpers into the serializer to simply include the helpers into a base serializer and inherit from that one.

```
class API::V1::BaseSerializer
  include Rails.application.routes.url_helpers
end
```

and then inherit

```
class API::V1::PostSerializer < API::V1::BaseSerializer
   ....
   def url
    post_url(object)
  end
```

Hope this helps someone who ran into this problem like i did.

**Comment by lachlanjc** [comment]
@andreasklinger 🙏  Thank you!
