### ISSUE TITLE
Specifing timestamp format

### ISSUE THREAD

**Issue by bradly** [rails-api/active_model_serializers#582]
My timestamps are coming out in my json responses like "created_at":"2014-07-07T18:01:26.000Z" when I'd really prefer all timestamps in iso8601 format. Is there a way to set this for all my serializers? 

fyi... Time.now.to_json does give me iso8601 in my rails console.

Thanks for any help!

**Comment by agis-** [comment]
Adding the commit for future reference: https://github.com/rails/rails/commit/28ab79d7c579fa1d76ac868be02b38b02818428a.

**Comment by joaomdmoura** [comment]
:+1:

**Comment by tilo** [comment]
for an API it would be great if there was support built-in to AMS to display times in UNIX format, either as decimals or floats

**Comment by Dhirendra24** [comment]
We can also override `read_attribute_for_serialization`.
```
  def read_attribute_for_serialization(attr)
    value = super

    if value.kind_of?(ActiveSupport::TimeWithZone)
      # change format
    end

    value
  end
```
