### ISSUE TITLE
Optional attributes / Passing arbitrary params to serializer

### ISSUE THREAD

**Issue by kenn** [rails-api/active_model_serializers#599]
(from #552) I just realized that AMS is in flux. But I'd throw in my issue (based on 0.9), anyway.

We have a master-detail view where the master shows a list of conversations with the last message included, and the detail displays one conversation with all messages.

One way to do it is:

```ruby
class Conversation
  has_many :messages
  has_one :last_message
  attr_accessor :show_details
end

class ConversationSerializer < ActiveModel::Serializer
  attributes :last_message, :messages

  def attributes
    if object.show_details
      super.except(:last_message)
    else
      super.except(:messages)
    end
  end
end

# controller
@conversation.show_details = true
render json: @conversation
```

But this feels wrong on two fronts:

* The model shouldn't contain view (or serializer, in this case) concerns like `show_details`. There should be a way to directly pass the hint from controller to serializer, not through model.
* It doesn't work when it's called from an array context - you need to do `conversations.each{|i| i.show_details = true }`. The hint should be stored at the array level, not at the item level.

For those reason, I would suggest that we enable to pass arbitrary parameters to the serializer, from controller.

```ruby
class ConversationSerializer < ActiveModel::Serializer
  params :show_details

  def attributes
    if @show_details
      super.except(:last_message)
    else
      super.except(:messages)
    end
  end
end

# controller
render json: @conversation, serializer_params: { show_details: true }
```

and pass down the params to each item, when the target was an array.

That way, we don't have to alter the model and separation can be done nicely. What do you think?

**Comment by toobulkeh** [comment]
:+1:

**Comment by jszwedko** [comment]
Is there a recommended way to do this with `0.10`? I see https://github.com/rails-api/active_model_serializers/pull/679 was merged in after this issue was opened, but since 0.10 is based on 0.8 it is not in master.

**Comment by jszwedko** [comment]
Never mind, found it under `instance_options` :smile:

**Comment by bf4** [comment]
@jszwedko do you have an example of what you did? This issue has great discussion in it..

**Comment by jszwedko** [comment]
@bf4 

Sure thing, I did something like:

PostController
```ruby
...
  def show 
    render json: @post, user_id: 1234
  end
...
```

PostSerializer
```ruby
...
  def my_comments
    Comments.where(user_id: instance_options[:user_id], post_id: object.id)
  end
...
```

**Comment by bf4** [comment]
ah, @jszwedko awesome, very clever use of all options going to the serializer unless the adapter ~~eats~~ uses them

**Comment by davidwparker** [comment]
Thanks @jszwedko - exactly what I needed!

**Comment by oyeanuj** [comment]
Great discussion, I was struggling with the similar behavior (follow vs not). Since I am still on 0.9, wondering if there any options for those 0.9 apart from adding a hack (attr_accessor)?

**Comment by victormier** [comment]
Any solution for `0.10.0`? `instance_options` are empty when I do this:
```
render json: @post, user_id: 1234
```

**Comment by bf4** [comment]
@jszwedko I think everyone would :100: if you were to write a documentation PR for this... :smile: or maybe even with tests :)

**Comment by cickes** [comment]
I too receive `undefined local variable or method 'instance_options'` when trying `render json: @post, user_id: 1234` with v0.10.0.  Can anyone help to explain or point to the correct resource?

**Comment by beauby** [comment]
@cickes `instance_options` is only available in the master branch, not in the current RC. In the current RC, you have to use `options` instead.

**Comment by dilizarov** [comment]
While instance_options is a method that I think works great, I'd like to say that I really enjoy the attr_accessor way of doing things as well. For example, in a feed of posts, I need to mark if a user has liked each post.

After fetching the feed's posts, I then do something like `current_user.mark_liked_posts!(@posts)` which for each Post would mark the `attr_accessor :liked` as false or true. I suppose you could pass in another hash of post ids all with false/true values and access that via instance_options... But I wouldn't look away from the attr_accessor approach just because it feels hacky. It's just Ruby :)

**Comment by cickes** [comment]
Thanks @beauby.  Changing from `instance_options` to `options` worked.

**Comment by kenn** [comment]
@dilizarov your case is one of the "legit" use cases of `attr_accessor`, as `liked` sounds like a model concern. But you clearly don't want `show_details` option in the model, do you? :)

I consider serializer as one of the presenter / decorator patterns, and the view (serializer) concerns should be self-contained.

And considering how often we use them, repetitive `@instance_options[:show_details]` is an eyesore and I prefer having `@show_details` or `params.show_details` instead.

**Comment by bf4** [comment]
Closing as I've extracted @jszwedko  solution to #1506 to make it easier for new contributors.  Also possibly relevant is serialization scope https://github.com/rails-api/active_model_serializers/pull/1252

**Comment by Malachi-Holden** [comment]
I tried @options, @instance_options, and serialization_options, no luck on any of them. I'm using v 0.10.6. @options and @instance_options are always nil, and serialization_options gives me a undefined local variable or method `serialization_options'
Has this changed again? What's the latest term?

**Comment by Malachi-Holden** [comment]
I also tried instance_options (without the @) and it still didn't work. Undefined method or variable
