### ISSUE TITLE
undefined method 'url'

### ISSUE THREAD

**Issue by KurtRMueller** [rails-api/active_model_serializers#604]
Hey guys,
I wanted to take AMS `0.10.0.pre` out for a test drive, especially because of the new `url` method. Unfortunately, I get a `NoMethodError: undefined method 'url'`  error whenever I try to instantiate a serializer object with this url method. 

Can anybody help me out? Thank you!

**Comment by JoshSmith** [comment]
@KurtRMueller would you be alright with closing this since this is quite outdated?

**Comment by beauby** [comment]
Closing this one for now, feel free to reopen if needed.
