### ISSUE TITLE
0.9 no longer automatically removes ? from boolean methods

### ISSUE THREAD

**Issue by dangalipo** [rails-api/active_model_serializers#605]
So this is more of an issue when using AMS in a class not backed by active model.

In 0.8 you could specify a boolean method and AMS would strip the ? in the JSON output how ever it no longer does this.

Example:

``` ruby
class Foo
  include ActiveModel::Serialization

  def has_a_bar?
    true
  end

  def active_model_serializer
    FooSerializer
  end
end

class FooSerializer < ActiveModel::Serializer
  attributes :has_a_bar?
end

#0.8
FooSerializer.new(Foo.new).to_json # "{\"foo\":{\"has_a_bar\":true}}"
#0.9
FooSerializer.new(Foo.new).to_json #"{\"foo\":{\"has_a_bar?\":true}}"
```

**Comment by pedromtavares** [comment]
Could we get this behavior ported to master please?

**Comment by NullVoxPopuli** [comment]
for a work around for now, you could do:

```ruby
  attributes :has_a_bar
  def has_a_bar
    object.has_a_bar?
  end
```

**Comment by pedromtavares** [comment]
Yeah, but sort of a pain to rewrite 20 serializers with around 10 of these methods each after upgrading.

**Comment by NullVoxPopuli** [comment]
I know it's a pain, but I think including the `?` makes more sense, as far as getting what you specify.

@rails-api/ams ?

**Comment by Sija** [comment]
@NullVoxPopuli: I disagree, no way to use 'em sensibly from js-side of things (`object.is_visible` vs `object['is_visible?']`)

**Comment by pedromtavares** [comment]
Yeah it doesn't make sense since '?' isn't used in Javascript. I'm trying to figure out a monkey patch in master for this (my entire Ember app is broken ATM), first time reading AMS code :)

**Comment by NullVoxPopuli** [comment]
what if someone, for some reason wanted a `?`, by omitting it by default, how would one specify to keep it?

**Comment by Sija** [comment]
`?` is IMO as much part of ruby's syntactic sugar as it's attribute name so it's more about compatibility with every other client-side language than with ruby <-> ruby API

**Comment by NullVoxPopuli** [comment]
@Sija, that's a good reason / argument -- I could get on board with that. 
I'm curious what other @rails-api/ams members think.

**Comment by bf4** [comment]
Just reading in email, but would be best to strip '?' From json key.  If previous behavior, def need to fix.  Failing test?

B mobile phone

**Comment by NullVoxPopuli** [comment]
I can submit a failing test real quick, one moment
