### ISSUE TITLE
serialization_scope error in 0.9.0

### ISSUE THREAD

**Issue by magg** [rails-api/active_model_serializers#622]
I recently updated the active_model_serializers gem to 0.9.0 and Nginx won't start

I have this on my controller: http://pastie.org/9517971

Here is the Nginx log: http://pastie.org/9517917, complaining about the line "serialization_scope :view_context"

and here is my serializer: http://pastie.org/9518000

Any help?

EDIT:

On my local machine it works fine with webrick

**Comment by JoshSmith** [comment]
@magg did you try an updated `0.9.x` release?

**Comment by magg** [comment]
@JoshSmith 

Thanks guys, it works in the later releases.

Sorry for the late response. I'm closing the issue.

**Comment by JoshSmith** [comment]
Thanks @magg!
