### ISSUE TITLE
How i can pass current_user now to serializer?

### ISSUE THREAD

**Issue by OpakAlex** [rails-api/active_model_serializers#624]
What happens with scope? 

`undefined local variable or method `current_user' for`

**Comment by toobulkeh** [comment]
Might want to add serialization_scope to the README. very helpful.

**Comment by joaomdmoura** [comment]
@toobulkeh just checked the README, it's already [here](https://github.com/rails-api/active_model_serializers/tree/0-9-stable#customizing-scope).
I'm closing this one

**Comment by petermumford** [comment]
For me I had to include the **view_context** to the ArraySerializer please see my comment on this issue: #510 (sorry don't know how to link to a comment on the issue)

**Comment by linjunpop** [comment]
@joaomdmoura The README on master branch does not have this section. Maybe add one?

**Comment by joaomdmoura** [comment]
@linjunpop Indeed, it would be great to add it, but maybe to our new [docs](https://github.com/rails-api/active_model_serializers/tree/master/docs) instead. I'm sure if the behavior still exactly the same but `serialization_scope_name` is implemented on 0.10.x

**Comment by danielfahy** [comment]
I'm passing information to the front end using the gon gem, as we are slowly moving towards a react front end.

In my application controller I call the UserSerializer manually if the user visits the /users endpoint

 gon.users = current_account.users.map do |user|
        UserSerializer.new(user, {scope: current_user}).attributes
      end

**Comment by peyterkim** [comment]
How would we mock this in an RSpec test for Serializers?

`allow_any_instance_of(Serializer).to receive(:scope).and_return(BaseController.new)`

this includes the scope, but RSpec would not recognize the `current_user` method on the scope.

**Comment by mapreal19** [comment]
@peyterkim you need to mock/set `scope_name` as `:current_user`
