### ISSUE TITLE
Improved examples in the README

### ISSUE THREAD

**Issue by zachaysan** [rails-api/active_model_serializers#633]
How do deal with common things like polymorphic associations, or specifying a custom serializer in a controller would be awesome.

**Comment by CodedBeardedSignedTaylor** [comment]
So, this is almost a year old.

@zachaysan, could you look over the current README give some suggestions for missing tutorials or examples? I'm going through and mocking up as many examples as I currently can!

**Comment by zachaysan** [comment]
Hey Josh! I can do that over the next week if that is ok. I'm still working on the application I started building a year ago but I wasn't keeping up to date with the changes being made over at http://jsonapi.org/ and it seems much more robust, but (sadly) much more chatty too. I do have the complex relationships that I can help make documentation for, but I've stayed on AMS 0.8, so it will take me some time to even assess how this changes my application and then how to apply it to the changes in the standard.

**Comment by joaomdmoura** [comment]
Cool, @zachaysan. You should give it a try to 0.10x just saying :stuck_out_tongue_closed_eyes: 
Btw, you might also check out [new docs](https://github.com/rails-api/active_model_serializers/tree/master/docs). I'm closing this one specifically in order to concentrate the discussion on #1074
