### ISSUE TITLE
Doesn't work with rails-api 4.1.5

### ISSUE THREAD

**Issue by Vakintoshka** [rails-api/active_model_serializers#637]
Hi, guys! Please, help.
So, I started with <pre>rails-api new test_app</pre>. It generates new project with Gemfile like
<pre>
source 'https://rubygems.org'
gem 'rails', '4.1.5'
gem 'rails-api'
gem 'spring', :group => :development
gem 'sqlite3'
</pre>
After that, I changed it to
<pre>
source 'https://rubygems.org'
gem 'rails', '4.1.5'
gem 'rails-api'
gem 'sqlite3'
gem 'active_model_serializers'
</pre> and used <pre>bundle update</pre>
After that, I used <pre>rails-api generate scaffold Post title:string body:string</pre>
It generated model/controller/serializer for me. After that, I added few rows in db and started server with <pre>rails s</pre>
and went to /posts url. <b> It returned an array of models without using serializer </b>. But if I simple clone your `active-model-serializers-example` repo, it works fine. So I don't know what I am doing wrong. Please help, and sorry for my engilsh. I think it some trouble with versions.
In me project I have
<pre>
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-linux]
Rails 4.1.5
active_model_serializers-0.9.0
also I use rbenv on ubuntu
</pre>

**Comment by gwagener** [comment]
Upgrading to AMS 0.8.3 fixed it under Rails 4.2.

**Comment by beauby** [comment]
Closing this one for now, feel free to reopen if needed.
