### ISSUE TITLE
undefined method attribute for serializer

### ISSUE THREAD

**Issue by kbullaughey** [rails-api/active_model_serializers#657]
I have a problem with AMS (0.9.0 stable) overshadowing my attributes. 

I have an attribute called `root` which gets overshadowed by `ActiveModel::Serializer#root`. According to the readme, I thought I could do the following:

```
attribute :original_root, key: :root

def original_root 
  object.root 
end
```

But it seems there is no method `attribute`. And with the plural version of this method, it's not obvious how one would specify a different name for just one attribute. 

Are the docs out of date? Or do I need to wait for 0.10.0 for this to work?

Any suggested workarounds? I'd rather not rename my property in the database. This was working fine before I upgraded from 0.8.0 to 0.9.0 (at least I think that's what broke it).

**Comment by jeremyhaile** [comment]
@joaomdmoura I like the new behavior, but as others have mentioned - the README still references the 'attribute' method.

**Comment by joshkinabrew** [comment]
I have a serializer that is using the old `attribute` method, but can someone let me know what the new syntax would be for this line? I too was bitten by the docs :frowning: 
```ruby
attribute :active_ingredients, key: "ActiveIngredient"
```

**Comment by partmendoza** [comment]
attributes :ActiveIngredient
def ActiveIngredient
  object. active_ingredients
end

**Comment by jfragoulis** [comment]
I cannot find any solid examples on how to replace the `attribute` method, for the life of me. Can anyone provide some or update the `README.md` ?

```ruby
class MySerializer < ActiveModel::Serializer
  # from
  attribute :id_path, key: :path
  
  # to
  def path
    object.id_path
  end
```

Is this the way ?

**Comment by joaomdmoura** [comment]
Hey ppl, sorry for take soo long to come back to this. We've being really busy with the new version 0.10.0. Btw I strongly recommend you to give it a try :smile: 
@jfragoulis yes, you are right.

FYI the `key` feature is back already on 0.10.0
