### ISSUE TITLE
has_many uses symbol keys for embedding at root and has_one used strings

### ISSUE THREAD

**Issue by kbullaughey** [rails-api/active_model_serializers#659]
I ran into a problem when I had a `has_one` association of the same type as another `has_many` association and I wanted to embed them all together in one array at the root. 

Unfortunately this didn't work because `has_many` uses symbol keys for embedding at root and `has_one` used strings.

Simply converting the key to a string fixes this. 

I'll link a pull request including the fix and a diagnostic spec. I also needed to fix a bunch of other specs that relied on symbol keys for `has_many`.

**Comment by NullVoxPopuli** [comment]
looks like this was resolved via #660
