### ISSUE TITLE
can't specify serializer for a collection

### ISSUE THREAD

**Issue by pushcx** [rails-api/active_model_serializers#70]
In a controller, if I:
    render json: Post.all, serializer: SpecialSerializer

it fails with the exception:
    undefined method `read_attribute_for_serialization' for #ActiveRecord::Relation:0x000000030bcf18

It's trying to use the SpecialSerializer on the list of Posts, not on each post. If I pass in `serializer: ArraySerializer`, it asks Post what its serializer is and uses the default PostSerializer instead of the SpecialSerializer I want to specify. I don't want to define Post#active_model_serializer because everywhere else I do want to use PostSerializer, not the SpecialSerializer.

I'm not sure how this should be fixed: letting ArraySerializer take an option specifying a serializer, or _render_option_json should know how to deal with enumerables, or if there's some better approach for my controller that I'm completely missing. Ideas?

**Comment by ajkochanowicz** [comment]
@josevalim I don't understand how this answers @ahawkins 's question.

It seems to me that we should be able to tell the render to just use a serializer "because I said so"?
