### ISSUE TITLE
Name collisions when attribute name ends with _url

### ISSUE THREAD

**Issue by RKushnir** [rails-api/active_model_serializers#704]
I'm on **0-8-stable** branch. When you have a structure like the following
```ruby
create_table :social_media_account
  string :profile_url

SocialMediaAccountSerializer
  attributes :profile_url

routes:
  resource :profile # <-- generates profile_url helper
```

AMS will choose route helper `profile_url` instead of the model attribute.
I don't have any good ideas how to solve this. Just in case someone has a similar problem, the workaround is `delegate :profile_url, to: :object` in serializer.

**Comment by jdenquin** [comment]
+1, work with delegate fix

**Comment by bf4** [comment]
@jdenquin it would make a nice PR to the 0-8-stable branch :)
