### ISSUE TITLE
No Matter What I do I only get a normal object hash

### ISSUE THREAD

**Issue by btate** [rails-api/active_model_serializers#706]
I have a versioned api that I'm trying to implement active model serializers in.  My models are not namespaced but my controllers and serializers are.  

Friendship Model
	
	class Friendship < ActiveRecord::Base
	  attr_accessible :friend_id, :user_id, :source_id
	  
	  scope :visible, -> { joins(:status).where("friend_status_descriptors.show = ?", true) }
	  
	  # Relationships
	  belongs_to :user, :touch => true
	  belongs_to :friend, :class_name => "User", :touch => true
	  belongs_to :source
	  
	  has_one :status, :class_name => "FriendStatusDescriptor", :foreign_key => 'friendship_id'
	  
	  validates_uniqueness_of :user_id, :scope => [:friend_id, :source_id]
     end

Friendship Serizalizer

	class Api::V1::FriendshipSerializer < ActiveModel::Serializer
	  attributes :id
	  
	  has_one :user
	  has_one :friend
	  has_one :status
	  
	end

When I render an array of friendships in my controller I get an array of hashes

     {
        "created_at" = "2014-10-28T16:44:57.000Z";
        "friend_id" = 4;
        id = 6;
        "source_id" = 2;
        "updated_at" = "2014-10-28T16:44:57.000Z";
        "user_id" = 1;
    } 

I've tried explicitly setting the serializer for an array of friendship objects and it doesn't work.
`render :json => friends, each_serializer: FriendshipSerializer`

I've updated to rails 4.1.6 but it's had no effect.  I'm on ruby 1.9.3

**Comment by fsainz** [comment]
I tried different things to solve this but with every attempt I ended up getting a serialization of the whole associated record/s (like if i just did .to_json) instead of going through their custom serializer.

I got this pattern working, it's ugly but it worked well with 0.10.0.pre, it might not be longer needed:

instead of a *has_many* :attachments, I would add this method:

```ruby
def attachments
  attachments = object.attachments.to_a
  return [] if attachments.empty?
  serializer = ActiveModel::Serializer::ArraySerializer.new(attachments, each_serializer:AttachmentSerializer)
  ActiveModel::Serializer::Adapter::JsonApi.new(serializer).as_json[:attachments]
end
```

for a *belongs_to* :category, I would do

```ruby
def category
  if object.category
    serializer = CategorySerializer.new(object.category)
    ActiveModel::Serializer::Adapter::JsonApi.new(serializer).as_json[:categories]
  end
end
```

**Comment by BrianTheCoder** [comment]
I am seeing the same behavior. Even when I manually specify the serializer, it's just returning #to_json

**Comment by CedricLor** [comment]
Hello, I ran into the same issue. It was solved after restarting my server... if it may help anyone.
