### ISSUE TITLE
Active Model Serializer and root key in json array

### ISSUE THREAD

**Issue by DmitryKK** [rails-api/active_model_serializers#716]
Hello! I have the following problem. My controller:

class Api::V1::ProfilesController < Api::V1::BaseController
  def me
    respond_with current_resource_owner
  end

  def index
    @users = User.where.not(id: current_resource_owner)
    respond_with @users
  end
end

My routes:

namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get 'me', on: :collection
      end
    end
  end

My serializer (user_serializer.rb):

class UserSerializer < ActiveModel::Serializer
  attributes :id, :name, :email, :location, :birthday, :created_at, :updated_at, :admin
end

If request is "get '/api/v1/profiles/me', format: :json" then it returns:

{"user":{"id":2900,"name":"name1","email":"user1001@test.com","location":"MyLocation","birthday":"2014-11-04","created_at":"2014-11-04T18:55:01.727...

root key is "user"

But If request is "get '/api/v1/profiles', format: :json" then it returns:

{"profiles":[{"id":6039,"name":"tag12","email":"user1012@test.com","location":"MyLocation","birthday":"2014-11-.....

root key is "profiles". Why "profiles" and not "users" ?????

**Comment by beauby** [comment]
Closing this for now, feel free to reopen if needed.
