### ISSUE TITLE
A decimal is converted into a string

### ISSUE THREAD

**Issue by Davidslv** [rails-api/active_model_serializers#721]
Hi again

I'm currently using master branch (although this is happening in 0.9.0) and in my model I have a decimal column, but that comes as string in the response, is that normal?
Thank you

```ruby
irb(main):003:0> Product
=> Product(id: integer, name: string, net_price: decimal, created_at: datetime, updated_at: datetime)
```

![screen shot 2014-11-06 at 20 22 02](https://cloud.githubusercontent.com/assets/136777/4943246/b9374ee6-65f2-11e4-960b-546cd1624234.png)

**Comment by kurko** [comment]
You're absolutely right, @mieko. Closing.

**Comment by spidergears** [comment]
Can we make it configurable? So that developer may opt out this behaviour if they need to.

All  id and other numeric attributes are converted to String, I know very specifically that non of my numeric attributes do not care about precision.

**Comment by bf4** [comment]
@spidergears you're commenting on an issue closed over two years ago. Please open a new issue.
