### ISSUE TITLE
Unexpected Array Root Handling

### ISSUE THREAD

**Issue by davidkovsky** [rails-api/active_model_serializers#724]
According to http://www.rubydoc.info/github/rails-api/active_model_serializers/frames#Arrays, I should be able to do:
```
  def index
    @speakers = Speaker.all
    render json: @speakers, root: true # please see note at the bottom of this issue
  end
```
And expect the following result:
```
{"speakers":
  [
    {"id":1,"name":"Bugs Bunny"},
    {"id":2,"name":"Wile E. Coyote"},
    {"id":3,"name":"Yosemite Sam"}
  ]
}
```
Instead, I get:
```
[
  {"speaker":{"id":1,"name":"Bugs Bunny"}},
  {"speaker":{"id":2,"name":"Wile E. Coyote"}},
  {"speaker":{"id":3,"name":"Yosemite Sam"}}
]
```
The following gives me what I need but is less elegant:
```
  def index
    @speakers = Speaker.all
    render json: "{\"speakers\": #{@speakers.to_json}}"
  end
```
Am I missing something? Is there a cleaner way to get the result I'm looking for?

This is on 0.9.0. I haven't disabled root as far as I can tell but if I don't set it to true in the render call in my first code block above then it acts as if I did disable it. That's less important to me right now.

Without ```root: true```, I get:
```
[
 {"id":1,"name":"Bug Bunny"},
 {"id":2,"name":"Wile E. Coyote"},
 {"id":3,"name":"Yosemite Sam"}
]
```

**Comment by kirillplatonov** [comment]
I has same problem after upgrading to rails 4.2.

@davidkovsky You can use temporary solution for this:

```ruby
def index
  @speakers = Speaker.all
  render json: ActiveModel::ArraySerializer.new(@speakers, root: :speakers)
end
```

I will try understand whats wrong and fix it.

**Comment by kurenn** [comment]
I think you can also use something like:

```ruby
  def index
    @speakers = Speaker.all
    render json: @speakers, each_serializer: SpeakerSerializer, root: "speakers" # please see note at the bottom of this issue
  end
```
