### ISSUE TITLE
Optional attributes

### ISSUE THREAD

**Issue by vasilakisfil** [rails-api/active_model_serializers#738]
If I pass an object to the serializer that has less attributes than defined inside the serializer I get 'missing attribute' error. Is there a quick way to remove this error (monkeypatch?) and instead make the serializer to not try to serialize this attribute? It would save me a lot of time and effort since my authorization takes place before the serializer (and slices the record attributes according to current user persmissions). To achieve the same result I will have to define more serializers for the same resource (which could be really ugly when you have many permission levels like in my case!)

I am using 0.9 version.

**Comment by NullVoxPopuli** [comment]
looks like this is resolved

**Comment by zeiv** [comment]
I don't think this is a satisfactory resolution.  If I have dozens of attributes I want to omit, I can't really define a new method like that for each one.

**Comment by NullVoxPopuli** [comment]
@zeiv what's your use case?

**Comment by zeiv** [comment]
In my API I would like to return only the attributes requested.  For example, given the following GET request, `/some_resources?only=["id","title","created_at"]` I would get a response with data like
```JSON
...
{
  "id": "1234",
  "type": "some_resource",
  "attributes": {
    "title": "Resource 1234",
    "created_at": "2016-02-10"
  }
}
...
```

versus the default request which would return the resources with all attributes, which could number upwards of 30 or 40.

**Comment by NullVoxPopuli** [comment]
if you're using JSON API, you can use the `fields` option.

**Comment by zeiv** [comment]
Huh, I think that's exactly what I'm looking for.  I don't think there is a link to the documentation for that feature on `docs/README.md`.  I'll submit a pull request.  Thanks!  👍

**Comment by NullVoxPopuli** [comment]
https://github.com/rails-api/active_model_serializers/blob/master/docs/general/rendering.md#fields :-)
