### ISSUE TITLE
Add serialization_scope to README

### ISSUE THREAD

**Issue by rafaelcgo** [rails-api/active_model_serializers#741]
Just a small suggestion that might help others...

I was struggling with `undefined method 'authenticate' for nil:NilClass` for my requests using the serializer (Rspec).

Turns out all I needed was to add `serialization_scope :view_context` but I only discovered it when watching the amazing Railcast about the gem: http://railscasts.com/episodes/409-active-model-serializers?view=asciicast

I think you guys should add `serialization_scope` documentation to the readme, to make things easier. And refer to the Railscast as well..

**Comment by bf4** [comment]
@rafaelcgo in case you're interested, I'm documenting this in https://github.com/rails-api/active_model_serializers/pull/1252

Thanks for the view_context idea

**Comment by rafaelcgo** [comment]
I'm glad I could help! :clap:
