### ISSUE TITLE
Wrong serializer with 0.9.1

### ISSUE THREAD

**Issue by pierrickrouxel** [rails-api/active_model_serializers#747]
0.9.1 breaks the serializer choice. 

In my project I have this two models:

* Employee
* Workshop::Employee

and the attached serializers:

* EmployeeSerializer
* Workshop::EmployeeSerializer

With the 0.9.0 version all work correctly but with update the Workshop::Employee serialization tries to use EmployeeSerializer.

**Comment by remear** [comment]
We're focusing on completing 0.10. We'd welcome a PR for this if anyone is interested.
