### ISSUE TITLE
0.9.1 incompatible with Draper 1.4.0?

### ISSUE THREAD

**Issue by bdmac** [rails-api/active_model_serializers#754]
After upgrading to 0.9.1 I got this when I tried to run our specs:

```
/.gem/ruby/2.1.3/gems/draper-1.4.0/lib/draper/railtie.rb:48:in `block (2 levels) in <class:Railtie>': uninitialized constant ActiveModel::ArraySerializerSupport (NameError)
```

**Comment by tricknotes** [comment]
It seems a draper's issue https://github.com/drapergem/draper/issues/644

**Comment by tricknotes** [comment]
Fixed by https://github.com/drapergem/draper/pull/596 .
draper 2.0 or later works fine with AMS.

**Comment by kurko** [comment]
Giving this a close :smile: Thanks
