### ISSUE TITLE
0.10 - ADAPTER_OPTION_KEYS is too limiting.

### ISSUE THREAD

**Issue by jejacks0n** [rails-api/active_model_serializers#760]
This should be moved into the Adapter layer, and should not happen at the controller level.

This is because of the unlimited nature of what options an adapter might want to take, and how `:include` could be expanded upon to also provide `:exclude` -- so in general, it seems like it might be better to pass all options to the adapter layer, and the adapter should be able to mutate the options that are then provided to the serializer.

This provides a much better structure for options to be handled by the adapter layer, while still making it into the serializer layer -- if applicable.

My thinking is that the adapter should be instantiated *before* the serializer (in the ActionController `_render_*` methods), which allows the options to be mutated by the adapter. Then the serializer should be instantiated with the potentially mutated options, and provided to the adapter via a standard API.

This would make it read more like (psuedo code):

```ruby
  def default_serializer_options
    {}
  end

  [:_render_option_json, :_render_with_renderer_json].each do |renderer_method|
    define_method renderer_method do |resource, options|
      @_serialization_options = default_serializer_options.merge(options) # restore 0.8 functionality

      if use_adapter? && (serializer = get_serializer(resource))
        adapter = ActiveModel::Serializer::Adapter.create(@_serialization_options)
        adapter.set_serializer(serializer.new(resource, @_serialization_options))
        super(adapter, options)
      else
        super(resource, options)
      end
    end
  end
```

**Comment by kurko** [comment]
I agree with you, @jejacks0n. I implemented some options that were needed by JsonApi adapter and it felt very dirty to have those options being managed by the serializer. I've seen adapters in other languages using this dependency direction and it was way cleaner. So if you could craft a PR, I'd definitely support it.

cc @steveklabnik could you chime in if this kind of refactoring is something you see as a benefit, or would you rather keep the current dependency direction?

**Comment by beauby** [comment]
I believe this is done in master. Closing for now, feel free to reopen if needed.
