### ISSUE TITLE
has_one with embed: :id still loads the associated model

### ISSUE THREAD

**Issue by YoranBrondsema** [rails-api/active_model_serializers#762]
I have the following scenaro:

```
class Child < ActiveRecord::Base
  belongs_to :parent
end

class Parent < ActiveRecord::Base
  has_one :child
end
```

In `ChildSerializer`, if I do
```
class ChildSerializer < ActiveModel::Serializer
  has_one :parent, embed: :id
end
```

then it does a query to fetch the `Parent` model from the database, even though only the `id` attribute is needed (which equals to the foreign key `parent_id` on the `Child` model). So this database query is kind of redundant.

I can fix it by doing
```
class ChildSerializer < ActiveModel::Serializer
  attribute :parent_id
end
```

which gives me the same JSON without the extra query. But I don't like it that much because by using `attribute` I lose the semantics of the association. Readability is important.

I don't know if it's doable to detect such cases where a query on the associated model is not needed, and prevent it. Maybe someone who's more familiar with the AMS code can give his opinion, then I don't mind doing a PR that solves it.

**Comment by YoranBrondsema** [comment]
@kurko I'm using 0.8.3. While I figure out how I can write a failing test, I created a sample app that demonstrates the behavior: https://github.com/YoranBrondsema/ams-test-case.

**Comment by toreriklinnerud** [comment]
I'm seeing the same thing on 0.8.3. Is this likely fixed on newer versions or should I try to submit a fix?

**Comment by joaomdmoura** [comment]
@toreriklinnerud I think it's fixed on master already, but we don't have a test covering that, maybe open a PR with this test would be a good start :smile:
