### ISSUE TITLE
Controller tests fail with 0.9.2 and Rails 4.2

### ISSUE THREAD

**Issue by brandonhilkert** [rails-api/active_model_serializers#766]
I just recently upgraded an app to Rails 4.2. All my controllers tests are failing with:

```ruby
  1) Error:
MarketingControllerTest#test_should_get_landing:
NoMethodError: undefined method `clear' for nil:NilClass
    test/controllers/marketing_controller_test.rb:5:in `block in <class:MarketingControllerTest>'
```

Here are the details:

https://gist.github.com/brandonhilkert/2f39218578b27e264efe

If i remove `active_model_serializers`, the tests pass.

The inclusion of `ActionController::TestCase.send(:include, ::ActionController::SerializationAssertions)` in the gem is causing this. If I comment it out, the tests again pass.

It appears when `super` is called from https://github.com/rails-api/active_model_serializers/blob/0-9-2/lib/action_controller/serialization_test_case.rb#L25, when it goes back to rails (https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L64), it fails out with the `clear` calls on those instance variables.

It's still not clear to me why the inclusion of this would causing those vars to be nil, but maybe it's more obvious to you.

The master branch passes, but I'm not sure if I should be relying on this given that it's not released yet.

**Comment by kapso** [comment]
+1 seeing the same, but `0.9.1` has an issue #746 so cant use that

**Comment by quekshuy** [comment]
+1 affects our controller tests as well.

**Comment by kurko** [comment]
Released https://rubygems.org/gems/active_model_serializers/versions/0.9.3. It's basically 0.9.1 (tons of bugfixes) minus the commit that caused tons of regressions. Please test and let us know how it goes :grin:
