### ISSUE TITLE
URL helpers no longer works within Serializer in Rails 4.2

### ISSUE THREAD

**Issue by jiexinhuang** [rails-api/active_model_serializers#770]
Hi, I am using AMS 0.9.2
After upgrade to Rails 4.2.0, I got errors inside my old serializers that call url helpers.

Anyone having the same issue?

Follow up:
I did add responders gem in my Gemfile.

Current workaround is to call Rails.application.routes.url_helpers inside serializer to get routes

**Comment by typeoneerror** [comment]
I am as well. Did you also add the responders gem? `respond_with` has been moved to that gem in 4.2. I think there's some kind of conflict there.

**Comment by igorgue** [comment]
I have the same issue, but I'm using AMS 0.8.1, also, I added the new responders gem as they instruct in the upgrading to Rails guide.

I don't use the url helpers nor I get an error but it looks like it completely ignores the serializers, so my associations no longer work nor the fields that I exclude in the serializers.

**Comment by franzejr** [comment]
I have the same issue. Rails 4.2.5.1. 

I'm using the workaround proposed by @jiexinhuang `url: Rails.application.routes.url_helpers...`.

**Comment by remear** [comment]
I want to quickly mention that I'm currently working on adding the url_helpers to 0.10. After that's complete, I'll see what I can do about 0.9.

**Comment by typeoneerror** [comment]
Believe it's related to https://github.com/rails-api/active_model_serializers/issues/704. Recommend changing your database field names that end with _url to _link ;)

**Comment by remear** [comment]
We're focusing on 0.10 right now. We'd welcome a PR for adding this to 0.9 if anyone is interested.
