### ISSUE TITLE
nested serializer behavior

### ISSUE THREAD

**Issue by ashanbrown** [rails-api/active_model_serializers#777]
I'd like to know if, at any point in this project, serializers classes were first located with the serializer class itself, and if I'm mistaken -- because I thought they had been -- whether this might be desirable behavior.  Here's an example:

```
class UserSerializer
  attributes :nested
  def nested; false; end
end
class UserInfoSerializer < ActiveModel::Serializer
  class UserSerializer < ActiveModel::Serializer
    attributes :nested
    def nested; true; end
  end

  has_one :user
end
```

You can currently say `has_one :user, UserSerializer` and you'll end up using the nested serializer, but otherwise you'll default to a serializer defined outside of the class.  But maybe the nested serializer definition should be used by default.  Thoughts?  Thanks.

**Comment by steveklabnik** [comment]
Nope. Rails autoloading loads files by name, so generally, they are one class, one file.

**Comment by dontfidget** [comment]
Nope = not desirable, or nope = never behaved like this, or both?  I'm gathering both.  The reason I find it desirable is that I've found myself serializing a whole hierarchy of objects, and the domain is really based on the parent object (say AdminSerializer vs generic UserSerializer).  I suppose I could create a namespaced version of each sub-serializer, but a whole bunch of 3 line files seems like overkill to me.

**Comment by steveklabnik** [comment]
Sorry, should have been more explanatory :)

"Nope, I doubt this behavior was ever considered, because that's not normally how things are done."

I'm not sure if we should or shouldn't support this, just providing the historical context.

**Comment by bf4** [comment]
ref: https://github.com/rails-api/active_model_serializers/issues/1442
