### ISSUE TITLE
attributes does not accept an Array of symbols

### ISSUE THREAD

**Issue by tilo** [rails-api/active_model_serializers#779]
It would be awesome if `attributes` could accept an Array of symbols, then one could do this:
````
  MyClassSerializer < ActiveModel::Serializer
    # this could be useful to define in a DRY way:   all attributes of the class minus these..
    # without having to maintain the list of standard attributes in multiple places
    attributes self.to_s.sub('Serializer','').constantize.attribute_names.map(&:to_sym) - [:user_id,:status]
  end
````

**Comment by tilo** [comment]
of course it would be even nicer if there was a convenient way to say:
"all the attributes of the associated class, except these: ..."

**Comment by Tyr0** [comment]
it's possible to use the splat (*) operator to convert your array of symbols to the appropriate argument format

```
  MyClassSerializer < ActiveModel::Serializer
    attributes *self.to_s.sub('Serializer','').constantize.attribute_names.map(&:to_sym) - [:user_id,:status]
  end
```

I've tested this using Rails 4.2 and it works as expected

**Comment by JoshSmith** [comment]
@tilo Is this PR related to your request? https://github.com/rails-api/active_model_serializers/pull/780

**Comment by JoshSmith** [comment]
@tilo ping.

**Comment by beauby** [comment]
Closing this as the following workaround seems acceptable:
```ruby
attributes *attribute_list

def attribute_list
  Post.attribute_names.map(&:to_sym) - [:user_id,:status]
end
```

**Comment by bf4** [comment]
@beauby Nice job pointing out the splat `*`.  Vital Ruby syntax!
