### ISSUE TITLE
problem with nested has_one that uses embed: :objects

### ISSUE THREAD

**Issue by kbullaughey** [rails-api/active_model_serializers#785]
I'm having a peculiar problem involving several layers of nested associations. 

I'm using the 0-9-stable branch, and something like what I include below used to work on that branch and somewhere along the way it broke.

When the spec below is run, I get a `NoMethodError` exception with the message `undefined method more_inner for nil:NilClass`

I would have expected that since `inner` returns `nil` there would be no reason to call the serializer `TestNilHasOneInnerSerializer`. But somehow, `more_inner` is called on `nil`.

Here's the full example:

    RSpec.describe "active model serializers problem involving nil association" do
      class TestNilHasOneOuter
        def inner
          nil
        end
      end
    
      class TestNilHasOneInner
        def more_inner
          nil
        end
      end
    
      class TestNilHasOneMoreInner < ActiveModel::Serializer
      end
    
      class TestNilHasOneInnerSerializer < ActiveModel::Serializer
        has_one :more_inner, embed: :objects,
          serializer: 'TestNilHasOneMoreInner', embed_in_root: false
      end
    
      class TestNilHasOneOuterSerializer < ActiveModel::Serializer
        has_one :inner, root: :inner_object, serializer: 'TestNilHasOneInnerSerializer'
      end
    
      it "can serialize when there is no inner object" do
        model = TestNilHasOneOuter.new
        serializer = TestNilHasOneOuterSerializer.new(model)
        expect(serializer.as_json).
          to eq({'test_nil_has_one_outer' => {'inner_id' => nil}, 'inner_objects' => []})
      end
    end

The second-to-last line in the backtrace occurs in this function inside `lib/active_model/serializer.rb`:

    def build_serializer(association)
      object = send(association.name)
      association.build_serializer(object, association_options_for_serializer(association))
    end

Here, object is nil, and normally this is fine, but for some reason in this circumstance the exception is raised.

**Comment by mhenrixon** [comment]
I am having a similar issue I have to use `object.object.username` to access what used to be `object.username`. 

```ruby
module PaymentIQ
  class PlayerSerializer < ApplicationSerializer
    attributes :user_id, :success, :first_name, :last_name, :street, :city,
               :zip, :country, :dob, :mobile, :balance, :balance_cy, :email

    def dob
      object.object.birthdate
    end

    def user_id
      object.object.username
    end

    def success
      true
    end

    def country
      object.object.country_alpha3
    end

    def balance
      (ExchangeMoney.new(object.object.money_balance_cents,  object.object.currency).into(balance_cy) / 100).to_f
    end

    def balance_cy
      object.object.country_code == 'SE' ? 'SEK' : 'EUR'
    end
  end
end
```
I didn't have to use `object.object` before 0.9.3.
