### ISSUE TITLE
It looks like v0.9.3 was accidentally pushed as 0.9.3 and isn't in 0-9-stable

### ISSUE THREAD

**Issue by bf4** [rails-api/active_model_serializers#786]
See https://github.com/rails-api/active_model_serializers/compare/v0.9.2...0.9.3

(i.e. it's `0.9.3` not `v0.9.3`).

and https://github.com/rails-api/active_model_serializers/compare/0-9-stable...0.9.3

cc @kurko

ref: https://rubygems.org/gems/active_model_serializers/versions/0.9.3

was also confused by the changelog...

**Comment by kurko** [comment]
Thanks for pointing that out. I forgot to push. Will do once I'm back to a
computer.

**Comment by bf4** [comment]
n/p. I have a patch in my code that blows up when changing versions from 0.9.2, noticed the release of 0.9.3, but couldn't find what had changes, and if I still needed my patch https://github.com/rails-api/active_model_serializers/issues/641#issuecomment-69685535  It appears the answer is that I can remove the patch, yay!

**Comment by kurko** [comment]
yay. Good to know.

Merged :)

**Comment by bf4** [comment]
`v0.9.3` tag is still missing, fyi

**Comment by steveklabnik** [comment]
How odd, I thought that Bundler handled that for me.

**Comment by kurko** [comment]
Seriously? I pushed it that same day. Will check when I get to a computer.

**Comment by bf4** [comment]
@kurko @steveklabnik however it happened, there is a `0.9.3` tag where there should be `v0.9.3` e.g. [v0.9.2...0.9.3](https://github.com/rails-api/active_model_serializers/compare/v0.9.2...0.9.3)

**Comment by kurko** [comment]
Fixed :grin:

**Comment by bf4** [comment]
W00t
