### ISSUE TITLE
scope and serialization_scope

### ISSUE THREAD

**Issue by mateomurphy** [rails-api/active_model_serializers#796]
While giving master a try, I've noticed these methods no longer exist; are they being permanently removed or will awaiting reimplementation? My use case is needing to access helpers from within serializers; there doesn't seem to be any way to do this anymore...

**Comment by kurko** [comment]
@mateomurphy waiting reimplementation. Would you be interested in helping us with a PR?

**Comment by mateomurphy** [comment]
certainly, I've already got some code working, will tidy it up an make a PR soon
