### ISSUE TITLE
Fragment Cache

### ISSUE THREAD

**Issue by joaomdmoura** [rails-api/active_model_serializers#802]
Considering my PR #693 
Cache Composition (http://robots.thoughtbot.com/fast-json-apis-in-rails-with-key-based-caches-and) is one of the work-arounds for the absence of fragmente cache on AMS.

As we know, a fragment cache implementation would be extremely efficient to improve API's that have some dynamic attributes that may vary on every request.

Assuming that PR #693 will be merged soon, this should be a new feature to the cache implementation, my proposal is to follow Rails conventions, adding two new options to ```cache``` method: ```only``` and ```except```.

Example:
```ruby
class PostSerializer < ActiveModel::Serializer
  cache key: 'post', expires_in: 3.hours, only: [:title]
  attributes :title, :body

  has_many :comments

  url :post
end
```

In the example, only the ```title``` attribute would be cached, everything else would be retrieved from the ```Post``` object. ```Except``` would work exactly the opposite.

Despite of being a simple new feature it isn't quite easy and small. So I'm not moving forward with this on PR #693 

I'll try to work on this asap, but would like to hear some thoughts about it.
cc/ @kurko @steveklabnik @nwjsmith

**Comment by guilleiguaran** [comment]
I just want to say that if this is done active_model_serializers will be shipped by default in new Rails 5.0 apps.

**Comment by joaomdmoura** [comment]
@guilleiguaran haha :+1: it will be done!

**Comment by kurko** [comment]
Go go go, @joaomdmoura :grin:

**Comment by antonioparisi** [comment]
:+1:

**Comment by joaomdmoura** [comment]
I'm not sure if I should also enable users to cache relationships (all their attributes). @kurko any thoughts?

**Comment by joaomdmoura** [comment]
@kurko, never mind haha I ended up doing it.
So now you can also specify ```only``` or ```except``` with associations names, it will fragment cache it.

ex. 
```ruby
LikeSerializer = Class.new(ActiveModel::Serializer) do
  cache only: [:post]
  attributes :id, :time

  belongs_to :post
end
``` 

The ```post``` part of the response will be cached, but it won't cache the ```post``` **object**. So, your ```PostSerializer``` will not use this cache because it may not contain exactly what you want.

Will squash, document it and open the PR probably tomorrow.

**Comment by antonioparisi** [comment]
Excellent work!

On Wednesday, 11 February 2015, João Moura <notifications@github.com> wrote:

> @kurko <https://github.com/kurko>, never mind haha I ended up doing it.
> So now you can also specify only or except with associations names, it
> will fragment cache it.
>
> ex.
>
> LikeSerializer = Class.new(ActiveModel::Serializer) do
>   cache only: [:post]
>   attributes :id, :time
>
>   belongs_to :postend
>
> The post part of the response will be cached, but it won't cache the post
> *object*. So, your PostSerializer will not use this cache because it may
> not contain exactly what you want.
>
> Will squash, document it and open the PR probably tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails-api/active_model_serializers/issues/802#issuecomment-73823665>
> .
>


-- 
Sent from Gmail Mobile

**Comment by kurko** [comment]
Promising!

**Comment by gaurish** [comment]
Hey, how are things going with this? do you need any help?

**Comment by joaomdmoura** [comment]
@gaurish just finishing actually :smile: Yesterday I've made the final adjustments that @kurko pointed out. I'll update the PR this weekend.

**Comment by JoshSmith** [comment]
Hey @joaomdmoura this is awesome to hear. Looking forward to seeing the updates!

**Comment by kenips** [comment]
thanks so much for your work @joaomdmoura :beers:

**Comment by joaomdmoura** [comment]
it was already merged. I'm closing it <3
