### ISSUE TITLE
undefined method `config' for ActiveModel::Serializer:Class

### ISSUE THREAD

**Issue by chadwtaylor** [rails-api/active_model_serializers#803]
Using 0.8.3, added this to an initializer per the docs:

`ActiveModel::Serializer.config.adapter = :json_api`

This resulted in `undefined method 'config' for ActiveModel::Serializer:Class`.

Please advise?

**Comment by bradleypriest** [comment]
Hi Chad,
If you're using version 0.8.3 of the gem, you need to check out the [0.8 docs](https://github.com/rails-api/active_model_serializers/tree/0-8-stable)

If you want to be using the `:json_api` format, you have to use the 0.10.0 branch off of Github as it was only just added to the library.

**Comment by chadwtaylor** [comment]
Thank you @bradleypriest for the quick response! Much appreciated and I'm going to close this issue.
