### ISSUE TITLE
Usage outside of Rails

### ISSUE THREAD

**Issue by sschepens** [rails-api/active_model_serializers#808]
This is a great gem, is it usable outside of rails? with sinatra or padrino maybe, using Sequel::Models? Through Tilt?

**Comment by steveklabnik** [comment]
Only if you're willing to drag rails in as a dependency :wink:

**Comment by sschepens** [comment]
Is there no way of making it rails-independent? :yum:

**Comment by manfrin** [comment]
You could give this a try for a non-rails dependent serializer: 
https://github.com/RestPack/restpack_serializer

**Comment by steveklabnik** [comment]
It would require lots of work, as we currently tie into many of Rails' features. I don't have an objection, but it would require someone to actually write the code.

The core of the gem doesn't inherently need Rails, though ActiveModel is still pretty much assumed.

**Comment by SauloSilva** [comment]
I did a [adapter](https://rubygems.org/gems/sinatra-active-model-serializers) to able to use with Sinatra.

**Comment by endash** [comment]
The situation here used to be somewhat better, with heavy Rails-specific code being conditionally loaded (ActiveSupport is a different story). However, both 0.10.0.rc2 and master increasingly assume Rails is present entirely: rc2 merely requires manually requiring `active_support/base_ext` and stubbing `Rails::Railtie.initializer`. Master removes a begin/rescue around the ActionController setup, as well as explicitly adding several more Rails components to the dependencies, significantly enlarging the footprint.

Of course, the project is well within its rights to exclude the non-rails use cases. I don't think it's necessary, personally, and it'd be nice for there to be one gold-standard Ruby serialization library, but I'd understand that decision, on the balance. My hunch is that depending more explicitly on Rails was in fact a conscious decision.

If it were not, I don't think it would take much to tweak master to work without Rails—at present. I'd be willing to submit a PR to restore the sanity checking. My only concern there is a mushy middle ground—no explicit intent to exclude non-Rails use-cases, but with the likelihood that any given commit might introduce new, unguarded Rails-specific code. Then it just becomes a game of whack-a-mole, and that energy could be better spent elsewhere.

**Comment by joaomdmoura** [comment]
@endash this is indeed a conscious decision.
Now that we are becoming part of Rails 5 we are starting to become more dependent of it naturally, also because we want to provide a set of new feature related to the integration itself.

This doesn't means we don't plan to support non-Rails users, we will, but right now we are focused on get it done in order to keep out rollout plans, but once we finish the task we need we will probably spare sometime to go over it adding the necessary fallbacks and treatments in order to support non-Rails users.

I cant guarantee that it will be on the 0.10.x release, but we definitely have it on our radar and still want to support the most ruby developers as possible.

**Comment by bf4** [comment]
Yes, it is usable outside of Rails. See `ActiveModel::SerializableResource` [docs](https://github.com/rails-api/active_model_serializers#using-a-serializer-without-render) and [`ActiveModelSerializers::Model`](https://github.com/rails-api/active_model_serializers/blob/8aaaa44ba3d5b328fbbf92d59b9f3ecf1b802c8f/lib/active_model_serializers/model.rb)

However, it does have some [rails-related runtime dependencies](https://github.com/rails-api/active_model_serializers/blob/8aaaa44ba3d5b328fbbf92d59b9f3ecf1b802c8f/active_model_serializers.gemspec#L24-L33)

**Comment by bf4** [comment]
Please re-open if I am closing this in error.
