### ISSUE TITLE
0.9.x: recursive has_many fails with: stack level too deep

### ISSUE THREAD

**Issue by Awem** [rails-api/active_model_serializers#809]
In 0.8.3 these serializers worked fine:

    class ASerializer < ActiveModel::Serializer
      attributes :id
      has_many :bs
    end

    class BSerializer < ActiveModel::Serializer
      attributes :id
      has_many :as
    end

In 0.9.x they fail on rendering with:

    SystemStackError - stack level too deep:
      actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:79:in `'

Removing ONE of the has_many declarations makes rendering possible again without issue.

*Update: Initially, I thought it wasn't failing in 0.9.0. Then I noticed that 0.9.0 just did not use the serializers at all because of #641*

**Comment by AW-UC** [comment]
Maybe related to #723? However, that one is closed without fixing commit.

**Comment by krukgit** [comment]
I don't think this is a bug, although I admit it would be really neat if that setup worked. 

I don't think there currently is an easy way to implement this behaviour without some serious code duplication, especially if the dependance is a level or two deeper.

**Comment by AW-UC** [comment]
I don't understand, why this shouldn't be a bug? It worked in 0.8.3 so it is already implemented. Seems to be a regression or buggy refactor in ``0.9.0`.
https://github.com/rails-api/active_model_serializers/blob/master/README.md says, that "`0.10.x` will be based on the `0.8.0`", so this issue might be fixed anyway in the next version. But I think it is good to keep this issue open, so that developers are aware of it.

**Comment by brancusi** [comment]
Bump, same issue here. Thanks.

**Comment by joaomdmoura** [comment]
Tks @AW-UC .
Indeed we had the same problem when developing ```0.10.0```, but we fixed it.
I'm more into the ```0.10.0``` development, so I'm not sure about ```0.9.x```, but I can see where it would fail to replicate this error.
```0.10.0``` wasn't release yet but we are already conducting some production tests with it.

**Comment by AW-UC** [comment]
@joaomdmoura Great to hear it is fixed. Is there a test for this case? Would be so easily testable...

**Comment by joaomdmoura** [comment]
@AW-UC I think there isn't an specific test, but it's covered by other tests for sure.

**Comment by NullVoxPopuli** [comment]
it's recommended to use JSON-API in 0.10 to avoid recursive infinite loops.
