### ISSUE TITLE
serializer association doesn't support lambda

### ISSUE THREAD

**Issue by itsSaad** [rails-api/active_model_serializers#816]
Raises an error:
    /app/serializers/student_serializer.rb:9 (lambda)> is not a symbol):
      app/serializers/student_serializer.rb:9:in `<class:StudentSerializer>'
      app/serializers/student_serializer.rb:1:in `<top (required)>'
      app/controllers/api/v1/users_controller.rb:5:in `index'

`line 9` has this: 
      has_many :unapproved_applications, -> {where(:accepted => false)},foreign_key: :student_id, class_name: 'Application'

Any alternative or way around ?

**Comment by sandelius** [comment]
```ruby
has_many :unapproved_applications

def unapproved_applications
  object.applications.where(accepted: false)
end
```

**Comment by itsSaad** [comment]
thanks. thats what i figured out at the end.
