### ISSUE TITLE
Generator not found anymore

### ISSUE THREAD

**Issue by AlexCppns** [rails-api/active_model_serializers#818]
```
$ rails g serializer channel
Could not find generator serializer.
```
Was there any recent change in the gem?

**Comment by steveklabnik** [comment]
What version are you using?

**Comment by AlexCppns** [comment]
version 0.9.3

**Comment by mehlah** [comment]
I created a new app to verify the issue: https://github.com/mehlah/ams-issue-818
All green and working as expected, with 0.9.3 and Rails 4.2.1

@AlexCppns Do you still experience this issue?

**Comment by AlexCppns** [comment]
@mehlah no the issue disappeared...

**Comment by davidbiehl** [comment]
It looks like this can be closed since the issue couldn't be repeated and the problem disappeared.

**Comment by bf4** [comment]
Please reopen if this is still an issue.
