### ISSUE TITLE
belongs_to for non-existent model

### ISSUE THREAD

**Issue by 7h3kk1d** [rails-api/active_model_serializers#820]
This might be outside the scope of AMS but I'm using the JSON-API format and have a model which has a related field which I would like to show up in the links section but there is no associated model(since it lives in a different service). Is there a straight forward way to represent this in the serializer.

i.e.

```ruby
class FavoriteSerializer < ActiveModel::Serializer
  attributes :id
  belongs_to :account #account model does not exist
end
```

Favorite model has a column named 'account_id'. I'm just trying to avoid creating a account table so I don't have to keep them in sync between services.

**Comment by kurko** [comment]
You can do the following, according to https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L73-L78 :

```ruby
class FavoriteSerializer < ActiveModel::Serializer
  attributes :id
  belongs_to :account

  def account
    :some_value
  end
end
```
