### ISSUE TITLE
ActiveModel::Serializer does not handle SimpleDelegator instances properly

### ISSUE THREAD

**Issue by twoism** [rails-api/active_model_serializers#824]
I am encountering errors when passing a `SimpleDelegator` instance to a `Serializer`. It seems that the serializer only respects the instance held by  `__getobj__` and does not forward any methods that are handled in the delegate. This is a bit dense so I put together an example.

```ruby
require 'delegate'

class A
  include ActiveModel::Model
  include ActiveModel::Serialization

  attr_accessor :name
end

class B
  include ActiveModel::Model
  include ActiveModel::Serialization

  attr_accessor :desc
end

class ABDelegate < SimpleDelegator
  attr_reader :b

  def initialize a, b
    @b = b
    super a
  end

  def desc
    b.desc
  end
end

class ABSerializer < ActiveModel::Serializer
  attributes :name, :desc
end
 
a = A.new(name: 'Name for A')
b = B.new(desc: 'Desc for B')
delegate = ABDelegate.new(a,b)
serializer = ABSerializer.new(delegate)

puts delegate.name == "Name for A"
=> true
puts delegate.desc == "Desc for B"
=> true
puts serializer.to_json
NoMethodError: undefined method `desc' for #<A:0x007ff5439614d8 @name="Name for A">
(eval):4:in `_fast_attributes'
```
My expectation would be that the serializer would use the `ABDelegate` instance but from the error that does not seem to be the case.

**Comment by rounders** [comment]
@twoism - were you able to find a solution this? I just encountered the same issue.

**Comment by rounders** [comment]
@twoism nm, I was able to solve it in my case by adding 'include ActiveModel::SerializerSupport' to my class.

**Comment by Nitrodist** [comment]
Any solution to this?

**Comment by Matt888** [comment]
Running into this problem too.  Tried overriding attributes hash, as_json and to_json but it doesn't serialize using any of these values.

**Comment by twoism** [comment]
I didn't see this getting any traction for a while so I closed it. My solution was a bit heavy handed but it works for me. I wrote a serializer minus all the eval magic that I believe is causing the issue. You're welcome to use it as well.

https://gist.github.com/twoism/8ef0f7a3b1ebf6a8e76c

**Comment by joaomdmoura** [comment]
Hi @twoism what is the version of AMS that you used? :)

**Comment by twoism** [comment]
I open the issue in February. I remember trying a couple versions and then giving up. Seeing as others are experiencing this still, I would imagine that this is still an issue.

**Comment by xionon** [comment]
@joaomdmoura This bit me at work today, too. It fails for me on both master 0.10.0rc1 and the Rubygems latest version, 0.9.3

I created [a blank Rails app with a reproduction and a test](https://github.com/xionon/active-model-serializer-with-delegators) for you.

**Comment by joaomdmoura** [comment]
@xionon thank you so much! It'll definitely help! I'm having a hard time pushing every PR forward but I'll try to give it some attention asap :smile:

**Comment by danielgrippi** [comment]
Per the [PORO documentation](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/serialize_poro.md), we added `alias :read_attribute_for_serialization :send` to our SimpleDelegator and it fixed the issue for us.

**Comment by danielgrippi** [comment]
per @rounders's comment, including 'ActiveModel::SerializerSupport' to a delegator fixes this.

**Comment by craigweston** [comment]
`ActiveModel::SerializerSupport` seems to be no longer available. Is there a more up to date solution for this?

**Comment by bf4** [comment]
@craigweston Please open a new issue. I don't know what you're trying to do or what version or on or what you've tried.  From your comment 'seems to be no longer available' it's unclear what docs you've looked at.
