### ISSUE TITLE
Specify association serializer with conditional?

### ISSUE THREAD

**Issue by eliduke** [rails-api/active_model_serializers#825]
Hello AMSers!

I need some help and I hope I have come to the right place.

I am using AMS 0.8.3 and I am trying to use a conditional in a serializer to specify which serializer to use for a certain association. The standard json end point has a list of users with basic information. Then I want to have an "export" end point where more detailed user information would be output into a CSV or something like that.

Here's what I have so far...

```
class PrizeController < ApplicationController

def entrants
  render json: @prize, export: true, serializer: PrizeEntrantsSerializer
end
```

I'm passing in the `export: true` option thinking that I can use that in the conditional.

```
class PrizeEntrantsSerializer < ActiveModel::Serializer

  attributes :id, :event, :event_prize_type,
  has_many :entrants, serializer: which_serializer

  def which_serializer
    @options[:export] == true ? PrizeEntrantExportSerializer : PrizeEntrantSerializer
  end

end
```

That didn't work. I get `undefined local variable or method 'which_serializer'`, so I tried this:

```
class PrizeEntrantsSerializer < ActiveModel::Serializer

  attributes :id, :event, :event_prize_type

  if @options[:export] == true
    has_many :entrants, serializer: PrizeEntrantExportSerializer
  else
    has_many :entrants, serializer: PrizeEntrantSerializer
  end

end
```

That doesn't work either. I get `undefined method '[]' for Nil Class`. I am able to pass in the `@options` successfully because I tested it out by adding as an attribute and it does return correctly. Is it just not possible to have conditionals in a serializer?

Thanks for your help!

**Comment by mehlah** [comment]
Hello guys,

I created a Rails app that reproduces what's described by @eliduke https://github.com/mehlah/ams-issue-825/

I'm suggesting a fix at #865, to support Symbols for `:serializer` option, that refers to a method to call.
I'm making myself familiar with AMS code and architecture, so I'm not sure this is the right direction. If so, I think we should support passing a Proc too.
@JoshSmith thoughts?
Is this something to port to 0.10.x/master?

**Comment by kurko** [comment]
@eliduke `has_many` is a class method whereas `which_serializer` is an instance method. Try `def self. which_serializer` instead. Should work.

**Comment by beauby** [comment]
@eliduke Did @kurko's suggestion help?

**Comment by eliduke** [comment]
@beauby Thanks for pinging me again on this. In the end I switched things up and found a different solution, but now that this is back in my brain I will take a look and see if @kurko's suggestion works.

**Comment by eliduke** [comment]
I came across another instance where I could use a conditional serializer, and so I was very excited to give this a shot again. Unfortunately, it didn't work. Keep in mind, that I am using AMS 0.8.3.

```
module Adm
  class PostSerializer < ActiveModel::Serializer
    attributes :id, :title, :body
    has_many :authors, serializer: authors_serializer

    def authors
      object.authors
    end

    def self.authors_serializer
      if object.authors.first.class.class_name == "EventSpeaker"
        Adm::EventSpeakerSerializer
      else
        Adm::PostContributorSerializer
      end
    end
  end
end
```

And that gives me this error:
```
undefined local variable or method `authors_serializer' for Adm::PostSerializer:Class
```

That `authors` method just checks a couple things and conditionally returns Event Speakers or Post Contributors.

**Comment by NullVoxPopuli** [comment]
@eliduke just curious, what's keeping you on 0.8.3? 0.10 has some really nice syntax that would help clean this up (cause @beauby is awesome)

**Comment by eliduke** [comment]
@NullVoxPopuli I have been waiting for it to be an official release. As far as I know, it's still just a release candidate. Has 0.10 been officially released yet?

**Comment by NullVoxPopuli** [comment]
it has not been released yet, but AMS is on the *3rd* release candidate. so, you could use the tag `v0.10.0.rc3` in your gemfile, or the branch `master`. 

It's not 100% guaranteed, but master is raaaaaarrreeelllyy ever has any failing tests (and it's usually because of an oversight when merging something else)

**Comment by eliduke** [comment]
Okay. So, let's say that I can convince my team that we should upgrade, how would 0.10 make what I want to accomplish here easier? You say that there's some nice syntax that would help clean up what I want to do.

**Comment by beauby** [comment]
@eliduke In 0.10 the serializer lookup is made in such a way that if your `author` is an instance of `EventSpeaker` and you have defined an `EventSpeakerSerializer`, then that's what will be used.

**Comment by NullVoxPopuli** [comment]
:+1:

**Comment by eliduke** [comment]
Curious... So, when `authors` is a collection of `EventSpeakers` it will use the `EventSpeakerSerializer` and when `authors` is collection of `PostContributors` it will use the `PostContributorSerializer`?

**Comment by beauby** [comment]
Yes, exactly.

**Comment by eliduke** [comment]
Ok. That's awesome. That would work perfectly in that instance. Is there a way to specify the serializer you want to use in some conditional?

**Comment by beauby** [comment]
Not per se, but you can define nested serializers, which might help. Could you elaborate on what you're trying to achieve?

**Comment by eliduke** [comment]
There are times where, if we could, we would pass in some `options` in the `render json:` that would tell the root level serializer to conditionally use 2 different serializer. Like in the example I give at the very top of this issue.

**Comment by beauby** [comment]
Currently the only way to do that is to pick your serializer in your controller.

**Comment by eliduke** [comment]
But this is a 2nd level serializer, not the root serializer. How can I pick a secondary serializer (for a has_many association) from the controller? Is this just not a feature that people want or is it prohibitively difficult to implement? I have run into this type of situation many times over the last 6 months on this project.

**Comment by webattitude** [comment]
+1

**Comment by doei** [comment]
would love that feature too..

**Comment by bf4** [comment]
@doei If your issue is not on the 0.8 series, please create a new PR. In any case, all help appreciated.  We're all just people with day jobs, right? :)

**Comment by fzngagan** [comment]
Guys, I need to implement this in my project. What's the easiest way to implement this?

**Comment by bf4** [comment]
@fzngagan allow me to respond with the same level of detail

I tried to reproduce your problem, but `if:` works fine for me.
