### ISSUE TITLE
Skip association key if object doesn't have any associated records

### ISSUE THREAD

**Issue by nitinstp23** [rails-api/active_model_serializers#826]
Is there a way i can skip association key if object doesn't have any associated records.

For Example - 

```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :name, :email, :auth_token

  has_many :addresses
end

class AddressSerializer < ActiveModel::Serializer
  attributes :street, :city, :country

  belongs_to :user
end
```

Now when i do - 
```ruby
render json: user
```

It generate this JSON - 
```
{ 
  "user" =>
     {
        "name" => "Nitin Misra",
        "email" => "nitin@example.com",
        "auth_token" => "1700772e_4946_49e7_8039_75804c34bda1",
        "addresses" => []
     }
}
```

But i want to skip `addresses => []` key if user doesn't have any associated addresses.

Is it possible, or do we need to implement this.

**Comment by nitinstp23** [comment]
For now i have done it like this - 

```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :name, :email, :auth_token

  has_many :addresses

  # Skip association key if its value is blank ([])
  def associations
    hash = super

    hash.select { |k, v| v.present? }
  end
end
```

**Comment by joaomdmoura** [comment]
I'm not sure but I haven't seen any support to this at AMS.
It seems a valid idea, but could you explain the benefits of removing associations key from the hash? Why have you chosen this approach?

**Comment by nitinstp23** [comment]
I'm just thinking loud here, other gems like `jbuilder` have that kind of flexibility, then why not AMS?

Ideas @joaomdmoura ...

**Comment by JoshSmith** [comment]
I'm not sure I understand the use case. I think that's what @joaomdmoura is fishing for. Could you give me an example?

I feel like it's useful to know that the user doesn't have addresses by having the empty array. This seems indicative of the fact that they could have them, but do not. Lacking the key altogether would indicate to me that `addresses` are not even a concept for the user.

**Comment by nitinstp23** [comment]
Agreed @JoshSmith  :+1: 

And I can't think of a valid example for this for now. ;)
Closing...

**Comment by JoshSmith** [comment]
Hah, alrighty!

Please keep opening issues like this though @nitinstp23! The more thoughtful people we have here the better :facepunch:

**Comment by joaomdmoura** [comment]
:+1:  @nitinstp23 keep up the good work!
