### ISSUE TITLE
JSONAPI: support RC3 features

### ISSUE THREAD

**Issue by kurko** [rails-api/active_model_serializers#829]
- [ ] new structure with `data`
    - [ ] include `type` in every resource
- [ ] rename `linked` to `included`

**Comment by joaomdmoura** [comment]
:+1: @kurko let me know if you need any help with this :smile:

**Comment by steveklabnik** [comment]
We just labeled an RC3, and are gonna stop changing so that you all can implement stuff :heart: 


https://github.com/json-api/json-api/issues/484

**Comment by zekefast** [comment]
Guys, do you need any help with that? Please, let me know! I want to faciliate development of 0.10.x and json-api standard support.

**Comment by kurko** [comment]
I won't have time to work on this until mid april. @zekefast do you have some time to craft a PR? I have time to review 😄

**Comment by zekefast** [comment]
@kurko, Yes, I do.

So, we need look into the difference of current implementation and RC3 and fill it right?
Do you have any info about currently implemented version of JSON-API standard?

**Comment by mateomurphy** [comment]
I'm currently implementing these changes for my own use, I can also submit a PR when I'm done

**Comment by kurko** [comment]
@zekefast current master is supporting RC1. We have to move into using `data` as root key. @mateomurphy can you coordinate with @zekefast :D

**Comment by mateomurphy** [comment]
@zekefast do you have anything done already, or when were you planning on working on this? I've started already as our app needs to support RC3.

**Comment by jasonkriss** [comment]
I haven't started any work on this yet, but it's something that I'd love to land asap. I'd be happy to help. @mateomurphy is there a way we could see what you've done so far?

**Comment by mateomurphy** [comment]
I can put together a PR tomorrow

**Comment by jasonkriss** [comment]
That'd be great. Thanks @mateomurphy!

**Comment by zekefast** [comment]
@mateomurphy, I haven't done anything yet. I can look into your PR today and we can then coordinate work further. Please, let me know what's lack in your PR and what part of spec is missing in it.

Thanks!

**Comment by mateomurphy** [comment]
Mostly done: https://github.com/rails-api/active_model_serializers/pull/853 the main thing remaining are the URLs in links

**Comment by kurko** [comment]
yay closing

**Comment by zekefast** [comment]
@mateomurphy, @kurko thank you guys!
