### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by ZackMattor** [rails-api/active_model_serializers#831]
https://github.com/rails-api/active_model_serializers/tree/0-9-stable#render-independently

This really should be in the master Readme... it took me way to long to find it :) Such a simple solution too. I'm using it to generate data releases for offline clients in a background task.

**Comment by migeorge** [comment]
+1

**Comment by JoshSmith** [comment]
@Criten we're not quite sure how to handle documenting `master` which is `0.10.x` and significantly different from `0.9.x`.

Do you have plans to migrate forward when `0.10.x` is released? How about you @migeorge?

**Comment by Criten** [comment]
Hey @JoshSmith, does `0.10.x` provide a way to serialize with without going through ActiveController's render paths? If so I believe it requires a mention in the documentation.

The documentation on `master` should reflect `0.10.x`, maybe provide a link to the `0.9.x` documentation? Just my opinion :)

**Comment by JoshSmith** [comment]
@Criten want to open a PR that provides such a link to `0.9.x` from `README.md`?

**Comment by JoshSmith** [comment]
I'm not familiar enough with `0.10.x` to provide a satisfactory answer to your broader question.

**Comment by bf4** [comment]
independent rendering has been added to the 0.10 series/master
