### ISSUE TITLE
0.8 :only and :except options don't support filtering by keys

### ISSUE THREAD

**Issue by gwagener** [rails-api/active_model_serializers#838]
When setting attributes with `attribute` you can specify a `key` value that will be used in the serialized JSON. However, if you pass options values for `:only` or `:except` they only work on attribute names, not keys.

Filtering by keys would be useful in order to allow API consumers to specify the data they're interested in because they only know about the key. There is a workaround of including the key in `attributes` and creating a custom method with the key for the name.

As this is a feature request for 0.8 I'm not sure if it's likely to be considered at all.

**Comment by JoshSmith** [comment]
@gwagener do you intend to upgrade to `0.10.x` when it's ready? If so, I'd opt for that, and IMO work on `0.8.x` should really die off.

**Comment by gwagener** [comment]
I always like to stay up-to-date with my gems, so yes. I haven't checked whether this works in 0.10 or not or if things are different enough with the fieldsets that it's irrelevant. If it's relevant and missing from 0.10 it would be a nice feature for that.
