### ISSUE TITLE
embed: :ids requires fully loaded objects and their associations

### ISSUE THREAD

**Issue by mrbrdo** [rails-api/active_model_serializers#846]
I would expect `embed: :ids` to only get the ids of the objects, however it seems that it constructs Serializers for each of these objects and requires them to be fully loaded. Moreover, it seems to even touch the associations of these associated objects. This is terrible from a performance standpoint since it recursively does queries for all the associations.

Why is this the case and can this be improved? v0.9

**Comment by JoshSmith** [comment]
Not to discourage users of `0.9.x` too terribly much, but since that branch is kind of a dead end, I would not expect a lot of performance work done there. We're generally rallying efforts around `0.10.x` and beyond, which means you'll find the majority of work headed in that direction.

**Comment by mrbrdo** [comment]
It's not a performance tweak that much, I am working on https://github.com/kundi/active_loaders and because of this issue I cannot do preloading for embeds: :id assocs. Forgive me as well but `0.10.x` has been started quite a while ago so I am looking for a more short-term solution. I also took a look at current master before and it doesn't seem it even has embeds id implemented.

**Comment by kurko** [comment]
Not sure JSONAPI is your thing, but master implements `embeds: :ids` in that adapter: https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter/json_api.rb#L153

It can definitely be improved on 0.9, though. If you definitely need it, is there any chance you could craft a PR?

**Comment by mrbrdo** [comment]
Ok, I got confused by https://github.com/rails-api/active_model_serializers/blob/master/test/serializers/associations_test.rb#L47 - I thought you were planning to implement it but it's not yet. Perhaps an outdated test?

I will see if I have spare time for a PR. For now we just manually output the IDs instead of using embeds. Would you also please keep this in mind for future versions? I don't have time right now to go too deep into the linked code, but does the current version require the associated objects to respond to any other fields besides id (or whatever the primary key is) in case when `embeds: :ids` is being used? Honestly I can't even find `embeds` anywhere in the codebase (even `embed` I can only see in two test files but nowhere in the implementation).

**Comment by kurko** [comment]
> I thought you were planning to implement it but it's not yet.

@mrbrdo hmmm it's implemented in master. I think that if you're on 0.9 and need a short term solution, you should stick to 0.9. Trying master will likely consume you some time. If you PR against 0.9, I can review it pretty quick and try to merge it asap.

yes, only `ids` are used by convention. I think that if people want other non-conventional primary keys, they can PR then.
