### ISSUE TITLE
@options variable exists

### ISSUE THREAD

**Issue by ccaratori** [rails-api/active_model_serializers#855]
In the active_model_serializers 0.9.3 the `@options` variable is not initialized anymore. This prevents users from passing custom options to the serializer. 
Was this on purpose? If it was, is there any other way to pass custom options to the serializer?

**Comment by kurko** [comment]
I don't remember  anyone removing it. Can you PR a failing test?

**Comment by ccaratori** [comment]
My mistake @kurko, it is initialized as you said. My problem might be somewhere else.

**Comment by ccaratori** [comment]
Just to close this matter, the 0.9.3 version took a different approach to custom options.

As it shows in the `active_model_serializers/test/unit/active_model/serializer/options_test.rb` v.0.9.3, the custom options are accessed through the context method
```
class OptionsTest < Minitest::Test
  def setup
    @serializer = ProfileSerializer.new(nil, context: {foo: :bar})
  end

  def test_custom_options_are_accessible_from_serializer
    assert_equal({foo: :bar}, @serializer.context)
  end
end
```

In the v.0.8.3 and the current master branch they are accessed through the @options variable
