### ISSUE TITLE
Namespacing serializers does not work

### ISSUE THREAD

**Issue by EtienneDepaulis** [rails-api/active_model_serializers#860]
Hi,

I've been using AMS for few months and I still struggle on the same problem for every single API I try to build with AMS. Let me take a very simple exemple with a `Post` which has_may `Comments`.

When I go to `/comments.json`, I have a collection of `current_user.comments`
When I go to `/posts.json`, I have a collection of `current_user.posts`
When I go to `/posts/4.json`, I have the `post` data and the `post.comments` as well.

For `/comments.json` I have a CommentSerializer:
```
class CommentSerializer < ActiveModel::Serializer
  attributes :id, :body
  has_one :post, embed_in_root: true
end
```

For `/posts.json` I have a PostSerializer:
```
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body
end
```

Then for `/posts/4.json` confusion starts :/
If I try something like:
```
class SinglePostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body

  has_many :comments, embed_in_root: true
end
```
The `comments` are serialized using the previous CommentSerializer which will then call the PostSerializer. I can't see the logic in that strategy :/

My next iteration is to create a second serializer pour the `comments`:
```
class SinglePostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body

  has_many :comments, embed_in_root: true, serializer: SingleCommentSerializer
end

class SingleCommentSerializer < ActiveModel::Serializer
  attributes :id, :body
end
```
This strategy works but now I have 4 serializers and this does not sound DRY at all :(

In order to have better organization for my serializers I tried namespacing them:
```
class API::V1::PostsController < API::V1::APIController
  def show
    respond_with @posts, root: "post", serializer: Post::PostSerializer
  end
end

class Post::PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :body
  has_many :comments, embed_in_root: true, serializer: Post::CommentSerializer
end

class Post::CommentSerializer < ActiveModel::Serializer
  attributes :id, :body
end
```

But this doesn't work as `serializer: Post::PostSerializer` keeps pointing to `PostSerializer` and triggers a warning `warning: toplevel constant PostSerializer referenced by Post::PostSerializer`.

Am I doing something wrong ?
Thanks for your help

**Comment by JoshSmith** [comment]
Hey @EtienneDepaulis, I would say that something like this is an API design question better suited for StackOverflow and perhaps tagged with `active-model-serializers`.

I think you're misunderstanding how something like this might work.

What you really want is something like:

```
class PostSerializer < ActiveModel::Serializer
  has_many :comments
end
```

```
class CommentSerializer < ActiveModel::Serializer
  attributes :id, :post_id
end
```

Does this make sense?

**Comment by JoshSmith** [comment]
Also, I would try to familiarize yourself more with jsonapi.org which is certainly where this is heading.

**Comment by EtienneDepaulis** [comment]
@JoshSmith Will take a look. Apparently I'm not the only one confused by this situation :) Thanks for answering me.
