### ISSUE TITLE
Rails 4.2, Mongo, responders gem

### ISSUE THREAD

**Issue by Konnigun** [rails-api/active_model_serializers#869]
Hey there!
I am using AMS with Rails 4.2.1 and  responders 2.1.0.
It was getting ignored by controllers in latest Rubygems version (0.9.3 I think?) so I needed to use 0.9.1 to get it working (found it here: http://discuss.emberjs.com/t/rails-4-2-and-active-model-serializer/7051).
My proposal is to add this to Readme because I am sure there are people like me and these guys from EmberJS forum who stumbled into the same issue, so we can help them.

**Comment by JoshSmith** [comment]
I'm debating whether this is a documentation thing or not. I don't know that explicit documentation for this necessarily makes sense. It sounds more like a bug that needs fixed.

I'm also hesitant to add edge cases in documentation for a version that is fundamentally different than what's being supported going forward. I personally would actively discourage development on `0.9.x` and encourage switching to `0.10.x` as soon as feasible.

**Comment by Konnigun** [comment]
I meant adding something like a temporary notice/alert there, like "MAINTENANCE, PLEASE READ" section currently, something along these lines

**Comment by kurko** [comment]
People are saying that the bug was in 0.9.2, and 0.9.1 was good. 0.9.3 is the same as 0.9.1 minus a regression commit. Can you try that version?

**Comment by Konnigun** [comment]
Thank you, 0.9.3 works great as well. Closing this one.
