### ISSUE TITLE
Version 0.9.4 release

### ISSUE THREAD

**Issue by laserlemon** [rails-api/active_model_serializers#871]
There are [quite a few changes](https://github.com/rails-api/active_model_serializers/compare/v0.9.3...0-9-stable) between `v0.9.3` and `0-9-stable` that have yet to be released. Could we cut a version 0.9.4? Specifically, the [ability to specify a serializer class per model](https://github.com/rails-api/active_model_serializers/commit/d8b78a36cfde1bef6dc23c6a64f6b92c4597258d) would be great to have back. Thank you!

**Comment by imanel** [comment]
Bump - any news about when it will be released?

**Comment by karlentwistle** [comment]
:+1:

**Comment by remear** [comment]
0.9.4 was released. https://rubygems.org/gems/active_model_serializers/versions/0.9.4
