### ISSUE TITLE
Changelog should mention caching

### ISSUE THREAD

**Issue by trashhalo** [rails-api/active_model_serializers#873]
seems like this is missed in the https://github.com/rails-api/active_model_serializers/blob/master/CHANGELOG.md

https://github.com/rails-api/active_model_serializers/commit/8a432ad2b3a11b54183630b08b47ad2d249f9327

**Comment by kurko** [comment]
Yes, we started the changelog after that. Can you open a PR to add it there? I'll merge it right away :)

**Comment by joaomdmoura** [comment]
@trashhalo actually the last two lines are:
```
adds fragment cache support [@joaomdmoura]
adds cache support to attributes and associations [@joaomdmoura]
```
