### ISSUE TITLE
8.x: active_model_serializers not intercepting error responses?

### ISSUE THREAD

**Issue by emma-borhanian** [rails-api/active_model_serializers#875]
If I do `render json: resource`, and `resource` has `ActiveModel` errors, instead of using active_model_serializers controller hooks, rails seems to end up delegating to [ActionController:: Responder#json_resource_errors](https://github.com/rails/rails/blob/0c2854fa0302acfeb27f1316f2163b3c1dfc4f95/actionpack/lib/action_controller/metal/responder.rb#L289)

**Comment by langalex** [comment]
I have the same problem. Just upgraded from Rails 4.0.13 (worked) to 4.2.3 (stopped working).

**Comment by langalex** [comment]
fixed it by upgrading to 0.10.

**Comment by joaomdmoura** [comment]
> fixed it by upgrading to 0.10.

:+1: :+1: :+1: :+1: :+1: 

@emma-borhanian we would need to check on this, but we are focusing out efforts into 0.10.x, so it might take a while.
