### ISSUE TITLE
0.10.stable / master is ignoring (key/root) option in has_many method 

### ISSUE THREAD

**Issue by bernardogalindo** [rails-api/active_model_serializers#882]
Example
```ruby
has_many :charts, root: :rows,  serializer: ChartSerializer 
```

This produce a json with charts collection and ignore the custom name as follow
```json
  { charts: [ ... ] }
```
When I'm expecting
```json
   { rows: [ ... ] }
```

also fails using key option

```ruby
  has_many :charts, key: :rows,  serializer: ChartSerializer
```

**Comment by bf4** [comment]
I think this is a feature request

**Comment by bernardogalindo** [comment]
@bf4 I think is backward compatibility. This functionality is a good option to avoid create a method just for customize the name of relationship

0.9 version
https://github.com/rails-api/active_model_serializers/tree/0-9-2#associations
0.8 version
https://github.com/rails-api/active_model_serializers/tree/0-8-stable#associations

**Comment by bf4** [comment]
Oh, my bad for not looking back. So, it's either a bug or a breaking change.

**Comment by maurogeorge** [comment]
Hi @joaomdmoura I try to write a broken test and got no success :cry: 
I think the https://github.com/rails-api/active_model_serializers/pull/984 closes this issue. Could you please review this and close this issue if make sense?

Thanks

**Comment by bf4** [comment]
@bernardogalindo Does #984 resolve you issue so we can close this?

**Comment by bernardogalindo** [comment]
@bf4 I still having the same issues that I mentioned with the current master branch. 

Version 0.9.3 allow me to do `root=false`  to get  

```json
"{\"name\":\"Test\",\"parent_id\":null,\"subaccount_ids\":null}"
```
instead of

```json
+"{\"object\":{\"name\":\"Test\",\"parent_id\":null,\"subaccount_ids\":null}
```

And allow me customize my the object keys as I mentioned

```json
  { charts: [ ... ] }
```
When I'm expecting
```json
   { rows: [ ... ] }
```

##### The current master branch still ignoring the root and key options

**Comment by bernardogalindo** [comment]
Here is one of my test result

```ruby
16) Failure:
TestLowChartsDecoratorSerializer#test_json_serializer_should_return_low_charts_format [/Users/bgalindo/projects/advance_account_managment/test/serializers/low_charts_decorator_serializer_test.rb:27]:
--- expected
+++ actual
@@ -1 +1 @@
-{"p"=>{"date_format"=>"%b %e", "omit_legend"=>true}, "rows"=>[{"c"=>[{"v"=>"2015-08-29", "f"=>"2015-08-29"}, {"v"=>1, "ts"=>"2015-08-29", "te"=>"2015-08-30", "f"=>"", "partial"=>false}]}], "cols"=>[{"label"=>"test", "type"=>"number"}]}

+{"object"=>{"columns"=>[{"name"=>"test", "type"=>"number"}], "charts"=>[{"points"=>[{"value"=>1, "format"=>"", "partial"=>false, "start_time"=>"2015-08-29", "end_time"=>"2015-08-30"}], "legend"=>{"value"=>"2015-08-29"}, "start_time"=>"2015-08-29", "end_time"=>"2015-08-30"}], "options"=>{"date_format"=>"%b %e", "omit_legend"=>true}}, "options"=>{}, "root"=>nil, "meta"=>nil, "meta_key"=>nil, "scope"=>nil}
```

I'm expecting a false object root and  rows as key instead of charts, also that collections use the correct serializer with settings.

File code

```ruby
  class LowChartsDecoratorSerializer < ActiveModel::Serializer
    self.root = false 
    attributes :p
    has_many :charts, root: :rows,  serializer: ChartSerializer 
    has_many :columns, root: :cols, serializer: ColumnSerializer 

    def p
       object.options  
    end
  end
```

**Comment by bf4** [comment]
Which commit ref are you on on master? (It would be in your Gemfile.lock)

I think you want [`self.root=nil`](https://github.com/rails-api/active_model_serializers/pull/936#issuecomment-108621699) depending on what commit you're on.

If you have the `FlattenJson` adapter available, that might do what you want.

(Also, I'm not sure if this is from your real code, but calling anything `p` is bug-prone since it's a method on Kernel, so unless you're really careful about the context, you mind end up calling `Kernel.p whatever`)

**Comment by bernardogalindo** [comment]
@bf4 the master branch returns

`undefined method root=  for  Class`

p method is just under serializer scope.

**Comment by bernardogalindo** [comment]
@bf4 however if I deleted this requirement the custom keys seems to be working I think we can close this issue however `self.root= nil` and `self.root=false` is not working.

**Comment by joaomdmoura** [comment]
Hey @bernardogalindo so, there is a bunch of different things in here.

If you are using master, you will have access to different adapters one of them is `FlattenJson` that basically removes the `root` for you. You can check more about it on [its docs](https://github.com/rails-api/active_model_serializers/blob/master/docs/general/adapters.md). This is now the way to control the `root` existence, you can also find out more about it [here](https://github.com/rails-api/active_model_serializers/blob/master/docs/howto/add_root_key.md).

About changing the `key` on a relationship declaration, AFAIK you should use `key` option on the relationship, you can check some tests we have around this [here](https://github.com/rails-api/active_model_serializers/blob/master/test/adapter/json_test.rb#L31) using [this serializer declaration](https://github.com/rails-api/active_model_serializers/blob/master/test/fixtures/poro.rb#L241)

**Comment by beauby** [comment]
Closing this for now as the issue seems to be solved by @joaomdmoura's suggestions. Feel free to reopen if needed.
