### ISSUE TITLE
Serializers don't inherit attributes

### ISSUE THREAD

**Issue by malroc** [rails-api/active_model_serializers#884]
In 0.10.x, serializers don't inherit attributes. It was working fine in 0.8.x, and is absolutely required to keep serializers DRY.
I see there is already a pull request fixing this issue: #880 
Posting a ticket just to make sure this PR won't be lost.

**Comment by JoshSmith** [comment]
Since #880 is merged can you verify this fixes this issue @malroc?

**Comment by malroc** [comment]
@JoshSmith I'll check a bit later today.

**Comment by malroc** [comment]
Fixed by #880

**Comment by joaomdmoura** [comment]
:+1:
