### ISSUE TITLE
Dynamic cache keys

### ISSUE THREAD

**Issue by apolzon** [rails-api/active_model_serializers#893]
AMS 0.10 is really looking great, thanks for all the work thats gone into it.

The one thing I'm looking for that I don't believe is currently possible is a way to cache serializers on a per-user (or some other runtime-attribute) basis.

ie, I'd like to specify my cache key as:

```ruby
cache key: "project", additional_models: [current_user]
```
(current_user being the serialization scope)

or, if the cache key attribute supported a lambda:
```ruby
cache key: -> { "project/#{current_user.id}-#{current_user.updated_at}" }
```

I guess another approach would be to pass the serialization scope to object.cache_key.

Thanks.

**Comment by joaomdmoura** [comment]
Hey @apolzon, I'm glad you are enjoying AMS 0.10

Indeed, the only way of doing this today would be interpolating string as key:

```ruby
cache key: "project-#{current_user.id}-#{current_user.updated_at}"
```

I'm not sure what is your use case, but having cache per user may not scale as you might need.
But you could use [fragment cache](https://github.com/rails-api/active_model_serializers#fragmenting-caching), so you can cache only the attributes that makes sense to be cache to ever user.

**Comment by apolzon** [comment]
Yeah, the problem is that the cache key is interpolated when the serializer class is initially loaded, so current_user doesn't exist at that point -- thats why I thought of the lambda approach.

I have a couple associations that return different values based on the user's role, so I was planning on putting them in a separate serializer so that the bulk of my model has a shared cache, but a couple fields have per-role cache keys.

**Comment by joaomdmoura** [comment]
Oh, I forgot about it, you are right.
Yes, we could implement lambda support, it wouldn't be so hard.
But still, I don't think it is the best way to go, once that it won't scale.
Fragment cache may fit you well

```ruby
 cache except: [:user_attribute_one, :user_attribute_two]
```

**Comment by JoshSmith** [comment]
@apolzon would you mind responding to @joaomdmoura's thoughts on this when you have a moment? Thanks!

**Comment by arc9-admin** [comment]
I'm using the fragment cache now -- however I still think there is a valid use case for a cache key that is evaluated at the instance level instead of the class level (either via lambda or other mechanism).

Obviously the use case I originally raised is not a good one for caching, but a better example might be a field that has a different value for authenticated vs non-authenticated users.

**Comment by apolzon** [comment]
I'm using the fragment cache now -- however I still think there is a valid use case for a cache key that is evaluated at the instance level instead of the class level (either via lambda or other mechanism).

Obviously the use case I originally raised is not a good one for caching, but a better example might be a field that has a different value for authenticated vs non-authenticated users.

(Sorry for any notification spam/confusion -- originally accidentally made this comment from the wrong account)

**Comment by joaomdmoura** [comment]
@apolzon I'm closing it. I understand the request, but I can't see a demand for it right now.
The authenticated vs unauthenticated example might be a fit, but se a edge case, I'd probably use fragment cache to cache the other attributes.
But I would be willing to discuss it further if some request show up! :smile:
