### ISSUE TITLE
Add serializer file digest to cache key

### ISSUE THREAD

**Issue by cristianbica** [rails-api/active_model_serializers#901]
Rails' `ActionView` caching uses a template file digest (md5 on the file) in the cache key so the cache will expire if you update the template file. I think AMS should also have this. I can work on a PR in the coming days if you guys think this is acceptable.

**Comment by joaomdmoura** [comment]
Hey @cristianbica, thank you for the issue.
Indeed this makes sense, and would be acceptable.

**Comment by joaomdmoura** [comment]
btw in order to help you to pull it off, this is probable where you will make the magic happens, but amke yourself comfortable :)

https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/adapter.rb#L65-L67

**Comment by cristianbica** [comment]
@joaomdmoura thanks. Looking into the 0.10 stuff. looks beautiful :+1:
