### ISSUE TITLE
Gitter room?

### ISSUE THREAD

**Issue by jimmybaker** [rails-api/active_model_serializers#905]
Can we start a gitter room for this repo? It's definitely popular enough and would open up a place to possibly get instant answers. :P

**Comment by joaomdmoura** [comment]
uhmm @JoshSmith how do you feel about, it's your field :smile:

**Comment by locks** [comment]
There's #rails-api on Freenode, for what it's worth.

**Comment by joaomdmoura** [comment]
@locks indeed, I'm almost always there :stuck_out_tongue_closed_eyes:

**Comment by jimmybaker** [comment]
Sweet. thanks guys.
