### ISSUE TITLE
AMS is modifying data format (without a serializer)

### ISSUE THREAD

**Issue by rbarrera87** [rails-api/active_model_serializers#910]
I started to use AMS to serialize some data, and it worked pretty good, but I had some issues when I'm rendering json without a serializer.

I have this controller :
```ruby
class HospitalsController < ApplicationController
  def states
    country = params[:country]
    states = ( country.present? && Carmen::Country.coded(country).try(:subregions?) ) ? Carmen::Country.coded(country).subregions.sort.map{ |s| [s.name, s.code] } : []
    render :json => states
  end
end
```
And this code was getting the data in this format:
```js
[
  [ 0] [
        [0] "Alabama",
        [1] "AL"
  ],
  [ 1] [
        [0] "Alaska",
        [1] "AK"
    ]
]
```
But since I started to use AMS the data is like follows:

```js
{
  "hospitals" => [
    [ 0] [
      [0] "Alabama",
      [1] "AL"
    ],
    [ 1] [
      [0] "Alaska",
      [1] "AK"
    ]
  ]
}
```
Why is AMS adding the "hospitals" key even though I don't have any serializer for it, in addition I also added the initializer with the following code:

```ruby
ActiveModel::Serializer.setup do |config|
  config.embed = :ids
  config.root = false
end
```
Is this a bug or is there any kind of configuration that I am missing?

**Comment by joaomdmoura** [comment]
Hey @rbarrera87 thank you for the issue, what version of AMS are you using?

**Comment by rbarrera87** [comment]
Hey! I am using the **0.9.3** version, thank you for your response :+1:

**Comment by rbarrera87** [comment]
I've checked the code and it seems like that issue is fixed in the **0.10.0.rc1**. I saw this test in **0.9.3**
```ruby
def test_render_array
  get :render_array
  assert_equal 'application/json', @response.content_type
  assert_equal '{"my":[{"name":"Name 1","description":"Description 1"}]}', @response.body
end
```
As you can see this test has the key `my` before the array. In the version number **0.10.0.rc1** you have this test:
```ruby
def test_render_array_using_implicit_serializer
  get :render_array_using_implicit_serializer
  assert_equal 'application/json', @response.content_type

  expected = [
    {
      name: 'Name 1',
      description: 'Description 1',
    },
    {
      name: 'Name 2',
      description: 'Description 2',
    }
  ]

  assert_equal expected.to_json, @response.body
end
```
In this second test you guys are testing the array without a key at the beginning of the array, which is the correct behavior (I guess).

**Comment by ignasio** [comment]
Same issue. Will it be fixed at 0.9.3?

**Comment by rbarrera87** [comment]
@ignasio The workaround that I found was adding `to_json` in your render response, something like this:
```ruby
render :json => states.to_json
```

**Comment by ignasio** [comment]
@rbarrera87 You`re right, but in my case this issue is breaking gem "rails3-jquery-autocomplete".

**Comment by rbarrera87** [comment]
@joaomdmoura I am trying to fix this bug, it seems like the error is in this function:
```ruby
#lib/active_model/array_serializer.rb
def json_key
  key = root.nil? ? @resource_name : root

  key_format == :lower_camel && key.present? ? key.camelize(:lower) : key
end
```
I was trying to modified this function, but I am facing a problem when the option `embed_in_root` is true. Is there any way to access to `ActiveModel::Serializer::CONFIG.embed_in_root` in `lib/active_model/array_serializer.rb` or am I misunderstanding/missing  something?

You can check my commit [here](https://github.com/rbarrera87/active_model_serializers/commit/0f05a252c652870c5440d0066ca0390dc73a9a96)

**Comment by joaomdmoura** [comment]
Hey @rbarrera87, glad to hear ta you are into it!
I made some digging, maybe found the solution, did you tried?:
```ruby
ActiveSupport.on_load(:active_model_serializers) do
  # Disable for all serializers (except ArraySerializer)
  ActiveModel::Serializer.root = false

  # Disable for ArraySerializer
  ActiveModel::ArraySerializer.root = false
end
```

Other option, that will affect the object being rendered, would be:
```ruby
render :json => @posts, :root => false
```

I agree that taking apart this config, AMS shouldn't mess with the object without a serializer, but as I are really focused into 0.10.x it's hard to develop new thing to older versions. (btw I strongly recommend you to give a try to 0.10.x - at master)

**Comment by hendricius** [comment]
@rbarrera87 for this you should always use `to_json` as you specified. Else a serializer is always used.

I think this is not really a bug.

**Comment by joaomdmoura** [comment]
I'm closing this for now. 
@rbarrera87 btw, Let me know if the solution I posted before worked for you :smile:
