### ISSUE TITLE
Associations with namespaced models not working

### ISSUE THREAD

**Issue by dpmccabe** [rails-api/active_model_serializers#916]
I have two models that come from a Rails engine, `Spree::Product` and `Spree::Variant`, and I can't figure out how to correctly specify an association between them in my serializers. Here is my current setup:

##### app/serializers/spree/product_serializer.rb

```ruby
module Spree
  class ProductSerializer < ActiveModel::Serializer
    attributes :id, :name
    has_many :variants, serializer: Spree::VariantSerializer
  end
end
```

##### app/serializers/spree/variant_serializer.rb

```ruby
module Spree
  class VariantSerializer < ActiveModel::Serializer
    attributes :id, :price
    belongs_to :product, serializer: Spree::ProductSerializer
  end
end
```

A serialization of products loads the attributes correctly, but the variants don't appear (not even an empty array). If I change `has_many :variants, serializer: Spree::VariantSerializer` to simply `has_many :variants` then I get the variants, but it includes all the default attributes instead of using `VariantSerializer`.

I've tried all sorts of combinations of file placement, class declarations, and associations to no avail.

**Comment by saneshark** [comment]
May be related to #879 (pending discussion)

**Comment by groyoh** [comment]
@dpmccabe I'm not sure if I understood your need, but basically you want the serializer to automatically find a matching association serializer in the same module without specifying any additional option, right? If that's the case, then #879 won't solve this. It is mainly useful when you deal with polymorphic relationship and/or serializer that are defined in a different module. You would still have to specify `namespace: Spree` in your case.

**Comment by groyoh** [comment]
I don't think that it is related to #879. It might be a bug.
@dpmccabe could you provide a snippet of how you serialize the products?

**Comment by dpmccabe** [comment]
The pull request referenced in #879 fixed this for me. Here are the working association method calls:

`has_many :variants, serializer: VariantSerializer, namespace: Spree`

`belongs_to :product, serializer: ProductSerializer, namespace: Spree`

**Comment by groyoh** [comment]
@dpmccabe I'm glad that it fixed it for you. BTW, you don't need to specify `serializer: VariantSerializer`, this should do it:
```ruby
has_many :variants, namespace: Spree
belongs_to :product, namespace: Spree
```
Could you still provide a snippet of the serialization call please? There might still be a bug. What I would like to know is if you render it this way:
```ruby
render json: products
```
or
```ruby
serializer = ActiveModel::Serializer::ArraySerializer.new(products)
ActiveModel::Serializer::Adapter.create(serializer).to_json
```

**Comment by dpmccabe** [comment]
Yes, I believe there is still a bug. I'm going to write it up as a comment in the pull request.

**Comment by dpmccabe** [comment]
(Scratch that, I'll leave it here since I'm not sure it's actually related to the changed code in the PR.)

When I omit the explicit `serializer` argument in `has_many :variants`, I get an exception (you can see the call to the serialization there):
https://gist.github.com/dpmccabe/39aa96034b599fee81f8

I don't have time to make an example app at the moment, but here's a simple comparison I ran from the Rails console.

```ruby
products = Spree::Product.where(id: [28, 30])
serializer = ActiveModel::Serializer::ArraySerializer.new(products)
json = ActiveModel::Serializer::Adapter.create(serializer).as_json
```

```
=> [#<Spree::Product id: 28, name: "RFID Sticker", description: "", available_on: "2015-01-21 06:00:00", deleted_at: nil, slug: "rfid-sticker", meta_description: "", meta_keywords: "", tax_category_id: 3, shipping_category_id: 5, created_at: "2015-01-21 23:13:41", updated_at: "2015-05-20 17:40:36", ordinal: 7>,
 #<Spree::Product id: 30, name: "Battery", description: "", available_on: "2015-02-05 06:00:00", deleted_at: nil, slug: "battery", meta_description: "", meta_keywords: "", tax_category_id: 3, shipping_category_id: 7, created_at: "2015-02-05 23:23:15", updated_at: "2015-05-20 17:40:36", ordinal: 8>]

=> #<ActiveModel::Serializer::ArraySerializer:0x007fc856920b50
 @meta=nil,
 @meta_key=nil,
 @objects=
  [#<Spree::ProductSerializer:0x007fc856920970
    @meta=nil,
    @meta_key=nil,
    @object=
     #<Spree::Product id: 28, name: "RFID Sticker", description: "", available_on: "2015-01-21 06:00:00", deleted_at: nil, slug: "rfid-sticker", meta_description: "", meta_keywords: "", tax_category_id: 3, shipping_category_id: 5, created_at: "2015-01-21 23:13:41", updated_at: "2015-05-20 17:40:36", ordinal: 7>,
    @options={:root=>nil},
    @root=false,
    @scope=nil>,
   #<Spree::ProductSerializer:0x007fc8569208d0
    @meta=nil,
    @meta_key=nil,
    @object=
     #<Spree::Product id: 30, name: "Battery", description: "", available_on: "2015-02-05 06:00:00", deleted_at: nil, slug: "battery", meta_description: "", meta_keywords: "", tax_category_id: 3, shipping_category_id: 7, created_at: "2015-02-05 23:23:15", updated_at: "2015-05-20 17:40:36", ordinal: 8>,
    @options={:root=>nil},
    @root=false,
    @scope=nil>]>

=> [{:id=>28, :name=>"RFID Sticker", :variants=>[]}, {:id=>30, :name=>"Battery", :variants=>[{:id=>64, :price=>#<BigDecimal:7fc85550b660,'0.0',9(18)>}, {:id=>65, :price=>#<BigDecimal:7fc8537cc6d0,'0.0',9(18)>}]}]
```

If I omit the `serializer: VariantSerializer` in my `has_many` call, I get this exception on the last command (the serializer object is identical):

```
ArgumentError: When assigning attributes, you must pass a hash as an argument.
from /Users/devin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.1.5/lib/active_record/attribute_assignment.rb:16:in `assign_attributes'
```

**Comment by groyoh** [comment]
@dpmccabe thanks for the details. I'll try to take a look a this.

**Comment by groyoh** [comment]
@dpmccabe This error is really strange IMO. A few questions:
* Does your model have an `serializer_class` method in your models?
* Are you using master? HEAD or older commit?

My best guess right now is that `ActiveModel::Serializer.serializer_for` returns `ActiveRecord::Base` class (or one of its subclass, basically your model) but I have no clue how that could happen.
I managed to reproduce the exception but the context is really weird. Basically, I needed the following setup:
```ruby                                                                                                               
module Spree
  class Product < ActiveRecord::Base; end
  class Variant < ActiveRecord::Base; end
  class ProductSerializer < ActiveModel::Serializer
    attributes :id, :name
    has_many :variants
  end                                                                                                                                                                                         
  class VariantSerializer < ActiveRecord::Base; end
end      
```

**Comment by groyoh** [comment]
@dpmccabe bump

**Comment by joaomdmoura** [comment]
related to: https://github.com/rails-api/active_model_serializers/pull/879

**Comment by nahtnam** [comment]
Im having a similar issue.

I have two serializers in my rails mountable engine.

```
module Status
  class SteamSerializer < ActiveModel::Serializer
    attributes :id, :login, :community, :matchmaking, :online_servers, :online_players, :searching, :wait_time

    has_many :steam_datacenters
  end
end
```

and

```
module Status
  class SteamDatacenterSerializer < ActiveModel::Serializer
    attributes :id, :name, :capacity, :load

    belongs_to :steam, namespace: Status
  end
end
```


The resulting JSON for `Steam` is ok but for some reason, the has_many association isn't working. The JSON is returning things like the created_at and updated_at attributes even though they aren't in my serializer which leads me to believe that AMS cant find my serializer.

Thanks.

**Comment by remear** [comment]
Closing. If this is still an issue, please try with 0.10 master and open a new issue.
