### ISSUE TITLE
Unable to overwrite the id value

### ISSUE THREAD

**Issue by pywebdesign** [rails-api/active_model_serializers#926]
Hi,

It seams impossible to overwrite the id value when serializing. I am using the jsonapi adapter.

this line:

````ruby
 attribute :conversation_id, key: :id
````

will output the value of id instead of the conversation_id as the value of the json id key

**Comment by benedikt** [comment]
For a quick workaround, try overwriting the `id` method like this instead:

```ruby
def id
  object.conversation_id
end
```

**Comment by joaomdmoura** [comment]
Yes @pywebdesign it's impossible the way it's designed today, unless you use the workaround proposed by @benedikt 
Would be nice to replicate this kind of questions on stackoverflow, we are trying to create a pool of good and usual questions there.
