### ISSUE TITLE
My model already has an attribute named 'scope'

### ISSUE THREAD

**Issue by JonasSynergium** [rails-api/active_model_serializers#932]
Hi,  
one of my models that I try to serialize has an attribute named 'scope'.  Once serialized this attribute is replaced by the value of the current user (as is stated in the documentation).  

How can I get the 'scope' value from my model and not from the 'scope' method that AMS provides?

**Comment by joaomdmoura** [comment]
@JonasSynergium You can create a virtual attribute in your serializer:

```ruby
class PostSerializer < ActiveModel::Serializer
  attributes :id, :body, :scope_attribute

  def scope_attribute
    object.scope
  end
end
```

**Comment by conf** [comment]
For anybody, who is, like me, still needs to keep `scope` key, you can do the following trick:
```ruby
class PostSerializer < ActiveModel::Serializer
  attributes :id, :body # don't list :scope here

  def attributes
    super.merge(scope: object.scope)
  end
end
```
