### ISSUE TITLE
Associations of associations are not using proper serializer

### ISSUE THREAD

**Issue by jeffsaracco** [rails-api/active_model_serializers#934]
For instance, if I have 

```
class Foo
  has_many :bars
end
class Bar
  has_many :bazs
end
class Baz
end
```
With serializers:
```
class FooSerializer
  has_many :bars
end

class BarSerializer
  attribute :type
  has_many :bazs
end

class BazSerializer
  attributes :name
end
```

When I do a `render json: foo` it properly uses `FooSerializer` and `BarSerializer` but for `Baz` it does not use the serializer but rather the default rails `as_json` method

**Comment by jeffsaracco** [comment]
I should add that if I request bar directly and render it with `render json: bar` it properly uses the `BazSerializer`

**Comment by groyoh** [comment]
Which version do you use?

**Comment by jeffsaracco** [comment]
we are using it straight from master.. rev 48ed7cf9ba85e124f41321b4d0d6d2aab44ece08 to be exact

**Comment by groyoh** [comment]
On master, associations of associations should not be rendered by the json adapter (see #921 for a work around). Are the `Baz` elements rendered? If it is, then this might be a bug.

**Comment by jeffsaracco** [comment]
They are rendered, just not with the `BazSerializer`... the default `to_json` is being used

**Comment by groyoh** [comment]
I can't reproduce your case. For me, `bazs` are not rendered. Maybe you could be more specific on the context or provide a gist that reproduce it.

**Comment by jeffsaracco** [comment]
FWIW, we are using MongoMapper as our ORM, not ActiveRecord... the work around in #921 works for us for now
