### ISSUE TITLE
Is it possible to ignore all adapters?

### ISSUE THREAD

**Issue by eliduke** [rails-api/active_model_serializers#935]
I am working on a large rails-api project with AMS v0.8.3 that currently has 2 native apps and a front-end web app. I am interested in upgrading to AMS v0.10.0 for some of the new features (primarily caching), but then it forces us into the JSON API adapter and essentially renders our end points useless without a substantial rewrite of all the front ends. Is it possible to override the default adapter to the "standard" that existed with v0.8.3?

The concept of adapters is new to me with AMS v0.10.0 and I see that the JSON API just hit v1.0 a couple days ago. It's exciting, but not practical to try to implement it right now.

**Comment by groyoh** [comment]
It depends what you mean by "standard" but you can do this:
```ruby
ActiveModel::Serializer.config.adapter = :json
```
to set the default adapter to JSON instead of JSON API.

**Comment by groyoh** [comment]
JSON API isn't the default on v0.10. At least not yet (or not anymore #930 ). By default it will format as json by rendering attributes and attributes of associations.

The serializers allow you to define WHAT (attributes and associations) would be serialized whereas the adapter basically allow you to define HOW they are serialized. Using adapters also allow you to add your own output format if need be. For example, you could write your own XML format that would output your serialized objects as XML.

**Comment by eliduke** [comment]
Thank for the breakdown, but I think I am still a little confused. You say that there isn't a default adapter for v0.10, but without doing anything else aside from switching from v0.8.3 to v0.10, this app_label end point went from outputting this:

```
{
  "app_labels": [
    {
      "id": 1,
      "key": "username",
      "label": "Corporate Email Address",
      "label_plural": ""
    },
    {
      "id": 2,
      "key": "password",
      "label": "Password",
      "label_plural": ""
    }
  ]
}
```

To this:

```
{
  "data": [
    {
      "id": "1",
      "type": "app_labels",
      "attributes": {
        "key": "username",
        "label": "Corporate Email Address",
        "label_plural": ""
      }
    },
    {
      "id": "2",
      "type": "app_labels",
      "attributes": {
        "key": "password",
        "label": "Password",
        "label_plural": ""
      }
    }
  ]
}
```

I understand the technical benefits of the latter, but it's just not plausible at this time to rewrite the front ends to receive that new json data format.

Is it possible for v0.10 to output like the former?

**Comment by groyoh** [comment]
You can try setting the config:
```ruby
ActiveModel::Serializer.config.adapter = :json
```

**Comment by eliduke** [comment]
And where is the best place to put that?

**Comment by groyoh** [comment]
If you use Rails, then `config/initializers/active_model_serializer.rb`.

**Comment by eliduke** [comment]
Awesome. That did the trick! In my mind that seems like there IS a default adapter then, right?

**Comment by groyoh** [comment]
BTW are you using `0.10.0.rc1` version or master?

**Comment by eliduke** [comment]
I'm using `0.10.0.rc1` as such:

```
gem 'active_model_serializers', '0.10.0.rc1', git: 'https://github.com/rails-api/active_model_serializers.git'
```

**Comment by groyoh** [comment]
Then try `bundle update active_model_serializers` and try to run it without the config initialized.

**Comment by eliduke** [comment]
That did it! Wow. So, that was a recent change? Thanks for all your help!

**Comment by groyoh** [comment]
Yep, it was changed to JSON API 3 weeks days ago and then reverted a few days ago :wink: 
Please close this issue if you're all done :smile:
