### ISSUE TITLE
Scope is not passed through the custom attributes

### ISSUE THREAD

**Issue by sungwoncho** [rails-api/active_model_serializers#937]
Scope is nil when serializer is called within a custom attribute of another serializer.

Contrived example:

```ruby
class ApplicationController < ActionController::Base
  serialization_scope :view_context
end
```

```ruby
class UserSerializer < ActiveModel::Serializer
  attributes :can_vote

  def can_vote
    VotePolicy.allowed?(user) if object == scope.current_user
  end
end
```

Above works fine. However, `scope` is `nil` when I use `UserSerializer` in a custom attribute of another serializer:

```ruby
class CourseSerializer < ActiveModel::Serializer
  attributes :student

  def student
    UserSerializer(object.enrollment.student)
  end
end
```

**Update**

After reading the [code](https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L165), I realize that I can pass in scope when initializing the Serializer.

What are your thoughts on passing the scope by default, if one is defined?

**Comment by joaomdmoura** [comment]
@sungwoncho just checkin, are you using 0.10? from master or rc1?

**Comment by bf4** [comment]
Also, is there any reason you can't use `belongs_to :student` or some such so that it will just work? I know has_one was removed.

**Comment by bf4** [comment]
Propose closing since OP hasn't responded with version. (Though I correct myself, [`has_one` was removed, but has since been re-added](https://github.com/rails-api/active_model_serializers/pull/725))

**Comment by sungwoncho** [comment]
@bf4 I am using `0.9.3`.I am no longer working on this project so I am not sure if upgrading the gem would have fixed the issue.

**Comment by joaomdmoura** [comment]
```belongs_to: student``` as @bf4 pointed out seems the way to go for me.
IMHO passing an scope by default is unnecessary. :smile: 
It indeed won't work, but it seems just an edge-case for me that could be handled with the ```belongs_to```, so I'm closing this for now.
