### ISSUE TITLE
Postgres 9.4 incompatible with active_model_serializers 0.8 or 0.10

### ISSUE THREAD

**Issue by glennfu** [rails-api/active_model_serializers#940]
I have a Rails 4.1 app where I use active_model_serializers and grape to serve an API endpoint. Recently I tinkered around with upgrading from 0.8 to 0.9, only to read a bit more deeply and decide I should probably be skipping 0.9 and checking out either the 0.10 rc or master branch. I made changes to adjust to using the "v0.10.0.rc1" and things were going well.

Then yesterday I upgraded my database to Postgres 9.4, and started getting "IOError: not opened for reading" whenever hitting active_model_serializers. Here's the line (after testing Rails 4.2) in case it's useful:

```
# Activesupport (4.2.1) lib/active_support/core_ext/object/json.rb:128:in `each'
module Enumerable
    def as_json(options = nil) #:nodoc:
        to_a.as_json(options)
    end
end
```

I noticed that both Rails 4.1 and 4.2 had the same issue. Switching to active_model_serializers 0.9.3 fixed the error. Using 0.8, 0.10, or master branch all have this problem.

I'm not sure why upgrading to Postgres 9.4 made a difference, but that's the only intentional change I made. Since it was a bit of a headache (followed these steps: https://kkob.us/2014/12/20/homebrew-and-postgresql-9-4/) to upgrade from Postgres 9.3 to 9.4 I couldn't very easily jump back and forth between them for better testing on my local machine.

On the other hand, on my Heroku app, after promoting a 9.4 database and testing the code, I first saw the error, but when promoting the 9.3 database BACK and restarting, the error persisted. I don't know what that means. I didn't change any code so my only guess is that the gems were built against the different Postgres version and that makes a difference.

Hopefully this is enough information to go on! I'm having trouble drilling down any more specifically but let me know if there anything else I can answer.

**Comment by aaronlerch** [comment]
I just verified this in my Rails 4.2 app using Postgres 9.4.1. I just deployed my upgrade from AMS 0.9.3 to `master` (`35fb9d`) and it works without a problem. Not on heroku though, I'm using AWS OpsWorks for the app server and RDS for the database.

**Comment by joaomdmoura** [comment]
@glennfu did you trying master head? Does it still doesn't work?

**Comment by jtippett** [comment]
Running postgres 9.4.2 (installed by brew) I've seen no such issues running both 0.8 and 0.9 branches on separate projects. Just FYI.

**Comment by SweeD** [comment]
I have the same issue.

My setup:
- Rails 4.1.11
- Ruby 2.1.2
- postgres 9.3.5
- active_model_serializers on commit f67fd976ecbe41305c484e4689003758e8631998

I get following error
```
IOError: not opened for reading
```

Do you need any details to go further?

**Comment by SweeD** [comment]
@glennfu @aaronlerch 

Do you use `active_model_serializers` with the `grape-active_model_serializers` gem?

I had this problem only with the combination of these 2 gems. 

I changed to a more maintained version of that gem here:
https://github.com/Thanx/grape-active_model_serializers.git

And the problem was gone. :dancer:

**Comment by aaronlerch** [comment]
I do use AMS, but do not use `grape-active_model_serializers`

**Comment by joaomdmoura** [comment]
I'm closing this one for now until updates from @glennfu

**Comment by glennfu** [comment]
I do indeed use grape-active_model_serializers and switching to the one authored by Thanx fixed my problem. Thanks @SweeD !

**Comment by joaomdmoura** [comment]
@glennfu amazing!
I think the ppl at ```grape-active_model_serializers ``` would appreciate with you let them know about this issue.
