### ISSUE TITLE
Overridden attributes function does not get called if using fragment cache

### ISSUE THREAD

**Issue by kev5873** [rails-api/active_model_serializers#941]
I have a serializer that only shows certain attributes if a user is logged in, in this case I would want the fragment cache to only cache a specific set of attributes.  It appears that the attributes function doesn't get called when using cache.

```ruby
class StreamSerializer < ActiveModel::Serializer

  cache only: [:name]
  attributes :id, :name
  
  def attributes(*args)
    data = super
    # scope check if user is authorized to see this attribute, etc.
    data[:protected_attribute] = "Protected Attribute"
    data
  end

end
```

**Comment by joaomdmoura** [comment]
Hey @kev5873, are you using rc1 or master?
Btw why don't create a virtual attribute?

```rubyt
class StreamSerializer < ActiveModel::Serializer

  cache only: [:name]
  attributes :id, :name, :protected_attribute

  def protected_attribute
    # scope check if user is authorized to see this attribute, etc.
    "Protected Attribute"
  end
end
```

This should work. :smile: 
Sorry for take some time to reply you, was off for the weekend

**Comment by kev5873** [comment]
I am using master.

I can use a virtual attribute, but I would prefer unauthorized users not see those virtual attributes though, even if they were null.

**Comment by joaomdmoura** [comment]
Got it. 
Indeed this is something that we don't support yet.
Another workaround, you can create 2 serializers, and put the authorized inside you controllers action, depending on the validation you can use one or another. How does it feels for you? :smile:

**Comment by kev5873** [comment]
Hmm.. That sounds like an interesting idea, I'll give it a try!

**Comment by joaomdmoura** [comment]
0.8.x versions had the ```filter``` method in order to deal with this kind of things..
We have being discussing it on #922 so I'm closing this one for now :smile: but make youself comfortable to update it in case you need more help :smile:
