### ISSUE TITLE
JSONAPI 1.0 Support

### ISSUE THREAD

**Issue by SeyZ** [rails-api/active_model_serializers#944]
JSONAPI 1.0 is now released. Any plans to support it instead of the RC4? I would be happy to contribute if you need help.

**Comment by joaomdmoura** [comment]
@SeyZ as far as I know there isn't anyone working on it, and I would be glad to review it! :smile:

**Comment by SeyZ** [comment]
@joaomdmoura It seems that the master branch is compliant with the 1.0. It supports relationships intead of deprecated linkage for example.

**Comment by joaomdmoura** [comment]
Hm... @SeyZ I'll just double check if it's being fully supported before merge this. :smile:
