### ISSUE TITLE
Serialize Object/Array when no AMS Serializer is defined

### ISSUE THREAD

**Issue by kayakyakr** [rails-api/active_model_serializers#945]
I'm receiving an issue, in latest master, where I receive ```NoMethodError (undefined method `new' on nil:NilClass.)``` when I attempt to serialize something like, ['Result is invalid'].

From everything I can tell, it's rolling through the get_serializer_for method, failing to find a serializer for my object, but trying to create an instance of that serializer anyway. It should fall back to a default serializer.

Sorry if this has been addressed, I checked through the issues but didn't see anything that stood out to me. As a workaround, I'm having to specify "render json: obj, adapter: false" when I want to render a json-ready hash rather than a rails model.

**Comment by bf4** [comment]
Needs more info.  What is obj? Which ref are you on? (paste output of `bundle show active_model_serializers`) Which Ruby?  Which Rails?  What does your serializer look like?  Could you provide some more of the stack trace?

**Comment by kayakyakr** [comment]
active_model_serializers-7b0a85fdda85
rbx 2.2.10
rails 4.1

code is called as:

```Ruby
render json: {error: 'Result is Invalid'}
# throws exception because serializer is nil
```

Stack trace is less than interesting and I don't currently have an example set up to cause the error, but digging through the code:

```Ruby
#action_controller/serialization.rb:23
@_serializer ||= ActiveModel::Serializer.serializer_for(resource) # @_serializer is nil when resource is not explicitly specified.

#action_controller/serialization.rb:47
object = serializer.new(resource, @_serializer_opts) # calls new on serializer when it may be nil
```

Is ```render json: {}``` supposed to fall back to a more appropriate renderer?

**Comment by bf4** [comment]
perfect. So, the bug is there's no serializer for Hash. solutions: call 
`to_json` on your hash, and the resulting string will be your response 
body :)

**Comment by kayakyakr** [comment]
That's a pretty ugly solution. I like my adapter: false workaround better.

**Comment by bf4** [comment]
I suppose we could argue this is a bug in AMS in that if it can't find a serializer for non-string object, it should either just pass it through untouched or call to_json on it depending on the context.

**Comment by kayakyakr** [comment]
That would be the best, I think.

I also noticed that if you pass it a model that you haven't built a serializer for (yet or at all), it fails in the same way. Previous versions of AMS either passed those objects on to a lower renderer or just called to_json on them. Also chokes in the same way with an association without a serializer.

**Comment by bf4** [comment]
Yeah, wanna pair on a PR to pass through if adapter is nil or serializer is nil?

**Comment by kayakyakr** [comment]
I need to do some more digging. It looks like it should be passing it to super as soon as serializer comes back nil, which means something else is going on.

**Comment by bf4** [comment]
I think you have it on the nose, if I understand what you understand. tl;dr

```ruby
def _render_with_renderer_json(resource, options)
  if use_adapter? && (serializer = get_serializer(resource))
    # adapter ~ Adapter.create(serializer.new(resource))
     super(adapter, options)
  else
    super(resource, options)
  end
end
```

- where `use_adapter?` is true either when `:adapter` is not given or when it's given and falsy
- where `get_serializer(resource)` returns a serializer class either when `:serializer` is given or when it can be inferred by `ActiveModel::Serializer.serializer_for(resource)`
- thus, the AMS adapter is used when the adapter is given or inferred AND the serializer is given or inferred.

So, it's surprising that `render json: {error: 'Result is Invalid'}` would hit `object = serializer.new(resource, @_serializer_opts)`

**Comment by kayakyakr** [comment]
Yeah, that's what is confusing me. Let cause this error to occur and see what happens.

**Comment by bf4** [comment]
So, that's an easy test to write.

**Comment by kayakyakr** [comment]
I got it!

```Ruby
render json: ['errors']
```

It's because it's wrapped in an array. The error isn't in the rendering code, but instead is here:
```active_model_serializers-7b0a85fdda85/lib/active_model/serializer/array_serializer.rb:17:in `initialize'```

```Ruby
    def initialize(objects, options = {})
        options.merge!(root: nil)

        @objects = objects.map do |object|
          serializer_class = options.fetch(
            :serializer,
            ActiveModel::Serializer.serializer_for(object)
          )
          serializer_class.new(object, options.except(:serializer))
        end
        @meta     = options[:meta]
        @meta_key = options[:meta_key]
      end
```

So it's the array serializer that needs to know how to handle non-serializer data.

**Comment by kayakyakr** [comment]
Easier test to write. Much harder thing to fix because array serializer feeds that straight in to the adapter which doesn't know how to handle a non-serializer object or string.

**Comment by bf4** [comment]
I guess it would need a procy serializer that just calls to_json?

**Comment by joaomdmoura** [comment]
Hey ppl, just read trough the thread, I'm happy to see that you narrowed that the issue! 
Just keep in mind that we are kind starting the fix the ```has_many``` at #955 
I know that it's probably not related to ```array_serializer``` it self but just keep it in mind! :smile:

**Comment by kayakyakr** [comment]
That should fix it @joaomdmoura, or at least indicate how this should be fixed. It's the same issue at the core if it isn't the exact same issue.

**Comment by GriffinHeart** [comment]
I think this is the same as #772

**Comment by kayakyakr** [comment]
Yes, it is. Also the same as #955, or at least should be fixed by the fix for that issue.

**Comment by GriffinHeart** [comment]
Just to add some info the `nil` comes from here

https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer.rb#L243-L247
```ruby
def self.get_serializer_for(klass)
  serializers_cache.fetch_or_store(klass) do
    serializer_class_name = "#{klass.name}Serializer"
    serializer_class = serializer_class_name.safe_constantize

    if serializer_class
      serializer_class
    elsif klass.superclass
      get_serializer_for(klass.superclass)
    end
  end
end
```

When using `render json: ['errors']` class will be `String` which has no serialiser, same thing as `render json: [{a: 1}]` where class will be `Hash` which also has no serialiser, thus `serializer_class` is `nil`

**Comment by joaomdmoura** [comment]
It was fixed at #962
I'm closing this for now, but would be awesome if you guys could test it yourself :smile:

**Comment by kayakyakr** [comment]
Seems to be working. Had to switch up to using the FlattenJson serializer for some of the parts where I was building up a serializable hash outside of the context of the controller, but that was an unrelated change.

**Comment by phuongnd08** [comment]
This issue has been re-introduced in 0.10.5. "render [{}]" is returning error.

`UncaughtThrowError: uncaught throw :no_serializer`

**Comment by bf4** [comment]
@phuongnd08 You've commented on an issue from over a year ago without sufficient information to debug. I can't think of a realistic scenario where you'd be using AMS and render an array with a hash in it to json. Please open a new issue.
