### ISSUE TITLE
ASM issue with render :json with status code

### ISSUE THREAD

**Issue by victorhazbun87** [rails-api/active_model_serializers#956]
The problem with this piece of code: 

    render json: application_invitation, serializer: Api::V2::ApplicationInvitationSerializer, status: :created

Then in my tests:
expected: "201"
got: "400"

Finally when I switch to the code to be like:

    render json: Api::V2::ApplicationInvitationSerializer.new(application_invitation), status: :created

And my test pass. What is going on here? It is clear that ASM has an issue with the status codes...

I'm using: 
gem 'active_model_serializers', '0.9.2'
gem 'rails', '4.1.7'
gem 'rails-api', '0.3.1'

**Comment by bf4** [comment]
Does the 400 have any more info associated with it? stack trace?  do your tests also test the structure of the serialized resource? Is the test failing in only one situation but working on the live service for both? Thanks.

**Comment by bf4** [comment]
Propose closing as stale, pending OP response.

**Comment by joaomdmoura** [comment]
Agreed.
@victorhazbun87 let us know in case you still have the issue.
