### ISSUE TITLE
Not able to have the root

### ISSUE THREAD

**Issue by GCorbel** [rails-api/active_model_serializers#964]
Hello,

I have this serializer : 

```ruby
    class SkillSerializer < ActiveModel::Serializer
      attributes :id, :name, :description, :user_ids
      def user_ids
        object.user_ids
      end
    end
```
And this controller : 
```ruby
    module Api
      module V1
        class SkillsController < ::ApplicationController
          def index
            render json: Skill.search(params[:search]), root: true
          end

          def show
            render json: Skill.find(params[:id]), root: true
          end

          def default_serializer_options
            {root: true}
          end
        end
      end
    end
```
And this initializer : 
```ruby
    # Be sure to restart your server when you modify this file.
    #
    # This file contains settings for ActionController::ParamsWrapper

    # Enable parameter wrapping for JSON.
    ActiveSupport.on_load(:action_controller) do
      wrap_parameters format: [:json] if respond_to?(:wrap_parameters)
    end

    # To enable root element in JSON for ActiveRecord objects.
    ActiveSupport.on_load(:active_record) do
     self.include_root_in_json = true
    end
```
I always have this result : 

```ruby
{"id":2,"name":"Rails","description":"Ruby Framework","user_ids":[2]}
```

Is there a solution ?

Thanks!

**Comment by klautcomputing** [comment]
Which adapter are you using? And which ams version?

If you are using 0.10 then the docu states that:
FlattenJSON  generates a json response **without** a root key.
JSON - generates a json response **with** a root key. The **root key can't be overridden**, and will be automatically defined accordingly with the objects being serialized.

So you would need to use the JSON adapter and live with the name for the root key it chooses for you. Don't really get why you cannot set the root key on your own anymore in 0.10, which by the way is a pity.

**Comment by GCorbel** [comment]
Yes, as you said, it's a pitty. I want to create a web api for a ember application. Ember needs a very specific format. Accodring to [the Ember's doc](http://guides.emberjs.com/v1.12.0/models/connecting-to-an-http-server/), the model have to be contained in a root with the singular model name. If I understand, adapters will give plural name. 

Is it possible to use AMS to create an API with Ember? Rabl or JBuilder will be more appropriate?

Thanks!

**Comment by joaomdmoura** [comment]
@GCorbel actually we have being working closely with ember to make this kind of integration a piece-of-cake.
And it is! The JSON Adapter matches the expected by ember. The root in singular when retrieving a single resource as a ```show``` method for example and plural when returning a set of resources, like a ```index``` method for example.

@spastorino made and awesome example just some days ago:
[Ember app](https://github.com/spastorino/todo-rails-api-ember-frontend)
[Rails app](https://github.com/spastorino/todo-rails-api-ember-backend)

Closing this for now. @GCorbel let me know in case of any problem so we can reopen it :smile:

**Comment by GCorbel** [comment]
I changed to use the json adapter. When I do this `render json: skill`, I have this result : 

    {"skill":{"id":1,"name":"Ember","description":"JS Framework","user_ids":[2]}}

With ember, I have to add another key "users" to add. I tried this : 

      def show
        skill = Skill.find(params[:id])
        render json: { skill: skill, users: skill.users }
      end

But I have this result : 

    {"skill":{"id":1,"name":"Ember","description":"JS Framework","link":"emberjs.com"},"users":[{"id":2,"email":"test@test1234.com","nickname":"dougui","bio":"blabla","created_at":"2015-06-21T10:40:50.493Z","updated_at":"2015-06-25T00:29:14.819Z","encrypted_password":"$2a$10$GXw.n0uoddoUmRnUvrERNuQ/uTQHV7VoylxMAnhkVrDnH0PeSYgPq","confirmation_token":null,"remember_token":"db937fc1daa2bb81912471c2236d683ec15b5582"}]}

It does not use the serializer.

Can you give me some help ?

**Comment by joaomdmoura** [comment]
Yeah @GCorbel, I'm not sure exactly what you need, but if you want the user that have this particular skill, you should add the user relationship into you SkillSerializer.

eg:
```ruby
class SkillSerializer < ActiveModel::Serializer
  attributes :name, :description, :link
  has_many :users
end
```
