### ISSUE TITLE
JSON API Adapter, don't include relationships

### ISSUE THREAD

**Issue by hhff** [rails-api/active_model_serializers#969]
Using the JSON API Adapter with 0.10.0rc2.

```
class CourseSerializer < ActiveModel::Serializer
  attributes :id
  has_many :tracks
end
```

Response looks like this:
```
{
  data: [
    {
      id: "1",
      type: "courses",
      relationships: {
        tracks: {
          data: [
            {
              type: "tracks",
              id: "1"
            }
          ]
        }
      }
    }
  ]
}
```

How can I get this response to only include the `tracks` IDs ?

Thanks so much for all the hard work here!  Happy to update the README when this is solved.

**Comment by Rodrigora** [comment]
Hi @hhff,

To follow JSON API specifications, this is the way that relationships should be rendered (always include the `type` of the object).

One solution to render an array of tracks IDs is add `:track_ids` to attributes list. So you'll have an list of IDs inside `attributes` object of `Course`.

Maintainers, I'm following this project to know it better, so please correct me if I'm wrong.

**Comment by hhff** [comment]
Oh thanks @Rodrigora ! got it.  That means it's working as expected :smile:

**Comment by joaomdmoura** [comment]
@Rodrigora is right. This is the way JSON API is expected to work :smile: I'm glad you guys managed to narrow it down.
