### ISSUE TITLE
Where do I put the code to change the adapter?

### ISSUE THREAD

**Issue by amosjyng** [rails-api/active_model_serializers#973]
Where am I supposed to put this?

    ActiveModel::Serializer.config.adapter = :json_api

Doesn't seem to work in `config/application.rb` or in the serializers I've generated.

**Comment by ivaravko** [comment]
@amosjyng in an initializer (config/initializers/ ).

**Comment by amosjyng** [comment]
Ah excellent, thank you!

**Comment by joaomdmoura** [comment]
:smile:

**Comment by gahissy** [comment]
```ruby
# file: config/initializers/active_model_serializers.rb

ActiveModel::Serializer.setup do |config|
  config.adapter = :json_api
end
```
