### ISSUE TITLE
Any ideas about customize attribute?

### ISSUE THREAD

**Issue by wittyfox** [rails-api/active_model_serializers#979]
Any ideas about allowing a block or a proc or a lambda for customizing attribute:

```ruby
attribute(:title, key: :slug) do |title|
  # the return value of block will be the value of :slug
  title.downcase.join('-')
end
```

or maybe:

```ruby
attribute(:title, ->(title) { title.downcase.split(' ').join('-') }, key: :slug)
```

or maybe:

```ruby
attribute(:title, key: :slug, proc: ->(title) { title.downcase.split(' ').join('-') })
```

In this way, the value of `:slug` will be `title.downcase.split(' ').join('-')`.

**Comment by Rodrigora** [comment]
You can specify a method as attribute:

```ruby

attribute :slug


def slug
  object.title.downcase.split(' ').join('-')
end
```

**Comment by joaomdmoura** [comment]
@wittyfox, today there is no way of use proc or lambda to customize the attribute. But this isn't the first time ppl talk about it.

The alternative the @Rodrigora mentioned would be my recommendation right now, the most straightforward way. I"m really in favor of this one, it seems cleaner for me.

I'm closing this one for now but make yourself comfortable to reopen it and let us know if this doesn't works for you.

**Comment by wittyfox** [comment]
That's ok, quite cleaner solution.

**Comment by zhustec** [comment]
Almost 2 years later, I find my proposal was implemented a year ago. 👍
