### ISSUE TITLE
What is initializer syntax in 0.10.0.rc2?

### ISSUE THREAD

**Issue by wrburgess** [rails-api/active_model_serializers#980]
Using `active_model_serializers 0.9.3` on `rails 4.2.3` I would establish settings in this manner:

```
ActiveModel::Serializer.setup do |config|
  config.embed = :ids
  config.include = true
end
```

Using `0.10.0.rc2` I'm receiving this error:

```
config/initializers/active_model_serializers.rb:1:in `<top (required)>': undefined method `setup' for ActiveModel::Serializer:Class (NoMethodError)
```

What is the proper syntax for the initializer?

**Comment by bf4** [comment]
Well, it looks like the `ActiveSupport.on_load(:active_model_serializers) {}` hook has been removed.

The only global config options I see are

```ruby
ActiveModel::Serializer.config.array_serializer = ActiveModel::Serializer::ArraySerializer
ActiveModel::Serializer.config.adapter = :flatten_json
```

There other configs are per instance or per serializer.

So, you might have

```ruby
  has_many :posts, embed: :ids
```

or

```ruby
          render json: @post, include: 'author', adapter: :json_api
```

(the `include` gets passed into the adapter)

**Comment by joaomdmoura** [comment]
Hey @wrburgess, indeed @bf4 is right. 
We are moving always from global configs and focusing on adapters.
I'm closing this one but want to know more about how your migration from 0.9.3 to 0.10.x is going :smile: We know it isn't an easy migration but there are a lot of improvements, including performance :)
