### ISSUE TITLE
root attribute ignored

### ISSUE THREAD

**Issue by mareczek** [rails-api/active_model_serializers#986]
```ruby
render json: @current_user, root: 'resource', adapter: :json
```
gives output 
```json
{
  "user": {
    "id": 1,
    "name": "Rambo"
  }
}
```
when expected 
```json
{
  "resource": {
    "id": 1,
    "name": "Rambo"
  }
}
```

**Comment by joaomdmoura** [comment]
Hey @mareczek, :smile: 
Yes, it was meant to be, as you can see on [README](https://github.com/rails-api/active_model_serializers#built-in-adapters):

> FlattenJSON

> It's the default adapter, it generates a json response without a root key. Doesn't follow any specifc convention.

> JSON

> It also generates a json response but always with a root key. The root key can't be overridden, and will be automatically defined accordingly with the objects being serialized. Doesn't follow any specifc convention.

I know it seems hard, but it seemed to us that it would help ppl into being consistent with their objects names and overall APIs structure this way.

I'm not saying that I'll not accept your PR (actually I think it makes sense to bring root option back),  but wanted to understand what is your motivation first :smile:

**Comment by mareczek** [comment]
I have a case where i wan't to mask the root name (it has to do with using different serializers depending on the permissions of the current user).

Thanks for the explanation, overall i think it will not be a bad thing to allow developers to change the root key :+1:

**Comment by meltingice** [comment]
This is currently a roadblock for me. Because there is no longer a way to filter attributes, I have two different serializers for the same object that return different attributes based on the API endpoint that is called. Because of this, the root key for the JSON is wrong when using one of the serializers and there is no way to change it.

I say, either bring back the ability to filter attributes or allow the root key to be changed. Personally I think the latter is a better approach.

**Comment by bf4** [comment]
I think in the short run you could 

```ruby
class BrandBaseSerializer < ActiveModel::Serializer
  def json_key
    "brand-base"
  end
end
```

or make your own adapter

```ruby
require "active_model/serializer/adapter/json"
class MyAdapter < ActiveModel::Serializer::Adapter::Json
  def root
     serializer.root || super
  end
end
ActiveModel::Serializer.config.adapter = MyAdapter
```

**Comment by meltingice** [comment]
Oh cool, both look like good solutions.
Thanks!

--
Ryan LeFevre (@meltingice)
HODINKEE, Inc.
Sr. Software Engineer




On Tue, Jul 7, 2015 at 3:37 PM -0700, "Benjamin Fleischer" <notifications@github.com> wrote:












I think in the short run you could 

class BrandBaseSerializer < ActiveModel::Serializer
  def json_key
    "brand-base"
  end
end



or make your own adapter

require "active_model/serializer/adapter/json"
class MyAdapter < ActiveModel::Serializer::Adapter::Json
  def root
     serializer.root || super
  end
end
ActiveModel::Serializer.config.adapter = MyAdapter

**Comment by bf4** [comment]
@meltingice let us know what you do, and maybe add it to the wiki

**Comment by meltingice** [comment]
I ended up going with overriding `json_key` and it worked like a charm. I'll add it to the wiki now.

**Comment by bf4** [comment]
cool (and please reference this issue, and the ams version or ref you're on)

**Comment by meltingice** [comment]
Looks like there aren't any pages in the wiki that I can edit. I'll send a PR for the README.

**Comment by joaomdmoura** [comment]
Hey ppl, I glad to see how you guys are working it out.

@meltingice I understand your needs, and as I said, I'm inclined to merge #987. (I'll try to review it today)

Another change I might do is to define the root key based on the model name and not on the serializer one.

**Comment by joaomdmoura** [comment]
sorry for the flood. About the wiki thing, we are aborting the GH wiki and I'm already working on a ```docs``` folder structure. (Will also try to push it tonight)

**Comment by meltingice** [comment]
Sounds good to me :+1:

**Comment by joaomdmoura** [comment]
Just letting you guys know that I just opened the Docs PR we mentioned before. #994
