### ISSUE TITLE
is it possible to use it on top of rack?

### ISSUE THREAD

**Issue by Orgil** [rails-api/active_model_serializers#988]
i'm just testing out that latest release jsonapi adapter. I setup grape on rack and tried to serialize objects. But seems it is not possible currently. Is it going to support on next releases or only supports rails?

**Comment by joaomdmoura** [comment]
@Orgil it's deeply based on Rails, Ithink you could use it with PORO objects if you implemented to some AR methods, take look at our [fixture file](https://github.com/rails-api/active_model_serializers/blob/master/test/fixtures/poro.rb) we use some PORO objects, that would be a goos start point.
I'm closing this one for now but make yourself comfortable to keep updating it in case you need more help.
