### ISSUE TITLE
Naming collision of 'instrument' in ActiveModel::Serializable

### ISSUE THREAD

**Issue by daino3** [rails-api/active_model_serializers#989]
Hello,

I have a serializer like so:
```
class DooDadSerializer
  attributes :name, :location

  has_one :instrument
end
```

It actually doesn't matter where the ```:instrument``` is but I get the following error:

```
ArgumentError: wrong number of arguments (0 for 1)
from /usr/lib/ruby/gems/2.1.0/gems/active_model_serializers-0.9.3/lib/active_model/serializable.rb:50:in `instrument'
```

After digging through the code, it appears that private methods are available inside the class that includes the module and are being called. 

This seems like a relatively easy fix -> change the method name to something like ```serializable_instrument``` to avoid  naming collisions with a pretty ubiquitous model / class / method name. 

Is that indeed the fix you'd like to see? If so, I can submit a PR.

**Comment by daino3** [comment]
Closing this because rc2 doesn't appear to have the same issue.

**Comment by joaomdmoura** [comment]
Awesome! Tks @daino3  :smile:
