### ISSUE TITLE
How to filter attributes?

### ISSUE THREAD

**Issue by Yoshyn** [rails-api/active_model_serializers#992]
Hi, I want to be able to filter over attributes like this :
 
```ruby
   render json: @model, fields: [:fields1, :fields2]
```
The fields options can be found here : https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb
```ruby
   ADAPTER_OPTION_KEYS = [:include, :fields, :adapter]
``` 

But this does not work. I try to understand a few the code and write something like this and binding inside the attributes method :
```ruby
ActiveModel::Serializer::Adapter::JsonApi.new(MyModelSerializer.new(Model.find(X), fields: [:id])).serializable_hash(fields: [:fields1])
```
Let's see the attributes method inside serializer: 
```ruby
    def attributes(options = {})
      attributes =
        if options[:fields] #options is nil, @options is {:fields=>[:fields1]}
          self.class._attributes & options[:fields]
        else
          self.class._attributes.dup
        end
    ....
    end
```

I don't understand where i have to pass the fields options in order to the attributes method get it in these params method.
Why there's an options parameter on the attributes method. Why not use the @options var?

**Comment by joaomdmoura** [comment]
Hey @Yoshyn,

Indeed, ```fields``` seems to be only used on JSON API adapter, like ```included```.

You can check the PR that implemented it [here](https://github.com/rails-api/active_model_serializers/commit/fc1562c04ad5df16a264c2a5b7b15f507d5588f7)

I've just opened a new PR (#999) that fix some options mistakes and implements the fields option on Json Adapter.

**Comment by joaomdmoura** [comment]
@Yoshyn, have you checked #999 already? Wanted tome :+1: before thinking about merge it.

**Comment by joaomdmoura** [comment]
closing this one in favor of https://github.com/rails-api/active_model_serializers/issues/1058
